--SELECT * FROM  [BI].[dbo].[COMPRAS_AGENDA_PEDIDO_AUTO] WHERE flg_ativo = 1 and id not in (12,556)
--select * FROM  [BI].[dbo].[COMPRAS_AGENDA_PEDIDO_AUTO] WHERE flg_ativo = 1 and cod_fornecedor = 18438
DECLARE @DATA_PEDIDO AS DATE = GETDATE()

DECLARE @TAB_MODEL_ARMAZENAGEM AS TABLE
(
	COD_PRODUTO INT
	,ModelArmazenagem INT
	,PRIMARY KEY (COD_PRODUTO)
)

INSERT INTO @TAB_MODEL_ARMAZENAGEM
SELECT
	COD_PRODUTO
	,ModelArmazenagem
FROM AX2009_INTEGRACAO.DBO.TAB_PRODUTO_FORNECEDOR_PREFERENCIAL AS AFP
WHERE 1=1
	AND AFP.COD_LOJA = 5
	AND AFP.COD_PRODUTO IN (SELECT DISTINCT COD_PRODUTO FROM [BI].[DBO].[COMPRAS_PEDIDOS] AS P WHERE CONVERT(DATE,DATA) = CONVERT(DATE,@DATA_PEDIDO) AND FLG_AUTOMATICO = 1)

SELECT
	P.ID_SIMULADO
	,P.ID_AGENDA
	,A.COD_FORNECEDOR
	,CF2.DESCRICAO AS [Desc. Forn. Agenda]
	,P.[COD_FORNECEDOR] as [Cod. Forn.]
	,P.TIPO_PEDIDO
	,CF.DESCRICAO AS [Desc. Forn.]
	,P.[COD_LOJA] as [Loja]
	,P.[COD_PRODUTO] as [PLU]
	,CP.DESCRICAO AS [Desc. PLU]
	,CP.NO_DEPARTAMENTO
	,CP.NO_SECAO
	,BI.DBO.FN_FORMATAVLR_EXCEL([QTD_EMBALAGEM]) AS [Pedido]
	,P.[COD_COMPRADOR] as [Cod. Comprador]
	,BI.DBO.FN_FORMATAVLR_EXCEL([QTD_ESTOQUE]) AS [Estoque]
	,BI.DBO.FN_FORMATAVLR_EXCEL([VLR_EMB]) AS [Valor CX]
	,BI.DBO.FN_FORMATAVLR_EXCEL([VLR_MULTIPLO]) AS [Qtde Múltiplo]
	,BI.DBO.FN_FORMATAVLR_EXCEL([QTD_EMB_ORG]) AS [Qtde Embalagem]
	,BI.DBO.FN_FORMATAVLR_EXCEL([VLR_REV_TIME]) AS [Freq. Pedido]
	,BI.DBO.FN_FORMATAVLR_EXCEL([VLR_LEAD_TIME]) AS [Lead time]
	,BI.DBO.FN_FORMATAVLR_EXCEL(p.[AVG_QTD_U30D_PD]) AS [VMD 180D]
	,BI.DBO.FN_FORMATAVLR_EXCEL([QTD_SS_DIAS]) AS [Est. Seg. (dias)]
	,BI.DBO.FN_FORMATAVLR_EXCEL([FAT_SAZ]) AS [% Sazon.]
	,BI.DBO.FN_FORMATAVLR_EXCEL([QTD_MIN_UN]) AS [Exposição (qtde)]
	,E.CLASSIF_PRODUTO_LOJA as [Classif. PLU]
	,PABC.ABC_LOJA as [Classif. Supply] 
	,P.COD_PEDIDO
	,P.DATA
	,(CASE
		WHEN afp.ModelArmazenagem = 0 THEN 'Direto'
		WHEN afp.ModelArmazenagem = 1 THEN 'CrossDocking'
		WHEN afp.ModelArmazenagem = 2 THEN 'Armazenagem'
		WHEN afp.ModelArmazenagem = 3 THEN 'PickingUnitario'
	END) AS TIPO_ABASTECIMENTO
	,ISNULL(P.ERRO_CENTRALIZACAO,'') AS ERRO_CENTRALIZACAO
	,P.FLG_CENTRALIZADO
	,P.FORNECEDOR_PRINCIPAL_PROD
	,(CASE WHEN P.FLG_ERRO_FORNECEDOR_PRINCIPAL = 1 THEN 'Alterar no AX campo de Fornecedor na aba de Referencia' else '' end) as FLG_ERRO_FORNECEDOR_PRINCIPAL	
	,(CASE 
		WHEN P.FLG_ERRO_TIPO_ABASTECIMENTO = 1 THEN 
			(CASE
				WHEN P.TIPO_PEDIDO = 3 AND afp.ModelArmazenagem = 1 AND (SELECT TOP 1 1 FROM [BI].[dbo].[COMPRAS_AGENDA_PEDIDO_AUTO] AS A_TIPO1 WHERE A.COD_FORNECEDOR = A_TIPO1.COD_FORNECEDOR AND A_TIPO1.TIPO = 1 AND A_TIPO1.FLG_ATIVO = 1) = 1 THEN 'Fornecedor possui agenda XD - Não alterar'
				WHEN P.TIPO_PEDIDO = 1 AND afp.ModelArmazenagem IN (0,2) AND (SELECT TOP 1 ID FROM [BI].[dbo].[COMPRAS_AGENDA_PEDIDO_AUTO] AS A_TIPO1 WHERE A.COD_FORNECEDOR = A_TIPO1.COD_FORNECEDOR AND A_TIPO1.TIPO = 3 AND A_TIPO1.FLG_ATIVO = 1) = 1 THEN 'Fornecedor possui agenda Armazenagem - Não alterar'
				ELSE 'Verificar se o fornecedor possui agenda XD/Abastecimento'
			END)
		ELSE ''
	END) as FLG_ERRO_TIPO_ABASTECIMENTO
	,(CASE WHEN P.FLG_ERRO_SEM_CUSTO = 1 THEN 'produto sem custo na ORBIS 18055' when P.FLG_ERRO_SEM_CUSTO = 2 THEN 'Não possui custo atualizado! Subir custo!' else '' end) as FLG_ERRO_SEM_CUSTO
	,(CASE WHEN P.FLG_COMPRA = 1 THEN 'ABC Liberado' else 'ABC bloqueado' end) as FLG_COMPRA	
	,(CASE WHEN P.FLG_ERRO_CONVERSAO_UNIDADE = 1 THEN 'Produto em CX sem conversão de unidade' else '' end) as FLG_ERRO_CONVERSAO_UNIDADE	
	,(CASE WHEN P.FLG_BLOQUEADO_SUPPLY = 1 THEN 'Produto bloqueado para compra pelo Supply' else '' end) as FLG_BLOQUEADO_SUPPLY	
	,(CASE
		WHEN P.FLG_ERRO_FORNECEDOR_PRINCIPAL = 0 AND P.FLG_ERRO_TIPO_ABASTECIMENTO = 0 AND P.FLG_ERRO_SEM_CUSTO = 0 AND P.FLG_COMPRA = 1 and P.FLG_BLOQUEADO_SUPPLY IS NULL AND P.FLG_ERRO_CONVERSAO_UNIDADE IS NULL AND P.ERRO_CENTRALIZACAO IS NOT NULL THEN 'Vai gerar Pedido COM ERRO'
		WHEN P.FLG_ERRO_FORNECEDOR_PRINCIPAL = 0 AND P.FLG_ERRO_TIPO_ABASTECIMENTO = 0 AND P.FLG_ERRO_SEM_CUSTO = 0 AND P.FLG_COMPRA = 1 AND P.FLG_BLOQUEADO_SUPPLY IS NULL AND P.FLG_ERRO_CONVERSAO_UNIDADE IS NULL AND P.ERRO_CENTRALIZACAO IS NULL THEN 'Vai gerar Pedido'
		ELSE 'Não vai gerar pedido'
	END) AS VAI_GERAR_PEDIDO
	,P.ID AS ID_PEDIDO
	,P.FLG_INTEGRADO_AX
    ,P.MARCHE_PURCHIDREF
	--update p set data = getdate() 
	--,ID	delete p
FROM
	[BI].[DBO].[COMPRAS_PEDIDOS] AS P
	INNER JOIN BI.DBO.BI_CAD_PRODUTO AS CP
		ON P.COD_PRODUTO = CP.COD_PRODUTO
	INNER JOIN BI.DBO.BI_CAD_FORNECEDOR AS CF
		ON P.COD_FORNECEDOR = CF.COD_FORNECEDOR
	LEFT JOIN [BI].[dbo].[COMPRAS_AGENDA_PEDIDO_AUTO] AS A
		ON P.ID_AGENDA = A.ID
	LEFT JOIN BI.DBO.BI_CAD_FORNECEDOR AS CF2
		ON A.COD_FORNECEDOR = CF2.COD_FORNECEDOR
	LEFT JOIN @TAB_MODEL_ARMAZENAGEM AS AFP
			ON 1=1
			AND P.COD_PRODUTO = AFP.COD_PRODUTO	
	LEFT JOIN BI.DBO.[SUPPLY_PRODUTO_ABC_LOJA] AS PABC
		ON 1=1
		AND P.COD_LOJA = PABC.COD_LOJA
		AND P.COD_PRODUTO = PABC.COD_PRODUTO	
	LEFT JOIN BI.dbo.COMPRAS_ESTATISTICA_PRODUTO AS E
		ON 1=1
		AND P.COD_LOJA = E.COD_LOJA
		AND P.COD_PRODUTO = E.COD_PRODUTO
WHERE 1=1
	AND CONVERT(DATE,DATA) = CONVERT(DATE,@DATA_PEDIDO)
	AND FLG_AUTOMATICO = 1
	AND COD_PEDIDO IS null
	--AND ID_AGENDA = 479
	--and ID_SIMULADO = 50
	--AND A.COD_FORNECEDOR in (18438)
	--AND P.COD_PRODUTO IN (1013789)
	
	/*USADO PARA DELETAR PRE ZEUS*/	
	--AND P.FLG_ERRO_FORNECEDOR_PRINCIPAL = 1
	--AND P.FLG_ERRO_TIPO_ABASTECIMENTO = 1
	--AND P.FLG_ERRO_SEM_CUSTO = 1
	--AND P.FLG_COMPRA = 0