DECLARE @DATA_ANALISE AS DATE = GETDATE()

DECLARE @WEEK_DAY AS INT = DATEPART(DW,@DATA_ANALISE)

DECLARE @TAB_FORN_AGENDA AS TABLE
(
	COD_FORNECEDOR INT
)
INSERT INTO @TAB_FORN_AGENDA
SELECT 
	[COD_FORNECEDOR]
FROM
	[BI].[DBO].[COMPRAS_AGENDA_PEDIDO_AUTO]
WHERE 1=1
	AND FLG_ATIVO = 1
	AND DATEPART(DW,[DATA_BASE]) = @WEEK_DAY


SELECT
	@DATA_ANALISE AS DATA_PEDIDO
	,FA.[COD_FORNECEDOR]
	,COUNT(DISTINCT COD_PEDIDO) AS QTD_PEDIDO_LOJA
FROM
	@TAB_FORN_AGENDA AS FA
	LEFT JOIN [BI].[DBO].[COMPRAS_PEDIDOS] AS P
		ON 1=1
		AND FA.COD_FORNECEDOR = P.COD_FORNECEDOR
		AND CONVERT(DATE,P.DATA) = CONVERT(DATE,@DATA_ANALISE)
		AND P.COD_PEDIDO IS NOT NULL
		AND P.FLG_AUTOMATICO = 1
		AND P.FLG_TESTE= 1
WHERE 1=1
GROUP BY
	FA.[COD_FORNECEDOR]
ORDER BY
	QTD_PEDIDO_LOJA DESC