/*				
	SELECT 
		AFP.COD_LOJA
		,CP.COD_PRODUTO
		,CP.DESCRICAO AS NO_PRODUTO
		,CP.CLASSIF_PRODUTO AS ABC_GLOBAL
		,AFP.COD_FORNECEDOR AS COD_FORNECEDOR_CENTRALIZACAO_planilha
		,CF1.DESCRICAO AS NO_FORNECEDOR_CENTRALIZACAO_planilha
		,AFP.ModelArmazenagem
		,(CASE
			WHEN afp.ModelArmazenagem = 0 THEN 'Direto'
			WHEN afp.ModelArmazenagem = 1 THEN 'CrossDocking'
			WHEN afp.ModelArmazenagem = 2 THEN 'Armazenagem'
			WHEN afp.ModelArmazenagem = 3 THEN 'PickingUnitario'
		END) AS TIPO_ABASTECIMENTO
		,AFP.FORNECEDOR_COMPRAS as FORNECEDOR_COMPRAS_ax
		,CF2.DESCRICAO AS NO_FORNECEDOR_COMPRAS_AX		
	FROM				
		AX2009_INTEGRACAO.DBO.TAB_PRODUTO_FORNECEDOR_PREFERENCIAL AS AFP
		INNER JOIN BI.DBO.BI_CAD_PRODUTO AS CP
			ON AFP.COD_PRODUTO = CP.COD_PRODUTO						
		INNER JOIN BI.DBO.BI_CAD_FORNECEDOR AS CF1
			ON AFP.COD_Fornecedor = CF1.COD_FORNECEDOR						
		INNER JOIN BI.DBO.BI_CAD_FORNECEDOR AS CF2
			ON AFP.FORNECEDOR_COMPRAS = CF2.COD_FORNECEDOR						
		LEFT JOIN BI.DBO.VW_ESTOQUE_ATUAL AS EA
			ON AFP.COD_LOJA = EA.COD_LOJA
			AND AFP.COD_PRODUTO = EA.COD_PRODUTO
	WHERE 1=1
	AND AFP.COD_LOJA IN (5)
	AND ISNULL(AFP.COD_FORNECEDOR ,'') <> ''
	AND AFP.COD_FORNECEDOR <> FORNECEDOR_COMPRAS
	AND AFP.COD_FORNECEDOR <> 18055
	--AND AFP.MODELARMAZENAGEM <> 1
	--AND afp.COD_PRODUTO = 418843
*/		
		
		
/*		
	IF OBJECT_ID('TEMPDB.DBO.#TAB_RETORNO_TESTE') IS NOT NULL DROP TABLE #TAB_RETORNO_TESTE
	CREATE TABLE  #TAB_RETORNO_TESTE
	(
		[COD_LOJA] INT
		,[COD_PRODUTO] INT
		,[COD_DEPARTAMENTO] INT
		,[COD_SECAO] INT 		
		,[QTD_EST_ATUAL]  NUMERIC(18,3)
		,[QTD_EMBALAGEM_COMPRA] NUMERIC(18,3)
		,[QTD_MULTIPLO_EMB] NUMERIC(18,3) --QTD_MINIMA_COMPRA
		,[AVG_QTD_U30D_PD] NUMERIC(18,3)
		,[QTD_QUEBRA_3M] NUMERIC(18,3)--QTD_QUEBRA_PERC_3M
		,[ABC] VARCHAR(5)
		,[VAL_CUSTO_EMBALAGEM] NUMERIC(18,3)
		,[DES_UNIDADE_VENDA]   VARCHAR(10)
		,[DES_UNIDADE_COMPRA]  VARCHAR(10)
		--CAMPOS NAO USADOS
		,ITEMID INT
		,COD_FORNECEDOR INT
		,DES_REFERENCIA VARCHAR(50)
		,FORA_MIX VARCHAR(5)
		,ENVIA_PDV VARCHAR(5)
		,QTD_EST_CD NUMERIC(18,2)
		,COD_FORNECEDOR_PREFERENCIAL INT
		,TIPO_ABASTECIMENTO INT
	)
	CREATE CLUSTERED INDEX IX_TBRETORNOCALC ON #TAB_RETORNO_TESTE (COD_LOJA, COD_PRODUTO)
		
			
	DECLARE @COD_FORNECEDOR AS INT;

	DECLARE nome_cursor CURSOR FOR 
		select COD_FORNECEDOR FROM BI.DBO.BI_CAD_FORNECEDOR WHERE COD_FORNECEDOR IN	(104486)--(104550,104486,1022,623,104489,1789,14682,102639,104451,104541,103265,16517)
		
	OPEN nome_cursor
	FETCH NEXT FROM nome_cursor 
	INTO @COD_FORNECEDOR

	WHILE @@FETCH_STATUS = 0
	BEGIN
		-- -------------------------------------------------------------------------------------
		-- -------------------------------------------------------------------------------------	
			PRINT @COD_FORNECEDOR
			INSERT INTO #TAB_RETORNO_TESTE (ITEMID, COD_FORNECEDOR , COD_PRODUTO ,COD_LOJA , DES_REFERENCIA , FORA_MIX , ENVIA_PDV , QTD_EST_CD , COD_FORNECEDOR_PREFERENCIAL , TIPO_ABASTECIMENTO)
			exec dw.dbo.sp_Calculadora_Lista_Produtos_Fornecedor  '1', 18055 , null , null , 0, @COD_FORNECEDOR			
		-- -------------------------------------------------------------------------------------
		-- -------------------------------------------------------------------------------------
		FETCH NEXT FROM nome_cursor 
		INTO @COD_FORNECEDOR
	END 
	CLOSE nome_cursor;
	DEALLOCATE nome_cursor;
*/
--SELECT * FROM #TAB_RETORNO_TESTE

	SELECT DISTINCT
		TAB_ERROS.*
	FROM
		#TAB_RETORNO_TESTE AS R
		INNER JOIN 					
		(
			SELECT 
				AFP.COD_LOJA
				,CP.COD_PRODUTO
				,CP.DESCRICAO AS NO_PRODUTO
				,CP.CLASSIF_PRODUTO AS ABC_GLOBAL
				,AFP.COD_FORNECEDOR AS COD_FORNECEDOR_CENTRALIZACAO_planilha
				,CF1.DESCRICAO AS NO_FORNECEDOR_CENTRALIZACAO_planilha
				,AFP.ModelArmazenagem
				,(CASE
					WHEN afp.ModelArmazenagem = 0 THEN 'Direto'
					WHEN afp.ModelArmazenagem = 1 THEN 'CrossDocking'
					WHEN afp.ModelArmazenagem = 2 THEN 'Armazenagem'
					WHEN afp.ModelArmazenagem = 3 THEN 'PickingUnitario'
				END) AS TIPO_ABASTECIMENTO
				,AFP.FORNECEDOR_COMPRAS as FORNECEDOR_COMPRAS_ax
				,CF2.DESCRICAO AS NO_FORNECEDOR_COMPRAS_AX		
			FROM				
				AX2009_INTEGRACAO.DBO.TAB_PRODUTO_FORNECEDOR_PREFERENCIAL AS AFP
				INNER JOIN BI.DBO.BI_CAD_PRODUTO AS CP
					ON AFP.COD_PRODUTO = CP.COD_PRODUTO						
				INNER JOIN BI.DBO.BI_CAD_FORNECEDOR AS CF1
					ON AFP.COD_Fornecedor = CF1.COD_FORNECEDOR						
				INNER JOIN BI.DBO.BI_CAD_FORNECEDOR AS CF2
					ON AFP.FORNECEDOR_COMPRAS = CF2.COD_FORNECEDOR						
				LEFT JOIN BI.DBO.VW_ESTOQUE_ATUAL AS EA
					ON AFP.COD_LOJA = EA.COD_LOJA
					AND AFP.COD_PRODUTO = EA.COD_PRODUTO
			WHERE 1=1
			AND AFP.COD_LOJA IN (5)
			AND ISNULL(AFP.COD_FORNECEDOR ,'') <> ''
			AND AFP.COD_FORNECEDOR <> FORNECEDOR_COMPRAS
			AND AFP.COD_FORNECEDOR <> 18055
			--AND AFP.MODELARMAZENAGEM <> 1
			--AND afp.COD_PRODUTO = 418843
		) AS TAB_ERROS
		ON R.COD_PRODUTO = TAB_ERROS.COD_PRODUTO
	WHERE 1=1
	--AND R.COD_PRODUTO = 17992