-- ------------------------------------------------------------------
-- AUTOMATICOS ATIVOS
-- ------------------------------------------------------------------
	DECLARE @TAB_FORNECEDOR_AUTOMATICO AS TABLE
	(
		COD_FORNECEDOR INT
		,PRIMARY KEY (COD_FORNECEDOR)
	)	
	INSERT INTO @TAB_FORNECEDOR_AUTOMATICO	
		SELECT DISTINCT COD_FORNECEDOR FROM COMPRAS_AGENDA_PEDIDO_AUTO WHERE FLG_ATIVO = 1	

-- ------------------------------------------------------------------
-- PEDIDO MINIMO (MAIOR)
-- ------------------------------------------------------------------
	DECLARE @TAB_PEDIDO_MINIMO AS TABLE
	(
		COD_FORNECEDOR INT
		,VLR_PEDIDO_MIN NUMERIC(18,2)
		,PRIMARY KEY (COD_FORNECEDOR)
	)	
	INSERT INTO @TAB_PEDIDO_MINIMO
		SELECT
			COD_FORNECEDOR
			,MAX(ISNULL(VLR_PEDIDO_MIN,0)) AS VLR_PEDIDO_MIN
		FROM
		(
			SELECT DISTINCT COD_FORNECEDOR, VLR_PEDIDO_MIN  FROM COMPRAS_AGENDA_PEDIDO_AUTO
			UNION ALL
			SELECT DISTINCT COD_FORNECEDOR, VLR_PEDIDO_MIN FROM COMPRAS_AGENDA_PEDIDO_MATRIZ
		) AS A
		GROUP BY
			COD_FORNECEDOR

-- ------------------------------------------------------------------
-- ESTOQUE
-- ------------------------------------------------------------------	
	DECLARE @TAB_ESTOQUE_2015 AS TABLE
	(
		COD_LOJA INT
		,COD_PRODUTO INT
		,QTD_ESTOQUE NUMERIC(18,2)
		,PRIMARY KEY (COD_LOJA, COD_PRODUTO)
	)	
	INSERT INTO @TAB_ESTOQUE_2015
		SELECT
			EP.COD_LOJA
			,EP.COD_PRODUTO
			,EP.QTD_ESTOQUE
		FROM
			DW.dbo.ESTOQUE AS EP
			INNER JOIN BI.dbo.BI_CAD_PRODUTO AS CP
				ON EP.COD_PRODUTO = CP.COD_PRODUTO
		WHERE 1=1
			AND CP.PNP = 'NP'
			AND CONVERT(DATE,DATA) = '2015-06-30'
	
	DECLARE @TAB_ESTOQUE_2016 AS TABLE
	(
		COD_LOJA INT
		,COD_PRODUTO INT
		,QTD_ESTOQUE NUMERIC(18,2)
		,PRIMARY KEY (COD_LOJA, COD_PRODUTO)
	)	
	INSERT INTO @TAB_ESTOQUE_2016
		SELECT
			EP.COD_LOJA
			,EP.COD_PRODUTO
			,EP.QTD_ESTOQUE
		FROM
			DW.dbo.ESTOQUE AS EP
			INNER JOIN BI.dbo.BI_CAD_PRODUTO AS CP
				ON EP.COD_PRODUTO = CP.COD_PRODUTO
		WHERE 1=1
			AND CP.PNP = 'NP'
			AND CONVERT(DATE,DATA) = '2016-06-22'	


-- ------------------------------------------------------------------
-- VMD
-- ------------------------------------------------------------------	
	DECLARE @TAB_VMD_2015 AS TABLE
	(
		COD_LOJA INT
		,COD_PRODUTO INT
		,AVG_QTD_U180D_2015 NUMERIC(18,2)
		,PRIMARY KEY (COD_LOJA, COD_PRODUTO)
	)
	INSERT INTO @TAB_VMD_2015
		SELECT
			VP.COD_LOJA
			,VP.COD_PRODUTO
			,SUM(QTDE_PRODUTO)/180 AS AVG_QTD_U180D_2015
		FROM
			BI.DBO.BI_VENDA_PRODUTO AS VP
		WHERE 1=1
			AND CONVERT(DATE,VP.DATA) BETWEEN DATEADD(D,-180,CONVERT(DATE,'2015-06-30')) AND CONVERT(DATE,'2015-06-30')
		GROUP BY
			VP.COD_LOJA
			,VP.COD_PRODUTO
	
	DECLARE @TAB_VMD_2016 AS TABLE
	(
		COD_LOJA INT
		,COD_PRODUTO INT
		,AVG_QTD_U180D_2016 NUMERIC(18,2)
		,PRIMARY KEY (COD_LOJA, COD_PRODUTO)
	)
	INSERT INTO @TAB_VMD_2016
		SELECT
			VP.COD_LOJA
			,VP.COD_PRODUTO
			,SUM(QTDE_PRODUTO)/180 AS AVG_QTD_U180D_2015
		FROM
			BI.DBO.BI_VENDA_PRODUTO AS VP
		WHERE 1=1
			AND CONVERT(DATE,VP.DATA) BETWEEN DATEADD(D,-180,CONVERT(DATE,'2015-06-22')) AND CONVERT(DATE,'2015-06-22')
		GROUP BY
			VP.COD_LOJA
			,VP.COD_PRODUTO

-- ------------------------------------------------------------------
-- MULTIPLO
-- ------------------------------------------------------------------		
	DECLARE @TAB_MODEL_ARMAZENAGEM AS TABLE
	(
		COD_PRODUTO INT
		,ModelArmazenagem INT
		,FORNECEDOR_COMPRAS INT
		,PRIMARY KEY (COD_PRODUTO)
	)

	INSERT INTO @TAB_MODEL_ARMAZENAGEM
	SELECT DISTINCT
		COD_PRODUTO
		,ModelArmazenagem
		,FORNECEDOR_COMPRAS
	FROM AX2009_INTEGRACAO.DBO.TAB_PRODUTO_FORNECEDOR_PREFERENCIAL AS AFP
	WHERE 1=1
		AND AFP.COD_LOJA = 5
		AND AFP.COD_PRODUTO IN (SELECT DISTINCT COD_PRODUTO FROM [BI].[DBO].[BI_CAD_PRODUTO] AS P WHERE PNP = 'NP')
	
	SELECT
		LP.COD_LOJA
		,LP.COD_PRODUTO
		,CP.DESCRICAO
		--,ABC.ABC_LOJA AS ABC_SUPPLY
		,LP.CLASSIF_PRODUTO_LOJA AS ABC_LOJA
		--,CP.COD_DEPARTAMENTO
		--,CP.NO_DEPARTAMENTO
		--,CP.COD_SECAO
		--,CP.NO_SECAO
		,LP.FORA_LINHA
		,aFP.FORNECEDOR_COMPRAS
		--,CF.DESCRICAO AS NO_FORNECEDOR
		,BI.dbo.fn_FormataVlr_Excel(PR.MARCHEQTDEMBALAGEM) as MARCHEQTDEMBALAGEM
		,BI.dbo.fn_FormataVlr_Excel(PR.MARCHEMULTIPLO) as MARCHEMULTIPLO
		,BI.dbo.fn_FormataVlr_Excel(PR.MARCHEUNITID) as MARCHEUNITID
		,FA.COD_FORNECEDOR as FORN_AUTOMATICO
		,BI.dbo.fn_FormataVlr_Excel(PM.VLR_PEDIDO_MIN) as VLR_PEDIDO_MIN
		,BI.dbo.fn_FormataVlr_Excel(EP2015.QTD_ESTOQUE) as QTD_ESTOQUE_2015
		,BI.dbo.fn_FormataVlr_Excel(EP2016.QTD_ESTOQUE) as QTD_ESTOQUE_2016
		,BI.dbo.fn_FormataVlr_Excel(VMD2015.AVG_QTD_U180D_2015) as AVG_QTD_U180D_2015
		,BI.dbo.fn_FormataVlr_Excel(VMD2016.AVG_QTD_U180D_2016) as AVG_QTD_U180D_2016		
		--,(CASE
		--	WHEN afp.ModelArmazenagem = 0 THEN 'Direto'
		--	WHEN afp.ModelArmazenagem = 1 THEN 'CrossDocking'
		--	WHEN afp.ModelArmazenagem = 2 THEN 'Armazenagem'
		--	WHEN afp.ModelArmazenagem = 3 THEN 'PickingUnitario'
		--END) AS TIPO_ABASTECIMENTO
		--,BI.dbo.fn_FormataVlr_Excel(C.VLR_EMB_COMPRA) as VLR_EMB_COMPRA
		--,BI.dbo.fn_FormataVlr_Excel(C.QTD_EMB_COMPRA) as QTD_EMB_COMPRA		
	FROM
		BI.DBO.BI_CAD_PRODUTO AS CP
		INNER JOIN BI.dbo.BI_LINHA_PRODUTOS AS LP
			ON CP.COD_PRODUTO = LP.COD_PRODUTO
		INNER JOIN BI.dbo.BI_CAD_LOJA2 AS L
			ON LP.COD_LOJA = L.COD_LOJA
		LEFT JOIN [BI].[dbo].SUPPLY_PRODUTO_ABC_LOJA AS ABC
			ON 1=1
			AND LP.COD_PRODUTO = ABC.COD_PRODUTO
			AND LP.COD_LOJA = ABC.COD_LOJA
		left join @TAB_MODEL_ARMAZENAGEM AS aFP
			ON 1=1
			AND LP.COD_PRODUTO = aFP.COD_PRODUTO
		LEFT JOIN AX2009_INTEGRACAO.DBO.TAB_PRODUTO_REFERENCIA AS PR
			ON 1=1
			AND LP.COD_PRODUTO = PR.COD_PRODUTO
			AND aFP.FORNECEDOR_COMPRAS = PR.COD_FORNECEDOR
		--LEFT JOIN BI.dbo.BI_CAD_FORNECEDOR AS CF
		--	ON 1=1
		--	AND aFP.FORNECEDOR_COMPRAS = cF.COD_FORNECEDOR			
		LEFT JOIN @TAB_FORNECEDOR_AUTOMATICO AS FA
			ON 1=1
			AND aFP.FORNECEDOR_COMPRAS = FA.COD_FORNECEDOR		
		LEFT JOIN @TAB_PEDIDO_MINIMO AS PM
			ON 1=1
			AND aFP.FORNECEDOR_COMPRAS = PM.COD_FORNECEDOR		
		LEFT JOIN @TAB_ESTOQUE_2015 AS EP2015
			ON 1=1
			AND LP.COD_LOJA = EP2015.COD_LOJA
			AND LP.COD_PRODUTO = EP2015.COD_PRODUTO		
		LEFT JOIN @TAB_ESTOQUE_2016 AS EP2016
			ON 1=1
			AND LP.COD_LOJA = EP2016.COD_LOJA
			AND LP.COD_PRODUTO = EP2016.COD_PRODUTO		
		LEFT JOIN @TAB_VMD_2015 AS VMD2015
			ON 1=1
			AND LP.COD_LOJA = VMD2015.COD_LOJA
			AND LP.COD_PRODUTO = VMD2015.COD_PRODUTO		
		LEFT JOIN @TAB_VMD_2016 AS VMD2016
			ON 1=1
			AND LP.COD_LOJA = VMD2016.COD_LOJA
			AND LP.COD_PRODUTO = VMD2016.COD_PRODUTO
			
	WHERE 1=1
		--AND LP.FORA_LINHA = 'N'
		AND CP.PNP = 'NP'
		AND CP.COD_DEPARTAMENTO NOT IN (7,15,16,17,18,20,99)
		AND CP.COD_SECAO NOT IN (32)
		AND LP.COD_LOJA NOT IN (5,29,33,8)
		AND L.NO_REGIONAL = 'Fernanda'
		
		
		
		