--SELECT * FROM  [BI].[DBO].[COMPRAS_AGENDA_PEDIDO_AUTO] WHERE FLG_ATIVO = 1 AND ID NOT IN (12,556)
--SELECT * FROM  [BI].[DBO].[COMPRAS_AGENDA_PEDIDO_AUTO] WHERE FLG_ATIVO = 1 AND COD_FORNECEDOR = 18438
DECLARE @DATA_INI AS DATE = '2016-04-01'
DECLARE @DATA_FIM AS DATE = GETDATE()-1

/*
select * from DW.DBO.VW_MARCHE_ENTRADAS AS ENT
WHERE  1 = 1
		AND ENT.PURCHID LIKE 'CD%'
		AND ENT.DATAAREAID = 'ORB'
		and COD_FORNECEDOR = 103419
		AND CONVERT(DATE,ENT.DTA_ENTRADA) BETWEEN CONVERT(DATE,@DATA_INI) AND CONVERT(DATE,@DATA_FIM)
*/

DECLARE @TAB_PEDIDO AS TABLE
(
	ID_SIMULADO INT
	,ID_AGENDA INT
	,COD_FORNECEDOR INT
	,NO_FORNECEDOR VARCHAR(150)
	,COD_FORNECEDOR_PED INT
	,NO_FORNECEDOR_PED VARCHAR(150)
	,COD_PRODUTO INT
	,NO_PRODUTO VARCHAR(50)
	,NO_DEPARTAMENTO VARCHAR(50)
	,NO_SECAO VARCHAR(50)
	,DATA DATE
	,FLG_INTEGRADO_AX INT
	,MARCHE_PURCHIDREF  VARCHAR(50)
	,QTD_PEDIDO NUMERIC(18,3)
	,VLR_PEDIDO NUMERIC(18,3)
)

INSERT INTO @TAB_PEDIDO		
	SELECT
		P.ID_SIMULADO
		,P.ID_AGENDA
		,A.COD_FORNECEDOR
		,CF2.DESCRICAO AS [DESC. FORN. AGENDA]
		,P.[COD_FORNECEDOR] AS [COD. FORN.]		
		,CF.DESCRICAO AS [DESC. FORN.]
		--,P.[COD_LOJA] AS [LOJA]
		,P.[COD_PRODUTO] AS [PLU]
		,CP.DESCRICAO AS [DESC. PLU]
		,CP.NO_DEPARTAMENTO
		,CP.NO_SECAO	
		--,P.COD_PEDIDO
		,CONVERT(DATE,P.DATA) AS DATA
		,P.FLG_INTEGRADO_AX
		,P.MARCHE_PURCHIDREF
		,(SUM([QTD_EMBALAGEM])) AS [QTDPEDIDO]
		,(SUM([QTD_EMBALAGEM]*[VLR_EMB])) AS [VLRPEDIDO]
	FROM
		[BI].[DBO].[COMPRAS_PEDIDOS] AS P
		INNER JOIN BI.DBO.BI_CAD_PRODUTO AS CP
			ON P.COD_PRODUTO = CP.COD_PRODUTO
		INNER JOIN BI.DBO.BI_CAD_FORNECEDOR AS CF
			ON P.COD_FORNECEDOR = CF.COD_FORNECEDOR
		LEFT JOIN [BI].[DBO].[COMPRAS_AGENDA_PEDIDO_AUTO] AS A
			ON P.ID_AGENDA = A.ID
		LEFT JOIN BI.DBO.BI_CAD_FORNECEDOR AS CF2
			ON A.COD_FORNECEDOR = CF2.COD_FORNECEDOR
	WHERE 1=1
		AND CONVERT(DATE,DATA) BETWEEN CONVERT(DATE,@DATA_INI) AND CONVERT(DATE,@DATA_FIM)
		AND FLG_AUTOMATICO = 1
		AND P.COD_PEDIDO IS NOT NULL
		AND (P.TIPO_PEDIDO = 1 or P.TIPO_PEDIDO is null)
		AND P.QTD_EMBALAGEM > 0
		and P.COD_FORNECEDOR = 18055
		AND (isnull(P.FLG_ERRO_FORNECEDOR_PRINCIPAL,0) = 0 AND isnull(P.FLG_ERRO_TIPO_ABASTECIMENTO,0) = 0 AND isnull(P.FLG_ERRO_SEM_CUSTO,0) = 0 AND isnull(P.FLG_COMPRA,1) = 1 AND P.FLG_BLOQUEADO_SUPPLY IS NULL AND P.FLG_ERRO_CONVERSAO_UNIDADE IS NULL)
	GROUP BY
		P.ID_SIMULADO
		,P.ID_AGENDA
		,A.COD_FORNECEDOR
		,CF2.DESCRICAO
		,P.[COD_FORNECEDOR]
		,P.TIPO_PEDIDO
		,CF.DESCRICAO
		,P.[COD_PRODUTO]
		,CP.DESCRICAO
		,CP.NO_DEPARTAMENTO
		,CP.NO_SECAO	
		,CONVERT(DATE,P.DATA)
		,P.FLG_INTEGRADO_AX
		,P.MARCHE_PURCHIDREF

DECLARE @TAB_RECEBIMENTO AS TABLE
(
	COD_LOJA INT
	,COD_FORNECEDOR INT	
	,MARCHE_PURCHIDREF VARCHAR(20)
	,COD_PRODUTO INT
	--,DTA_ENTRADA DATE
	--,NUM_NF_FORN INT
	--,NUM_SERIE_NF INT	
	,QTD_ENTRADA NUMERIC(18,2)
	,VAL_TABELA NUMERIC(18,2)
	,VLR_TOTAL_RECEBIMENTO NUMERIC(18,2)
	,PRIMARY KEY (COD_LOJA,COD_FORNECEDOR,MARCHE_PURCHIDREF,COD_PRODUTO)
)

INSERT INTO @TAB_RECEBIMENTO
	SELECT
		ENT.COD_LOJA
		,ENT.COD_FORNECEDOR		
		,ENT.PURCHID AS COD_PEDIDO
		,ENT.COD_PRODUTO
		--,ENT.DTA_ENTRADA
		--,ENT.NUM_NF_FORN
		--,ENT.NUM_SERIE_NF		
		,SUM(ENT.QTD_ENTRADA*-1) AS QTD_ENTRADA
		,SUM(ENT.VAL_TABELA) AS VAL_TABELA
		,SUM(ENT.VAL_TABELA_FINAL*-1) AS VLR_TOTAL_RECEBIMENTO
	FROM
		DW.DBO.VW_MARCHE_ENTRADAS AS ENT
		--LEFT JOIN BI.DBO.BI_CAD_FORNECEDOR AS CF
		--	ON ENT.COD_FORNECEDOR = CF.COD_FORNECEDOR
		--LEFT JOIN BI.DBO.BI_CAD_PRODUTO AS CP
		--	ON ENT.COD_PRODUTO = CP.COD_PRODUTO
	WHERE  1 = 1
		AND ENT.PURCHID LIKE 'CD%'
		AND ENT.DATAAREAID = 'ORB'
		AND CONVERT(DATE,ENT.DTA_ENTRADA) BETWEEN CONVERT(DATE,@DATA_INI) AND CONVERT(DATE,@DATA_FIM)
	GROUP BY
		ENT.COD_LOJA
		,ENT.COD_FORNECEDOR		
		,ENT.PURCHID
		,ENT.COD_PRODUTO
		--,ENT.DTA_ENTRADA
		--,ENT.NUM_NF_FORN
		--,ENT.NUM_SERIE_NF

/*	
SELECT
	P.ID_SIMULADO
	,P.ID_AGENDA
	,P.COD_FORNECEDOR
	,P.NO_FORNECEDOR
	,P.COD_FORNECEDOR_PED
	,P.NO_FORNECEDOR_PED
	,P.COD_PRODUTO
	,P.NO_PRODUTO
	,P.NO_DEPARTAMENTO
	,P.NO_SECAO
	,P.DATA
	,P.FLG_INTEGRADO_AX
	,P.MARCHE_PURCHIDREF
	,BI.dbo.fn_FormataVlr_Excel(P.QTD_PEDIDO) AS QTD_PEDIDO
	,BI.dbo.fn_FormataVlr_Excel(P.VLR_PEDIDO) AS VLR_PEDIDO
	,BI.dbo.fn_FormataVlr_Excel(R.QTD_ENTRADA) AS QTD_ENTRADA
	,BI.dbo.fn_FormataVlr_Excel(R.VLR_TOTAL_RECEBIMENTO) AS VLR_TOTAL_RECEBIMENTO
	,(CASE WHEN R.QTD_ENTRADA > 0 THEN 1 ELSE 0 END) AS FLG_REC
FROM
	@TAB_PEDIDO AS P
	LEFT JOIN @TAB_RECEBIMENTO AS R
		ON 1=1
		--AND P.COD_FORNECEDOR = R.COD_FORNECEDOR
		AND P.COD_PRODUTO = R.COD_PRODUTO
		AND P.MARCHE_PURCHIDREF = R.MARCHE_PURCHIDREF
WHERE 1=1
	and P.MARCHE_PURCHIDREF = 'CD_0001465'
*/

--SELECT * FROM @TAB_PEDIDO AS P WHERE P.MARCHE_PURCHIDREF = 'CD_0001144'
--SELECT * FROM @TAB_RECEBIMENTO AS R WHERE R.MARCHE_PURCHIDREF = 'CD_0001144'


SELECT
	P.ID_SIMULADO
	,P.ID_AGENDA
	,P.COD_FORNECEDOR
	,P.NO_FORNECEDOR
	,P.COD_FORNECEDOR_PED
	,P.NO_FORNECEDOR_PED
	,CONVERT(DATE,P.DATA) AS DATA
	,P.FLG_INTEGRADO_AX
	,P.MARCHE_PURCHIDREF
	,BI.dbo.fn_FormataVlr_Excel(count(distinct P.MARCHE_PURCHIDREF)) AS QTD_PEDIDO
	,BI.dbo.fn_FormataVlr_Excel(COUNT(distinct R.MARCHE_PURCHIDREF)) AS QTD_ENTRADA
FROM
	@TAB_PEDIDO AS P
	LEFT JOIN @TAB_RECEBIMENTO AS R
		ON 1=1
		--AND P.COD_FORNECEDOR = R.COD_FORNECEDOR
		AND P.COD_PRODUTO = R.COD_PRODUTO
		AND P.MARCHE_PURCHIDREF = R.MARCHE_PURCHIDREF
WHERE 1=1
	and P.MARCHE_PURCHIDREF <> ''
GROUP BY
	P.ID_SIMULADO
	,P.ID_AGENDA
	,P.COD_FORNECEDOR
	,P.NO_FORNECEDOR
	,P.COD_FORNECEDOR_PED
	,P.NO_FORNECEDOR_PED
	,CONVERT(DATE,P.DATA)
	,P.FLG_INTEGRADO_AX
	,P.MARCHE_PURCHIDREF

/*	
select * from @TAB_PEDIDO
select * from @TAB_RECEBIMENTO
*/


--BI.DBO.FN_FORMATAVLR_EXCEL