DECLARE @TAB_FORN_AUTO AS TABLE
(
	COD_FORNECEDOR INT
)
INSERT INTO @TAB_FORN_AUTO
	SELECT DISTINCT COD_FORNECEDOR
	FROM
		[BI].[dbo].[COMPRAS_AGENDA_PEDIDO_AUTO] APA
	WHERE 1=1
		AND FLG_ATIVO = 1

INSERT INTO BI.dbo.COMPRA_PRODUTO_PARAMETRO
(
	COD_LOJA
	,COD_PRODUTO
	,FAT_SZ
	,DIA_SS
	,QTD_EXP
	,QTD_DIAS_MAX_COMPRA
	,COD_USUARIO
)
SELECT DISTINCT
	LP.COD_LOJA
	,FP.COD_PRODUTO
	--,CP.DESCRICAO AS NO_PRODUTO
	,1 AS FAT_SZ
	,3 AS DIA_SS
	,3 AS QTD_EXP
	,1 AS QTD_DIAS_MAX_COMPRA
	,99999
FROM
	BI.DBO.BI_CAD_FORNECEDOR_PRODUTO AS FP
	INNER JOIN @TAB_FORN_AUTO AS FA
		ON FP.COD_FORNECEDOR = FA.COD_FORNECEDOR
	INNER JOIN BI.dbo.BI_LINHA_PRODUTOS AS LP
		ON FP.COD_PRODUTO = LP.COD_PRODUTO	
	INNER JOIN BI.dbo.BI_CAD_PRODUTO AS CP
		ON FP.COD_PRODUTO = CP.COD_PRODUTO
	INNER JOIN BI.dbo.BI_CAD_FORNECEDOR AS CF
		ON FP.COD_FORNECEDOR = CF.COD_FORNECEDOR		
	LEFT JOIN COMPRA_PRODUTO_PARAMETRO AS PP
		ON 1=1
		AND FP.COD_PRODUTO = PP.COD_PRODUTO
		AND LP.COD_LOJA = PP.COD_LOJA		
WHERE 1=1
	AND LP.FORA_LINHA = 'N'
	AND PP.COD_PRODUTO IS NULL