	SELECT DISTINCT
		'OC criada no AX, PARA OUTRO FORNECEDOR. OV marcada incorretamente. NAO CENTRALIZOU' --+ convert(varchar(max),ISNULL(PT.MARCHE_ERRO_INTEGRACAO,'')) AS MSG_ERRO
		,P.ID_SIMULADO
		,P.ID_AGENDA
		,A.COD_FORNECEDOR
		,CF2.DESCRICAO AS [Desc. Forn. Agenda]
		,P.COD_PEDIDO
		,CONVERT(DATE,P.DATA)
		,P.[COD_LOJA] as [Loja]	
		--,SUM(ISNULL(P.FLG_ITEM_PURCHTABLE,0)) AS QTD_ITEM_PURCH
	FROM
		[BI].[DBO].[COMPRAS_PEDIDOS] AS P
		INNER JOIN BI.DBO.BI_CAD_PRODUTO AS CP
			ON P.COD_PRODUTO = CP.COD_PRODUTO
		INNER JOIN BI.DBO.BI_CAD_FORNECEDOR AS CF
			ON P.COD_FORNECEDOR = CF.COD_FORNECEDOR
		LEFT JOIN [BI].[dbo].[COMPRAS_AGENDA_PEDIDO_AUTO] AS A
			ON P.ID_AGENDA = A.ID
		LEFT JOIN BI.DBO.BI_CAD_FORNECEDOR AS CF2
			ON A.COD_FORNECEDOR = CF2.COD_FORNECEDOR
	WHERE 1=1
		AND CONVERT(DATE,DATA) >= CONVERT(DATE,GETDATE()-7)
		AND P.COD_PEDIDO IS NOT NULL
		AND P.FLG_CENTRALIZADO = 1
		AND FLG_INTEGRADO_AX = 1
		AND ISNULL(P.MARCHE_PURCHIDREF,'') <> ''
		and P.FLG_INTEGRADO_PURCHTABLE IS not NULL
	GROUP BY
		P.ID_SIMULADO
		,P.ID_AGENDA
		,A.COD_FORNECEDOR
		,CF2.DESCRICAO
		,P.COD_PEDIDO
		,CONVERT(DATE,P.DATA)
		,P.[COD_LOJA]
	HAVING
		SUM(ISNULL(P.FLG_ITEM_PURCHTABLE,0)) = 0
		
	SELECT * FROM COMPRAS_PEDIDOS AS P WHERE ID_SIMULADO = 7167 AND CONVERT(DATE,DATA) = CONVERT(DATE,'2016-09-12')
	
	AND P.COD_PEDIDO IS NOT NULL
		AND P.FLG_CENTRALIZADO = 1
		AND FLG_INTEGRADO_AX = 1
		AND ISNULL(P.MARCHE_PURCHIDREF,'') <> ''
		and P.FLG_INTEGRADO_PURCHTABLE IS not NULL
		
		
	SELECT * FROM SMA_AX50_SP1_DB_PROD.DBO.PURCHTABLE AS PT WHERE PURCHID = 'CD_0004293'
	SELECT * FROM SMA_AX50_SP1_DB_PROD.DBO.PURCHLINE AS PT WHERE PURCHID = 'CD_0004293'