		SELECT
			--COUNT(CASE WHEN DATEDIFF(MINUTE,WMS.DT_INCLUSAO,NFN.DTAUTORIZACAONFE) > 30 THEN 1 ELSE NULL END) AS QTD_NFD_EMITIDA_FORA_SLA
			RC_DEV.COD_PEDIDO
			,WMS.NU_NOTA
			,WMS.CD_FORNECEDOR
			,WMS.DT_INCLUSAO
			,NFN.DTAUTORIZACAONFE
			,(CASE WHEN DATEDIFF(MINUTE,WMS.DT_INCLUSAO,NFN.DTAUTORIZACAONFE) > 30 THEN 1 ELSE NULL END) AS NFD_EMITIDA_FORA_SLA
		FROM
			(SELECT
			DISTINCT
			IDENTIFICADOR,
			COD_PEDIDO
			FROM MARCHECORP.dbo.TAB_RECEB_MERCADORIA_CONFERENCIA
			WHERE
			CAST(DTA_CRIACAO as DATE) >= '2016-04-01'
			--CAST(DTA_CRIACAO as DATE) = CAST(GETDATE() as DATE)
			AND ((QTD_CONTAGEM <> 0 AND QTD_ORIGINAL <> QTD_CONTAGEM) OR QTD_DEVOLUCAO <> 0)
			AND DTA_CONTAGEM IS NOT NULL) RC_DEV
			 
			LEFT JOIN WMS.DBO.INT_S_CAB_NOTA_FISCAL WMS ON
			WMS.NU_NOTA = RC_DEV.IDENTIFICADOR AND
			WMS.NU_DOC_ERP = RC_DEV.COD_PEDIDO		 
		LEFT JOIN 
			(select
			DISTINCT
			DTA_EMISSAO,
			COD_FORNECEDOR,
			NUM_NF_FORN,
			NUM_SERIE_NF,
			purchId,
			NF_REFER
			from
			[DW].[dbo].[vw_NF_Devolucao]
			where DTA_EMISSAO >= GETDATE() - 30) NF_DEV ON
			NF_DEV.NF_REFER = RC_DEV.IDENTIFICADOR
		 
		LEFT JOIN NortiaIT.DBO.MOV_SAIDA NFN ON
			NFN.NUMNOTA = NF_DEV.NUM_NF_FORN AND
			NFN.CODFIL = 5		 
		WHERE NF_DEV.NF_REFER IS NOT NULL
		AND DTA_EMISSAO = CONVERT(dATE,GETDATE());
