select
	COD_LOJA
	,COD_PRODUTO
	,CLASSIF_PRODUTO_LOJA AS ABC
	,BI.dbo.fn_FormataVlr_Excel(AVG_QTD_U30D_PD) AS AVG_QTD_U30D_PD
	,BI.dbo.fn_FormataVlr_Excel(AVG_QTD_U90D_PD) AS AVG_QTD_U90D_PD
	,BI.dbo.fn_FormataVlr_Excel(AVG_QTD_U180D_PD) AS AVG_QTD_U180D_PD
from
	BI.dbo.COMPRAS_ESTATISTICA_PRODUTO 