SELECT
	ENC.COD_FORNECEDOR
	,CONVERT(DATE,ENC.DATA_PAGTO) AS DUEDATE
	,CONVERT(DATE,DOCUMENTDATE) AS DATA_ENTRADA_NF
	,BI.DBO.FN_FORMATAVLR_EXCEL(ENC.[VALOR_PAGO]) AS VALOR_ENCERRADO
	,ENC.NUM_NF_PARCELA AS [NUM_NF]
	,[METODO_PAGTO]
	,ENC.[COD_LOJA]	
	,(CASE WHEN ENC.[PRIORITARIO] = 1 THEN 'Prioritario' ELSE 'Normal' END) AS [PRIORITARIO]
	,ENC.TIPO_ESTABELECIMENTO
	,'Já Pago' as STATUS_PGTO
FROM
	[AX2009_INTEGRACAO].[dbo].TAB_CONTAS_A_PAGAR_ENCERRADAS as ENC
WHERE 1=1
	AND CONVERT(DATE,ENC.DATA_PAGTO) between CONVERT(DATE,'2015-01-01') AND CONVERT(DATE,'2016-12-30')
	--AND TIPO_ESTABELECIMENTO NOT IN ('OUTROS','PJ','PRESTADOR SERVIÇOS','INTERCOMPANY')
;