DECLARE @TAB_ID_DUPLICADO AS TABLE
(
	COD_FORNECEDOR INT
	,MAX_ID INT
)

INSERT INTO @TAB_ID_DUPLICADO
	SELECT 
		COD_FORNECEDOR
		,MAX(ID) AS MAX_ID
	FROM
		BI.DBO.COMPRAS_AGENDA_PEDIDO_AUTO
	WHERE 1=1
		AND FLG_ATIVO IS NULL
		AND COD_FORNECEDOR IN
			(SELECT COD_FORNECEDOR FROM
			(
				SELECT
					COD_FORNECEDOR
					,FLG_ATIVO
					,TIPO
					,LISTA_LOJA
					,LISTA_DEP
					,LISTA_SECAO
					,COUNT(DISTINCT ID) AS QTD_ID
				FROM
					BI.DBO.COMPRAS_AGENDA_PEDIDO_AUTO
				WHERE 1=1
					--AND FLG_ATIVO IS NULL
				GROUP BY
					COD_FORNECEDOR
					,FLG_ATIVO
					,TIPO
					,LISTA_LOJA
					,LISTA_DEP
					,LISTA_SECAO
				HAVING
					COUNT(DISTINCT ID) > 1
			) AS X )
	GROUP BY
		COD_FORNECEDOR
	ORDER BY
		COD_FORNECEDOR
		
--DELETE A
FROM
	BI.DBO.COMPRAS_AGENDA_PEDIDO_AUTO AS A
	INNER JOIN @TAB_ID_DUPLICADO AS T
		ON A.ID = T.MAX_ID

