	DECLARE @DATA_INI AS DATE = GETDATE()-90
	DECLARE @DATA_FIM AS DATE = GETDATE()
	
	DECLARE @TEMP_PEDIDOS_ABERTOS AS TABLE
	(
		COD_LOJA INT
		,COD_FORNECEDOR INT
		,DTA_EMISSAO DATE
		,COD_PRODUTO INT
		,QTD_PEDIDO NUMERIC(18,2)
		,QTD_RECEBIDA NUMERIC(18,2)
	)
	INSERT INTO @TEMP_PEDIDOS_ABERTOS
		SELECT	
			P.COD_LOJA
			,convert(int,P.COD_PARCEIRO) as COD_FORNECEDOR
			,CONVERT(DATE,DTA_EMISSAO) as DTA_EMISSAO
			,PP.COD_PRODUTO
			,SUM(PP.QTD_PEDIDO) AS QTD_PEDIDO
			,SUM(PP.QTD_RECEBIDA) AS QTD_RECEBIDA		
		FROM
			[192.168.0.6].[ZEUS_RTG].DBO.[TAB_PEDIDO] AS P
			INNER JOIN [192.168.0.6].[ZEUS_RTG].DBO.[TAB_PEDIDO_PRODUTO] AS PP
				ON 1=1
				and P.NUM_PEDIDO = PP.NUM_PEDIDO
				AND P.COD_LOJA = PP.COD_LOJA
				AND P.COD_PARCEIRO = PP.COD_PARCEIRO
		WHERE 1 = 1
			AND CONVERT(DATE,P.DTA_EMISSAO) between CONVERT(DATE,@DATA_INI) AND CONVERT(DATE,@DATA_FIM)
			--AND CONVERT(DATE,DATEADD(D,7,P.DTA_ENTREGA)) <= CONVERT(DATE,GETDATE())
			AND PP.QTD_EMBALAGEM <> 0
			--AND P.COD_LOJA = 3
		GROUP BY
			P.COD_LOJA
			,convert(int,P.COD_PARCEIRO)
			,CONVERT(DATE,DTA_EMISSAO)
			,PP.COD_PRODUTO	
	
	DECLARE @TAB_PEDIDOS_SHELFLIFE AS TABLE
	(
		COD_LOJA INT
		,COD_PRODUTO INT
		,QTD_PEDIDO NUMERIC(18,2)
	)
	INSERT INTO @TAB_PEDIDOS_SHELFLIFE	
		SELECT
			T.COD_LOJA
			,T.COD_PRODUTO
			,sum(T.QTD_PEDIDO) as QTD_PEDIDO_SHELF_LIFE
		FROM
			@TEMP_PEDIDOS_ABERTOS AS T
			INNER JOIN BI.dbo.BI_CAD_PRODUTO AS CP
				ON T.COD_PRODUTO = CP.COD_PRODUTO				
		WHERE 1=1
			AND T.QTD_RECEBIDA = 0
			AND CONVERT(DATE,T.DTA_EMISSAO) >= CONVERT(DATE,DATEADD(D,CP.MARCHE_SHELFLIFE*-1,GETDATE()))
			AND CP.COD_DEPARTAMENTO = 4
			AND CP.COD_SECAO IN (44,45,46,48)
			AND T.COD_LOJA = 3
		GROUP BY
			T.COD_LOJA
			,T.COD_PRODUTO
	
	DECLARE @TAB_VENDA_SHELFLIFE AS TABLE
	(
		COD_LOJA INT
		,COD_PRODUTO INT
		,QTD_VENDA NUMERIC(18,2)
	)
	INSERT INTO @TAB_VENDA_SHELFLIFE		
		SELECT
			VP.COD_LOJA
			,VP.COD_PRODUTO
			,sum(VP.QTDE_PRODUTO) as QTD_VENDA
		FROM
			BI.dbo.BI_VENDA_PRODUTO AS VP
			INNER JOIN BI.dbo.BI_CAD_PRODUTO AS CP
				ON VP.COD_PRODUTO = CP.COD_PRODUTO				
		WHERE 1=1
			AND CONVERT(DATE,VP.DATA) >= CONVERT(DATE,DATEADD(D,CP.MARCHE_SHELFLIFE*-1,GETDATE()))
			AND CP.COD_DEPARTAMENTO = 4
			AND CP.COD_SECAO IN (44,45,46,48)
			AND VP.COD_LOJA = 3
		GROUP BY
			VP.COD_LOJA
			,VP.COD_PRODUTO

	SELECT
		LP.COD_LOJA
		,LP.COD_PRODUTO
		,CP.DESCRICAO
		,BI.dbo.fn_FormataVlr_Excel(ISNULL(P.QTD_PEDIDO,0)) AS QTD_PEDIDO
		,BI.dbo.fn_FormataVlr_Excel(ISNULL(V.QTD_VENDA,0)) AS QTD_VENDA
		,BI.dbo.fn_FormataVlr_Excel(ISNULL(P.QTD_PEDIDO-V.QTD_VENDA,0)) AS QTD_ESTOQUE_VIRTUAL
	FROM
		BI.dbo.BI_LINHA_PRODUTOS AS LP
		INNER JOIN BI.dbo.BI_CAD_PRODUTO AS CP
				ON LP.COD_PRODUTO = CP.COD_PRODUTO
		LEFT JOIN @TAB_PEDIDOS_SHELFLIFE AS P
			ON 1=1
			AND LP.COD_LOJA = P.COD_LOJA
			AND LP.COD_PRODUTO = P.COD_PRODUTO
		LEFT JOIN @TAB_VENDA_SHELFLIFE AS V
			ON 1=1
			AND LP.COD_LOJA = V.COD_LOJA
			AND LP.COD_PRODUTO = V.COD_PRODUTO
	WHERE 1=1
		AND LP.COD_LOJA = 3
		AND LP.COD_DEPARTAMENTO = 4
		AND LP.COD_SECAO IN (44,45,46,48)
		AND LP.FORA_LINHA = 'N'