SELECT --top 10
	P.COD_LOJA
	,p.COD_PARCEIRO as [Cod Forn]
	,FORN.DES_FORNECEDOR as [Cod Forn]	
	,P.NUM_PEDIDO
	,CONVERT(DATE,P.DTA_EMISSAO) AS DT_EMISSAO		
	,COUNT(PP.COD_PRODUTO) [Qtd Itens]
FROM
	[ZEUS_RTG].DBO.[TAB_PEDIDO] AS P INNER JOIN [ZEUS_RTG].DBO.[TAB_PEDIDO_PRODUTO] AS PP
		ON 1=1
		AND P.NUM_PEDIDO = PP.NUM_PEDIDO
		AND P.COD_LOJA = PP.COD_LOJA
		AND P.COD_PARCEIRO = PP.COD_PARCEIRO
		AND P.COD_USUARIO = P.COD_USUARIO
	INNER JOIN [ZEUS_RTG].DBO.[TAB_PRODUTO] AS PROD ON (PP.COD_PRODUTO = PROD.COD_PRODUTO)
	INNER JOIN [ZEUS_RTG].DBO.[TAB_FORNECEDOR] AS FORN ON (PP.COD_PARCEIRO = FORN.COD_FORNECEDOR)
WHERE 1 = 1
	AND CONVERT(DATE,P.DTA_EMISSAO) BETWEEN CONVERT(DATE,GETDATE()-90) AND CONVERT(DATE,GETDATE()-1)
	--AND P.COD_PARCEIRO IN (13984)--(17467,1000,302,103055,14086,16583,102979,102875,103270,16088,15973,13956,2437,189)
	and p.COD_LOJA = 24
GROUP BY
	P.COD_LOJA
	,p.COD_PARCEIRO
	,FORN.DES_FORNECEDOR
	,P.NUM_PEDIDO
	,CONVERT(DATE,P.DTA_EMISSAO)
order by
	P.COD_LOJA
	,p.COD_PARCEIRO
	,CONVERT(DATE,P.DTA_EMISSAO)
