SELECT
	VP.COD_LOJA
	,CP.COD_PRODUTO
	,CP.DESCRICAO
	,BI.dbo.fn_FormataVlr_Excel(SUM(CASE WHEN CONVERT(DATE,VP.DATA) BETWEEN CONVERT(DATE,GETDATE()-180) AND CONVERT(DATE,GETDATE()-1) THEN VP.VALOR_TOTAL ELSE 0 END)) AS VLR_TOTAL_6M
	,BI.dbo.fn_FormataVlr_Excel(SUM(CASE WHEN CONVERT(DATE,VP.DATA) BETWEEN CONVERT(DATE,GETDATE()-180) AND CONVERT(DATE,GETDATE()-1) THEN VP.QTDE_PRODUTO ELSE 0 END)) AS QTD_TOTAL_6M
	,BI.dbo.fn_FormataVlr_Excel(SUM(CASE WHEN CONVERT(DATE,VP.DATA) BETWEEN CONVERT(DATE,GETDATE()-180) AND CONVERT(DATE,GETDATE()-1) THEN VP.VALOR_TOTAL ELSE 0 END) / NULLIF(SUM(CASE WHEN CONVERT(DATE,VP.DATA) BETWEEN CONVERT(DATE,GETDATE()-180) AND CONVERT(DATE,GETDATE()-1) THEN VP.QTDE_PRODUTO ELSE 0 END),0)) AS VM_6M
	,BI.dbo.fn_FormataVlr_Excel(SUM(CASE WHEN CONVERT(DATE,VP.DATA) BETWEEN CONVERT(DATE,GETDATE()-90) AND CONVERT(DATE,GETDATE()-1) THEN VP.VALOR_TOTAL ELSE 0 END)) AS VLR_TOTAL_3M
	,BI.dbo.fn_FormataVlr_Excel(SUM(CASE WHEN CONVERT(DATE,VP.DATA) BETWEEN CONVERT(DATE,GETDATE()-90) AND CONVERT(DATE,GETDATE()-1) THEN VP.QTDE_PRODUTO ELSE 0 END)) AS QTD_TOTAL_3M
	,BI.dbo.fn_FormataVlr_Excel(SUM(CASE WHEN CONVERT(DATE,VP.DATA) BETWEEN CONVERT(DATE,GETDATE()-90) AND CONVERT(DATE,GETDATE()-1) THEN VP.VALOR_TOTAL ELSE 0 END) / NULLIF(SUM(CASE WHEN CONVERT(DATE,VP.DATA) BETWEEN CONVERT(DATE,GETDATE()-90) AND CONVERT(DATE,GETDATE()-1) THEN VP.QTDE_PRODUTO ELSE 0 END),0)) AS VM_3M
FROM
	BI_CAD_PRODUTO AS CP
	INNER JOIN BI_VENDA_PRODUTO AS VP
		ON CP.COD_PRODUTO = VP.COD_PRODUTO
WHERE 1=1
	AND CONVERT(DATE,VP.DATA) BETWEEN CONVERT(DATE,GETDATE()-180) AND CONVERT(DATE,GETDATE()-1)
GROUP BY
	VP.COD_LOJA
	,CP.COD_PRODUTO
	,CP.DESCRICAO
ORDER BY
	CP.DESCRICAO
	,VP.COD_LOJA
	