DECLARE @TAB_FORN_AUTO AS TABLE
(
	COD_FORNECEDOR INT
)
INSERT INTO @TAB_FORN_AUTO
	SELECT DISTINCT COD_FORNECEDOR
	FROM
		[BI].[dbo].[COMPRAS_AGENDA_PEDIDO_AUTO] APA
	WHERE 1=1
		AND FLG_ATIVO = 1

SELECT DISTINCT
	FP.COD_PRODUTO
	,CP.DESCRICAO AS NO_PRODUTO
	,FP.COD_FORNECEDOR AS NO_PRODUTO
	,CF.DESCRICAO AS NO_PRODUTO
	,(CASE WHEN FB.COD_FORNECEDOR IS NOT NULL THEN 'BLOQUEADO' ELSE '' END) AS FLG_BLOQ
FROM
	BI.DBO.BI_CAD_FORNECEDOR_PRODUTO AS FP
	INNER JOIN @TAB_FORN_AUTO AS FA
		ON FP.COD_FORNECEDOR = FA.COD_FORNECEDOR
	INNER JOIN BI.dbo.BI_CAD_PRODUTO AS CP
		ON FP.COD_PRODUTO = CP.COD_PRODUTO
	INNER JOIN BI.dbo.BI_CAD_FORNECEDOR AS CF
		ON FP.COD_FORNECEDOR = CF.COD_FORNECEDOR		
	LEFT JOIN [SUPPLY_PRODUTO_BLOQUEADO_FORN_AUTO] AS FB
		ON 1=1
		AND FB.COD_PRODUTO = FP.COD_PRODUTO
		AND FB.COD_FORNECEDOR = FP.COD_FORNECEDOR		
WHERE 1=1
	AND CP.FORA_LINHA = 'N'
