/*
update COMPRAS_PEDIDOS set FLG_CENTRALIZADO = 1 where FLG_AUTOMATICO = 1 and COD_FORNECEDOR = 18055 and CONVERT(date,data) >= '2015-11-20' and COD_PEDIDO is not null and FLG_CENTRALIZADO is null

select *,DATEPART(DW,[DATA_BASE]) from [BI].[dbo].[COMPRAS_AGENDA_PEDIDO_AUTO] where cod_fornecedor = 102778

SELECT * FROM  [BI].[dbo].[COMPRAS_AGENDA_PEDIDO_AUTO] WHERE cod_fornecedor in (125)




SELECT * FROM  [BI].[dbo].[COMPRAS_AGENDA_PEDIDO_AUTO] WHERE flg_ativo = 1 and id not in (12,556)

select DATEPART(DW,'2015-09-25')

update [BI].[dbo].[COMPRAS_AGENDA_PEDIDO_AUTO] set FLG_ATIVO = null where id in (978)


SELECT * FROM [SUPPLY_PRODUTO_BLOQUEADO_LOJA_AUTO] where COD_PRODUTO = 927956 
--AND COD_LOJA = 3


select * from [SUPPLY_PRODUTO_BLOQUEADO_FORN_AUTO] where  COD_PRODUTO = 1013790	 
*/
DECLARE @TAB_FORN_AUTO AS TABLE
(
	COD_FORNECEDOR INT
	,DIA_SEMANA INT
)
INSERT INTO @TAB_FORN_AUTO
	SELECT DISTINCT COD_FORNECEDOR, DATEPART(DW,[DATA_BASE])
	FROM
		[BI].[dbo].[COMPRAS_AGENDA_PEDIDO_AUTO] APA
	WHERE 1=1
		AND FLG_ATIVO = 1

SELECT
	P.[COD_FORNECEDOR] as [Cod. Forn.]
	,CF.DESCRICAO AS [Desc. Forn.]
	,P.DATA
	,DATEPART(DW,DATA) AS DIA_SEMANA_PEDIDO
	,F.DIA_SEMANA AS DIA_SEMANA_AGENDA_AUTO
	,P.[COD_LOJA] as [Loja]
	,P.[COD_PRODUTO] as [PLU]
	,CP.DESCRICAO AS [Desc. PLU]
	,(CASE WHEN PB.COD_PRODUTO IS NOT NULL OR PBF.COD_PRODUTO IS NOT NULL THEN 1 ELSE 0 END) FLG_BLOQUEADO
	,(CASE WHEN PB.COD_PRODUTO IS NOT NULL THEN 1 ELSE 0 END) FLG_BLOQUEADO_LOJA
	,(CASE WHEN PBF.COD_PRODUTO IS NOT NULL THEN 1 ELSE 0 END) FLG_BLOQUEADO_FORN
	,BI.DBO.FN_FORMATAVLR_EXCEL([QTD_EMBALAGEM]) AS [Pedido]
	,[COD_COMPRADOR] as [Cod. Comprador]
	,BI.DBO.FN_FORMATAVLR_EXCEL([QTD_ESTOQUE]) AS [Estoque]
	,BI.DBO.FN_FORMATAVLR_EXCEL([VLR_EMB]) AS [Valor CX]
	,BI.DBO.FN_FORMATAVLR_EXCEL([VLR_MULTIPLO]) AS [Qtde Múltiplo]
	,BI.DBO.FN_FORMATAVLR_EXCEL([QTD_EMB_ORG]) AS [Qtde Embalagem]
	,BI.DBO.FN_FORMATAVLR_EXCEL([VLR_REV_TIME]) AS [Freq. Pedido]
	,BI.DBO.FN_FORMATAVLR_EXCEL([VLR_LEAD_TIME]) AS [Lead time]
	,BI.DBO.FN_FORMATAVLR_EXCEL([AVG_QTD_U30D_PD]) AS [VMD 180D]
	,BI.DBO.FN_FORMATAVLR_EXCEL([QTD_SS_DIAS]) AS [Est. Seg. (dias)]
	,BI.DBO.FN_FORMATAVLR_EXCEL([FAT_SAZ]) AS [% Sazon.]
	,BI.DBO.FN_FORMATAVLR_EXCEL([QTD_MIN_UN]) AS [Exposição (qtde)]
	,[ABC_VLR] as [Classif. PLU]
	,P.COD_PEDIDO AS [Cod Pedido]
	,BI.DBO.FN_FORMATAVLR_EXCEL([QTD_EMBALAGEM]*[VLR_EMB]) AS [Pedido * Valor CX]
	,(case when FLG_TESTE is not null then 1 else 0 end) as FLG_AUTO
	--,DATA
	--,ID
FROM
	[BI].[DBO].[COMPRAS_PEDIDOS] AS P
	INNER JOIN @TAB_FORN_AUTO AS F
		ON P.COD_FORNECEDOR = F.COD_FORNECEDOR
	INNER JOIN BI.DBO.BI_CAD_PRODUTO AS CP
		ON P.COD_PRODUTO = CP.COD_PRODUTO
	INNER JOIN BI.DBO.BI_CAD_FORNECEDOR AS CF
		ON P.COD_FORNECEDOR = CF.COD_FORNECEDOR	
	LEFT JOIN [BI].[dbo].[SUPPLY_PRODUTO_BLOQUEADO_LOJA_AUTO] AS PB
		ON 1=1
		AND P.COD_LOJA = PB.COD_LOJA
		AND P.COD_PRODUTO = PB.COD_PRODUTO
	LEFT JOIN [BI].[dbo].[SUPPLY_PRODUTO_BLOQUEADO_FORN_AUTO] AS PBF
		ON 1=1
		AND PBF.COD_FORNECEDOR = P.COD_FORNECEDOR
		AND P.COD_PRODUTO = PBF.COD_PRODUTO				
WHERE 1=1
	AND CONVERT(DATE,DATA) >= CONVERT(DATE,'2015-10-07')
	AND CP.COD_DEPARTAMENTO IN (2,9,10,13,3,12)
	AND P.COD_PEDIDO IS NOT NULL
	AND P.COD_LOJA not in (29,33,5)
	--AND P.COD_PEDIDO = 900835
	--AND PB.COD_PRODUTO IS NULL
	--AND PBF.COD_PRODUTO IS NULL
	--and FLG_TESTE is null
ORDER BY
	DATA


/*
SELECT
	[ID]
	,CF.COD_FORNECEDOR as [Cod Forn]
	,CF.DESCRICAO as Fornecedor			  
	,NO_COMPRADOR as Comprador
	,APA.[TIPO] as Tipo
	,CONVERT(DATE,[DATA_BASE]) as [Data Base]
	,(CASE
		WHEN DATEPART(DW,[DATA_BASE]) = 1 THEN 'Dom'
		WHEN DATEPART(DW,[DATA_BASE]) = 2 THEN 'Seg'
		WHEN DATEPART(DW,[DATA_BASE]) = 3 THEN 'Ter'
		WHEN DATEPART(DW,[DATA_BASE]) = 4 THEN 'Qua'
		WHEN DATEPART(DW,[DATA_BASE]) = 5 THEN 'Qui'
		WHEN DATEPART(DW,[DATA_BASE]) = 6 THEN 'Sex'
		WHEN DATEPART(DW,[DATA_BASE]) = 7 THEN 'Sab'
	END) AS DIA
	,CONVERT(DATE,[DATA_BASE]) as [Data Base]
	,[DIAS_REVIEW_TIME] as [Review(dias)]
	,[DIAS_LEAD_TIME]as [Lead Time(dias)]
	,[DIAS_SS]as [SS(dias)]
	,[LISTA_LOJA] as [Lista loja]
	,[LISTA_DEP] as [Lista dep]
	,[LISTA_SECAO] as [Lista sec]
	,[VLR_PEDIDO_MIN] as [Vlr ped min]
	,[COD_CFOP] as [CFOP]
	,APA.[FLG_ATIVO] as [Flg Ativo]
	,CONVERT(DATE,APA.[DTA_GRAVACAO]) [Data Gravacao]
	,[OBSERVACAO] as [Obs]
FROM
	[BI].[dbo].[COMPRAS_AGENDA_PEDIDO_AUTO] APA
	LEFT JOIN BI.dbo.BI_CAD_FORNECEDOR CF
		ON 1=1
		AND CF.COD_FORNECEDOR =  APA.COD_FORNECEDOR
	LEFT JOIN BI.dbo.COMPRAS_CAD_COMPRADOR CC
		ON 1=1
		AND CC.COD_USUARIO =  APA.COD_COMPRADOR
WHERE 1=1	
*/