	DECLARE @DATA_INI AS DATE = GETDATE()-90
	DECLARE @DATA_FIM AS DATE = GETDATE()

select
	COD_FORNECEDOR
	,DES_FORNECEDOR
	,NUM_NF_FORN
	,NUM_SERIE_NF
	,convert(date,DTA_ENTRADA) as DTA_ENTRADA
	,COD_PRODUTO
	,DES_PRODUTO
	,VAL_TABELA_LIQ as VLR_ENTRADA
from
	Zeus_rtg.dbo.vw_MARCHE_ENTRADAS as E
WHERE 1=1
	AND E.COD_FORNECEDOR IN (SELECT DISTINCT COD_PARCEIRO FROM [Zeus_rtg].DBO.[TAB_PEDIDO] AS P WHERE 1=1 AND CONVERT(DATE,DTA_EMISSAO) BETWEEN CONVERT(DATE,@DATA_INI) AND CONVERT(DATE,@DATA_FIM))
	AND CONVERT(DATE,DTA_ENTRADA) between CONVERT(DATE,@DATA_INI) AND CONVERT(DATE,@DATA_FIM)
	and E.COD_PRODUTO in (select distinct COD_PRODUTO from [192.168.0.13].bi.dbo.bi_cad_produto as cp where pnp = 'NP')