select
	E.COD_LOJA
	,''''+L.NUM_CGC AS CNPJ_LOJA
	,E.COD_FORNECEDOR
	,E.DES_FORNECEDOR
	,''''+F.NUM_CGC AS CNPJ_FORN
	,E.NUM_NF_FORN
	,E.NUM_SERIE_NF
	,convert(date,E.DTA_ENTRADA) as DTA_ENTRADA
	--,COD_PRODUTO
	--,DES_PRODUTO
	,SUM(E.VAL_TABELA_LIQ) as VLR_ENTRADA
from
	Zeus_rtg.dbo.vw_MARCHE_ENTRADAS as E
	LEFT JOIN Zeus_rtg.dbo.TAB_LOJA AS L
		ON E.COD_LOJA = L.COD_LOJA
	LEFT JOIN Zeus_rtg.dbo.TAB_FORNECEDOR AS F
		ON E.COD_FORNECEDOR = F.COD_FORNECEDOR
WHERE 1=1
	AND E.COD_FORNECEDOR = 18055
	AND CONVERT(DATE,E.DTA_ENTRADA) between CONVERT(DATE,'20150801') AND CONVERT(DATE,'20151207')
GROUP BY
	E.COD_LOJA
	,L.NUM_CGC
	,E.COD_FORNECEDOR
	,E.DES_FORNECEDOR
	,F.NUM_CGC
	,E.NUM_NF_FORN
	,E.NUM_SERIE_NF
	,convert(date,E.DTA_ENTRADA)
ORDER BY
	E.COD_LOJA
	,convert(date,E.DTA_ENTRADA)
