SELECT --top 10
	P.COD_LOJA
	,CONVERT(DATE,P.DTA_EMISSAO) AS DT_EMISSAO	
	,CONVERT(DATE,P.DTA_ENTREGA) AS DT_ENTREGA
	,p.COD_PARCEIRO as [Cod Forn]
	,FORN.DES_FORNECEDOR as [Cod Forn]
	,P.NUM_PEDIDO
	,PP.COD_PRODUTO AS [Plu]
	,PROD.DES_PRODUTO as [Produto]--PROD.DES_PRODUTO
	--,PP.DES_REFERENCIA as [Ref]
	,PP.QTD_PEDIDO as [Qtd Ped]
	,PP.QTD_EMBALAGEM as [Qtd Emb]
	,PP.VAL_TABELA as [Vlr Tabela]
	,(PP.VAL_TABELA*PP.QTD_PEDIDO) AS [Vlr Total]
	,ISNULL(PP.QTD_RECEBIDA,0) AS [Qtd Recebida]
--	,USR.NO_COMPRADOR  AS [Comprador]--USR.DES_NOME 
FROM
	[ZEUS_RTG].DBO.[TAB_PEDIDO] AS P INNER JOIN [ZEUS_RTG].DBO.[TAB_PEDIDO_PRODUTO] AS PP
		ON 1=1
		AND P.NUM_PEDIDO = PP.NUM_PEDIDO
		AND P.COD_LOJA = PP.COD_LOJA
		AND P.COD_PARCEIRO = PP.COD_PARCEIRO
		AND P.COD_USUARIO = P.COD_USUARIO
	INNER JOIN [ZEUS_RTG].DBO.[TAB_PRODUTO] AS PROD ON (PP.COD_PRODUTO = PROD.COD_PRODUTO)
	INNER JOIN [ZEUS_RTG].DBO.[TAB_FORNECEDOR] AS FORN ON (PP.COD_PARCEIRO = FORN.COD_FORNECEDOR)
		--LEFT JOIN [192.168.0.13].[BI].DBO.[BI_CAD_PRODUTO] AS PROD ON (PP.COD_PRODUTO = PROD.COD_PRODUTO)
		--INNER JOIN [ZEUS_RTG].DBO.[TAB_USUARIO] AS USR ON (P.COD_USUARIO = USR.COD_USUARIO)
		--LEFT JOIN [192.168.0.13].[BI].DBO.[COMPRAS_CAD_COMPRADOR] AS USR ON (P.COD_USUARIO = USR.COD_USUARIO)
WHERE 1 = 1
	AND CONVERT(DATE,P.DTA_EMISSAO) BETWEEN CONVERT(DATE,GETDATE()-180) AND CONVERT(DATE,GETDATE()-1)
	AND P.COD_PARCEIRO IN (13984)--(17467,1000,302,103055,14086,16583,102979,102875,103270,16088,15973,13956,2437,189)
	AND P.COD_LOJA = 24
order by
	P.COD_LOJA
	,CONVERT(DATE,P.DTA_EMISSAO)
