	SELECT	
		P.COD_LOJA
		,P.COD_PARCEIRO as COD_FORNECEDOR
		,P.NUM_PEDIDO AS NUM_PEDIDO
		,PP.COD_PRODUTO
		,PP.QTD_PEDIDO AS QTD_PEDIDO
		,ISNULL(PP.QTD_RECEBIDA,0) AS QTD_RECEBIDA	
		,PP.QTD_PEDIDO*PP.QTD_EMBALAGEM AS QTD_PEDIDO_VEZES_EMBALAGEM
    FROM
		[192.168.0.6].[ZEUS_RTG].DBO.[TAB_PEDIDO] AS P
		INNER JOIN [192.168.0.6].[ZEUS_RTG].DBO.[TAB_PEDIDO_PRODUTO] AS PP
			ON 1=1
			and P.NUM_PEDIDO = PP.NUM_PEDIDO
			AND P.COD_LOJA = PP.COD_LOJA
			AND P.COD_PARCEIRO = PP.COD_PARCEIRO
    WHERE 1 = 1
		AND CONVERT(DATE,P.DTA_EMISSAO) >= CONVERT(DATE,'2016-01-01') 
		AND PP.QTD_EMBALAGEM <> 0
		--and p.num_pedido = 1078180
		and PP.QTD_RECEBIDA > PP.QTD_PEDIDO