SELECT 
	CMV.COD_LOJA
	,CONVERT(DATE,CMV.DTA_CALCULO) AS DATA
	,CMV.COD_PRODUTO		
	,CMV.MARGEM_REF	
	,SUM(CMV.Total_Qtde) as QTD_VENDA
	,SUM(CMV.Total_Venda) as VLR_VENDA
	,SUM(CMV.Total_Impostos) as VLR_IMPOSTOS
	,SUM(CMV.VLR_CUSTO_MEDIO*CMV.Total_Qtde) AS CMV		
	,(sum(CMV.Total_Venda)-sum(CMV.Total_Impostos)-sum(CMV.VLR_CUSTO_MEDIO*CMV.Total_Qtde))/sum(CMV.Total_Venda) as Mrg
FROM
	DW.[dbo].[CMV] as CMV
	INNER JOIN BI.DBO.BI_CAD_PRODUTO AS CP
		ON CMV.COD_PRODUTO = CP.COD_PRODUTO
WHERE 1=1
	AND CONVERT(DATE,CMV.DTA_CALCULO) BETWEEN CONVERT(DATE,GETDATE()-1) AND CONVERT(DATE,GETDATE()-1)
	AND CMV.COD_PRODUTO NOT IN (1016980,1016982)
GROUP BY 	
	CMV.COD_LOJA
	,CONVERT(DATE,CMV.DTA_CALCULO)
	,CMV.COD_PRODUTO		
	,CMV.MARGEM_REF;