SELECT top 10000
	VE.[DATA]
	,VE.[COD_LOJA]
	,VE.[COD_PRODUTO]
	,CP.PNP
	,VE.[FORA_LINHA]
	,VE.[ENVIA_PDV]
	,BI.dbo.fn_FormataVlr_Excel(VE.[VLR_TOTAL]) AS [VLR_TOTAL]
	,BI.dbo.fn_FormataVlr_Excel(VE.[QTD_TOTAL]) AS [QTD_TOTAL]
	,BI.dbo.fn_FormataVlr_Excel(VE.[AVG_VLR_U30D]) AS [AVG_VLR_U30D]
	,BI.dbo.fn_FormataVlr_Excel(VE.[AVG_QTD_U30D]) AS [AVG_QTD_U30D]
	,BI.dbo.fn_FormataVlr_Excel(VE.[AVG_QTD_U180D]) AS [AVG_QTD_U180D]
	,BI.dbo.fn_FormataVlr_Excel(VE.[QTD_ESTOQUE]) AS [QTD_ESTOQUE]
	,BI.dbo.fn_FormataVlr_Excel(VE.[QTD_ESTOQUE_ZEUS]) AS [QTD_ESTOQUE_ZEUS]
	,BI.dbo.fn_FormataVlr_Excel(VE.[RUPTURA]) AS [RUPTURA]
FROM
	[BI].[dbo].[TAB_VENDA_ESTOQUE_ROBIN] as VE
	INNER JOIN [BI].[dbo].BI_CAD_PRODUTO AS CP
		ON VE.COD_PRODUTO = CP.COD_PRODUTO
WHERE 1=1
	--AND DATA >= '2015-07-05'
	AND COD_LOJA NOT IN (5,7,28,29,33)
	AND VE.FORA_LINHA = 'N'
	
	AND VE.RUPTURA IS NOT NULL
ORDER BY AVG_VLR_U30D DESC
	
/*	
UPDATE VE
SET
	RUPTURA = (CASE
				WHEN CP.PNP = 'NP' THEN (CASE WHEN QTD_ESTOQUE IS NULL THEN NULL ELSE (CASE WHEN QTD_ESTOQUE <= ISNULL(AVG_QTD_U180D,0) THEN 1 ELSE 0 END) END)	
				ELSE (CASE WHEN QTD_ESTOQUE = 0 THEN 1 ELSE 0 END)	
			END)
FROM
	[BI].[dbo].[TAB_VENDA_ESTOQUE_ROBIN] as VE
	INNER JOIN [BI].[dbo].BI_CAD_PRODUTO AS CP
		ON VE.COD_PRODUTO = CP.COD_PRODUTO
WHERE 1=1
	AND VE.FORA_LINHA = 'N'
	AND CONVERT(DATE,DATA) BETWEEN CONVERT(DATE,'2015-02-01') AND CONVERT(DATE,'2015-02-28')

UPDATE VE
SET
	RUPTURA = NULL
FROM
	[BI].[dbo].[TAB_VENDA_ESTOQUE_ROBIN] as VE
WHERE 1=1
	AND CONVERT(DATE,DATA) BETWEEN CONVERT(DATE,'2015-02-01') AND CONVERT(DATE,'2015-02-28')
	AND VE.FORA_LINHA = 'S'
*/


SELECT 
	YEAR(VE.DATA) AS ANO
	,MONTH(VE.DATA) AS MES
	,VE.COD_LOJA
	,BI.dbo.fn_FormataVlr_Excel(SUM(VE.RUPTURA)) AS QTD_RUPTURA
	,BI.dbo.fn_FormataVlr_Excel(COUNT(VE.COD_PRODUTO)) AS QTD_TOTAL
FROM
	[BI].[dbo].[TAB_VENDA_ESTOQUE_ROBIN] as VE
	--INNER JOIN [BI].[dbo].BI_CAD_PRODUTO AS CP
	--	ON VE.COD_PRODUTO = CP.COD_PRODUTO
WHERE 1=1
	--AND DATA >= '2015-07-05'
	AND COD_LOJA NOT IN (5,7,28,29,33)
	AND VE.FORA_LINHA = 'N'
	AND VE.RUPTURA IS NOT NULL
GROUP BY
	YEAR(VE.DATA)
	,MONTH(VE.DATA)
	,VE.COD_LOJA


SELECT 
	YEAR(VE.DATA) AS ANO
	,MONTH(VE.DATA) AS MES
	,VE.COD_LOJA
	,VE.COD_PRODUTO
	,BI.dbo.fn_FormataVlr_Excel(SUM(VE.RUPTURA)) AS QTD_RUPTURA
	,BI.dbo.fn_FormataVlr_Excel(COUNT(VE.COD_PRODUTO)) AS QTD_TOTAL
FROM
	[BI].[dbo].[TAB_VENDA_ESTOQUE_ROBIN] as VE
	INNER JOIN [BI].[dbo].BI_CAD_PRODUTO AS CP
		ON VE.COD_PRODUTO = CP.COD_PRODUTO
WHERE 1=1
	--AND DATA >= '2015-07-05'
	AND COD_LOJA NOT IN (5,7,28,29,33)
	AND VE.FORA_LINHA = 'N'	
	AND VE.RUPTURA IS NOT NULL
GROUP BY
	YEAR(VE.DATA)
	,MONTH(VE.DATA)
	,VE.COD_LOJA
	,VE.COD_PRODUTO
	
	
	
	
SELECT 
	YEAR(VE.DATA) AS ANO
	,MONTH(VE.DATA) AS MES
	,VE.COD_LOJA
	,VE.COD_PRODUTO
	,BI.dbo.fn_FormataVlr_Excel(LP.VLR_VENDA) VLR_VENDA
	,BI.dbo.fn_FormataVlr_Excel(SUM(VE.RUPTURA)) AS QTD_RUPTURA
	,BI.dbo.fn_FormataVlr_Excel(COUNT(VE.COD_PRODUTO)) AS QTD_TOTAL
	,BI.dbo.fn_FormataVlr_Excel(AVG(VE.AVG_QTD_U180D)) AS AVG_QTD_U180D
	,BI.dbo.fn_FormataVlr_Excel(SUM(VE.VLR_TOTAL)) AS VLR_TOTAL_VENDA
FROM
	[BI].[dbo].[TAB_VENDA_ESTOQUE_ROBIN] as VE
	INNER JOIN [BI].[dbo].BI_CAD_PRODUTO AS CP
		ON VE.COD_PRODUTO = CP.COD_PRODUTO
	INNER JOIN [BI].[dbo].BI_LINHA_PRODUTOS AS LP
		ON VE.COD_PRODUTO = LP.COD_PRODUTO
		AND VE.COD_LOJA = LP.COD_LOJA
WHERE 1=1
	--AND DATA >= '2015-07-05'
	AND VE.COD_LOJA NOT IN (5,7,28,29,33)
	AND VE.FORA_LINHA = 'N'	
	AND VE.RUPTURA IS NOT NULL
GROUP BY
	YEAR(VE.DATA)
	,MONTH(VE.DATA)
	,VE.COD_LOJA
	,VE.COD_PRODUTO
	,LP.VLR_VENDA
	
HAVING COUNT(VE.COD_PRODUTO) < 29