DECLARE @TEMP_CUSTO_ZEUS AS TABLE
(
	COD_PRODUTO INT
	,COD_FORNECEDOR INT
	,VAL_CUSTO_EMBALAGEM NUMERIC(18,4)
	,QTD_EMBALAGEM_COMPRA NUMERIC(18,4)
)
INSERT INTO @TEMP_CUSTO_ZEUS
SELECT
	COD_PRODUTO
	,COD_FORNECEDOR
	,VAL_CUSTO_EMBALAGEM
	,QTD_EMBALAGEM_COMPRA
FROM
	[192.168.0.6].ZEUS_RTG.DBO.TAB_PRODUTO_FORNECEDOR
WHERE 1=1
	AND COD_LOJA = 1
	AND COD_FORNECEDOR IN (18055,103256)

select
	P.COD_PRODUTO
	,P.DES_PRODUTO
	,CB.COD_EAN
	,CB.TIPO_EAN
	,CUSTO_ZEUS.COD_FORNECEDOR AS COD_FORN_ZEUS
	,CUSTO_ZEUS.VAL_CUSTO_EMBALAGEM
	,CUSTO_ZEUS.QTD_EMBALAGEM_COMPRA
	,CUSTO_AX.COD_FORNECEDOR AS COD_FORN_AX
	,CUSTO_AX.VLR_EMB_COMPRA
	,CUSTO_AX.QTD_EMB_COMPRA
from
	AX2009_INTEGRACAO.DBO.TAB_PRODUTO_SIMPLIFICADO AS P
	INNER JOIN AX2009_INTEGRACAO.dbo.TAB_CODIGO_BARRA AS CB
		ON P.COD_PRODUTO = CB.COD_PRODUTO
	LEFT JOIN @TEMP_CUSTO_ZEUS AS CUSTO_ZEUS
		ON 1=1
		AND P.COD_PRODUTO = CUSTO_ZEUS.COD_PRODUTO
	LEFT JOIN BI.dbo.VW_CUSTOS_ATIVOS AS CUSTO_AX
		ON 1=1
		AND P.COD_PRODUTO = CUSTO_AX.COD_PRODUTO
		AND CUSTO_AX.COD_FORNECEDOR IN (18055,103256)
		AND CUSTO_AX.COD_FORNECEDOR = CUSTO_ZEUS.COD_FORNECEDOR
		AND CUSTO_AX.COD_LOJA = 0
	
WHERE 1=1
AND COD_EAN IN
(
'5604823001906'--1004059
,'8032610060138'--1011385
--,'3450301110996'--990824
)