DECLARE @TAB_MAX_PED AS TABLE
(
	COD_LOJA INT
	,COD_PRODUTO INT
	,DTA_PEDIDO DATE
)

INSERT INTO @TAB_MAX_PED
	SELECT
		P.COD_LOJA
		,PROD.COD_PRODUTO
		,MAX(P.DTA_EMISSAO)
	FROM
		[192.168.0.6].[Zeus_rtg].dbo.TAB_PEDIDO AS P
		INNER JOIN [192.168.0.6].Zeus_rtg.dbo.TAB_PEDIDO_PRODUTO AS PROD
			ON 1=1
			AND P.NUM_PEDIDO = PROD.NUM_PEDIDO
			AND P.COD_LOJA = PROD.COD_LOJA
			AND P.COD_PARCEIRO = PROD.COD_PARCEIRO
	WHERE 1=1
		AND CONVERT(DATE,P.DTA_EMISSAO) >= CONVERT(DATE,'20140101')
	GROUP BY
		P.COD_LOJA
		,PROD.COD_PRODUTO


DECLARE @TAB_VENDA AS TABLE
(
	COD_LOJA INT
	,COD_PRODUTO INT
	,VLR_VENDA NUMERIC(18,2)
	,QTD_VENDA NUMERIC(18,2)
)

INSERT INTO @TAB_VENDA
SELECT
	COD_LOJA
	,COD_PRODUTO
	,SUM(VALOR_TOTAL)
	,SUM(QTDE_PRODUTO)
FROM
	BI_VENDA_PRODUTO
WHERE 1=1
	AND CONVERT(DATE,DATA) BETWEEN CONVERT(DATE,GETDATE()-180) AND CONVERT(DATE,GETDATE()-1)
GROUP BY
	COD_LOJA
	,COD_PRODUTO

SELECT --TOP 100
	LP.COD_LOJA
	,CP.PNP
	,CP.NO_DEPARTAMENTO
	,CP.NO_SECAO
	,CP.NO_GRUPO
	,CP.NO_SUBGRUPO
	,LP.COD_PRODUTO
	,CP.DESCRICAO AS NO_PRODUTO
	,LP.CLASSIF_PRODUTO_LOJA
	,CP.UNIDADE_COMPRA
	,CP.UNIDADE_VENDA
	,CP.COD_FORNECEDOR
	,CF.DES_FANTASIA AS NO_FORNECEDOR
	,LP.FORA_LINHA
	,BI.dbo.fn_FormataVlr_Excel(EP.QTD_ESTOQUE) as QTD_ESTOQUE
	,BI.dbo.fn_FormataVlr_Excel(V.VLR_VENDA) as VLR_VENDA
	,BI.dbo.fn_FormataVlr_Excel(V.QTD_VENDA) as QTD_VENDA
	,BI.dbo.fn_FormataVlr_Excel(C.VLR_EMB_COMPRA) AS VLR_EMB_COMPRA
	,BI.dbo.fn_FormataVlr_Excel(C.QTD_EMB_COMPRA) AS QTD_EMB_COMPRA
	,BI.dbo.fn_FormataVlr_Excel(LP.VLR_VENDA) AS PRECO_VENDA
	,PED.DTA_PEDIDO
	,(SELECT 1 FROM [BI].[dbo].[CADASTRO_CAD_PRODUTO_METADADOS] AS TM WHERE TM.COD_METADADO = 3 AND TM.VLR_METADADO = 1 AND TM.COD_PRODUTO = LP.COD_PRODUTO) AS IMPORTADO
	,(SELECT 1 FROM [BI].[dbo].[CADASTRO_CAD_PRODUTO_METADADOS] AS TM WHERE TM.COD_METADADO = 4 AND TM.VLR_METADADO = 1 AND TM.COD_PRODUTO = LP.COD_PRODUTO) AS IMPORTACAO_PROPRIA
FROM
	BI_LINHA_PRODUTOS AS LP
	INNER JOIN BI_CAD_PRODUTO AS CP
		ON LP.COD_PRODUTO = CP.COD_PRODUTO
	INNER JOIN BI_CAD_FORNECEDOR AS CF
		ON CP.COD_FORNECEDOR= CF.COD_FORNECEDOR
	LEFT JOIN BI_ESTOQUE_PRODUTO AS EP
		ON 1=1
		AND LP.COD_PRODUTO= EP.COD_PRODUTO
		AND LP.COD_LOJA= EP.COD_LOJA
	LEFT JOIN @TAB_VENDA AS V
		ON 1=1
		AND LP.COD_PRODUTO= V.COD_PRODUTO
		AND LP.COD_LOJA= V.COD_LOJA	
	LEFT JOIN BI.DBO.VW_CUSTOS_ATIVOS AS C
		ON 1=1
		AND LP.COD_PRODUTO= C.COD_PRODUTO
		AND CP.COD_FORNECEDOR= C.COD_FORNECEDOR
	LEFT JOIN @TAB_MAX_PED AS PED
		ON 1=1
		AND LP.COD_PRODUTO= PED.COD_PRODUTO
		AND LP.COD_LOJA= PED.COD_LOJA	
WHERE 1=1
	--AND LP.FORA_LINHA = 'N'
	AND (LP.QTDE_PRODUTO_1ANO > 0OR LP.FORA_LINHA = 'N')
	AND CP.COD_DEPARTAMENTO NOT IN (15,7,18,16,17,20)
ORDER BY
	LP.COD_LOJA
	,CP.PNP
	,CP.NO_DEPARTAMENTO
	,CP.NO_SECAO
	,CP.NO_GRUPO
	,CP.NO_SUBGRUPO
	,LP.COD_PRODUTO