--SELECT * FROM  [BI].[dbo].[COMPRAS_AGENDA_PEDIDO_AUTO] WHERE flg_ativo = 1 and id not in (12,556)
SELECT
	P.[COD_FORNECEDOR] as [Cod. Forn.]
	,CF.DESCRICAO AS [Desc. Forn.]
	,P.[COD_LOJA] as [Loja]
	,P.[COD_PRODUTO] as [PLU]
	,CP.DESCRICAO AS [Desc. PLU]
	,BI.DBO.FN_FORMATAVLR_EXCEL([QTD_EMBALAGEM]) AS [Pedido]
	,P.[COD_COMPRADOR] as [Cod. Comprador]
	,BI.DBO.FN_FORMATAVLR_EXCEL([QTD_ESTOQUE]) AS [Estoque]
	,BI.DBO.FN_FORMATAVLR_EXCEL([VLR_EMB]) AS [Valor CX]
	,BI.DBO.FN_FORMATAVLR_EXCEL([VLR_MULTIPLO]) AS [Qtde Múltiplo]
	,BI.DBO.FN_FORMATAVLR_EXCEL([QTD_EMB_ORG]) AS [Qtde Embalagem]
	,BI.DBO.FN_FORMATAVLR_EXCEL([VLR_REV_TIME]) AS [Freq. Pedido]
	,BI.DBO.FN_FORMATAVLR_EXCEL([VLR_LEAD_TIME]) AS [Lead time]
	,BI.DBO.FN_FORMATAVLR_EXCEL(p.[AVG_QTD_U30D_PD]) AS [VMD 180D]
	,BI.DBO.FN_FORMATAVLR_EXCEL([QTD_SS_DIAS]) AS [Est. Seg. (dias)]
	,BI.DBO.FN_FORMATAVLR_EXCEL([FAT_SAZ]) AS [% Sazon.]
	,BI.DBO.FN_FORMATAVLR_EXCEL([QTD_MIN_UN]) AS [Exposição (qtde)]
	,E.CLASSIF_PRODUTO_LOJA as [Classif. PLU]
	,PABC.ABC_LOJA as [Classif. Supply] 
	,CP.DIAS_VALIDADE
	,P.COD_PEDIDO
	,P.ID_AGENDA
	,A.COD_FORNECEDOR
	,CF2.DESCRICAO AS [Desc. Forn. Agenda]
	,(CASE
		WHEN afp.ModelArmazenagem = 0 THEN 'Direto'
		WHEN afp.ModelArmazenagem = 1 THEN 'CrossDocking'
		WHEN afp.ModelArmazenagem = 2 THEN 'Armazenagem'
		WHEN afp.ModelArmazenagem = 3 THEN 'PickingUnitario'
	END) AS TIPO_ABASTECIMENTO
	,P.ERRO_CENTRALIZACAO
	--,BI.DBO.FN_FORMATAVLR_EXCEL(E.AVG_QTD_U180D_ESTOQUE_PD) AS AVG_QTD_180_PD
	--,CP.COD_FORNECEDOR as forn_principal_custo
	--,DATA
	--update p set data = getdate() 
	--,ID	delete p	
FROM
	[BI].[DBO].[COMPRAS_PEDIDOS] AS P
	INNER JOIN BI.DBO.BI_CAD_PRODUTO AS CP
		ON P.COD_PRODUTO = CP.COD_PRODUTO
	INNER JOIN BI.DBO.BI_CAD_FORNECEDOR AS CF
		ON P.COD_FORNECEDOR = CF.COD_FORNECEDOR
	LEFT JOIN [BI].[dbo].[COMPRAS_AGENDA_PEDIDO_AUTO] AS A
		ON P.ID_AGENDA = A.ID
	LEFT JOIN BI.DBO.BI_CAD_FORNECEDOR AS CF2
		ON A.COD_FORNECEDOR = CF2.COD_FORNECEDOR
	LEFT JOIN AX2009_INTEGRACAO.DBO.TAB_PRODUTO_FORNECEDOR_PREFERENCIAL AS AFP
		ON 1=1
		AND AFP.COD_LOJA = 5
		AND P.COD_PRODUTO = AFP.COD_PRODUTO	
	LEFT JOIN BI.DBO.[SUPPLY_PRODUTO_ABC_LOJA] AS PABC
		ON 1=1
		AND P.COD_LOJA = PABC.COD_LOJA
		AND P.COD_PRODUTO = PABC.COD_PRODUTO	
	LEFT JOIN BI.dbo.COMPRAS_ESTATISTICA_PRODUTO AS E
		ON 1=1
		AND P.COD_LOJA = E.COD_LOJA
		AND P.COD_PRODUTO = E.COD_PRODUTO
WHERE 1=1
	AND CONVERT(DATE,DATA) = CONVERT(DATE,GETDATE())
	AND FLG_AUTOMATICO = 1
	AND FLG_TESTE= 1
	--AND P.COD_FORNECEDOR = 16904
	and ID_AGENDA = 887
	--and COD_DEPARTAMENTO = 19
	--and COD_SECAO = 72	
	AND COD_PEDIDO IS null
	--and p.cod_produto = 1030923
	--and p.COD_PRODUTO in (19163)
	