DECLARE @TAB_VENDA AS TABLE
(
	COD_LOJA INT
	,COD_PRODUTO INT
	,VLR_VENDA NUMERIC(18,2)
	,QTD_VENDA NUMERIC(18,2)
)

INSERT INTO @TAB_VENDA
SELECT
	COD_LOJA
	,COD_PRODUTO
	,SUM(VALOR_TOTAL)
	,SUM(QTDE_PRODUTO)
FROM
	BI_VENDA_PRODUTO
WHERE 1=1
	AND CONVERT(DATE,DATA) BETWEEN CONVERT(DATE,'20141001') AND CONVERT(DATE,'20141031')
GROUP BY
	COD_LOJA
	,COD_PRODUTO
	
SELECT --TOP 100
	LP.COD_LOJA
	,CP.PNP
	,CP.NO_DEPARTAMENTO
	,CP.NO_SECAO
	,CP.NO_GRUPO
	,CP.NO_SUBGRUPO
	,LP.COD_PRODUTO
	,CP.DESCRICAO AS NO_PRODUTO
	,LP.CLASSIF_PRODUTO_LOJA
	,CP.UNIDADE_COMPRA
	,CP.UNIDADE_VENDA
	,CP.COD_FORNECEDOR
	,CF.DES_FANTASIA AS NO_FORNECEDOR
	,LP.FORA_LINHA
	,BI.dbo.fn_FormataVlr_Excel(EP.QTD_ESTOQUE) as QTD_ESTOQUE
	,BI.dbo.fn_FormataVlr_Excel(V.VLR_VENDA) as VLR_VENDA
	,BI.dbo.fn_FormataVlr_Excel(V.QTD_VENDA) as QTD_VENDA
	,BI.dbo.fn_FormataVlr_Excel(C.VLR_EMB_COMPRA) AS VLR_EMB_COMPRA
	,BI.dbo.fn_FormataVlr_Excel(C.QTD_EMB_COMPRA) AS QTD_EMB_COMPRA
	,BI.dbo.fn_FormataVlr_Excel(LP.VLR_VENDA) AS PRECO_VENDA
	,(CASE WHEN EP.QTD_ESTOQUE < 0 THEN 0 ELSE EP.QTD_ESTOQUE END) * (C.VLR_EMB_COMPRA/(case when C.QTD_EMB_COMPRA = 0 then 1 else C.QTD_EMB_COMPRA end)) as ESTOQUE_CUSTO
	,V.QTD_VENDA * (C.VLR_EMB_COMPRA/(case when C.QTD_EMB_COMPRA = 0 then 1 else C.QTD_EMB_COMPRA end)) as QTD_VENDA_CUSTO
FROM
	BI_LINHA_PRODUTOS AS LP
	INNER JOIN BI_CAD_PRODUTO AS CP
		ON LP.COD_PRODUTO = CP.COD_PRODUTO
	INNER JOIN BI_CAD_FORNECEDOR AS CF
		ON CP.COD_FORNECEDOR= CF.COD_FORNECEDOR
	LEFT JOIN BI_ESTOQUE_PRODUTO_DIA AS EP
		ON 1=1
		AND LP.COD_PRODUTO= EP.COD_PRODUTO
		AND LP.COD_LOJA= EP.COD_LOJA
		AND EP.DATA = '20140901'
	LEFT JOIN @TAB_VENDA AS V
		ON 1=1
		AND LP.COD_PRODUTO= V.COD_PRODUTO
		AND LP.COD_LOJA= V.COD_LOJA	
	LEFT JOIN BI.DBO.VW_CUSTOS_ATIVOS AS C
		ON 1=1
		AND LP.COD_PRODUTO= C.COD_PRODUTO
		AND CP.COD_FORNECEDOR= C.COD_FORNECEDOR
WHERE 1=1
	--AND LP.FORA_LINHA = 'N'
	AND (LP.QTDE_PRODUTO_1ANO > 0OR LP.FORA_LINHA = 'N')
	AND CP.COD_DEPARTAMENTO NOT IN (15,7,18,16,17,20)

