UPDATE P
SET
	P.FLG_CENTRALIZADO = 1
FROM
	[BI].[DBO].[COMPRAS_PEDIDOS] AS P
	INNER JOIN [BI].[dbo].[COMPRAS_AGENDA_PEDIDO_AUTO] AS A
		ON P.ID_AGENDA = A.ID
WHERE 1=1
	AND CONVERT(DATE,DATA) >= CONVERT(DATE,GETDATE()-15)
	AND FLG_AUTOMATICO = 1
	AND P.COD_FORNECEDOR = 18055
	AND A.COD_FORNECEDOR <> 18055
	AND FLG_CENTRALIZADO IS NULL
	