-- -------------------------------------------------------------------------------------------------------
--
-- -------------------------------------------------------------------------------------------------------	
	DECLARE @TAB_PEDIDO_FLV AS TABLE
	(
		COD_LOJA INT
		,DATA DATE
		,COD_PRODUTO INT
		,QTD_PEDIDO NUMERIC(18,2)
		,QTD_RECEBIDA NUMERIC(18,2)
	)

	INSERT INTO @TAB_PEDIDO_FLV
	SELECT
		P.COD_LOJA
		,CONVERT(DATE,DTA_ENTREGA) AS DATA
		,PP.COD_PRODUTO
		,SUM(PP.QTD_PEDIDO)
		,SUM(PP.QTD_RECEBIDA)
	FROM
		[192.168.0.6].[ZEUS_RTG].DBO.[TAB_PEDIDO] AS P
		INNER JOIN [192.168.0.6].[ZEUS_RTG].DBO.[TAB_PEDIDO_PRODUTO] AS PP
			ON 1=1
			and P.NUM_PEDIDO = PP.NUM_PEDIDO
			AND P.COD_LOJA = PP.COD_LOJA
			AND P.COD_PARCEIRO = PP.COD_PARCEIRO
		LEFT JOIN BI.dbo.BI_CAD_PRODUTO AS CP
			ON PP.COD_PRODUTO = CP.COD_PRODUTO
	WHERE 1 = 1
		AND CONVERT(DATE,DTA_EMISSAO) between CONVERT(DATE,GETDATE()-90) AND CONVERT(DATE,GETDATE()-1)
		AND CP.COD_DEPARTAMENTO IN (4)
		AND P.COD_LOJA not in (7,8,29,33)
	GROUP BY
		P.COD_LOJA
		,CONVERT(DATE,DTA_ENTREGA)
		,PP.COD_PRODUTO
	
-- -------------------------------------------------------------------------------------------------------
--
-- -------------------------------------------------------------------------------------------------------
	SELECT --TOP 10
		VP.COD_LOJA
		,CONVERT(DATE,VP.DATA) as DATA
		,VP.COD_PRODUTO
		,CP.DESCRICAO AS NO_PRODUTO
		,CP.NO_DEPARTAMENTO
		,CP.NO_SECAO
		,CP.NO_GRUPO
		,LP.CLASSIF_PRODUTO_LOJA
		,LP.FORA_LINHA
		,BI.dbo.fn_FormataVlr_Excel(VP.VALOR_TOTAL) AS VLR_TOTAL_VENDA
		,BI.dbo.fn_FormataVlr_Excel(VP.QTDE_PRODUTO) AS QTD_TOTAL_VENDA
		,BI.dbo.fn_FormataVlr_Excel(TPF.QTD_PEDIDO) AS QTD_PEDIDO
		,BI.dbo.fn_FormataVlr_Excel(TPF.QTD_RECEBIDA) AS QTD_RECEBIDA
	FROM
		BI.dbo.BI_VENDA_PRODUTO AS VP
		INNER JOIN BI.dbo.BI_CAD_PRODUTO AS CP
			ON VP.COD_PRODUTO = CP.COD_PRODUTO	
		LEFT JOIN BI.dbo.BI_LINHA_PRODUTOS AS LP
			ON 1=1
			AND VP.COD_PRODUTO = LP.COD_PRODUTO
			AND VP.COD_LOJA = LP.COD_LOJA
		LEFT JOIN @TAB_PEDIDO_FLV AS TPF
			ON 1=1
			AND VP.COD_PRODUTO = TPF.COD_PRODUTO
			AND VP.COD_LOJA = TPF.COD_LOJA			
			AND VP.DATA = TPF.DATA			
	WHERE 1=1
		AND CP.COD_DEPARTAMENTO IN (4)
		AND VP.COD_LOJA not in (7,8,29,33)
		AND CONVERT(DATE,VP.DATA) BETWEEN CONVERT(DATE,GETDATE()-90) AND CONVERT(DATE,GETDATE()-1)
		--AND LP.FORA_LINHA = 'N'
	ORDER BY
		VP.COD_LOJA
		,CONVERT(DATE,VP.DATA)
		,CP.NO_DEPARTAMENTO
		,CP.NO_SECAO
		,CP.NO_GRUPO
		
