SELECT --TOP 10
	LP.COD_LOJA
	,LP.COD_PRODUTO
	,CP.DESCRICAO AS NO_PRODUTO
	,CP.NO_DEPARTAMENTO
	,CP.NO_SECAO
	,CP.NO_GRUPO
	,EP.CLASSIF_PRODUTO_LOJA
	,ABC.ABC_LOJA AS ABC_SUPPLY
	,LP.FORA_LINHA
	,BI.DBO.FN_FORMATAVLR_EXCEL(LP.VLR_VENDA) AS VLR_VENDA
	,BI.DBO.FN_FORMATAVLR_EXCEL(LP.VLR_OFERTA) AS VLR_OFERTA
	,BI.DBO.FN_FORMATAVLR_EXCEL(LP.VLR_VCMARCHE) AS VLR_VCMARCHE
	,BI.DBO.FN_FORMATAVLR_EXCEL(isnull(EP.AVG_QTD_U180D_PD,0)) as AVG_QTD_U180D_PD
	,BI.DBO.FN_FORMATAVLR_EXCEL(isnull(EP.AVG_QTD_U180D_ESTOQUE_PD,0)) as AVG_QTD_U180D_ESTOQUE_PD
	,BI.DBO.FN_FORMATAVLR_EXCEL(isnull(EP.AVG_QTD_U90D_PD,0)) as AVG_QTD_U90D_PD
	,BI.DBO.FN_FORMATAVLR_EXCEL(isnull(EP.AVG_QTD_U30D_PD,0)) as AVG_QTD_U30D_PD
	,BI.DBO.FN_FORMATAVLR_EXCEL(isnull(E.QTD_ESTOQUE,0)) as QTD_ESTOQUE
	,BI.DBO.FN_FORMATAVLR_EXCEL(isnull(EP.DIAS_ESTOQUE_U180D,0)) as DIAS_ESTOQUE
FROM
	BI.DBO.BI_LINHA_PRODUTOS AS LP
	INNER JOIN BI.dbo.BI_CAD_PRODUTO AS CP
		ON LP.COD_PRODUTO = CP.COD_PRODUTO	
	LEFT JOIN BI.dbo.COMPRAS_ESTATISTICA_PRODUTO AS EP
		ON 1=1
		AND LP.COD_PRODUTO = EP.COD_PRODUTO
		AND LP.COD_LOJA = EP.COD_LOJA		
	LEFT JOIN BI.dbo.VW_ESTOQUE_ATUAL AS E
		ON 1=1
		AND LP.COD_PRODUTO = E.COD_PRODUTO
		AND EP.COD_LOJA = E.COD_LOJA
	LEFT JOIN BI.dbo.SUPPLY_PRODUTO_ABC_LOJA AS ABC
		ON 1=1
		AND LP.COD_PRODUTO = ABC.COD_PRODUTO
		AND LP.COD_LOJA = ABC.COD_LOJA
WHERE 1=1
	AND CP.COD_DEPARTAMENTO IN (2,9,10,13,3,12)
	AND LP.COD_LOJA not in (29,33,5)
	--AND LP.FORA_LINHA = 'N'
ORDER BY
	LP.COD_LOJA
	,CP.NO_DEPARTAMENTO
	,CP.NO_SECAO
	,CP.NO_GRUPO
	,CP.DESCRICAO
	