--TRUNCATE TABLE BI.DBO.[BIDW_VENDA]
INSERT INTO BI.DBO.[BIDW_VENDA]
(
	[COD_LOJA]
	,[ANO_454]
	,[MES_454]
	,[SEMANA_454]
	--,[DATA]
	---,[COD_PRODUTO]
	,[VLR_VENDA]
	,[QTD_VENDA]
)
SELECT
	VP.COD_LOJA
	,S.ANO_454
	,S.MES_454
	,S.SEMANA_454
	--,VP.DATA
	--,CP.COD_PRODUTO
	,SUM(VP.VALOR_TOTAL) AS VLR_TOTAL
	,SUM(VP.QTDE_PRODUTO) AS QTD_TOTAL
FROM
	BI_CAD_PRODUTO AS CP
	INNER JOIN BI_VENDA_PRODUTO AS VP
		ON 1=1
		AND CP.COD_PRODUTO = VP.COD_PRODUTO
	INNER JOIN BI_CAD_SEMANA AS S
		ON 1=1
		AND VP.DATA = S.DATA
WHERE 1=1
	--AND CONVERT(DATE,VP.DATA) BETWEEN CONVERT(DATE,'20140101') AND CONVERT(DATE,'20140131')
GROUP BY
	VP.COD_LOJA
	,S.ANO_454
	,S.MES_454
	,S.SEMANA_454
	--,VP.DATA
	--,CP.COD_PRODUTO
WITH CUBE
