DECLARE @TAB_PROD_CUSTO AS TABLE
(
	COD_PRODUTO INT
	,VAL_CUSTO_REP NUMERIC(18,2)
)

INSERT INTO @TAB_PROD_CUSTO
	SELECT
		COD_PRODUTO
		,MAX(VAL_CUSTO_REP) VAL_CUSTO_REP
	FROM
		[192.168.0.6].ZEUS_rtg.DBO.TAB_PRODUTO_LOJA AS PL with(nolock)
	GROUP BY 
		COD_PRODUTO

SELECT
	C.COD_PRODUTO
	,CP.DESCRICAO AS NO_PRODUTO
	,C.VAL_CUSTO_REP
	,MAX(PV.VLR_VENDA) AS VLR_VENDA
FROM
	@TAB_PROD_CUSTO AS C
	INNER JOIN BI.DBO.BI_CAD_PRODUTO AS CP
		ON 1=1
		AND C.COD_PRODUTO = CP.COD_PRODUTO
	INNER JOIN BI.DBO.VW_PRECOS_VENDA_ATIVOS AS PV
		ON 1=1
		AND C.COD_PRODUTO = PV.COD_PRODUTO
WHERE 1=1
	AND CP.COD_DEPARTAMENTO = 5
GROUP BY
	C.COD_PRODUTO
	,CP.DESCRICAO
	,C.VAL_CUSTO_REP
ORDER BY
	CP.DESCRICAO