select GETDATE(), * from AX2009_INTEGRACAO.DBO.TAB_PRODUTO_REFERENCIA  where COD_FORNECEDOR = 14682

select * from AX2009_INTEGRACAO.DBO.TAB_PRODUTO_REFERENCIA  where COD_PRODUTO = 1032912 and COD_FORNECEDOR = 18055


select * from COMPRAS_AGENDA_PEDIDO_AUTO where ID = 96



	select MARCHE_PURCHIDREF, * from SMA_AX50_SP1_DB_PROD.dbo.SALESTABLE where MARCHE_PURCHIDREF = 'CD_0001258'
	select * from SMA_AX50_SP1_DB_PROD.dbo.SALESLINE where SALESID IN (select SALESID from SMA_AX50_SP1_DB_PROD.dbo.SALESTABLE where MARCHE_PURCHIDREF = 'CD_0001258')


	select * from SMA_AX50_SP1_DB_PROD.dbo.PURCHTABLE where PURCHID = 'CD_0001258'
	select * from SMA_AX50_SP1_DB_PROD.dbo.PURCHLINE where PURCHID = 'CD_0001258'




select * from [192.168.0.6].zeus_rtg.dbo.tab_pedido_cancelado where num_pedido = 1143304

select * FROM bi.DBO.COMPRAS_PEDIDOS AS PED where COD_PEDIDO like '%1141643%'
SELECT * FROM COMPRAS_AGENDA_PEDIDO_AUTO WHERE ID = 830




select * FROM bi.DBO.COMPRAS_PEDIDOS AS P where P.FLG_ERRO_FORNECEDOR_PRINCIPAL = 0 AND P.FLG_ERRO_TIPO_ABASTECIMENTO = 0 AND P.FLG_ERRO_SEM_CUSTO = 0 AND P.FLG_COMPRA = 1 and p.COD_PEDIDO = 1149161
select MARCHE_PURCHIDREF, * from SMA_AX50_SP1_DB_PROD.dbo.SALESTABLE where SALESID like '%1149161%'
select  * from SMA_AX50_SP1_DB_PROD.dbo.purchTABLE where PURCHID like '%1149161%'
select * FROM DW.DBO.VW_MARCHE_PEDIDOS_PROD AS PED where NUM_PEDIDO like '%1149161%'
select * FROM DW.DBO.VW_MARCHE_PEDIDOS_PROD AS PED where NUM_PEDIDO like 'CD%1305%'


select * FROM bi.DBO.COMPRAS_PEDIDOS AS P where P.FLG_ERRO_FORNECEDOR_PRINCIPAL = 0 AND P.FLG_ERRO_TIPO_ABASTECIMENTO = 0 AND P.FLG_ERRO_SEM_CUSTO = 0 AND P.FLG_COMPRA = 1 and p.ID_AGENDA = 746 order by DATA desc
select MARCHE_PURCHIDREF, * from SMA_AX50_SP1_DB_PROD.dbo.SALESTABLE where SALESID like '%1151606%'
select  * from SMA_AX50_SP1_DB_PROD.dbo.purchTABLE where PURCHID like '%1151606%'
select * FROM DW.DBO.VW_MARCHE_PEDIDOS_PROD AS PED where NUM_PEDIDO like '%1151606%'
select * FROM DW.DBO.VW_MARCHE_PEDIDOS_PROD AS PED where NUM_PEDIDO like 'CD%1328%'

select distinct COD_PEDIDO FROM bi.DBO.COMPRAS_PEDIDOS AS PED where convert(date,data) = convert(date,'2016-05-25') and ID_AGENDA = 1182

select * FROM bi.DBO.COMPRAS_PEDIDOS AS PED where COD_PEDIDO = 1149605

select MARCHE_PURCHIDREF, * from SMA_AX50_SP1_DB_PROD.dbo.SALESTABLE where SALESID like '%1149605%'

select  * from SMA_AX50_SP1_DB_PROD.dbo.purchTABLE where PURCHID like '%1149605%'

select * FROM DW.DBO.VW_MARCHE_PEDIDOS_PROD AS PED where NUM_PEDIDO like '%1149605%'






select * FROM DW.DBO.VW_MARCHE_PEDIDOS_PROD AS PED where NUM_PEDIDO like '%CD_0001240%'




select * FROM bi.DBO.COMPRAS_PEDIDOS AS PED where COD_PEDIDO like 103265




select * FROM bi.DBO.COMPRAS_PEDIDOS AS P where P.FLG_ERRO_FORNECEDOR_PRINCIPAL = 0 AND P.FLG_ERRO_TIPO_ABASTECIMENTO = 0 AND P.FLG_ERRO_SEM_CUSTO = 0 AND P.FLG_COMPRA = 1 and p.COD_PEDIDO = 1151366 and P.COD_PRODUTO = 1030615
select MARCHE_PURCHIDREF, * from SMA_AX50_SP1_DB_PROD.dbo.SALESTABLE where SALESID like '%1151366%'
select  * from SMA_AX50_SP1_DB_PROD.dbo.purchTABLE where PURCHID like '%1151366%'
select * FROM DW.DBO.VW_MARCHE_PEDIDOS_PROD AS PED where NUM_PEDIDO like '%1151366%'
select * FROM DW.DBO.VW_MARCHE_PEDIDOS_PROD AS PED where NUM_PEDIDO like 'CD%1323%'
select * from AX2009_INTEGRACAO.dbo.PURCHTABLE where PURCHID like '%1151366%'



select * from SMA_AX50_SP1_DB_PROD.dbo.SALESLINE where SALESID like '%1151366%' and ITEMID = 1030615
select * from AX2009_INTEGRACAO.dbo.SALESLINE where SALESID like '%1151366%' and ITEMID = 1030615