DECLARE @TAB_PROD_1083 AS TABLE
(
	COD_PRODUTO INT
)

INSERT INTO @TAB_PROD_1083
SELECT DISTINCT
	COD_PRODUTO
FROM
	[192.168.0.6].ZEUS_RTG.DBO.TAB_PRODUTO_FORNECEDOR
WHERE
	COD_FORNECEDOR = 1083
		
SELECT
	LP.COD_LOJA
	,L.NO_LOJA
	,CP.COD_PRODUTO
	,CP.DESCRICAO AS NO_PRODUTO
	,BI.dbo.fn_FormataVlr_Excel(MAX(ISNULL(EPD1.QTD_ESTOQUE,0))) AS ESTOQUE_01_03_14
	,BI.dbo.fn_FormataVlr_Excel(SUM(ISNULL(VP.QTDE_PRODUTO,0))) AS QTD_VENDA_03_14
	,BI.dbo.fn_FormataVlr_Excel(SUM(ISNULL(VP.VALOR_TOTAL,0))) AS VLR_VENDA_03_14
	,BI.dbo.fn_FormataVlr_Excel(MAX(ISNULL(EPD2.QTD_ESTOQUE,0))) AS ESTOQUE_31_03_14	
	,BI.dbo.fn_FormataVlr_Excel(MAX(ISNULL(EP.QTD_ESTOQUE,0))) AS ESTOQUE_ATUAL
	--,MAX(LP.VLR_VENDA) AS PV_ATUAL
	,BI.dbo.fn_FormataVlr_Excel(MAX(CASE WHEN LP.VLR_OFERTA IS NOT NULL THEN LP.VLR_OFERTA ELSE LP.VLR_VENDA END)) AS PRECO_ATUAL
FROM
	BI_CAD_PRODUTO AS CP
	INNER JOIN @TAB_PROD_1083 AS T
		ON CP.COD_PRODUTO = T.COD_PRODUTO
	INNER JOIN BI_LINHA_PRODUTOS AS LP
		ON 1=1
		AND CP.COD_PRODUTO = LP.COD_PRODUTO
	INNER JOIN BI_ESTOQUE_PRODUTO AS EP
		ON 1=1
		AND CP.COD_PRODUTO = EP.COD_PRODUTO
		AND LP.COD_LOJA = EP.COD_LOJA
	INNER JOIN BI_CAD_LOJA2 AS L
		ON 1=1
		AND L.COD_LOJA = LP.COD_LOJA
	LEFT JOIN BI_ESTOQUE_PRODUTO_DIA AS EPD1
		ON 1=1
		AND CP.COD_PRODUTO = EPD1.COD_PRODUTO
		AND LP.COD_LOJA = EPD1.COD_LOJA
		AND CONVERT(DATE,EPD1.DATA) = CONVERT(DATE,'20140301')
	LEFT JOIN BI_ESTOQUE_PRODUTO_DIA AS EPD2
		ON 1=1
		AND CP.COD_PRODUTO = EPD2.COD_PRODUTO
		AND LP.COD_LOJA = EPD2.COD_LOJA
		AND CONVERT(DATE,EPD2.DATA) = CONVERT(DATE,'20140331')
	LEFT JOIN BI_VENDA_PRODUTO AS VP
		ON 1=1
		AND CP.COD_PRODUTO = VP.COD_PRODUTO
		AND LP.COD_LOJA = VP.COD_LOJA
		AND CONVERT(DATE,VP.DATA) BETWEEN CONVERT(DATE,'20140301') AND CONVERT(DATE,'20140331')

WHERE 1=1
	AND LP.FORA_LINHA = 'N'
	AND LP.COD_LOJA <> 26
GROUP BY
	LP.COD_LOJA
	,L.NO_LOJA
	,CP.COD_PRODUTO
	,CP.DESCRICAO
ORDER BY
	CP.DESCRICAO
	,LP.COD_LOJA
	