DECLARE @TAB_ZEUS AS TABLE
(
	COD_FORNECEDOR INT
	,COD_PRODUTO INT
	,VAL_CUSTO_EMBALAGEM NUMERIC(10,2)
	,QTD_EMBALAGEM_COMPRRA NUMERIC(10,2)
)

INSERT INTO @TAB_ZEUS
SELECT
	COD_FORNECEDOR
	,COD_PRODUTO
	,MAX(VAL_CUSTO_EMBALAGEM)
	,MAX(QTD_EMBALAGEM_COMPRA)
FROM
	[192.168.0.6].ZEUS_RTG.DBO.TAB_PRODUTO_FORNECEDOR
WHERE 1 = 1
	AND COD_LOJA IN (1,2,3,4,6,7,9,10,12,13,17,18,19,20,21,30)
	AND COD_FORNECEDOR IN (SELECT DISTINCT COD_FORNECEDOR FROM BI.dbo.COMPRAS_AGENDA_PEDIDO_MATRIZ)
	AND VAL_CUSTO_EMBALAGEM <> 0
GROUP BY
	COD_FORNECEDOR
	,COD_PRODUTO

DECLARE @TAB_NEW AS TABLE
(
	COD_FORNECEDOR INT
	,COD_PRODUTO INT
	,VAL_CUSTO_EMBALAGEM NUMERIC(10,2)
	,QTD_EMBALAGEM_COMPRRA NUMERIC(10,2)
)

INSERT INTO @TAB_NEW
SELECT DISTINCT
	ZEUS.COD_PRODUTO as [CodProd]
	,ZEUS.COD_FORNECEDOR as [CodForn]
	,ZEUS.VAL_CUSTO_EMBALAGEM as [Custo Zeus]
	,ZEUS.QTD_EMBALAGEM_COMPRRA as [Emb Zeus]
FROM
	@TAB_ZEUS AS ZEUS INNER JOIN [BI].dbo.[BI_CAD_FORNECEDOR] AS F ON (ZEUS.COD_FORNECEDOR = F.COD_FORNECEDOR)
		INNER JOIN [BI].dbo.[BI_CAD_PRODUTO] AS P ON (ZEUS.COD_PRODUTO = P.COD_PRODUTO)
		INNER JOIN [BI].dbo.[COMPRAS_CAD_COMPRADOR] AS C ON (P.COD_USUARIO = C.COD_USUARIO)
		LEFT JOIN [BI].dbo.[VW_CUSTOS_ATIVOS] AS AX ON (ZEUS.COD_FORNECEDOR = AX.COD_FORNECEDOR AND ZEUS.COD_PRODUTO = AX.COD_PRODUTO)
WHERE 1 = 1
	AND AX.COD_PRODUTO IS NULL
	AND ZEUS.COD_FORNECEDOR NOT IN (14699,18689,102226,18682,16384,14322,17095,2355,14775,16386,14357,14721,17930,17486,18546,102227,102378)
	AND P.FORA_LINHA = 'N'
	AND ZEUS.VAL_CUSTO_EMBALAGEM <> 1

INSERT INTO BI.dbo.BI_PRECO_COMPRA
SELECT
	0 AS COD_LOJA
	,COD_PRODUTO
	,COD_FORNECEDOR
	,CONVERT(DATE,'20140101') AS DTA_INI
	,CONVERT(DATE,'20160101') AS DTA_FIM
	,'Tabela Compra'
	,VAL_CUSTO_EMBALAGEM
	--,NULL AS RECID
	,CONVERT(DATE,'20140101') AS DTA_GRAVACAO
	,NULL AS ATIVO
	,QTD_EMBALAGEM_COMPRRA
	,10398
	,NULL
	,CONVERT(DATE,'20140101')
FROM
	@TAB_NEW AS T

/*
SELECT DISTINCT
	ZEUS.COD_FORNECEDOR as [CodForn]
	,F.DES_FANTASIA as [Forn]
	,ZEUS.COD_PRODUTO as [CodProd]
	,P.DESCRICAO as [Prod]
	,ZEUS.VAL_CUSTO_EMBALAGEM as [Custo Zeus]
	,ZEUS.QTD_EMBALAGEM_COMPRRA as [Emb Zeus]
	,C.NO_COMPRADOR as [Comprador]
	,P.FORA_LINHA as [Fora Linha]
	,P.CLASSIF_PRODUTO AS [ABC] 
FROM
	@TAB_ZEUS AS ZEUS INNER JOIN [BI].dbo.[BI_CAD_FORNECEDOR] AS F ON (ZEUS.COD_FORNECEDOR = F.COD_FORNECEDOR)
		INNER JOIN [BI].dbo.[BI_CAD_PRODUTO] AS P ON (ZEUS.COD_PRODUTO = P.COD_PRODUTO)
		INNER JOIN [BI].dbo.[COMPRAS_CAD_COMPRADOR] AS C ON (P.COD_USUARIO = C.COD_USUARIO)
		LEFT JOIN [BI].dbo.[VW_CUSTOS_ATIVOS] AS AX ON (ZEUS.COD_FORNECEDOR = AX.COD_FORNECEDOR AND ZEUS.COD_PRODUTO = AX.COD_PRODUTO)
WHERE 1 = 1
	AND AX.COD_PRODUTO IS NULL
	AND ZEUS.COD_FORNECEDOR NOT IN (14699,18689,102226,18682,16384,14322,17095,2355,14775,16386,14357,14721,17930,17486,18546,102227,102378)
	AND P.FORA_LINHA = 'N'
	AND ZEUS.VAL_CUSTO_EMBALAGEM <> 1
*/