SELECT
	CP.COD_PRODUTO
	,CP.DESCRICAO
	,CP.NO_DEPARTAMENTO
	,CP.NO_SECAO
	,CP.NO_GRUPO
	,LP.FORA_LINHA
	,BI.dbo.fn_FormataVlr_Excel(ISNULL(EP.QTD_ESTOQUE,0)) AS QTD_ESTOQUE_ATUAL
	,BI.dbo.fn_FormataVlr_Excel(SUM(ISNULL(VP.VALOR_TOTAL,0))) AS VLR_TOTAL
	,BI.dbo.fn_FormataVlr_Excel(SUM(ISNULL(QP.VLR_QUEBRA*-1,0))) AS QUEBRA_TOTAL
	,BI.dbo.fn_FormataVlr_Excel(sum(ISNULL(CMV.Total_Impostos,0))) AS VLR_IMPOSTOS
	,BI.dbo.fn_FormataVlr_Excel(sum(ISNULL(CMV.CMV,0))) AS VLR_CMV
	,BI.dbo.fn_FormataVlr_Excel(ISNULL((sum(VP.VALOR_TOTAL)-sum(CMV.Total_Impostos)-sum(CMV.CMV))/sum(VP.VALOR_TOTAL),0)) AS MARGEM
FROM 
	BI.DBO.BI_CAD_PRODUTO AS CP
	INNER JOIN BI.dbo.BI_LINHA_PRODUTOS AS LP
		ON 1=1
		AND CP.COD_PRODUTO = LP.COD_PRODUTO
	INNER JOIN BI.DBO.BI_CAD_SEMANA AS S
		ON 1=1
	LEFT JOIN BI.DBO.BI_VENDA_PRODUTO AS VP
		ON 1=1
		AND CP.COD_PRODUTO = VP.COD_PRODUTO
		AND S.DATA = VP.DATA
		AND VP.COD_LOJA = LP.COD_LOJA
	LEFT JOIN BI.DBO.BI_QUEBRA_PRODUTO AS QP
		ON 1=1
		AND CP.COD_PRODUTO = QP.COD_PRODUTO
		AND S.DATA = QP.DATA
		AND QP.COD_LOJA = LP.COD_LOJA
	LEFT JOIN DW.DBO.CMV AS CMV
		ON 1=1
		AND CP.COD_PRODUTO = CMV.COD_PRODUTO
		AND S.DATA = CMV.DTA_CALCULO
		AND CMV.COD_LOJA = LP.COD_LOJA
	LEFT JOIN BI.dbo.VW_ESTOQUE_ATUAL AS EP
		ON 1=1
		AND CP.COD_PRODUTO = EP.COD_PRODUTO
		AND CMV.COD_LOJA = EP.COD_LOJA
WHERE 1=1
	AND LP.COD_LOJA = 31
	AND CP.COD_DEPARTAMENTO = 21
	AND CP.COD_SECAO IN (90,89,88)
	AND CONVERT(DATE,S.DATA) BETWEEN CONVERT(DATE,'2016-01-01') AND CONVERT(DATE,'2016-05-15')
GROUP BY
	CP.COD_PRODUTO
	,CP.DESCRICAO
	,CP.NO_DEPARTAMENTO
	,CP.NO_SECAO
	,CP.NO_GRUPO	
	,LP.FORA_LINHA
	,EP.QTD_ESTOQUE