SELECT
	'P1' AS PERIODO
	,CP.NO_DEPARTAMENTO
	,CP.NO_SECAO
	,CP.NO_GRUPO
	,CP.COD_PRODUTO
	,CP.DESCRICAO AS NO_PRODUTO	
	,CP.COD_FORNECEDOR
	,CF.DESCRICAO AS NO_FORNECEDOR
	,(SELECT VLR_METADADO FROM CADASTRO_CAD_PRODUTO_METADADOS TPM WHERE TPM.COD_PRODUTO = CP.COD_PRODUTO AND TPM.COD_METADADO = 2) AS [MTD ORG PRODUCAO]
	,(SELECT VLR_METADADO FROM CADASTRO_CAD_PRODUTO_METADADOS TPM WHERE TPM.COD_PRODUTO = CP.COD_PRODUTO AND TPM.COD_METADADO = 1 AND TPM.VLR_METADADO = 1) AS [MTD MARCA PROPRIA]
	,(SELECT VLR_METADADO FROM CADASTRO_CAD_PRODUTO_METADADOS TPM WHERE TPM.COD_PRODUTO = CP.COD_PRODUTO AND TPM.COD_METADADO = 18 AND TPM.VLR_METADADO = 1) AS [MTD PRODUCAO PROPRIA]	
	,BI.dbo.fn_FormataVlr_Excel(SUM(VP.VALOR_TOTAL)) AS VLR_TOTAL
	,BI.dbo.fn_FormataVlr_Excel(SUM(VP.QTDE_PRODUTO)) AS QTD_TOTAL
FROM
	BI.dbo.BI_VENDA_PRODUTO AS VP
	INNER JOIN BI_CAD_PRODUTO AS CP
		ON VP.COD_PRODUTO = CP.COD_PRODUTO
	LEFT JOIN BI_CAD_FORNECEDOR AS CF
		ON CP.COD_FORNECEDOR = CF.COD_FORNECEDOR
WHERE 1=1
	--AND CP.FORA_LINHA = 'N'
	AND VP.COD_LOJA = 7
	AND CP.COD_DEPARTAMENTO = 6
	AND CP.COD_SECAO IN (42,50)
	AND CONVERT(DATE,VP.DATA) BETWEEN CONVERT(DATE,'20131230') AND CONVERT(DATE,'20140209')
	--AND CP.COD_PRODUTO IN (SELECT COD_PRODUTO FROM CADASTRO_CAD_PRODUTO_METADADOS TPM WHERE TPM.COD_PRODUTO = CP.COD_PRODUTO AND TPM.COD_METADADO = 1 AND TPM.VLR_METADADO = 1)
GROUP BY
	CP.NO_DEPARTAMENTO
	,CP.NO_SECAO
	,CP.NO_GRUPO
	,CP.COD_PRODUTO
	,CP.DESCRICAO
	,CP.COD_FORNECEDOR
	,CF.DESCRICAO

UNION ALL

SELECT
	'P2' AS PERIODO
	,CP.NO_DEPARTAMENTO
	,CP.NO_SECAO
	,CP.NO_GRUPO
	,CP.COD_PRODUTO
	,CP.DESCRICAO AS NO_PRODUTO	
	,CP.COD_FORNECEDOR
	,CF.DESCRICAO AS NO_FORNECEDOR
	,(SELECT VLR_METADADO FROM CADASTRO_CAD_PRODUTO_METADADOS TPM WHERE TPM.COD_PRODUTO = CP.COD_PRODUTO AND TPM.COD_METADADO = 2) AS [MTD ORG PRODUCAO]
	,(SELECT VLR_METADADO FROM CADASTRO_CAD_PRODUTO_METADADOS TPM WHERE TPM.COD_PRODUTO = CP.COD_PRODUTO AND TPM.COD_METADADO = 1 AND TPM.VLR_METADADO = 1) AS [MTD MARCA PROPRIA]
	,(SELECT VLR_METADADO FROM CADASTRO_CAD_PRODUTO_METADADOS TPM WHERE TPM.COD_PRODUTO = CP.COD_PRODUTO AND TPM.COD_METADADO = 18 AND TPM.VLR_METADADO = 1) AS [MTD PRODUCAO PROPRIA]	
	,BI.dbo.fn_FormataVlr_Excel(SUM(VP.VALOR_TOTAL)) AS VLR_TOTAL
	,BI.dbo.fn_FormataVlr_Excel(SUM(VP.QTDE_PRODUTO)) AS QTD_TOTAL
FROM
	BI.dbo.BI_VENDA_PRODUTO AS VP
	INNER JOIN BI_CAD_PRODUTO AS CP
		ON VP.COD_PRODUTO = CP.COD_PRODUTO
	LEFT JOIN BI_CAD_FORNECEDOR AS CF
		ON CP.COD_FORNECEDOR = CF.COD_FORNECEDOR
WHERE 1=1
	--AND CP.FORA_LINHA = 'N'
	AND VP.COD_LOJA = 7
	AND CP.COD_DEPARTAMENTO = 6
	AND CP.COD_SECAO IN (42,50)
	AND CONVERT(DATE,VP.DATA) BETWEEN CONVERT(DATE,'20141229') AND CONVERT(DATE,'20150208')
	--AND CP.COD_PRODUTO IN (SELECT COD_PRODUTO FROM CADASTRO_CAD_PRODUTO_METADADOS TPM WHERE TPM.COD_PRODUTO = CP.COD_PRODUTO AND TPM.COD_METADADO = 1 AND TPM.VLR_METADADO = 1)
GROUP BY
	CP.NO_DEPARTAMENTO
	,CP.NO_SECAO
	,CP.NO_GRUPO
	,CP.COD_PRODUTO
	,CP.DESCRICAO
	,CP.COD_FORNECEDOR
	,CF.DESCRICAO
