	INSERT INTO BI.DBO.BI_PRECO_COMPRA
		(
			[COD_LOJA]
			,[COD_PRODUTO]
			,[COD_FORNECEDOR]
			,[DTA_INI]
			,[DTA_FIM]
			,[DESCRICAO]
			,[VLR_EMB_COMPRA]
			,[QTD_EMB_COMPRA]
			,[COD_USUARIO]
		)		
	SELECT DISTINCT
		C.[COD_LOJA]
		,S.COD_PRODUTO_DST AS COD_PRODUTO
		,C.[COD_FORNECEDOR]
		,C.[DTA_INI]
		,C.[DTA_FIM]
		,C.[DESCRICAO]
		,C.[VLR_EMB_COMPRA]
		,C.[QTD_EMB_COMPRA]
		,9999
	FROM
		[BI].[dbo].[BI_PRECO_COMPRA] AS C
		INNER JOIN [BI].[dbo].[COMPRAS_DEPARA_PRODUTO] S
			ON (C.COD_PRODUTO = S.COD_PRODUTO_ORG)
	WHERE 1 = 1
		AND CONVERT(DATE,DTA_GRAVACAO) >= CONVERT(DATE,GETDATE()-1)
		AND S.COD_PRODUTO_ORG <> S.COD_PRODUTO_DST
		AND S.COD_PRODUTO_DST NOT IN (SELECT DISTINCT COD_PRODUTO FROM [BI].[dbo].[BI_PRECO_COMPRA] TC WHERE TC.COD_PRODUTO = S.COD_PRODUTO_DST AND TC.COD_FORNECEDOR = C.COD_FORNECEDOR AND CONVERT(DATE,TC.DTA_GRAVACAO) = CONVERT(DATE,GETDATE()) AND TC.[DTA_INI] = C.[DTA_INI] AND TC.[VLR_EMB_COMPRA] = C.[VLR_EMB_COMPRA])		