DECLARE @BI_VENDA_COMPRADOR_CHECK AS VARCHAR(10)
DECLARE @BI_VENDA_CUPOM_CHECK AS VARCHAR(10)
DECLARE @BI_VENDA_CUPOM_DELIVERY_CHECK AS VARCHAR(10)
DECLARE @BI_VENDA_CUPOM_PRODUTO_CHECK AS VARCHAR(10)
DECLARE @BI_VENDA_DEPARTAMENTO_CHECK AS VARCHAR(10)
DECLARE @BI_VENDA_GRUPO_CHECK AS VARCHAR(10)
DECLARE @BI_VENDA_PRODUTO_CHECK AS VARCHAR(10)

SELECT
	@BI_VENDA_COMPRADOR_CHECK = (CASE WHEN MAX(CONVERT(DATE,DATA)) = CONVERT(DATE,GETDATE()-1) THEN 'Success' ELSE 'Error' END)
FROM
	BI.DBO.BI_VENDA_COMPRADOR

SELECT
	@BI_VENDA_CUPOM_CHECK = (CASE WHEN MAX(CONVERT(DATE,DATA)) = CONVERT(DATE,GETDATE()-1) THEN 'Success' ELSE 'Error' END)
FROM
	BI.DBO.BI_VENDA_CUPOM

SELECT
	@BI_VENDA_CUPOM_DELIVERY_CHECK = (CASE WHEN MAX(CONVERT(DATE,DATA)) = CONVERT(DATE,GETDATE()-1) THEN 'Success' ELSE 'Error' END)
FROM
	BI.DBO.BI_VENDA_CUPOM_DELIVERY

SELECT
	@BI_VENDA_CUPOM_PRODUTO_CHECK = (CASE WHEN MAX(CONVERT(DATE,DATA)) = CONVERT(DATE,GETDATE()-1) THEN 'Success' ELSE 'Error' END)
FROM
	BI.DBO.BI_VENDA_CUPOM_PRODUTO

SELECT
	@BI_VENDA_DEPARTAMENTO_CHECK = (CASE WHEN MAX(CONVERT(DATE,DATA)) = CONVERT(DATE,GETDATE()-1) THEN 'Success' ELSE 'Error' END)
FROM
	BI.DBO.BI_VENDA_DEPARTAMENTO

SELECT
	@BI_VENDA_GRUPO_CHECK = (CASE WHEN MAX(CONVERT(DATE,DATA)) = CONVERT(DATE,GETDATE()-1) THEN 'Success' ELSE 'Error' END)
FROM
	BI.DBO.BI_VENDA_GRUPO

SELECT
	@BI_VENDA_PRODUTO_CHECK = (CASE WHEN MAX(CONVERT(DATE,DATA)) = CONVERT(DATE,GETDATE()-1) THEN 'Success' ELSE 'Error' END)
FROM
	BI.DBO.BI_VENDA_PRODUTO

SELECT
	@BI_VENDA_COMPRADOR_CHECK AS BI_VENDA_COMPRADOR_CHECK
	,@BI_VENDA_CUPOM_CHECK AS BI_VENDA_CUPOM_CHECK
	,@BI_VENDA_CUPOM_DELIVERY_CHECK AS BI_VENDA_CUPOM_DELIVERY_CHECK
	,@BI_VENDA_CUPOM_PRODUTO_CHECK AS BI_VENDA_CUPOM_PRODUTO_CHECK
	,@BI_VENDA_DEPARTAMENTO_CHECK AS BI_VENDA_DEPARTAMENTO_CHECK
	,@BI_VENDA_GRUPO_CHECK AS BI_VENDA_GRUPO_CHECK
	,@BI_VENDA_PRODUTO_CHECK AS BI_VENDA_PRODUTO_CHECK
