SELECT
	L.NO_LOJA
	,CONVERT(DATE,C.DATA) AS DATA
	,ISNULL(R.NO_RESTAURANTE,'') AS NO_RESTAURANTE
	,BI.dbo.fn_FormataVlr_Excel(C.QTDE_CUPOM) AS QTDE_CUPOM
	,BI.dbo.fn_FormataVlr_Excel(C.VALOR_TOTAL) AS VALOR_TOTAL
FROM
	BI.DBO.BI_VENDA_CUPOM AS C
	INNER JOIN BI.dbo.BI_CAD_LOJA2 AS L
		ON C.COD_LOJA = L.COD_LOJA	
	LEFT JOIN BI.dbo.BI_CAD_RESTAURANTE AS R
		ON C.TIPO = R.COD_RESTAURANTE
WHERE 1=1	
	AND C.COD_LOJA IN (29,33)
	AND CONVERT(DATE,C.DATA) >= '2015-05-18'
	and CONVERT(DATE,C.DATA) <> '2015-06-01'
ORDER BY
	C.COD_LOJA
	,C.DATA