DECLARE @TAB_PARAM_DATA_CC AS TABLE
(
	DATA DATE
	,DATA_INI DATE
	,DATA_FIM DATE
)

INSERT INTO @TAB_PARAM_DATA_CC
SELECT
	S.DATA	
	,(CASE
		WHEN DAY(S.DATA) <= 25 THEN
			(CASE 
				WHEN MONTH(S.DATA) = 1 THEN CONVERT(VARCHAR,S.ANO-1)+'-12-26'
				ELSE CONVERT(VARCHAR,S.ANO)+'-'+RIGHT('00'+CONVERT(VARCHAR,MONTH(S.DATA)-1),2)+'-26' 
			END)
		ELSE
			CONVERT(VARCHAR,S.ANO)+'-'+RIGHT('00'+CONVERT(VARCHAR,MONTH(S.DATA)),2)+'-26' 
	END) AS DT_INI
	,(CASE
		WHEN DAY(S.DATA) <= 25 THEN CONVERT(VARCHAR,S.ANO)+'-'+RIGHT('00'+CONVERT(VARCHAR,MONTH(S.DATA)),2)+'-25' 
		ELSE
		(CASE
			WHEN MONTH(S.DATA) = 12 THEN CONVERT(VARCHAR,S.ANO+1)+'-01-25'
			ELSE CONVERT(VARCHAR,S.ANO)+'-'+RIGHT('00'+CONVERT(VARCHAR,MONTH(S.DATA)+1),2)+'-25'
		END)		
	END) AS DT_FIM	
FROM
	BI.dbo.BI_CAD_SEMANA AS S
WHERE 1=1
	--AND CONVERT(DATE,S.DATA) BETWEEN CONVERT(DATE,'2015-12-20') AND CONVERT(DATE,'2016-01-28')

DECLARE @TAB_DATA_CONTA_CLIENTE AS TABLE
(
	DATA DATE
	,DATA_CONTA_CLIENTE DATE
)

INSERT INTO @TAB_DATA_CONTA_CLIENTE
SELECT
	DATA
	,CONVERT(VARCHAR,YEAR(DATA_FIM)) + '-' + RIGHT('00'+CONVERT(VARCHAR,MONTH(DATA_FIM)),2) + '-10' AS DATA_CONTA_CLIENTE
FROM @TAB_PARAM_DATA_CC


UPDATE S
SET
	S.DATA_CONTA_CLIENTE = DCC.DATA_CONTA_CLIENTE
FROM
	BI.dbo.BI_CAD_SEMANA AS S
	INNER JOIN @TAB_DATA_CONTA_CLIENTE AS DCC
		ON S.DATA = DCC.DATA