select * from DW.dbo.BI_ANAL_TICKET 
where 1=1
and COD_LOJA = 18
and CONVERT(date,data) = CONVERT(date,'20140609')

/*
delete from DW.dbo.BI_ANAL_TICKET 
where 1=1
and COD_LOJA = 18
and CONVERT(date,data) = CONVERT(date,'20140609')
*/

DECLARE @DT_INICIO [DATETIME] = CONVERT(DATE,'20140601')
DECLARE @DT_TERMINO [DATETIME]  = CONVERT(DATE,'20140706')

DELETE FROM [BI].[DBO].BI_VENDA_CUPOM
WHERE 1 = 1
AND DATA >= @DT_INICIO 
AND DATA <= @DT_TERMINO
--AND COD_LOJA = @COD_LOJA

INSERT INTO [BI].[DBO].BI_VENDA_CUPOM
		   ([COD_LOJA]
		   ,[DATA]
		   ,[QTDE_CUPOM]
		   ,[VALOR_TOTAL]
		   ,[CUPOM_MEDIO] 
		   ,TIPO)		

SELECT
	COD_LOJA
	,DATA
	,COUNT(CUPOM)
	,SUM(VALOR_TOTAL)
	,AVG(VALOR_TOTAL)
	,1
FROM DW.DBO.BI_ANAL_MOVTO_CAIXA
WHERE 1 = 1
	AND DATA >= @DT_INICIO
	AND DATA <= @DT_TERMINO
	--AND COD_LOJA = @COD_LOJA
GROUP BY
	COD_LOJA
	,DATA

	
DELETE FROM [BI].[DBO].BI_VENDA_PRODUTO
WHERE 1 = 1
AND DATA >= @DT_INICIO 
AND DATA <= @DT_TERMINO
--AND COD_LOJA = @COD_LOJA
	
INSERT INTO [BI].[DBO].BI_VENDA_PRODUTO
	   ([COD_LOJA]
	   ,[DATA]
	   ,[COD_PRODUTO]
	   ,[TIPO_VENDA]
	   ,[QTDE_PRODUTO]
	   ,[VALOR_TOTAL]
	   ,[VALOR_UNITARIO]
	   ,[QTDE_DEMANDA]
	   ,[COD_CLIENTE])
SELECT 
	COD_LOJA 
	,DATA
	,COD_PRODUTO
	,1 AS [TIPO_VENDA]
	,SUM(QTDE) AS [QTDE_PRODUTO]
	,SUM(VALOR) AS [VALOR_TOTAL]
	,0 AS [VALOR_UNITARIO]
	,COUNT(QTDE) AS [QTDE_DEMANDA]
	,0 AS [COD_CLIENTE]
FROM DW.DBO.BI_ANAL_TICKET WITH (NOLOCK) 
WHERE 1 = 1
	AND DATA >= @DT_INICIO
	--AND COD_LOJA = @COD_LOJA
	AND DATA <= @DT_TERMINO
	AND COD_PRODUTO IS NOT NULL
GROUP BY COD_LOJA , DATA , COD_PRODUTO


exec bi.[dbo].[CARGA_COMPRAS_DNV_CALCULADORA]