EXEC [CARGA_BI_MARGEM_PRODUTO_MES] '20140331'
EXEC [CARGA_BI_MARGEM_PRODUTO_MES] '20140430'
EXEC [CARGA_BI_MARGEM_PRODUTO_MES] '20140531'
EXEC [CARGA_BI_MARGEM_PRODUTO_MES] '20140630'
EXEC [CARGA_BI_MARGEM_PRODUTO_MES] '20140731'
EXEC [CARGA_BI_MARGEM_PRODUTO_MES] '20140831'
EXEC [CARGA_BI_MARGEM_PRODUTO_MES] '20140930'
EXEC [CARGA_BI_MARGEM_PRODUTO_MES] '20141031'
EXEC [CARGA_BI_MARGEM_PRODUTO_MES] '20141130'
EXEC [CARGA_BI_MARGEM_PRODUTO_MES] '20141231'

--NAO RODOU AINDA
EXEC [CARGA_BI_MARGEM_PRODUTO_MES] '20150131'
EXEC [CARGA_BI_MARGEM_PRODUTO_MES] '20150228'
EXEC [CARGA_BI_MARGEM_PRODUTO_MES] '20150331'

/*
	--TRUNCATE TABLE [BI].[dbo].[BI_MARGEM_PRODUTO_MES]
	
	DECLARE @DATA AS DATE = '20140131'

	DECLARE @DTA_INI_MES AS DATE = DW.[DBO].[fn_PrimeiroDiadoMes](CONVERT(DATE,@DATA)) 

	INSERT INTO [BI].[dbo].[BI_MARGEM_PRODUTO_MES]
	(
		[COD_LOJA]
		,[ANO]
		,[MES]
		,[COD_PRODUTO]
		,[LUCRO_BRUTO]
		,[VLR_VENDA]
		,[VLR_AJUSTE]	
		,[VLR_MRG]
	)
	SELECT
		VPM.COD_LOJA
		,YEAR(VPM.DATA) AS ANO
		,MONTH(VPM.DATA) AS MES
		,VPM.COD_PRODUTO	
		,(SUM(VPM.VLR_VENDA_BRUTA) - SUM(VPM.VLR_CMV) - SUM(VPM.VLR_PISCOFINS) - SUM(VPM.VLR_ICMS_SAIDA*VPM.VLR_VENDA_BRUTA)) AS LB
		,SUM(VPM.VLR_VENDA_BRUTA) AS VLR_VENDA
		,ISNULL((SELECT A.AJUSTE_NET FROM [BI].[dbo].[BI_MARGEM_PRODUTO_AJUSTE] AS A WHERE VPM.COD_LOJA = A.COD_LOJA AND YEAR(VPM.DATA) = A.ANO AND MONTH(VPM.DATA) = A.MES AND VPM.COD_PRODUTO = A.COD_PRODUTO),0) as VLR_AJUSTE
		,(SUM(VPM.VLR_VENDA_BRUTA) - SUM(VPM.VLR_CMV) - SUM(VPM.VLR_PISCOFINS) - SUM(VPM.VLR_ICMS_SAIDA*VPM.VLR_VENDA_BRUTA) + ISNULL((SELECT A.AJUSTE_NET FROM [BI].[dbo].[BI_MARGEM_PRODUTO_AJUSTE] AS A WHERE VPM.COD_LOJA = A.COD_LOJA AND YEAR(VPM.DATA) = A.ANO AND MONTH(VPM.DATA) = A.MES AND VPM.COD_PRODUTO = A.COD_PRODUTO),0)) / (CASE WHEN SUM(VLR_VENDA_BRUTA) = 0 THEN 9999999 ELSE SUM(VLR_VENDA_BRUTA) END) AS VLR_MRG
	FROM
		[BI].[dbo].[BI_VENDA_PRODUTO_CMV] AS VPM	
	WHERE 1=1
		AND CONVERT(DATE,VPM.DATA) BETWEEN CONVERT(DATE,@DTA_INI_MES) AND CONVERT(DATE,@DATA)
	GROUP BY
		VPM.COD_LOJA
		,YEAR(VPM.DATA)
		,MONTH(VPM.DATA)
		,VPM.COD_PRODUTO
	ORDER BY
		VPM.COD_LOJA
		,YEAR(VPM.DATA)
		,MONTH(VPM.DATA)
		,VPM.COD_PRODUTO
*/