	SELECT
		ANO
		,MES
		,BI.dbo.fn_FormataVlr_Excel((SUM(M.[LUCRO_BRUTO])+SUM(M.[VLR_AJUSTE]))/SUM(M.[VLR_VENDA])) AS VLR_MRG_IMP
	FROM 
		BI_CAD_PRODUTO AS CP
		INNER JOIN [BI].[dbo].[BI_MARGEM_PRODUTO_MES] AS M
			ON 1=1
			AND CP.COD_PRODUTO = M.COD_PRODUTO
	WHERE 1 = 1
		AND CP.COD_FORNECEDOR = 18055
		--AND CP.COD_DEPARTAMENTO NOT IN (6)
		AND CP.COD_DEPARTAMENTO IN (1,2,3,4,7,9,10,11,14,15,19,20)
		AND CP.COD_PRODUTO IN (SELECT DISTINCT COD_PRODUTO FROM CADASTRO_CAD_PRODUTO_METADADOS AS M WHERE M.COD_METADADO = 4 AND VLR_METADADO = 1)
	GROUP BY
		ANO
		,MES
	ORDER BY
		ANO
		,MES 
		
		
	SELECT
		ANO
		,MES
		,BI.dbo.fn_FormataVlr_Excel((SUM(M.[LUCRO_BRUTO])+SUM(M.[VLR_AJUSTE]))/SUM(M.[VLR_VENDA])) AS VLR_MRG
	FROM 
		BI_CAD_PRODUTO AS CP
		INNER JOIN [BI].[dbo].[BI_MARGEM_PRODUTO_MES] AS M
			ON 1=1
			AND CP.COD_PRODUTO = M.COD_PRODUTO
	WHERE 1 = 1
		AND CP.COD_FORNECEDOR = 18055
		--AND CP.COD_DEPARTAMENTO NOT IN (6)
		AND CP.COD_DEPARTAMENTO IN (1,2,3,4,7,9,10,11,14,15,19,20)
		AND CP.COD_PRODUTO NOT IN (SELECT DISTINCT COD_PRODUTO FROM CADASTRO_CAD_PRODUTO_METADADOS AS M WHERE M.COD_METADADO = 4 AND VLR_METADADO = 1)
	GROUP BY
		ANO
		,MES
	ORDER BY
		ANO
		,MES 