SELECT
	COD_LOJA
	,RIGHT('000000' + CONVERT(VARCHAR(6),CADASTRO), 6) AS CRACHA
	,NOME
	,CARGO
FROM INTRANET.DBO.TAB_FUNCIONARIOS
WHERE 1 = 1
	--AND CADASTRO = 348
	AND CARGO LIKE '%COORD%'
	AND DEPARTAMENTO IN ('GERENCIA','OPERACOES')
	AND SITUACAO = 'TRABALHANDO'

UNION ALL

SELECT
	COD_LOJA
	,RIGHT('000000' + CONVERT(VARCHAR(6),CADASTRO), 6) AS CRACHA
	,NOME
	,CARGO
FROM INTRANET.DBO.TAB_FUNCIONARIOS
WHERE 1 = 1
	--AND CADASTRO = 348
	AND CARGO LIKE '%GER%'
	AND DEPARTAMENTO IN ('GERENCIA','OPERACOES')
	AND SITUACAO = 'TRABALHANDO'
ORDER BY
	COD_LOJA
	,NOME
	

	
SELECT * FROM INTRANET.DBO.TAB_FUNCIONARIOS
WHERE 1 = 1
	AND CARGO LIKE '%FISC%'
	AND SITUACAO = 'TRABALHANDO'