	/*
	SELECT top 10
		*
	FROM
		[DW].[dbo].[TAB_CHEFFSOLUTION_CUPOM]
	WHERE 1=1
		--AND CONVERT(DATE,DT_CUPOM) BETWEEN CONVERT(DATE,@DT_INICIO) AND CONVERT(DATE,@DT_TERMINO)
		AND COD_LOJA = 26
	*/
	INSERT INTO BI.DBO.BI_VENDA_CUPOM_CAPA
	(
		[COD_LOJA]
		,[DATA]
		,[CAIXA]
		,[CUPOM]
		,[HORA]
		,[COD_OPERADOR]
		,[CPF_NFP]
		,[CPF_VCM]
		,[VLR_CUPOM]
		,[VLR_DESCONTO]
		,[QTD_ITEM]
		,[CUPOM_HASH]
	)	
	
	SELECT --top 10
		[COD_LOJA]
		,DT_CUPOM
		,[CAIXA]
		,[CUPOM]
		,CONVERT(NUMERIC(18,0),REPLACE([HORA],':',''))
		,0
		,CONVERT(NUMERIC(18,0),CPF)
		,null
		,VALOR_TOTAL_PRODUTOS
		,0
		,(
			SELECT
				COUNT(DISTINCT ITEM.COD_PRODUTO)
			FROM
				[DW].[dbo].[TAB_CHEFFSOLUTION_CUPOM_ITENS] AS ITEM
			WHERE 1=1
				AND ITEM.COD_LOJA = CAPA.COD_LOJA    
				AND ITEM.CUPOM = CAPA.CUPOM
				AND ITEM.DATA = CAPA.DT_CUPOM
				AND ITEM.CAIXA = CAPA.CAIXA
		) AS [QTD_ITEM]
		,CONVERT(VARCHAR,CAPA.DT_CUPOM,112)+ RIGHT('000'+ CONVERT(VARCHAR,CAPA.COD_LOJA),3) + RIGHT('000'+ CONVERT(VARCHAR,CAPA.CAIXA),3) + RIGHT('00000000'+ CONVERT(VARCHAR,CAPA.CUPOM),8) AS [CUPOM_HASH]
	FROM
		[DW].[dbo].[TAB_CHEFFSOLUTION_CUPOM] AS CAPA
	WHERE 1=1
		--AND CONVERT(DATE,DT_CUPOM) BETWEEN CONVERT(DATE,@DT_INICIO) AND CONVERT(DATE,@DT_TERMINO)
		AND COD_LOJA = 26
	