DECLARE @TAB_LISTA_ETIQUETA AS TABLE
(
	COD_PRODUTO INT
	,COD_EAN VARCHAR(50)
);

INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (1011361);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (1002547);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (1002568);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (558808);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (558822);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (558815);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (558839);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (1002479);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (1011414);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (990812);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (990812);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (990823);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (990823);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (990816);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (990816);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (1011415);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (1011418);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (990819);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (990819);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (1011412);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (990818);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (990818);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (990814);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (990814);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (990824);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (990824);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (990815);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (990815);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (990821);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (990821);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (1011413);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (990813);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (990813);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (1011411);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (1011383);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (1011409);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (1011366);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (1011391);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (1011389);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (1011408);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (1011365);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (1011401);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (1011399);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (1011397);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (1011405);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (1011406);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (1011394);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (1011381);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (1011407);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (1011385);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (1011363);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (1011364);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (1011395);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (1011410);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (1011404);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (1011387);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (226516);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (533690);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (81023);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (105583);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (1005491);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (533850);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (533980);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (534000);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (427098);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (540148);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (73127);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (540162);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (65566);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (491815);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (999460);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (999459);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (116046);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (920520);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (931212);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (995273);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (1008626);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (1008626);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (1008625);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (1008625);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (1008627);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (1008627);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (1008628);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (1008628);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (536110);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (1000352);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (142434);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (916189);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (986465);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (927970);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (14489);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (995266);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (995267);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (1010372);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (590532);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (1007918);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (1007920);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (1008101);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (994378);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (992820);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (1000781);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (1000837);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (1010375);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (1000780);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (1007919);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (590525);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (993320);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (558778);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (86561);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (86578);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (120098);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (216494);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (991398);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (120074);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (121736);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (727013);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (631242);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (71505);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (120395);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (558761);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (83706);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (69427);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (83041);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (724371);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (477185);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (724364);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (558785);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (55055);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (55062);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (881616);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (494410);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (291293);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (649346);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (362344);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (251549);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (251549);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (925044);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (288880);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (288880);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (925068);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (251563);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (251563);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (1008506);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (84581);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (107716);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (608220);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (55864);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (220927);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (992870);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (992869);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (102827);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (1001403);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (1001357);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (991290);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (991292);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (991293);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (991294);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (991295);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (594257);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (594288);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (478106);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (123631);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (115896);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (116015);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (123624);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (720977);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (721004);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (720991);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (584388);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (513746);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (594226);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (123617);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (991770);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (116107);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (513715);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (513722);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (54775);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (514576);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (54751);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (514569);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (1002045);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (1002046);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (223003);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (237314);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (211178);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (54829);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (552714);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (477048);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (235358);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (1001633);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (1001632);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (128285);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (678032);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (148375);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (1010053);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (992872);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (992871);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (111096);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (91091);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (91046);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (91022);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (91077);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (89005);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (91107);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (102636);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (980913);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (1010049);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (144407);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (257916);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (257893);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (279970);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (257909);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (603249);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (257930);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (257923);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (1010056);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (1010051);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (1010048);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (1010050);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (1010055);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (1010052);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (1010054);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (1010059);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (1010058);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (1010057);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (567367);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (213325);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (328463);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (235051);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (179553);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (193054);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (478731);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (478748);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (83294);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (994801);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (434980);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (240635);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (584210);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (51132);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (60110);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (60059);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (1000473);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (60141);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (584074);
INSERT INTO @TAB_LISTA_ETIQUETA (COD_PRODUTO) VALUES (584159);

UPDATE LISTA
SET
	LISTA.COD_EAN = CB.COD_EAN
FROM
	@TAB_LISTA_ETIQUETA AS LISTA INNER JOIN AX2009_INTEGRACAO.dbo.TAB_CODIGO_BARRA_PRINCIPAL AS CB ON (LISTA.COD_PRODUTO = CB.COD_PRODUTO)
	

DECLARE @COD_PRODUTO INT
DECLARE @COD_EAN VARCHAR(50)
DECLARE @COD_LISTA AS INT

select max(LISTA) from [MarcheCorp].[dbo].[Tab_Coletores]
select @COD_LISTA = max(LISTA) from [MarcheCorp].[dbo].[Tab_Coletores]

-- Cursor para percorrer os nomes dos objetos 
DECLARE cursor_objects CURSOR FOR
	SELECT
		COD_PRODUTO
		,COD_EAN
	FROM
		@TAB_LISTA_ETIQUETA;

-- Abrindo Cursor para leitura
OPEN cursor_objects

-- Lendo a próxima linha
FETCH NEXT FROM cursor_objects INTO @COD_PRODUTO, @COD_EAN

-- Percorrendo linhas do cursor (enquanto houverem)
WHILE @@FETCH_STATUS = 0
BEGIN
	
	exec [MarcheCorp].DBO.sp_MARCHE_COLETORES 
	'HASHtdhdgashauysdjkhasjkdhajkhhfgf4485' , 
	21 , 
	NULL , 
	@COD_EAN , 
	1 , 
	@COD_LISTA, 
	NULL , 
	'9999' , 
	1 , 
	0 , 
	0 , 
	0 


    -- Lendo a próxima linha
    FETCH NEXT FROM cursor_objects INTO @COD_PRODUTO, @COD_EAN
END
-- Fechando Cursor para leitura
CLOSE cursor_objects
-- Desalocando o cursor
DEALLOCATE cursor_objects 




