	DECLARE @TAB_CUSTO_MAX AS TABLE
	(
		COD_PRODUTO INT
		,COD_FORNECEDOR INT
		,DTA_GRAVACAO DATETIME
	)

	INSERT INTO @TAB_CUSTO_MAX
		SELECT
			COD_PRODUTO
			,COD_FORNECEDOR
			,MAX(DTA_GRAVACAO)
		FROM
			BI_PRECO_COMPRA
		WHERE 1=1
			AND COD_PRODUTO IN	(60721,12768,8433,13857,7375,12300,16988,12355,12416,12706,12256,60578,12362,12270,7870,12621,12331)
		GROUP BY
			COD_PRODUTO
			,COD_FORNECEDOR		
	
	DECLARE @TAB_CUSTO_NOVO AS TABLE
	(
		[COD_PRODUTO] INT
		,[COD_FORNECEDOR] INT
		,[DTA_INI] DATE
		,[DTA_FIM] DATE
		,[DESCRICAO] VARCHAR(50)
		,[VLR_EMB_COMPRA] NUMERIC(18,2)
		,[QTD_EMB_COMPRA] NUMERIC(18,2)
	)
	INSERT INTO @TAB_CUSTO_NOVO
	SELECT
		C.COD_PRODUTO
		,C.[COD_FORNECEDOR]
		,C.[DTA_INI]
		,C.[DTA_FIM]
		,C.[DESCRICAO]
		,C.[VLR_EMB_COMPRA]
		,C.[QTD_EMB_COMPRA]
	FROM
		BI_PRECO_COMPRA AS C
		INNER JOIN @TAB_CUSTO_MAX AS T
			ON 1=1
			AND C.COD_PRODUTO = T.COD_PRODUTO
			AND C.COD_FORNECEDOR = T.COD_FORNECEDOR
			AND C.DTA_GRAVACAO = T.DTA_GRAVACAO
	WHERE 1=1
		
	INSERT INTO BI.DBO.BI_PRECO_COMPRA
		(
			[COD_LOJA]
			,[COD_PRODUTO]
			,[COD_FORNECEDOR]
			,[DTA_INI]
			,[DTA_FIM]
			,[DESCRICAO]
			,[VLR_EMB_COMPRA]
			,[QTD_EMB_COMPRA]
			,[COD_USUARIO]
		)		
	SELECT DISTINCT
		0 AS COD_LOJA
		,S.COD_PRODUTO_DST AS COD_PRODUTO
		,C.[COD_FORNECEDOR]
		,C.[DTA_INI]
		,C.[DTA_FIM]
		,C.[DESCRICAO]
		,C.[VLR_EMB_COMPRA]
		,C.[QTD_EMB_COMPRA]
		,9999
	FROM
		@TAB_CUSTO_NOVO AS C
		INNER JOIN [BI].[dbo].[COMPRAS_DEPARA_PRODUTO] S
			ON (C.COD_PRODUTO = S.COD_PRODUTO_ORG)
	WHERE 1 = 1
		--AND CONVERT(DATE,DTA_GRAVACAO) >= CONVERT(DATE,GETDATE()-1)
		AND S.COD_PRODUTO_ORG <> S.COD_PRODUTO_DST
		AND S.COD_PRODUTO_DST NOT IN (SELECT DISTINCT COD_PRODUTO FROM [BI].[dbo].[BI_PRECO_COMPRA] TC WHERE TC.COD_PRODUTO = S.COD_PRODUTO_DST AND TC.COD_FORNECEDOR = C.COD_FORNECEDOR AND CONVERT(DATE,TC.DTA_GRAVACAO) = CONVERT(DATE,GETDATE()) AND TC.[DTA_INI] = C.[DTA_INI] AND TC.[VLR_EMB_COMPRA] = C.[VLR_EMB_COMPRA])		
		and (S.COD_PRODUTO_DST NOT IN (130) AND C.COD_FORNECEDOR NOT IN (13766))
		and (S.COD_PRODUTO_DST NOT IN (1601,1779,1793,3414,4060,4688,5074,7061) AND C.COD_FORNECEDOR NOT IN (15451))
		and (S.COD_PRODUTO_DST NOT IN (12577) AND C.COD_FORNECEDOR NOT IN (102986))
		and (S.COD_PRODUTO_DST NOT IN (60523) AND C.COD_FORNECEDOR NOT IN (15292))


