	DECLARE @DATA_INI AS DATE = GETDATE()-30
	DECLARE @DATA_FIM AS DATE = GETDATE()-1
	DECLARE @QTD_DIAS AS INT = DATEDIFF(D,@DATA_INI,@DATA_FIM) + 1
	
		SELECT
			LP.COD_LOJA
			,L.NO_LOJA
			,CFP.COD_FORNECEDOR
			,CF.DESCRICAO AS NO_FORNECEDOR
			,LP.COD_PRODUTO
			,CP.DESCRICAO AS NO_PRODUTO
			,CP.NO_DEPARTAMENTO
			,CP.NO_SECAO
			,CP.NO_GRUPO
			,BI.dbo.fn_FormataVlr_Excel(ISNULL(LP.VLR_VENDA,0)) AS PV
			,BI.dbo.fn_FormataVlr_Excel(ISNULL(LP.VLR_OFERTA,0)) AS PO
			,BI.dbo.fn_FormataVlr_Excel(ISNULL(SUM(VP.VALOR_TOTAL)/nullif(SUM(VP.QTDE_PRODUTO),0),0)) AS PV_PD
			,BI.dbo.fn_FormataVlr_Excel(ISNULL(EP.QTD_ESTOQUE,0)) AS QTD_ESTOQUE
			,BI.dbo.fn_FormataVlr_Excel(ISNULL(EP.QTD_ESTOQUE * (SUM(VP.VALOR_TOTAL)/nullif(SUM(VP.QTDE_PRODUTO),0)),0)) AS ESTOQUE_PV_PD
			,BI.dbo.fn_FormataVlr_Excel(ISNULL(SUM(VP.VALOR_TOTAL)/@QTD_DIAS,0)) AS AVG_VLR_PD		
			,BI.dbo.fn_FormataVlr_Excel(ISNULL(SUM(VP.QTDE_PRODUTO)/@QTD_DIAS,0)) AS AVG_QTD_PD
			,BI.dbo.fn_FormataVlr_Excel(ISNULL((EP.QTD_ESTOQUE*(SUM(VP.VALOR_TOTAL)/nullif(SUM(VP.QTDE_PRODUTO),0)))/(SUM(VP.VALOR_TOTAL)/@QTD_DIAS),0)) AS DPD
			,LP.FORA_LINHA
		FROM
			BI.dbo.BI_LINHA_PRODUTOS AS LP
			INNER JOIN BI.dbo.BI_CAD_PRODUTO AS CP
				ON LP.COD_PRODUTO = CP.COD_PRODUTO
			INNER JOIN BI.dbo.BI_CAD_FORNECEDOR_PRODUTO AS CFP
				ON LP.COD_PRODUTO = CFP.COD_PRODUTO
			INNER JOIN BI.dbo.BI_CAD_LOJA2 AS L
				ON LP.COD_LOJA = L.COD_LOJA
			LEFT JOIN BI.dbo.BI_CAD_FORNECEDOR AS CF
				ON CFP.COD_FORNECEDOR = CF.COD_FORNECEDOR				
			LEFT JOIN BI.DBO.BI_VENDA_PRODUTO AS VP
				ON 1=1
				AND LP.COD_LOJA = VP.COD_LOJA
				AND LP.COD_PRODUTO = VP.COD_PRODUTO
				AND CONVERT(DATE,VP.DATA) BETWEEN CONVERT(DATE,@DATA_INI) AND CONVERT(DATE,@DATA_FIM)
			LEFT JOIN DW.dbo.ESTOQUE AS EP
				ON 1=1
				AND LP.COD_LOJA = EP.COD_LOJA
				AND LP.COD_PRODUTO = EP.COD_PRODUTO
				AND CONVERT(DATE,EP.DATA) = CONVERT(DATE,GETDATE())			
		WHERE 1=1			
			AND CFP.COD_FORNECEDOR = 102985
			AND LP.FORA_LINHA = 'S'
		GROUP BY
			LP.COD_LOJA
			,L.NO_LOJA
			,CFP.COD_FORNECEDOR
			,CF.DESCRICAO
			,LP.COD_PRODUTO
			,CP.DESCRICAO
			,CP.NO_DEPARTAMENTO
			,CP.NO_SECAO
			,CP.NO_GRUPO
			,LP.VLR_VENDA
			,LP.VLR_OFERTA
			,EP.QTD_ESTOQUE
			,LP.FORA_LINHA

		
	/*
	SELECT
		COD_LOJA
		,COD_PRODUTO
		,QTD_ESTOQUE
	FROM
		DW.dbo.ESTOQUE
	WHERE 1=1
		AND COD_LOJA = 29
		AND CONVERT(DATE,DATA) = CONVERT(DATE,GETDATE())
	*/