
	--DECLARE @DATA_P1_INI AS DATE = '20121231'
	DECLARE @DATA_P1_INI AS DATE = '20150323'
	--DECLARE @DATA_P1_FIM AS DATE = '20131229'
	DECLARE @DATA_P1_FIM AS DATE = '20150323'

	
	SELECT
		EP.COD_LOJA
		,L.NO_LOJA
		,CP.COD_PRODUTO
		,CP.DESCRICAO AS NO_PRODUTO
		,CP.DESCRICAO + ' | ' + CONVERT(VARCHAR,CP.COD_PRODUTO) AS PROD_PLU
		,bi.dbo.fn_FormataVlr_Excel(NULLIF(EP.AVG_VLR_U30D_PD,0)) as AVG_VLR_U30D_PD
		,bi.dbo.fn_FormataVlr_Excel(EP.VLR_VENDA) as VLR_VENDA
		,bi.dbo.fn_FormataVlr_Excel(SUM(EP.QTD_ESTOQUE)) AS ESTOQUE
		,bi.dbo.fn_FormataVlr_Excel(SUM(EP.QTD_ESTOQUE * EP.VLR_VENDA)) AS ESTOQUE_VLR
		,bi.dbo.fn_FormataVlr_Excel(SUM(EP.QTD_ESTOQUE * EP.VLR_VENDA) / NULLIF(EP.AVG_VLR_U30D_PD,0)) as DPD
		,bi.dbo.fn_FormataVlr_Excel(NULLIF(EP.AVG_VLR_U30D_PD,0) * 95.3) as ESTOQUE_VLR_META_DPD
		,bi.dbo.fn_FormataVlr_Excel((SUM(EP.QTD_ESTOQUE * EP.VLR_VENDA) - (NULLIF(EP.AVG_VLR_U30D_PD,0) * 95.3))/EP.VLR_VENDA) as QTD_ESTOQUE_RETIRAR		
	FROM	
		BI.dbo.BI_CAD_PRODUTO AS CP
		INNER JOIN BI.dbo.BI_ESTOQUE_PRODUTO_DIA AS EP
			ON CP.COD_PRODUTO = EP.COD_PRODUTO
		INNER JOIN BI.dbo.BI_CAD_LOJA2 AS L
			ON EP.COD_LOJA = L.COD_LOJA
		--INNER JOIN BI.DBO.BI_CAD_SEMANA AS S
		--	ON EP.DATA = S.DATA
	WHERE 1=1
		--AND CFP.COD_FORNECEDOR = 1999
		--and CP.COD_PRODUTO = 59060
		and CP.COD_DEPARTAMENTO = 2
		AND CONVERT(DATE,EP.DATA) BETWEEN CONVERT(DATE,@DATA_P1_INI) AND CONVERT(DATE,@DATA_P1_FIM)
	GROUP BY
		EP.COD_LOJA
		,L.NO_LOJA
		,CP.COD_PRODUTO
		,CP.DESCRICAO
		,EP.VLR_VENDA
		,NULLIF(EP.AVG_VLR_U30D_PD,0) 
	ORDER BY
		DESCRICAO
		,(SUM(EP.QTD_ESTOQUE * EP.VLR_VENDA) / NULLIF(EP.AVG_VLR_U30D_PD,0)) desc
		,EP.COD_LOJA
		,SUM(EP.QTD_ESTOQUE) desc