DECLARE @dataIni AS DATE = '20141229'
DECLARE @dataFim AS DATE = '20150125'

SELECT SUM(VALOR_TOTAL)
FROM
	[DW].[DBO].[BI_ANAL_MOVTO_CAIXA]
WHERE 1=1
	AND COD_LOJA = 7
	AND CONVERT(DATE,data) between CONVERT(DATE,@dataIni) and  CONVERT(DATE,@dataFim)

SELECT SUM(VALOR)
FROM
	[DW].[dbo].[BI_ANAL_TICKET]
WHERE 1=1
	AND COD_LOJA = 7
	AND CONVERT(DATE,data) between CONVERT(DATE,@dataIni) and  CONVERT(DATE,@dataFim)

SELECT SUM(t.valor)
FROM
		[DW].[DBO].[BI_ANAL_MOVTO_CAIXA] AS MC
		INNER JOIN [DW].[DBO].[BI_ANAL_TICKET] AS T
			ON 1=1
			AND MC.COD_LOJA = T.COD_LOJA
			AND MC.CAIXA = T.CAIXA
			AND MC.CUPOM = T.CUPOM
			AND MC.DATA = T.DATA
	WHERE 1 = 1
		AND CONVERT(DATE,MC.DATA) BETWEEN CONVERT(DATE,@dataIni) AND CONVERT(DATE,@dataFim)
