	DECLARE @DATA_INI AS DATE = GETDATE()-90
	DECLARE @DATA_FIM AS DATE = GETDATE()

	SELECT	
		P.COD_LOJA
		,convert(int,P.COD_PARCEIRO) as COD_FORNECEDOR
		,CONVERT(VARCHAR(12),P.NUM_PEDIDO) AS NUM_PEDIDO
		,CONVERT(DATE,P.DTA_EMISSAO) as DATA_PEDIDO
		,CONVERT(DATE,P.DTA_ENTREGA) AS DATA_RECEBIMENTO_PEDIDO
		,CONVERT(DATE,P.DTA_ENTREGA) AS DATA_RECEBIMENTO		
		,PP.COD_PRODUTO
		,PP.QTD_EMBALAGEM
		,BI.dbo.fn_FormataVlr_Excel(PP.QTD_PEDIDO) AS QTD_PEDIDO
		,BI.dbo.fn_FormataVlr_Excel(ISNULL(PP.QTD_RECEBIDA,0)) AS QTD_RECEBIDA	
		,(CASE
			WHEN ISNULL(PP.QTD_RECEBIDA,0) <= 0 THEN 'PENDENTE'
			WHEN ISNULL(PP.QTD_RECEBIDA,0) < PP.QTD_PEDIDO THEN 'PARCIAL'		
			WHEN ISNULL(PP.QTD_RECEBIDA,0) >= PP.QTD_PEDIDO THEN 'OK'
		END) as [STATUS_PEDIDO]
		,BI.dbo.fn_FormataVlr_Excel(PP.VAL_TABELA*PP.QTD_PEDIDO) AS VLR_TOTAL_PEDIDO
		,BI.dbo.fn_FormataVlr_Excel(PP.VAL_TABELA*PP.QTD_RECEBIDA) AS VLR_TOTAL_RECEBIMENTO		
		,'Pedido Normal' as TIPO_PEDIDO
		--,(CASE WHEN DATEADD(D,7,P.DTA_ENTREGA) < GETDATE() AND PP.QTD_RECEBIDA = 0 THEN 'Expirado' ELSE 'Valido' END) AS VALIDADE_PEDIDO
		,(CASE
			WHEN DATEADD(D,7,P.DTA_ENTREGA) < GETDATE() AND PP.QTD_RECEBIDA = 0 THEN 'Expirado'
			WHEN DATEADD(D,7,P.DTA_ENTREGA) < GETDATE() AND P.DTA_ENTREGA <= P.DTA_ENTREGA THEN 'Entregue'
			ELSE 'Aguardando'
		END) AS VALIDADE_PEDIDO
    FROM
		[192.168.0.6].[ZEUS_RTG].DBO.[TAB_PEDIDO] AS P
		INNER JOIN [192.168.0.6].[ZEUS_RTG].DBO.[TAB_PEDIDO_PRODUTO] AS PP
			ON 1=1
			and P.NUM_PEDIDO = PP.NUM_PEDIDO
			AND P.COD_LOJA = PP.COD_LOJA
			AND P.COD_PARCEIRO = PP.COD_PARCEIRO
    WHERE 1 = 1
		AND CONVERT(DATE,P.DTA_EMISSAO) between CONVERT(DATE,@DATA_INI) AND CONVERT(DATE,@DATA_FIM)
		AND ISNULL(PP.QTD_RECEBIDA,0) > PP.QTD_PEDIDO*20

	SELECT DISTINCT P.NUM_PEDIDO
	FROM
		[192.168.0.6].[ZEUS_RTG].DBO.[TAB_PEDIDO] AS P
		INNER JOIN [192.168.0.6].[ZEUS_RTG].DBO.[TAB_PEDIDO_PRODUTO] AS PP
			ON 1=1
			and P.NUM_PEDIDO = PP.NUM_PEDIDO
			AND P.COD_LOJA = PP.COD_LOJA
			AND P.COD_PARCEIRO = PP.COD_PARCEIRO
    WHERE 1 = 1
		AND CONVERT(DATE,P.DTA_EMISSAO) between CONVERT(DATE,@DATA_INI) AND CONVERT(DATE,@DATA_FIM)
		AND ISNULL(PP.QTD_RECEBIDA,0) > PP.QTD_PEDIDO*10