	DECLARE @TAB_ESTOQUE_CUSTO AS TABLE
	(
		COD_LOJA INT
		,DATA DATE
		,ANO INT
		,MES INT
		,COD_PRODUTO INT
		,COD_DEPARTAMENTO INT
		,CUSTO_MEDIO NUMERIC(18,3)
		,QTD_ESTOQUE NUMERIC(18,3)
		,CUSTO_ULTIMAENTRADA NUMERIC(18,3)
		,CUSTO_AJUSTADO NUMERIC(18,3)
		,ESTOQUE_CUSTO NUMERIC(18,3)
		,PRIMARY KEY (COD_LOJA,DATA,COD_PRODUTO)
	)
		
	INSERT INTO @TAB_ESTOQUE_CUSTO
		--EXEC MARCHECORP.DBO.SP_RELATORIOS_GERA_IMPRESSAO_TIPO_072 1 ,@DATA_PROC, 1
		EXEC MARCHECORP.DBO.SP_RELATORIOS_GERA_IMPRESSAO_TIPO_072 1 ,'2015-02-18' , 1	