SELECT
	COMP.NO_COMPRADOR
	,PL.FORA_LINHA
	,EP.[COD_LOJA]
	,CP.NO_DEPARTAMENTO
	,CP.NO_SECAO
	,CP.NO_GRUPO
	,EP.[COD_PRODUTO]	
	,CP.DESCRICAO as NO_PRODUTO
	,dbo.fn_FormataVlr_Excel(SUM(EP.[QTD_ESTOQUE])) AS QTD_ESTOQUE
	,dbo.fn_FormataVlr_Excel(SUM(PF.VLR_EMB_COMPRA/nullif(PF.QTD_EMB_COMPRA,0))) AS CUSTO
	,dbo.fn_FormataVlr_Excel(SUM(EP.[QTD_ESTOQUE]*(PF.VLR_EMB_COMPRA/nullif(PF.QTD_EMB_COMPRA,0)))) AS ESTOQUE_CUSTO
FROM
	[BI].[DBO].[BI_ESTOQUE_PRODUTO] AS EP
		INNER JOIN BI.DBO.BI_CAD_PRODUTO AS CP
			ON 1 = 1
			AND EP.COD_PRODUTO = CP.COD_PRODUTO
		INNER JOIN [BI].[DBO].BI_LINHA_PRODUTOS AS PL
			ON 1 = 1
			AND EP.COD_PRODUTO = PL.COD_PRODUTO
			AND EP.COD_LOJA = PL.COD_LOJA
		INNER JOIN BI.dbo.COMPRAS_CAD_COMPRADOR AS COMP
			ON CP.COD_USUARIO = COMP.COD_USUARIO
		INNER JOIN VW_CUSTOS_ATIVOS AS PF
			ON 1 = 1
			AND EP.COD_PRODUTO = PF.COD_PRODUTO
			AND CP.COD_FORNECEDOR = PF.COD_FORNECEDOR				
WHERE 1=1
	AND EP.QTD_ESTOQUE>0
	AND CP.COD_USUARIO <> 8113
	AND CP.PESADO = 'N'
	--AND EP.COD_LOJA = 19
	AND CP.COD_DEPARTAMENTO NOT IN (7,99,20,15) --EXCLUSAO DEP OUTROS
	AND EP.COD_LOJA IN (1,2,3,4,6,7,9,10,12,13,17,18,19,20,21,30)
GROUP BY
	COMP.NO_COMPRADOR
	,PL.FORA_LINHA
	,EP.[COD_LOJA]
	,CP.NO_DEPARTAMENTO
	,CP.NO_SECAO
	,CP.NO_GRUPO
	,EP.[COD_PRODUTO]	
	,CP.DESCRICAO
