SELECT
	EPD.COD_LOJA
	,CP.COD_PRODUTO
	,BI.dbo.fn_FormataVlr_Excel(EPD.QTD_ESTOQUE) AS QTD_ESTOQUE
	,CP.DESCRICAO
	,CP.NO_DEPARTAMENTO
	,CP.NO_SECAO
	,CP.NO_GRUPO
	,CP.COD_FORNECEDOR
	,CF.DES_FANTASIA
	,BI.dbo.fn_FormataVlr_Excel(EPD.VLR_CUSTO_UN) AS VLR_CUSTO_UN
	,BI.dbo.fn_FormataVlr_Excel(EPD.VLR_VENDA) AS VLR_VENDA
FROM
	BI_ESTOQUE_PRODUTO_DIA AS EPD
	LEFT JOIN BI_CAD_PRODUTO AS CP
		ON EPD.COD_PRODUTO = CP.COD_PRODUTO
	LEFT JOIN BI_CAD_FORNECEDOR AS CF
		ON CP.COD_FORNECEDOR = CF.COD_FORNECEDOR
WHERE 1=1
	AND CONVERT(DATE,DATA) = '20150506'
	and cod_loja = 29
ORDER BY
	CP.NO_DEPARTAMENTO
	,CP.NO_SECAO
	,CP.NO_GRUPO
	,CP.DESCRICAO