SELECT --TOP 10
	LP.COD_LOJA
	,LP.COD_PRODUTO
	,CP.DESCRICAO
	,BI.dbo.fn_FormataVlr_Excel(EP.QTD_ESTOQUE) as QTD_ESTOQUE
	,BI.dbo.fn_FormataVlr_Excel(SUM(VP.VALOR_TOTAL)) AS VLR_TOTAL
	,BI.dbo.fn_FormataVlr_Excel(SUM(VP.QTDE_PRODUTO)) AS QTD_TOTAL
FROM
	BI_LINHA_PRODUTOS as LP
	INNER JOIN BI_CAD_PRODUTO AS CP
		ON 1=1
		AND LP.COD_PRODUTO = CP.COD_PRODUTO
	INNER JOIN BI_ESTOQUE_PRODUTO AS EP
		ON 1=1
		AND LP.COD_PRODUTO = EP.COD_PRODUTO
		AND LP.COD_LOJA = EP.COD_LOJA
	INNER JOIN BI_VENDA_PRODUTO AS VP
		ON 1=1
		AND LP.COD_PRODUTO = VP.COD_PRODUTO
		AND LP.COD_LOJA = VP.COD_LOJA
WHERE 1=1
	AND CONVERT(DATE,VP.DATA) BETWEEN CONVERT(DATE,'20150101') AND CONVERT(DATE,'20150131')
	AND LP.FORA_LINHA = 'S'
	AND LP.COD_DEPARTAMENTO = 2
	AND EP.QTD_ESTOQUE <> 0
GROUP BY
	LP.COD_LOJA
	,LP.COD_PRODUTO
	,CP.DESCRICAO
	,EP.QTD_ESTOQUE
order by
	CP.DESCRICAO
	,LP.COD_LOJA