--SELECT * FROM CADASTRO_CAD_PRODUTO_METADADOS WHERE COD_PRODUTO = 17

SELECT
	*
FROM
	BI_CAD_PRODUTO AS CP
WHERE 1=1
	AND CP.COD_PRODUTO IN (SELECT COD_PRODUTO FROM CADASTRO_CAD_PRODUTO_METADADOS TPM WHERE TPM.COD_PRODUTO = CP.COD_PRODUTO AND (TPM.COD_METADADO = 1 AND TPM.VLR_METADADO IN ('1'))    )
	AND CP.COD_PRODUTO IN (SELECT COD_PRODUTO FROM CADASTRO_CAD_PRODUTO_METADADOS TPM WHERE TPM.COD_PRODUTO = CP.COD_PRODUTO AND (TPM.COD_METADADO = 2 AND TPM.VLR_METADADO IN ('LOJA'))	 )
	AND CP.COD_PRODUTO IN (SELECT COD_PRODUTO FROM CADASTRO_CAD_PRODUTO_METADADOS TPM WHERE TPM.COD_PRODUTO = CP.COD_PRODUTO AND (TPM.COD_METADADO = 3 AND TPM.VLR_METADADO IN ('0'))	 )
	AND CP.COD_PRODUTO IN (SELECT COD_PRODUTO FROM CADASTRO_CAD_PRODUTO_METADADOS TPM WHERE TPM.COD_PRODUTO = CP.COD_PRODUTO AND (TPM.COD_METADADO = 6 AND TPM.VLR_METADADO IN ('STM'))	 )
	AND CP.COD_PRODUTO IN (SELECT COD_PRODUTO FROM CADASTRO_CAD_PRODUTO_METADADOS TPM WHERE TPM.COD_PRODUTO = CP.COD_PRODUTO AND (TPM.COD_METADADO = 18 AND TPM.VLR_METADADO IN ('1')) )
	AND CP.COD_PRODUTO IN (SELECT COD_PRODUTO FROM CADASTRO_CAD_PRODUTO_METADADOS TPM WHERE TPM.COD_PRODUTO = CP.COD_PRODUTO AND (TPM.COD_METADADO = 20 AND TPM.VLR_METADADO IN ('KG')) )
	AND CP.COD_PRODUTO IN (SELECT COD_PRODUTO FROM CADASTRO_CAD_PRODUTO_METADADOS TPM WHERE TPM.COD_PRODUTO = CP.COD_PRODUTO AND (TPM.COD_METADADO = 21 AND TPM.VLR_METADADO IN ('1')) )
	--AND CP.COD_PRODUTO IN (SELECT COD_PRODUTO FROM CADASTRO_CAD_PRODUTO_METADADOS TPM WHERE TPM.COD_PRODUTO = CP.COD_PRODUTO AND (TPM.COD_METADADO = 29 AND TPM.VLR_METADADO IN ('PÃO FRANCÊS ST MARCHE KG')) )
order by COD_PRODUTO




SELECT * FROM CADASTRO_CAD_PRODUTO_METADADOS TPM WHERE TPM.COD_METADADO = 6 AND TPM.VLR_METADADO IN ('STM')	