SELECT
*
FROM
(
	SELECT
		LP.COD_LOJA
		,CP.NO_DEPARTAMENTO
		,CP.NO_SECAO
		,CP.NO_GRUPO
		,LP.COD_PRODUTO
		,CP.DESCRICAO
		,MAX(VP.DATA) AS DATA_ULT_VENDA
		,MAX(EP.DATA) AS DATA_ULT_ENTRADA
	FROM
		BI.DBO.BI_LINHA_PRODUTOS AS LP
		INNER JOIN BI.DBO.BI_CAD_PRODUTO AS CP
			ON LP.COD_PRODUTO = CP.COD_PRODUTO
		LEFT JOIN BI.DBO.BI_VENDA_PRODUTO AS VP
			ON 1=1
			AND LP.COD_LOJA = VP.COD_LOJA
			AND LP.COD_PRODUTO = VP.COD_PRODUTO
			AND CONVERT(DATE,VP.DATA) >= '20150101'
		LEFT JOIN BI.DBO.BI_ENTRADA_PRODUTO AS EP
			ON 1=1
			AND LP.COD_LOJA = EP.COD_LOJA
			AND LP.COD_PRODUTO = EP.COD_PRODUTO
			AND CONVERT(DATE,EP.DATA) >= '20150101'
	WHERE 1=1
		AND LP.FORA_LINHA = 'S'
	GROUP BY
		LP.COD_LOJA
		,CP.NO_DEPARTAMENTO
		,CP.NO_SECAO
		,CP.NO_GRUPO
		,LP.COD_PRODUTO
		,CP.DESCRICAO
)AS A
WHERE 1=1
AND (DATA_ULT_VENDA IS NOT NULL OR DATA_ULT_ENTRADA IS NOT NULL)