DECLARE @TAB_CUSTO_PROD AS TABLE
(
	COD_PRODUTO INT
	,COD_FORNECEDOR INT
	,VLR_EMB_COMPRA NUMERIC(18,2)
	,QTD_EMB_COMPRA NUMERIC(18,2)
)

INSERT INTO @TAB_CUSTO_PROD
	SELECT
		COD_PRODUTO
		,COD_FORNECEDOR
		,MAX(VAL_CUSTO_EMBALAGEM)
		,MAX(QTD_EMBALAGEM_COMPRA)	
	FROM
		[192.168.0.6].ZEUS_RTG.DBO.TAB_PRODUTO_FORNECEDOR
	WHERE 1=1
		AND COD_LOJA IN (1,2,3,6,7,9,12,13,17,18,19,20,21,22,23,24,25,30)
	GROUP BY
		COD_PRODUTO
		,COD_FORNECEDOR

DECLARE @TAB_CUSTO_SUBIR AS TABLE
(
	[COD_LOJA] INT
	,[COD_PRODUTO] INT
	,[COD_FORNECEDOR] INT
	,[DTA_INI] DATE
	,[DTA_FIM] DATE
	,[DESCRICAO] VARCHAR(50)
	,[VLR_EMB_COMPRA] NUMERIC(18,2)
	,[Ativo] BIT
	,[QTD_EMB_COMPRA] NUMERIC(18,2)
	,[COD_USUARIO] INT
	,[VLR_EMB_COMPRA_ANTIGO] NUMERIC(18,2)
	,[DTA_PROCESSAMENTO] DATETIME
	,[ALTERAR_PV] BIT
)

INSERT INTO @TAB_CUSTO_SUBIR
SELECT
	0 AS COD_LOJA
	,TC.COD_PRODUTO
	,TC.COD_FORNECEDOR
	,GETDATE()-1 AS DTA_INI
	,GETDATE()+360 AS DTA_FIM
	,'Tabela Compra'
	,TC.VLR_EMB_COMPRA
	,NULL
	,TC.QTD_EMB_COMPRA
	,99999 AS COD_USUARIO
	,NULL
	,'20141022' AS DTA_PROCESSAMENTO
	,NULL
FROM
	@TAB_CUSTO_PROD AS TC
	INNER JOIN BI.dbo.BI_CAD_PRODUTO AS CP
		ON 1=1
		AND TC.COD_FORNECEDOR = CP.COD_FORNECEDOR
		AND TC.COD_PRODUTO = CP.COD_PRODUTO
WHERE 1=1
	AND CP.FORA_LINHA = 'N'
	AND TC.COD_FORNECEDOR IN (SELECT DISTINCT COD_FORNECEDOR FROM COMPRAS_AGENDA_PEDIDO_MATRIZ)

INSERT INTO [BI].[dbo].[BI_PRECO_COMPRA]
(
	[COD_LOJA]
	,[COD_PRODUTO]
	,[COD_FORNECEDOR]
	,[DTA_INI]
	,[DTA_FIM]
	,[DESCRICAO]
	,[VLR_EMB_COMPRA]
	,[Ativo]
	,[QTD_EMB_COMPRA]
	,[COD_USUARIO]
	,[VLR_EMB_COMPRA_ANTIGO]
	,[DTA_PROCESSAMENTO]
	,[ALTERAR_PV]
)
SELECT
	C.[COD_LOJA]
	,C.[COD_PRODUTO]
	,C.[COD_FORNECEDOR]
	,C.[DTA_INI]
	,C.[DTA_FIM]
	,C.[DESCRICAO]
	,C.[VLR_EMB_COMPRA]
	,C.[Ativo]
	,C.[QTD_EMB_COMPRA]
	,C.[COD_USUARIO]
	,C.[VLR_EMB_COMPRA_ANTIGO]
	,C.[DTA_PROCESSAMENTO]
	,C.[ALTERAR_PV]
FROM
	@TAB_CUSTO_SUBIR AS C
	LEFT JOIN BI.dbo.VW_CUSTOS_ATIVOS AS CA
		ON 1=1
		AND C.COD_FORNECEDOR = CA.COD_FORNECEDOR
		AND C.COD_PRODUTO = CA.COD_PRODUTO
WHERE 1=1
	AND CA.COD_FORNECEDOR IS NULL

	
	