
		SET NOCOUNT ON;		
		DECLARE @QTD_LOJAS AS INT		
		SELECT @QTD_LOJAS = COUNT(DISTINCT LP.COD_LOJA) FROM [BI].[DBO].[BI_LINHA_PRODUTOS] AS LP		
		
		DECLARE @TAB_PROD_FORN AS TABLE
		(
			COD_FORNECEDOR INT
			,COD_PRODUTO INT
			,DES_REFERENCIA VARCHAR(30)
			,VAL_CUSTO_EMBALAGEM NUMERIC(8,2)
			,QTD_EMBALAGEM_COMPRA NUMERIC(8,2)
			,QTD_MINIMA_COMPRA NUMERIC(8,2)
		);

		INSERT INTO @TAB_PROD_FORN
			SELECT DISTINCT
				PF.COD_FORNECEDOR
				,PF.COD_PRODUTO
				,PF.DES_REFERENCIA
				,PF.VAL_CUSTO_EMBALAGEM
				,PF.QTD_EMBALAGEM_COMPRA
				,PF.QTD_MINIMA_COMPRA
			FROM
				[192.168.0.6].ZEUS_RTG.DBO.TAB_PRODUTO_FORNECEDOR AS PF
			WHERE 1 = 1
				AND PF.COD_FORNECEDOR = `1`

		SELECT DISTINCT
			 PF.COD_FORNECEDOR as [Cod Forn]
			,PF.COD_PRODUTO as [PLU]
			,CP.DESCRICAO as [Produto]
			,PF.DES_REFERENCIA as [Referencia]
			,CB.COD_EAN as [EAN]
			,PF.VAL_CUSTO_EMBALAGEM as [CustoEmb]
			,PF.QTD_EMBALAGEM_COMPRA as [QtdEmb]
			,PF.QTD_MINIMA_COMPRA as [QtdMult]
			,CC.NO_COMPRADOR as Comprador
			,(CASE
				WHEN
					(SELECT COUNT(LP.COD_LOJA) FROM [BI].[DBO].[BI_LINHA_PRODUTOS] AS LP	WHERE LP.FORA_LINHA = 'N' AND  LP.COD_PRODUTO = CP.COD_PRODUTO) = @QTD_LOJAS THEN 'Todas'
				WHEN
					CP.FORA_LINHA = 'S' THEN 'Fora Linha'
				ELSE
					STUFF(
					(
						SELECT  
							CONVERT(VARCHAR,LP.COD_LOJA)+' | ' 
						FROM
							[BI].[DBO].[BI_LINHA_PRODUTOS] AS LP
						WHERE  1=1
							AND LP.FORA_LINHA = 'N'
							AND  LP.COD_PRODUTO = CP.COD_PRODUTO
						ORDER BY LP.COD_LOJA
						FOR XML PATH('')
					),1,0,'')
			END) AS [Lojas Linha]	
		FROM
			@TAB_PROD_FORN AS PF
			INNER JOIN [AX2009_INTEGRACAO].dbo.[TAB_CODIGO_BARRA_PRINCIPAL] AS CB
				ON (PF.COD_PRODUTO = CB.COD_PRODUTO)
			INNER JOIN [BI].dbo.[BI_CAD_PRODUTO] AS CP
				ON (PF.COD_PRODUTO = CP.COD_PRODUTO)
			LEFT JOIN BI.dbo.COMPRAS_CAD_COMPRADOR AS CC
				ON (CP.COD_USUARIO = CC.COD_USUARIO)
		ORDER BY
			CP.DESCRICAO