SELECT
	CP.NO_DEPARTAMENTO
	,CP.NO_SECAO
	,CP.NO_GRUPO
	,CP.NO_SUBGRUPO
	,CP.COD_PRODUTO
	,CP.DESCRICAO
	,CP.FORA_LINHA
	,CP.[FORA_LINHA]
	,CP.[DTA_CADASTRO]
	,CP.[PESADO]
	,CP.[UNIDADE_COMPRA]
	,CP.[UNIDADE_VENDA]
	,CP.[FLG_MARCA_PROPRIA]
	,CP.[COD_FORNECEDOR]
	,CF.DES_FANTASIA AS NO_FORNECEDOR	
	,CP.[CLASSIF_PRODUTO]
	,CP.[COD_PRODUTO_SIMILAR]
	,CP.[VLR_MRGREF_MED]
	,CP.[VLR_MRGREF_MAX]
	,CP.[VLR_MRGREF_MIN]
	,CP.[COD_USUARIO]
	,CC.NO_COMPRADOR
	,CP.[PNP]
	,CP.[DIAS_VALIDADE]
	,CP.[COD_NCM]
FROM
	BI.DBO.BI_CAD_PRODUTO AS CP
	LEFT JOIN BI_CAD_FORNECEDOR AS CF
		ON CP.COD_FORNECEDOR = CF.COD_FORNECEDOR
	LEFT JOIN COMPRAS_CAD_COMPRADOR AS CC
		ON CP.COD_USUARIO = CC.COD_USUARIO
WHERE 1=1
	and CP.COD_DEPARTAMENTO = 2
ORDER BY
	CP.NO_DEPARTAMENTO
	,CP.NO_SECAO
	,CP.NO_GRUPO
	,CP.NO_SUBGRUPO
	,CP.COD_PRODUTO
	,CP.DESCRICAO