--SELECT TOP 10 * FROM BI.dbo.VW_CUSTOS_ATIVOS2

SELECT
	L.NO_LOJA
	,L.DTA_ABERTURA
	--,VP.COD_PRODUTO
	,BI.DBO.FN_FORMATAVLR_EXCEL(SUM(VP.VALOR_TOTAL)) AS VLR_TOTAL
	,BI.DBO.FN_FORMATAVLR_EXCEL(SUM(VP.QTDE_PRODUTO)) AS QTD_TOTAL
	,BI.DBO.FN_FORMATAVLR_EXCEL(SUM(VP.QTDE_PRODUTO * C.VLR_EMB_COMPRA/C.QTD_EMB_COMPRA)) AS CUSTO_FORN_PRINCIPAL
	,BI.DBO.FN_FORMATAVLR_EXCEL((SUM(VP.VALOR_TOTAL)-SUM(VP.QTDE_PRODUTO * C.VLR_EMB_COMPRA/C.QTD_EMB_COMPRA))/SUM(VP.VALOR_TOTAL))
FROM
	BI.dbo.BI_VENDA_PRODUTO AS VP
	INNER JOIN BI.dbo.BI_CAD_PRODUTO AS CP
		ON VP.COD_PRODUTO = CP.COD_PRODUTO	
	LEFT JOIN BI.dbo.VW_CUSTOS_ATIVOS2 AS C
		ON 1=1
		AND VP.COD_PRODUTO = C.COD_PRODUTO
		AND CP.COD_FORNECEDOR = C.COD_FORNECEDOR
	LEFT JOIN BI.dbo.BI_CAD_LOJA2 AS L
		ON VP.COD_LOJA = L.COD_LOJA
WHERE 1=1
	AND CP.COD_DEPARTAMENTO = 2
	AND CONVERT(DATE,DATA) between CONVERT(DATE,'2015-12-01') AND CONVERT(DATE,'2015-12-31')
	--and VP.cod_loja = 3
	and VP.COD_PRODUTO not in
	(1016906,1016901,1016905,1016903)

GROUP BY
	L.NO_LOJA
	,L.DTA_ABERTURA
	--,VP.COD_PRODUTO
ORDER BY
	L.DTA_ABERTURA
