DECLARE @DATA_INI AS DATE = '20150901'
DECLARE @DATA_FIM AS DATE = '20150930'

SELECT-- TOP 10
	MKD.COD_LOJA
	,S.MES_454
	,S.SEMANA_454
	,CP.NO_DEPARTAMENTO
	,CP.NO_SECAO
	,CP.NO_GRUPO
	,(CASE WHEN MKD.MKT_CodCampanha IS NULL THEN MKD.MOTIVO ELSE MKD.Mkt_DESCRICAo END) AS MOTIVO_MKD
	,(CASE WHEN MKD.MKT_CodCampanha IS NULL THEN 0 ELSE 1 END) AS PROMO_MKT
	,SUM(MKD.MrkDown) AS MrkDown
FROM
	DW.DBO.[PRODUTO_MARKDOWN] as MKD
	INNER JOIN BI.dbo.BI_CAD_SEMANA AS S
		ON MKD.DATA = S.DATA
	INNER JOIN BI.dbo.BI_CAD_PRODUTO AS CP
		ON MKD.COD_PRODUTO = CP.COD_PRODUTO	
WHERE 1=1
	AND MKD.FLAG_ANALISAR IS NULL
	--AND MKD.Mkt_DESCRICAo IS NOT NULL
	AND CONVERT(DATE,MKD.DATA) BETWEEN CONVERT(DATE,@DATA_INI) AND CONVERT(DATE,@DATA_FIM)
GROUP BY
	MKD.COD_LOJA
	,S.MES_454
	,S.SEMANA_454
	,CP.NO_DEPARTAMENTO
	,CP.NO_SECAO
	,CP.NO_GRUPO
	,(CASE WHEN MKD.MKT_CodCampanha IS NULL THEN MKD.MOTIVO ELSE MKD.Mkt_DESCRICAo END)
	,(CASE WHEN MKD.MKT_CodCampanha IS NULL THEN 0 ELSE 1 END)