SELECT
	CP.COD_PRODUTO
	,CP.DESCRICAO AS NO_PRODUTO	
	,BI.dbo.fn_FormataVlr_Excel(REF.MARCHEMULTIPLO) AS MULTIPLO
	,BI.dbo.fn_FormataVlr_Excel(REF.MARCHEQTDEMBALAGEM) AS QTD_EMBALAGEM
	,REF.COD_FORNECEDOR
	,CF.DESCRICAO AS NO_FORNECEDOR
	,isnull((SELECT VLR_METADADO FROM CADASTRO_CAD_PRODUTO_METADADOS TPM WHERE TPM.COD_PRODUTO = CP.COD_PRODUTO AND TPM.COD_METADADO = 4),0) AS MTD_IMP_PROP
	,isnull((SELECT VLR_METADADO FROM CADASTRO_CAD_PRODUTO_METADADOS TPM WHERE TPM.COD_PRODUTO = CP.COD_PRODUTO AND TPM.COD_METADADO = 3),0) AS MTD_IMP
	,CP.FORA_LINHA
FROM 
	BI.DBO.BI_CAD_PRODUTO AS CP
	LEFT JOIN AX2009_INTEGRACAO.DBO.TAB_PRODUTO_REFERENCIA AS REF
		ON CP.COD_PRODUTO = REF.COD_PRODUTO
	LEFT JOIN BI.dbo.BI_CAD_FORNECEDOR AS CF
		ON REF.COD_FORNECEDOR = CF.COD_FORNECEDOR
WHERE 1=1