DECLARE @TAB_EXTRACAO_PRECOS AS TABLE
(
	COD_PRODUTO INT
	,COD_PRODUTO_TERCEIRO INT
	,COD_PRODUTO_SIMILAR INT
	,ANO_454 INT
	,MES_454 INT
	,SEMANA_454 INT
	,DATA DATE
	,MIN_PRECO_MEDIO_MARCHE NUMERIC(18,2)
	,MIN_PRECO_VENDA_MARCHE NUMERIC(18,2)
	,MIN_PRECO_PESQUISA NUMERIC(18,2)
	,TIPO_PESQUISA VARCHAR(10)
)

INSERT INTO @TAB_EXTRACAO_PRECOS
(
	COD_PRODUTO 
	,COD_PRODUTO_TERCEIRO
	,COD_PRODUTO_SIMILAR
	,ANO_454
	,MES_454
	,SEMANA_454
	,DATA
	,MIN_PRECO_MEDIO_MARCHE
	,MIN_PRECO_VENDA_MARCHE
	,MIN_PRECO_PESQUISA
	,TIPO_PESQUISA
)
	SELECT
		(CASE WHEN DEPARA_PROD.COD_PRODUTO IS NULL THEN EXT.COD_PRODUTO ELSE DEPARA_PROD.COD_PRODUTO END) AS COD_PRODUTO
		--,DEPARA_PROD.COD_PRODUTO
		,EXT.COD_PRODUTO_TERCEIRO
		,DEPARA_COD.COD_PRODUTO_SIMILAR
		,S.ANO_454
		,S.MES_454
		,S.SEMANA_454
		,CONVERT(DATE,EXT.DATA_EXTRACAO) AS DATA
		,EP.MIN_PRECO_MEDIO_MARCHE
		,PV.MIN_PRECO_VENDA_MARCHE
		,MIN(EXT.VLR_PRODUTO) AS MIN_PRECO_PESQUISA
		,'Site PA' AS TIPO_PESQUISA
	FROM
		[BI].[DBO].[BI_PRECOS_TERCEIROS] AS EXT		
		INNER JOIN BI.dbo.BI_CAD_SEMANA AS S
			ON EXT.DATA_EXTRACAO = S.DATA		
		INNER JOIN BI.dbo.BI_CAD_PRODUTO AS CP
			ON EXT.COD_PRODUTO = CP.COD_PRODUTO
		LEFT JOIN (SELECT COD_PRODUTO, MIN(VLR_VENDA_U90D_PD) AS MIN_PRECO_MEDIO_MARCHE FROM BI.dbo.COMPRAS_ESTATISTICA_PRODUTO GROUP BY COD_PRODUTO) AS EP
			ON EXT.COD_PRODUTO = EP.COD_PRODUTO
		LEFT JOIN (SELECT COD_PRODUTO, MIN(CASE WHEN VLR_VCMARCHE IS NOT NULL THEN VLR_VCMARCHE ELSE (CASE WHEN VLR_OFERTA IS NOT NULL THEN VLR_OFERTA ELSE VLR_VENDA END) END) AS MIN_PRECO_VENDA_MARCHE , COUNT(VLR_OFERTA) as QTD_OFERTA FROM BI.dbo.BI_LINHA_PRODUTOS GROUP BY COD_PRODUTO HAVING COUNT(VLR_OFERTA) = 0 OR COUNT(VLR_OFERTA) >=9) AS PV
			ON EXT.COD_PRODUTO = PV.COD_PRODUTO
		--DE PARA COPIANDO DADOS
		LEFT JOIN [BI].[dbo].[CADASTRO_DEPARA_PRODUTO_SIMILAR] AS DEPARA_COD
			ON EXT.COD_PRODUTO = DEPARA_COD.COD_PRODUTO
		LEFT JOIN [BI].[dbo].[CADASTRO_DEPARA_PRODUTO_SIMILAR] AS DEPARA_PROD
			ON DEPARA_COD.COD_PRODUTO_SIMILAR = DEPARA_PROD.COD_PRODUTO_SIMILAR		
	WHERE 1=1
		AND CP.FORA_LINHA = 'N'
		AND EXT.COD_PRODUTO IS NOT NULL
		AND CONVERT(DATE,DATA_EXTRACAO) >= CONVERT(DATE,GETDATE()-4)
		--AND EXT.COD_PRODUTO = 1687
	GROUP BY
		(CASE WHEN DEPARA_PROD.COD_PRODUTO IS NULL THEN EXT.COD_PRODUTO ELSE DEPARA_PROD.COD_PRODUTO END)
		,DEPARA_PROD.COD_PRODUTO 
		,EXT.COD_PRODUTO_TERCEIRO
		,DEPARA_COD.COD_PRODUTO_SIMILAR
		,S.ANO_454
		,S.MES_454
		,S.SEMANA_454
		,CONVERT(DATE,EXT.DATA_EXTRACAO)
		,EP.MIN_PRECO_MEDIO_MARCHE	
		,PV.MIN_PRECO_VENDA_MARCHE

DECLARE @TAB_EXTRACAO_PRECOS_FINAL AS TABLE
(
	COD_PRODUTO INT
	,COD_PRODUTO_TERCEIRO INT
	,COD_PRODUTO_SIMILAR INT
	,ANO_454 INT
	,MES_454 INT
	,SEMANA_454 INT
	,DATA DATE
	,MIN_PRECO_MEDIO_MARCHE NUMERIC(18,2)
	,MIN_PRECO_VENDA_MARCHE NUMERIC(18,2)
	,MIN_PRECO_PESQUISA NUMERIC(18,2)
	,TIPO_PESQUISA VARCHAR(10)
)

INSERT INTO @TAB_EXTRACAO_PRECOS_FINAL
(
	COD_PRODUTO 
	,ANO_454
	,MES_454
	,SEMANA_454
	,DATA
	,MIN_PRECO_MEDIO_MARCHE
	,MIN_PRECO_VENDA_MARCHE
	,MIN_PRECO_PESQUISA
	,TIPO_PESQUISA
)
	SELECT
		COD_PRODUTO
		,ANO_454
		,MES_454
		,SEMANA_454
		,DATA
		,MIN(MIN_PRECO_MEDIO_MARCHE) AS MIN_PRECO_MEDIO_MARCHE
		,MIN(MIN_PRECO_VENDA_MARCHE) AS MIN_PRECO_VENDA_MARCHE
		,MIN(MIN_PRECO_PESQUISA) AS MIN_PRECO_PESQUISA
		,TIPO_PESQUISA
	FROM
		@TAB_EXTRACAO_PRECOS
	GROUP BY
		COD_PRODUTO
		,ANO_454
		,MES_454
		,SEMANA_454
		,DATA
		,TIPO_PESQUISA

SELECT
	COD_PRODUTO 
	,ANO_454
	,MES_454
	,SEMANA_454
	,DATA
	,BI.dbo.fn_FormataVlr_Excel(MIN_PRECO_MEDIO_MARCHE) AS VLR_VENDA_MEDIO
	,BI.dbo.fn_FormataVlr_Excel(MIN_PRECO_VENDA_MARCHE) AS VLR_VENDA
	,BI.dbo.fn_FormataVlr_Excel(MIN_PRECO_PESQUISA) AS VLR_VENDA_PESQUISA
	,TIPO_PESQUISA
FROM
	@TAB_EXTRACAO_PRECOS_FINAL