		SELECT
			P.NUM_PEDIDO as [Pedido]
			,P.COD_PARCEIRO as [Cod Forn]
			,P.COD_LOJA as [Loja]
			,P.DTA_EMISSAO as [Dta Emissao]
			,P.DTA_ENTREGA as [Dta Entrega]
			,COUNT(PP.COD_PRODUTO) AS [Itens]
			--TOTAL DO PEDIDO
		FROM
			[ZEUS_RTG].DBO.[TAB_PEDIDO] AS P INNER JOIN [ZEUS_RTG].DBO.[TAB_PEDIDO_PRODUTO] AS PP ON (P.NUM_PEDIDO = PP.NUM_PEDIDO AND P.COD_LOJA = PP.COD_LOJA AND P.COD_PARCEIRO = PP.COD_PARCEIRO AND P.COD_USUARIO = P.COD_USUARIO)
		WHERE 1 = 1
			AND P.NUM_PEDIDO = 397039--`1`
			AND P.COD_PARCEIRO =  1103--`2`
			AND P.COD_LOJA = 3--`3`
			--AND CONVERT(DATE,DTA_EMISSAO) >= CONVERT(DATE,'20140501')
		GROUP BY
			P.NUM_PEDIDO
			,P.COD_PARCEIRO
			,P.COD_LOJA
			,P.DTA_EMISSAO
			,P.DTA_ENTREGA
	
	
		SELECT
			PP.COD_PRODUTO AS [Plu]
			,PROD.DESCRICAO as [Produto]--PROD.DES_PRODUTO
			,PP.QTD_PEDIDO as [Qtd Ped]
			,PP.QTD_EMBALAGEM as [Qtd Emb]
			,PP.VAL_TABELA as [Vlr Tabela]
			,PP.VAL_TABELA_FINAL AS [Vlr Total]
			,ISNULL(PP.QTD_RECEBIDA,0) AS [Qtd Recebida]
			,USR.NO_COMPRADOR  AS [Comprador]--USR.DES_NOME 
		FROM
			[ZEUS_RTG].DBO.[TAB_PEDIDO] AS P INNER JOIN [ZEUS_RTG].DBO.[TAB_PEDIDO_PRODUTO] AS PP ON (P.NUM_PEDIDO = PP.NUM_PEDIDO AND P.COD_LOJA = PP.COD_LOJA AND P.COD_PARCEIRO = PP.COD_PARCEIRO AND P.COD_USUARIO = P.COD_USUARIO)
				--INNER JOIN [ZEUS_RTG].DBO.[TAB_PRODUTO] AS PROD ON (PP.COD_PRODUTO = PROD.COD_PRODUTO)
				INNER JOIN [192.168.0.13].[BI].DBO.[BI_CAD_PRODUTO] AS PROD ON (PP.COD_PRODUTO = PROD.COD_PRODUTO)
				--INNER JOIN [ZEUS_RTG].DBO.[TAB_USUARIO] AS USR ON (P.COD_USUARIO = USR.COD_USUARIO)
				INNER JOIN [192.168.0.13].[BI].DBO.[COMPRAS_CAD_COMPRADOR] AS USR ON (P.COD_USUARIO = USR.COD_USUARIO)
		WHERE 1 = 1
			AND P.NUM_PEDIDO = 397039--`1`
			AND P.COD_PARCEIRO =  1103--`2`
			AND P.COD_LOJA = 3--`3`
			--AND CONVERT(DATE,DTA_EMISSAO) >= CONVERT(DATE,'20140501')
