SELECT
	P.NUM_PEDIDO as [Pedido]
	,sum(PP.VAL_TABELA*PP.QTD_PEDIDO) as [Vlr Pedido]
	,f.[DES_FORNECEDOR] as Fornecedor
	,f.[NUM_CGC] as CNPJ
	,P.COD_PARCEIRO as [Cod Forn]
	,P.COD_LOJA as [Loja]
	,L.NUM_CGC AS [CNPJ Loja]
	,P.DTA_EMISSAO as [Data Emissao]
	,P.DTA_ENTREGA as [Data Entrega]
	,convert(varchar,CF.COD_FISCAL_EXPORTACAO) + ' | ' + CF.DES_CODIGO_FISCAL AS [CFOP]
	,COUNT(PP.COD_PRODUTO) AS [Itens]
FROM
	[ZEUS_RTG].DBO.[TAB_PEDIDO] AS P
	INNER JOIN [ZEUS_RTG].DBO.[TAB_PEDIDO_PRODUTO] AS PP
		ON 1=1
		and P.NUM_PEDIDO = PP.NUM_PEDIDO
		AND P.COD_LOJA = PP.COD_LOJA
		AND P.COD_PARCEIRO = PP.COD_PARCEIRO
		AND P.COD_USUARIO = P.COD_USUARIO
	INNER JOIN [Zeus_rtg].[dbo].[TAB_FORNECEDOR] AS F
		ON (f.cod_fornecedor = p.cod_parceiro)
	INNER JOIN [ZEUS_RTG].DBO.TAB_CODIGO_FISCAL AS CF
		ON P.COD_FISCAL = CF.COD_FISCAL
	INNER JOIN [ZEUS_RTG].DBO.[TAB_LOJA] AS L
		ON P.COD_LOJA = L.COD_LOJA
WHERE 1 = 1
	AND CONVERT(DATE,DTA_EMISSAO) >= CONVERT(DATE,'2013-01-01')
	and P.COD_PARCEIRO = 101703
GROUP BY
	P.NUM_PEDIDO
	,P.COD_PARCEIRO
	,P.COD_LOJA
	,L.NUM_CGC
	,P.DTA_EMISSAO
	,P.DTA_ENTREGA
	,f.[DES_FORNECEDOR]
	,f.[NUM_CGC]
	,convert(varchar,CF.COD_FISCAL_EXPORTACAO) + ' | ' + CF.DES_CODIGO_FISCAL
ORDER BY
	P.DTA_EMISSAO
	

SELECT
	[COD_LOJA]
	,CONVERT(DATE,DTA_ENTRADA) AS DATA
	,NUM_NF_FORN
	,NUM_SERIE_NF
	,SUM([QTD_ENTRADA] * [QTD_EMBALAGEM]) AS QTD_ENTRADA
	,SUM([VAL_TABELA_LIQ]) AS VLR_ENTRADA
FROM
	[Zeus_rtg].[dbo].[vw_MARCHE_ENTRADAS] with(nolock)
WHERE 1=1
	AND CONVERT(DATE,DTA_ENTRADA) >= CONVERT(DATE,'2013-01-01')
	and COD_FORNECEDOR = 101703
GROUP BY
	[COD_LOJA]
	,CONVERT(DATE,DTA_ENTRADA)
	,NUM_NF_FORN
	,NUM_SERIE_NF
ORDER BY
	CONVERT(DATE,DTA_ENTRADA)