SELECT
	[NO_DEPARTAMENTO] AS [Departamento]
	,[COD_FORNECEDOR] AS [Cod Forn]
	,[DES_FANTASIA] AS [Fornecedor]
	,[2] AS Seg
	,[3] AS Ter
	,[4] AS Qua
	,[5] AS Qui
	,[6] AS Sex
	,[7] AS Sab
	,[1] AS Dom
	,[HORA_LIMITE] AS [Hora Limite]
	--,[COD_LOJA]
	--,[COD_DEPARTAMENTO_PEDIDO]
FROM
    (
		SELECT
			PL.[COD_LOJA]
			,PL.[COD_DEPARTAMENTO_PEDIDO]
			,(
				SELECT TOP 1
					NO_DEPARTAMENTO
				FROM
					[BI].[dbo].[VW_BI_CAD_HIERARQUIA_PRODUTO] AS H
				WHERE 1 = 1
				and H.COD_DEPARTAMENTO = PL.COD_DEPARTAMENTO_PEDIDO
			) AS NO_DEPARTAMENTO
			,PL.[COD_FORNECEDOR]
			,CF.DES_FANTASIA
			,PL.[DIA_PEDIDO]
			,PL.[HORA_LIMITE]
		FROM
			[BI].[dbo].[COMPRAS_AGENDA_PEDIDO_LOJA] AS PL
				INNER JOIN [BI].[dbo].[BI_CAD_FORNECEDOR] AS CF
					ON (PL.COD_FORNECEDOR = CF.COD_FORNECEDOR)
		WHERE 1 = 1
			AND PL.COD_DEPARTAMENTO_PEDIDO IS NOT NULL
			AND PL.COD_LOJA = 1
	) AS OrigTab
PIVOT
	(
		COUNT([DIA_PEDIDO])
		FOR [DIA_PEDIDO] IN ([2],[3],[4],[5],[6],[7],[1])
	) AS PivotTable
ORDER BY
	[HORA_LIMITE]
	,[DES_FANTASIA]



/*


SELECT
	[NO_DEPARTAMENTO] AS [Departamento]
	,[COD_FORNECEDOR] AS [Cod Forn]
	,[DES_FANTASIA] AS [Fornecedor]
	,[2] AS Seg
	,[3] AS Ter
	,[4] AS Qua
	,[5] AS Qui
	,[6] AS Sex
	,[7] AS Sab
	,[1] AS Dom
	,[HORA_LIMITE] AS [Hora Limite]
	,DIA_LIBERADO AS [Dia Liberado]
	--,[COD_LOJA]
	--,[COD_DEPARTAMENTO_PEDIDO]
FROM
    (
		SELECT
			PL.[COD_LOJA]
			,PL.[COD_DEPARTAMENTO_PEDIDO]
			,(
				SELECT TOP 1
					NO_DEPARTAMENTO
				FROM
					[BI].[dbo].[VW_BI_CAD_HIERARQUIA_PRODUTO] AS H
				WHERE 1 = 1
				and H.COD_DEPARTAMENTO = PL.COD_DEPARTAMENTO_PEDIDO
			) AS NO_DEPARTAMENTO
			,PL.[COD_FORNECEDOR]
			,CF.DES_FANTASIA
			,PL.[DIA_PEDIDO]
			,PL.[HORA_LIMITE]
			,ISNULL(PLIB.DIA_LIBERADO,0) AS DIA_LIBERADO
		FROM
			[BI].[dbo].[COMPRAS_AGENDA_PEDIDO_LOJA] AS PL
				INNER JOIN [BI].[dbo].[BI_CAD_FORNECEDOR] AS CF
					ON (PL.COD_FORNECEDOR = CF.COD_FORNECEDOR)
				LEFT JOIN [BI].[dbo].[COMPRAS_AGENDA_PEDIDO_LOJA_LIBERADOS] AS PLIB
					ON (1 = 1
						AND PL.COD_LOJA = PLIB.COD_LOJA
						AND PL.COD_DEPARTAMENTO_PEDIDO = PLIB.COD_DEPARTAMENTO_PEDIDO
						AND PL.COD_FORNECEDOR = PLIB.COD_FORNECEDOR
						)
		WHERE 1 = 1
			AND PL.COD_DEPARTAMENTO_PEDIDO IS NOT NULL
			AND PL.COD_LOJA = 1
	) AS OrigTab
PIVOT
	(
		COUNT([DIA_PEDIDO])
		FOR [DIA_PEDIDO] IN ([2],[3],[4],[5],[6],[7],[1])
	) AS PivotTable
ORDER BY
	[HORA_LIMITE]
	,[DES_FANTASIA]


*/