DECLARE @DATA_INI AS DATE = GETDATE()-30
DECLARE @DATA_FIM AS DATE = GETDATE()-1
DECLARE @COD_FORNECEDOR AS INT = 1999

SELECT
	FP.COD_FORNECEDOR
	,CF.DESCRICAO AS NO_FORNECEDOR
	,FP.COD_PRODUTO
	,CP.DESCRICAO AS NO_PRODUTO
	,VP.COD_LOJA
	, CONVERT(DATE,VP.DATA) AS DATA
	,VP.VALOR_TOTAL AS VLR_TOTAL
	,VP.QTDE_PRODUTO AS QTD_TOTAL
FROM
	[BI].dbo.BI_CAD_FORNECEDOR_PRODUTO AS FP
	INNER JOIN BI.dbo.BI_CAD_PRODUTO AS CP
		ON FP.COD_PRODUTO = CP.COD_PRODUTO
	INNER JOIN BI.dbo.BI_CAD_FORNECEDOR AS CF
		ON FP.COD_FORNECEDOR = CF.COD_FORNECEDOR
	INNER JOIN BI.dbo.BI_VENDA_PRODUTO AS VP
		ON FP.COD_PRODUTO = VP.COD_PRODUTO		
WHERE 1=1
	AND FP.COD_FORNECEDOR = @COD_FORNECEDOR
	AND CONVERT(DATE,VP.DATA) BETWEEN CONVERT(DATE,@DATA_INI) AND CONVERT(DATE,@DATA_FIM)
