DECLARE @DT_INICIO AS DATE = '20140425'
DECLARE @DT_TERMINO AS DATE = '20140426'

select
	8 AS COD_LOJA
	,ALTEC.DATA
	,isnull(PROD.PLU,999999) AS COD_PRODUTO
	,2 AS TIPO_VENDA 
	,SUM(QTDE) AS QTDE_PRODUTO
	,SUM(TOTAL) AS VALOR_TOTAL
	,0 AS VALOR_UNITARIO
	,COUNT(QTDE) AS QTDE_DEMANDA
	,0 AS COD_CLIENTE
from
	[192.168.0.6].Alltec.dbo.ITENS_CUPONS as ALTEC left outer join [192.168.0.6].Alltec.dbo.PRODUTO as PROD	on (PROD.CODPRODUTO = ALTEC.PRODUTO	AND PROD.COD_LOJA = ALTEC.COD_lOJA)
WHERE 1 = 1
	AND CONVERT(DATE,ALTEC.DATA) BETWEEN CONVERT(DATE,@DT_INICIO) AND CONVERT(DATE,@DT_TERMINO)
GROUP BY
	ALTEC.DATA
	,PROD.PLU
	
	
SET @DT_INICIO = '20141009'
SET @DT_TERMINO = '20141009'

select
	8 AS COD_LOJA
	,ALTEC.DATA
	,isnull(PROD.PLU,999999) AS COD_PRODUTO
	,2 AS TIPO_VENDA 
	,SUM(QTDE) AS QTDE_PRODUTO
	,SUM(TOTAL) AS VALOR_TOTAL
	,0 AS VALOR_UNITARIO
	,COUNT(QTDE) AS QTDE_DEMANDA
	,0 AS COD_CLIENTE
from
	[192.168.0.6].Alltec.dbo.ITENS_CUPONS as ALTEC left outer join [192.168.0.6].Alltec.dbo.PRODUTO as PROD	on (PROD.CODPRODUTO = ALTEC.PRODUTO	AND PROD.COD_LOJA = ALTEC.COD_lOJA)
WHERE 1 = 1
	AND CONVERT(DATE,ALTEC.DATA) BETWEEN CONVERT(DATE,@DT_INICIO) AND CONVERT(DATE,@DT_TERMINO)
GROUP BY
	ALTEC.DATA
	,PROD.PLU