	SELECT
		COD_LOJA
		,NUM_NF_FORN
		,NUM_SERIE_NF
		,DTA_EMISSAO
		,DTA_ENTRADA
		,COD_FORNECEDOR
		,COD_PRODUTO
		,QTD_ENTRADA
		,QTD_EMBALAGEM
		,VAL_TABELA_LIQ
		,NUM_DANFE		
	FROM
		[192.168.0.6].[ZEUS_RTG].[DBO].[VW_MARCHE_ENTRADAS] WITH(NOLOCK)
	WHERE 1=1
		AND CONVERT(DATE,DTA_ENTRADA) >= CONVERT(DATE,'2016-03-01')
		AND CONVERT(DATE,DTA_ENTRADA) < CONVERT(DATE,'2016-03-31')
		AND COD_LOJA <> 5
		AND COD_PRODUTO = 1017396
		AND COD_LOJA = 7