select
	P.COD_LOJA
	,P.NUM_PEDIDO
	,P.COD_PARCEIRO
	,CONVERT(DATE,P.DTA_ENTREGA) AS DTA_ENTREGA
	,SUM(PP.QTD_RECEBIDA) AS SUM_QTD_RECEBIDA	
from
	[ZEUS_RTG].DBO.[TAB_PEDIDO] AS P
    INNER JOIN [ZEUS_RTG].DBO.[TAB_PEDIDO_PRODUTO] AS PP
    ON 1=1
    and P.NUM_PEDIDO = PP.NUM_PEDIDO
    AND P.COD_LOJA = PP.COD_LOJA
    AND P.COD_PARCEIRO = PP.COD_PARCEIRO
where 1=1
	and dateadd(d,8,CONVERT(Date,DTA_ENTREGA)) <= CONVERT(Date,getdate())
	--and TIPO_RECEBIMENTO = 2
	and CONVERT(Date,DTA_ENTREGA)>= '2016-01-01'
GROUP BY
	P.COD_LOJA
	,P.NUM_PEDIDO
	,P.COD_PARCEIRO
	,CONVERT(DATE,P.DTA_ENTREGA)
HAVING
	SUM(PP.QTD_RECEBIDA) = 0
ORDER BY
	CONVERT(DATE,P.DTA_ENTREGA) DESC