	--SEGUNDA FEIRA
	--DESCONTO MUDAR PARA SEMANAL TAMBÉM -- SEGUNDA FEIRA
	DECLARE @DATA_INI AS DATE = GETDATE()-8
	DECLARE @DATA_FIM AS DATE = GETDATE()-1
	
	DECLARE @TAB_CUPOM_CANCELADO AS TABLE
	(
		M00AF DATE
		,M00ZA INT
		,M00AC INT
		,M00AD INT
		,M01AW INT
	)

	INSERT INTO @TAB_CUPOM_CANCELADO
	SELECT
		M00AF, M00ZA, M00AC, M00AD-1, M01AW
	FROM ZeusRetail.dbo.Zan_M01
	WHERE 1=1
		AND CONVERT(DATE,M00AF) BETWEEN CONVERT(DATE,@DATA_INI) AND CONVERT(DATE,@DATA_FIM)
		AND M01AE = 147
		--AND M00ZA = @COD_LOJA	

	SELECT
		M01.M00ZA AS COD_LOJA
		,CONVERT(DATE,M01.M00AF) AS DATA			
		,M01.M00AC AS PDV
		,M01.M00AD AS CUPOM		
		,(CASE WHEN ISNULL(M01.M01AW,0) = 0 THEN CANC.M01AW ELSE M01.M01AW END) AS CODIGO_SUPERVISOR
		-- ,'NOME CARTAO'	
		,M01.M01AK AS VLR_CUPOM
		,L.NO_REGIONAL		
		,(CASE
			WHEN CANC.M00AD IS NOT NULL THEN 'Cancelado'
			WHEN M01.M01ZZA03 = 9 THEN 'Cancelado - Registro Indevido'
		END) as Tipo_Cancelamento	
	FROM
		ZeusRetail.dbo.Zan_M01 AS M01
		LEFT JOIN @TAB_CUPOM_CANCELADO AS CANC
			ON 1=1
			AND M01.M00AF = CANC.M00AF
			AND M01.M00ZA = CANC.M00ZA
			AND M01.M00AC = CANC.M00AC
			AND M01.M00AD = CANC.M00AD
		LEFT JOIN BI.dbo.BI_CAD_LOJA2 AS L
			ON M01.M00ZA = L.COD_LOJA		
	WHERE 1=1
		AND (CANC.M00AD IS NOT NULL OR M01ZZA03 = 9)
		AND CONVERT(DATE,M01.M00AF) BETWEEN CONVERT(DATE,@DATA_INI) AND CONVERT(DATE,@DATA_FIM)		
	order by
		M01.M00ZA
		,CONVERT(DATE,M01.M00AF)		
		,M01.M00AC
		,M01.M00AD	
		