	DECLARE @DT_INICIO AS DATE = '20150902'
	
	DECLARE @TAB_LINHA AS TABLE
	(
		NO_LOJA VARCHAR(50)
		,NO_DEPARTAMENTO VARCHAR(50)
		,NO_COMPRADOR VARCHAR(50)
		,ABC VARCHAR(5)
		,QTD_LINHA NUMERIC(10,0)
	)
	INSERT INTO @TAB_LINHA
	SELECT
		CL.NO_LOJA
		,CP.NO_DEPARTAMENTO
		,CC.NO_COMPRADOR
		,LP.CLASSIF_PRODUTO_LOJA AS ABC
		,COUNT(LP.COD_PRODUTO) QTD_LINHA
	FROM
		BI.DBO.BI_LINHA_PRODUTOS AS LP
		INNER JOIN BI.DBO.BI_CAD_PRODUTO AS CP
			ON LP.COD_PRODUTO = CP.COD_PRODUTO
		INNER JOIN BI.dbo.COMPRAS_CAD_COMPRADOR AS CC
			ON CP.COD_USUARIO = CC.COD_USUARIO
		INNER JOIN BI_CAD_LOJA2 AS CL
			ON 1=1
			AND LP.COD_LOJA = CL.COD_LOJA
			AND CL.FLG_LOJA = 1	
	WHERE 1 = 1				
		AND LP.COD_DEPARTAMENTO NOT IN (15,20)
		AND LP.COD_SECAO NOT IN (72)
		--AND LP.COD_LOJA = 1
		AND LP.FORA_LINHA = 'N'
		AND LP.CLASSIF_PRODUTO_LOJA NOT IN ('Z')
	GROUP BY
		CL.NO_LOJA
		,CP.NO_DEPARTAMENTO
		,CC.NO_COMPRADOR
		,LP.CLASSIF_PRODUTO_LOJA
	ORDER BY
		CL.NO_LOJA
		,CP.NO_DEPARTAMENTO
		,CC.NO_COMPRADOR
		,LP.CLASSIF_PRODUTO_LOJA
	
	DECLARE @TAB_RUPTURA AS TABLE
	(
		NO_LOJA VARCHAR(50)
		,NO_DEPARTAMENTO VARCHAR(50)
		,NO_COMPRADOR VARCHAR(50)
		,ABC VARCHAR(5)
		,QTD_RUPTURA NUMERIC(10,0)
	)
	INSERT INTO @TAB_RUPTURA
	SELECT
		CL.NO_LOJA
		,CP.NO_DEPARTAMENTO
		,CC.NO_COMPRADOR
		,LP.CLASSIF_PRODUTO_LOJA
		,SUM(CASE WHEN ISNULL(EP.QTD_ESTOQUE,0) = 0 THEN 1 ELSE 0 END) AS RUPTURA
	FROM
		BI.DBO.BI_LINHA_PRODUTOS AS LP
		INNER JOIN BI.DBO.BI_CAD_PRODUTO AS CP
			ON LP.COD_PRODUTO = CP.COD_PRODUTO
		INNER JOIN BI.dbo.COMPRAS_CAD_COMPRADOR AS CC
			ON CP.COD_USUARIO = CC.COD_USUARIO
		INNER JOIN BI_CAD_LOJA2 AS CL
			ON 1=1
			AND LP.COD_LOJA = CL.COD_LOJA
			AND CL.FLG_LOJA = 1
		LEFT JOIN DW.dbo.ESTOQUE AS EP
			ON 1=1
			AND LP.COD_LOJA = EP.COD_LOJA
			AND LP.COD_PRODUTO = EP.COD_PRODUTO
			AND CONVERT(DATE,EP.DATA) BETWEEN CONVERT(DATE,@DT_INICIO) AND CONVERT(DATE,@DT_INICIO)
	WHERE 1 = 1				
		AND CP.COD_DEPARTAMENTO NOT IN (15,20)
		AND CP.COD_SECAO NOT IN (72)
		AND CONVERT(DATE,CP.DTA_CADASTRO) <= CONVERT(DATE,@DT_INICIO)
		--AND LP.COD_LOJA = 1
		AND LP.FORA_LINHA = 'N'
	GROUP BY
		CL.NO_LOJA
		,CP.NO_DEPARTAMENTO
		,CC.NO_COMPRADOR
		,LP.CLASSIF_PRODUTO_LOJA
	ORDER BY
		CL.NO_LOJA
		,CP.NO_DEPARTAMENTO
		,CC.NO_COMPRADOR
		,LP.CLASSIF_PRODUTO_LOJA

	
	SELECT
		L.NO_LOJA
		,L.NO_DEPARTAMENTO
		,L.NO_COMPRADOR
		,L.ABC
		,L.QTD_LINHA
		,R.QTD_RUPTURA
	FROM
		@TAB_LINHA AS L
		LEFT JOIN @TAB_RUPTURA AS R
			ON 1=1
			AND L.NO_LOJA = R.NO_LOJA	
			AND L.NO_DEPARTAMENTO = R.NO_DEPARTAMENTO
			AND L.NO_COMPRADOR = R.NO_COMPRADOR
			AND L.ABC = R.ABC