SELECT
	L.NO_LOJA
	,CC.NO_COMPRADOR
	,CP.NO_DEPARTAMENTO
	,CP.NO_SECAO
	,LP.CLASSIF_PRODUTO_LOJA AS ABC
	,sum(CASE WHEN E.QTD_ESTOQUE = 0 THEN 1 ELSE 0 END) AS COUNT_RUPTURA
	,count(LP.COD_PRODUTO) AS COUNT_LINHA	
FROM
	BI.dbo.BI_LINHA_PRODUTOS AS LP
	INNER JOIN BI.dbo.BI_CAD_PRODUTO AS CP
		ON LP.COD_PRODUTO = CP.COD_PRODUTO
	INNER JOIN BI.dbo.BI_CAD_LOJA2 AS L
		ON LP.COD_LOJA = L.COD_LOJA
	INNER JOIN BI.dbo.COMPRAS_CAD_COMPRADOR AS CC
		ON LP.COD_USUARIO = CC.COD_USUARIO
	LEFT JOIN BI.dbo.VW_ESTOQUE_ATUAL AS E
		ON 1=1
		AND LP.COD_LOJA = E.COD_LOJA
		AND LP.COD_PRODUTO = E.COD_PRODUTO
WHERE 1=1
	AND LP.FORA_LINHA = 'N'
	--AND LP.COD_LOJA IN (1,2)
GROUP BY
	L.NO_LOJA
	,CC.NO_COMPRADOR
	,CP.NO_DEPARTAMENTO
	,CP.NO_SECAO
	,LP.CLASSIF_PRODUTO_LOJA

SELECT
	L.NO_LOJA
	,CP.NO_DEPARTAMENTO
	,CP.NO_SECAO
	,CP.COD_PRODUTO
	,CP.DESCRICAO AS NO_PRODUTO
	,(CASE WHEN E.QTD_ESTOQUE = 0 THEN 1 ELSE 0 END) AS FLG_RUPTURA
	,LP.CLASSIF_PRODUTO_LOJA AS ABC
FROM
	BI.dbo.BI_LINHA_PRODUTOS AS LP
	INNER JOIN BI.dbo.BI_CAD_PRODUTO AS CP
		ON LP.COD_PRODUTO = CP.COD_PRODUTO
	INNER JOIN BI.dbo.BI_CAD_LOJA2 AS L
		ON LP.COD_LOJA = L.COD_LOJA
	LEFT JOIN BI.dbo.VW_ESTOQUE_ATUAL AS E
		ON 1=1
		AND LP.COD_LOJA = E.COD_LOJA
		AND LP.COD_PRODUTO = E.COD_PRODUTO
WHERE 1=1
	AND LP.FORA_LINHA = 'N'
	--AND LP.COD_LOJA IN (1,2)
ORDER BY
	L.DTA_ABERTURA
	,CP.NO_DEPARTAMENTO
	,CP.NO_SECAO
	,CP.DESCRICAO
	
	