SELECT
	L.NO_LOJA
	,LP.COD_PRODUTO
	,CP.DESCRICAO AS NO_PRODUTO
	,LP.CLASSIF_PRODUTO_LOJA AS ABC
	,CP.NO_DEPARTAMENTO
	,CP.NO_SECAO
	,LP.VLR_VENDA
	,CONVERT(DATE,LP.DATA_ULTIMA_VENDA) AS DATA_ULTIMA_VENDA
	,CONVERT(DATE,LP.DATA_ULTIMA_ENTRADA) AS DATA_ULTIMA_ENTRADA
	,DATEDIFF(D,LP.DATA_ULTIMA_VENDA,LP.DATA_ULTIMA_ENTRADA) AS VENDA_VS_ENTRADA
	,BI.dbo.fn_FormataVlr_Excel(LP.QTD_ULTIMA_ENTRADA) AS QTD_ULTIMA_ENTRADA	
FROM
	BI.DBO.BI_LINHA_PRODUTOS AS LP
	INNER JOIN BI.dbo.BI_CAD_LOJA2 AS L
		ON LP.COD_LOJA = L.COD_LOJA
	INNER JOIN BI.dbo.BI_CAD_PRODUTO AS CP
		ON LP.COD_PRODUTO = CP.COD_PRODUTO	
	LEFT JOIN BI.DBO.[COMPRAS_DEPARA_PRODUTO] AS DEPARA 
		ON DEPARA.COD_PRODUTO_ORG = CP.COD_PRODUTO	
WHERE 1=1
	AND CONVERT(DATE,LP.DATA_ULTIMA_ENTRADA) >= CONVERT(DATE,GETDATE()-5)
	AND CONVERT(DATE,LP.DATA_ULTIMA_VENDA) < CONVERT(DATE,LP.DATA_ULTIMA_ENTRADA)
	AND DATEDIFF(D,LP.DATA_ULTIMA_VENDA,LP.DATA_ULTIMA_ENTRADA) > 5
	--AND LP.COD_LOJA = 7
	AND LP.CLASSIF_PRODUTO_LOJA <> 'Z'	
	AND DEPARA.COD_PRODUTO_ORG IS NULL
ORDER BY
	LP.COD_LOJA
	,LP.CLASSIF_PRODUTO_LOJA
	,DATEDIFF(D,LP.DATA_ULTIMA_VENDA,LP.DATA_ULTIMA_ENTRADA) DESC
	
	
--SELECT * FROM BI.dbo.BI_ENTRADA_PRODUTO WHERE COD_PRODUTO = 132350 AND COD_LOJA = 1 ORDER BY DATA DESC
--SELECT * FROM BI.dbo.BI_VENDA_PRODUTO WHERE COD_PRODUTO = 132350 AND COD_LOJA = 1 ORDER BY DATA DESC