--select * from [CADASTRO_ALTERAR_MIX_LOJA]

SELECT
	VP.[COD_LOJA]
	,CL.[NO_LOJA]
	,YEAR(VP.[DATA]) AS ANO_VENDA
	,CP.PNP
	,CP.NO_DEPARTAMENTO
	,CP.NO_SECAO
	,CP.NO_GRUPO
	,CP.NO_SUBGRUPO
	,CP.COD_USUARIO
	,CCP.NO_COMPRADOR
	,VP.[COD_PRODUTO]
	,CP.DESCRICAO
	,CP.CLASSIF_PRODUTO
	,LP.FORA_LINHA AS FL_LOJA
	,CONVERT(DATE,(CAM.DTA_GRAVACAO)) AS DATA_FL_LOJA
	,CAM.MOTIVO
	,CP.FORA_LINHA_STM
	--,VP.[TIPO_VENDA]
	,BI.dbo.fn_FormataVlr_Excel(SUM(VP.[VALOR_TOTAL])) AS VENDA_VALOR
	,BI.dbo.fn_FormataVlr_Excel(SUM(VP.[QTDE_PRODUTO])) AS VENDA_QTDE
	,BI.dbo.fn_FormataVlr_Excel(SUM(VP.[QTDE_DEMANDA])) AS DEMANDA
	,BI.dbo.fn_FormataVlr_Excel(AVG(VP.[VALOR_UNITARIO])) AS PREÇO_VENDA

FROM
	[BI].[dbo].[BI_VENDA_PRODUTO] AS VP
	INNER JOIN [BI].[dbo].[BI_CAD_PRODUTO] AS CP
		ON 1=1
		AND VP.COD_PRODUTO=CP.COD_PRODUTO
	INNER JOIN [BI].[dbo].[BI_LINHA_PRODUTOS] AS LP
		ON 1=1
		AND VP.COD_PRODUTO=LP.COD_PRODUTO
		AND VP.COD_LOJA=LP.COD_LOJA
	INNER JOIN [BI].[dbo].[BI_CAD_LOJA2] AS CL
		ON 1=1
		AND VP.COD_LOJA=CL.COD_LOJA
	INNER JOIN [BI].[dbo].[COMPRAS_CAD_COMPRADOR] AS CCP
		ON 1=1
		AND CP.COD_USUARIO=CCP.COD_USUARIO
	INNER JOIN [BI].[dbo].[CADASTRO_ALTERAR_MIX_LOJA] AS CAM
		ON 1=1
		AND VP.COD_PRODUTO=CAM.COD_PRODUTO
		AND VP.COD_LOJA=CAM.COD_LOJA
WHERE 1=1
	AND CONVERT(DATE,(VP.[DATA])) BETWEEN '20150101' AND '20161231'
	AND LP.FORA_LINHA='S'
	AND VP.COD_PRODUTO=14786
	AND VP.COD_LOJA=1
	AND CP.COD_DEPARTAMENTO NOT IN (15,16,17,18,20,99)

	--> FILTRO ALTERAR MIX <--
	AND CONVERT(DATE,(CAM.[DTA_GRAVACAO])) BETWEEN '20160101' AND '20161231'
	AND CAM.TIPO_CADASTRO=0
GROUP BY
	VP.[COD_LOJA]
	,CL.[NO_LOJA]
	,YEAR(VP.[DATA])
	,CP.PNP
	,CP.NO_DEPARTAMENTO
	,CP.NO_SECAO
	,CP.NO_GRUPO
	,CP.NO_SUBGRUPO
	,CP.COD_USUARIO
	,CCP.NO_COMPRADOR
	,VP.[COD_PRODUTO]
	,CP.DESCRICAO
	,CP.CLASSIF_PRODUTO
	,LP.FORA_LINHA
	,CONVERT(DATE,(CAM.DTA_GRAVACAO))
	,CAM.MOTIVO
	,CP.FORA_LINHA_STM