	DECLARE @DATA_P1_INI AS DATE = '20121231'
	DECLARE @DATA_P1_FIM AS DATE = '20131229'
	DECLARE @COD_FORNECEDOR AS INT = 1999
	
	SELECT
		S.SEMANA_454
		,VP.COD_LOJA
		,CP.COD_PRODUTO
		,SUM(VP.VALOR_TOTAL)
		--,SUM(VP.QTDE_PRODUTO)
	FROM	
		BI.dbo.BI_CAD_PRODUTO AS CP
		INNER JOIN BI.dbo.BI_CAD_FORNECEDOR_PRODUTO AS CFP
			ON CP.COD_PRODUTO = CFP.COD_PRODUTO
		INNER JOIN BI.dbo.BI_VENDA_PRODUTO AS VP
			ON CP.COD_PRODUTO = VP.COD_PRODUTO
		INNER JOIN BI.DBO.BI_CAD_SEMANA AS S
			ON VP.DATA = S.DATA
	WHERE 1=1
		AND CFP.COD_FORNECEDOR = @COD_FORNECEDOR
		AND CONVERT(DATE,VP.DATA) BETWEEN CONVERT(DATE,@DATA_P1_INI) AND CONVERT(DATE,@DATA_P1_FIM)
		--AND CP.FORA_LINHA = 'N'
	GROUP BY
		S.SEMANA_454
		,VP.COD_LOJA
		,CP.COD_PRODUTO