	DECLARE @dataIni AS DATE = '2013-01-01'
	DECLARE @dataFim AS DATE = '2015-12-31'

	SELECT --TOP 100
		VP.COD_LOJA
		,YEAR(VP.DATA) AS ANO
		,MONTH(VP.DATA) AS MES		
		,bi.dbo.fn_FormataVlr_Excel(((SUM(PC.CUSTO)/SUM(VP.VALOR_UNITARIO))-1)*-1) as  PERC_MARGEM
		,SUM(CASE WHEN PC.CUSTO > VP.VALOR_UNITARIO THEN 1 ELSE 0 END) AS QTD_CUSTO_MAIOR
		,COUNT(VP.COD_PRODUTO) AS QTD_PRODUTOS
	FROM
		BI.dbo.BI_VENDA_PRODUTO as VP
		LEFT JOIN DW.dbo.PRODUTO_CUSTOS AS PC
			ON 1=1
			AND VP.COD_LOJA = PC.COD_LOJA
			AND VP.COD_PRODUTO = PC.COD_PRODUTO
	WHERE 1=1
		AND VP.VALOR_UNITARIO IS NOT NULL
		--AND PC.CUSTO  VP.VALOR_UNITARIO
		AND CONVERT(DATE,VP.DATA) BETWEEN CONVERT(DATE,@dataIni) AND CONVERT(DATE,@dataFim)
		--AND VP.COD_PRODUTO = 17
		AND VP.COD_LOJA IN (SELECT COD_LOJA FROM BI.dbo.BI_CAD_LOJA2 WHERE FLG_25M = 1)
		AND VP.COD_LOJA NOT IN (7,8,29,33)
	GROUP BY
		VP.COD_LOJA
		,YEAR(VP.DATA)
		,MONTH(VP.DATA)
		
		