SELECT
		LP.COD_LOJA
	,	LP.COD_PRODUTO
	,	DESCRICAO
	,	NO_DEPARTAMENTO
	,	NO_SECAO
	,	NO_GRUPO
	,	LP.FORA_LINHA
	,	LP.CLASSIF_PRODUTO_LOJA
	,	BI.DBO.fn_FormataVlr_Excel(LP.QTDE_PRODUTO_1ANO) AS QTDE_PRODUTO_1ANO
	,	BI.DBO.fn_FormataVlr_Excel(LP.VLR_TOTAL_1ANO) AS VLR_TOTAL_1ANO
	,	BI.DBO.fn_FormataVlr_Excel(LP.VLR_VENDA) AS VLR_VENDA
	,	LP.DATA_ULTIMA_VENDA
	,	LP.DATA_ULTIMA_ENTRADA
	,	BI.DBO.fn_FormataVlr_Excel(LP.QTD_ULTIMA_ENTRADA) AS QTD_ULTIMA_ENTRADA
FROM
	BI.dbo.BI_LINHA_PRODUTOS AS LP
	INNER JOIN BI.dbo.BI_CAD_PRODUTO AS CP
		ON LP.COD_PRODUTO = CP.COD_PRODUTO
WHERE 1=1
	AND LP.FORA_LINHA = 'N'
	AND CP.COD_SECAO NOT IN (6)