DECLARE @COD_LOJA_ANTIGA AS INT
DECLARE @COD_LOJA_NOVA AS INT

UPDATE A
SET
	A.COD_LOJA = @COD_LOJA_NOVA
FROM
	[BI].[dbo].[BI_CAD_LOJA] AS A
WHERE 1 = 1
	AND A.COD_LOJA = @COD_LOJA_ANTIGA

UPDATE A
SET
	A.COD_LOJA = @COD_LOJA_NOVA
FROM
	[BI].[dbo].[BI_CAD_LOJA2] AS A
WHERE 1 = 1
	AND A.COD_LOJA = @COD_LOJA_ANTIGA
	
UPDATE A
SET
	A.COD_LOJA = @COD_LOJA_NOVA
FROM
	[BI].[DBO].[BI_AUDITORIA_LINHA] AS A
WHERE 1 = 1
	AND A.COD_LOJA = @COD_LOJA_ANTIGA
	
UPDATE A
SET
	A.COD_LOJA = @COD_LOJA_NOVA
FROM
	[BI].[DBO].[BI_BALANCA] AS A
WHERE 1 = 1
	AND A.COD_LOJA = @COD_LOJA_ANTIGA
		
UPDATE A
SET
	A.COD_LOJA = @COD_LOJA_NOVA
FROM
	[BI].[DBO].[BI_CAD_PDV] AS A
WHERE 1 = 1
	AND A.COD_LOJA = @COD_LOJA_ANTIGA
	
UPDATE A
SET
	A.COD_LOJA = @COD_LOJA_NOVA
FROM
	[BI].[dbo].[BI_CLUSTER_LOJAS] AS A
WHERE 1 = 1
	AND A.COD_LOJA = @COD_LOJA_ANTIGA
	
UPDATE A
SET
	A.COD_LOJA = @COD_LOJA_NOVA
FROM
	[BI].[dbo].[BI_ENTRADA_PRODUTO] AS A
WHERE 1 = 1
	AND A.COD_LOJA = @COD_LOJA_ANTIGA
	
UPDATE A
SET
	A.COD_LOJA = @COD_LOJA_NOVA
FROM
	[BI].[dbo].[BI_ESTOQUE_PRODUTO] AS A
WHERE 1 = 1
	AND A.COD_LOJA = @COD_LOJA_ANTIGA

UPDATE A
SET
	A.COD_LOJA = @COD_LOJA_NOVA
FROM
	[BI].[dbo].[BI_INVENTARIO_MANIPULADOS] AS A
WHERE 1 = 1
	AND A.COD_LOJA = @COD_LOJA_ANTIGA

UPDATE A
SET
	A.COD_LOJA = @COD_LOJA_NOVA
FROM
	[BI].[dbo].[BI_LINHA_PRODUTOS] AS A
WHERE 1 = 1
	AND A.COD_LOJA = @COD_LOJA_ANTIGA
		
UPDATE A
SET
	A.COD_LOJA = @COD_LOJA_NOVA
FROM
	[BI].[dbo].[BI_PRECO_BLOQUEADO] AS A
WHERE 1 = 1
	AND A.COD_LOJA = @COD_LOJA_ANTIGA

UPDATE A
SET
	A.COD_LOJA = @COD_LOJA_NOVA
FROM
	[BI].[dbo].[BI_PRECO_MARCHE_CONCORRENTE] AS A
WHERE 1 = 1
	AND A.COD_LOJA = @COD_LOJA_ANTIGA

UPDATE A
SET
	A.COD_LOJA = @COD_LOJA_NOVA
FROM
	[BI].[dbo].[BI_PRECO_MRGREF_METADADO] AS A
WHERE 1 = 1
	AND A.COD_LOJA = @COD_LOJA_ANTIGA
		
UPDATE A
SET
	A.COD_LOJA = @COD_LOJA_NOVA
FROM
	[BI].[dbo].[BI_PRECO_MRGREF_PRODUTO] AS A
WHERE 1 = 1
	AND A.COD_LOJA = @COD_LOJA_ANTIGA

UPDATE A
SET
	A.COD_LOJA = @COD_LOJA_NOVA
FROM
	[BI].[dbo].[BI_PRECO_MRGREF_SUBGRUPO] AS A
WHERE 1 = 1
	AND A.COD_LOJA = @COD_LOJA_ANTIGA

UPDATE A
SET
	A.COD_LOJA = @COD_LOJA_NOVA
FROM
	[BI].[dbo].[BI_PRECO_PRE_VENDA] AS A
WHERE 1 = 1
	AND A.COD_LOJA = @COD_LOJA_ANTIGA
		
UPDATE A
SET
	A.COD_LOJA = @COD_LOJA_NOVA
FROM
	[BI].[dbo].[BI_PRECO_PRE_VENDA_COMPRAS] AS A
WHERE 1 = 1
	AND A.COD_LOJA = @COD_LOJA_ANTIGA

UPDATE A
SET
	A.COD_LOJA = @COD_LOJA_NOVA
FROM
	[BI].[dbo].[BI_PRECO_VENDA] AS A
WHERE 1 = 1
	AND A.COD_LOJA = @COD_LOJA_ANTIGA

UPDATE A
SET
	A.COD_LOJA = @COD_LOJA_NOVA
FROM
	[BI].[dbo].[BI_PRECO_VENDA_SIMILAR] AS A
WHERE 1 = 1
	AND A.COD_LOJA = @COD_LOJA_ANTIGA
		
UPDATE A
SET
	A.COD_LOJA = @COD_LOJA_NOVA
FROM
	[BI].[dbo].[BI_PRECOS_PADARIA] AS A
WHERE 1 = 1
	AND A.COD_LOJA = @COD_LOJA_ANTIGA

UPDATE A
SET
	A.COD_LOJA = @COD_LOJA_NOVA
FROM
	[BI].[dbo].[BI_VENDA_BUDGET] AS A
WHERE 1 = 1
	AND A.COD_LOJA = @COD_LOJA_ANTIGA

UPDATE A
SET
	A.COD_LOJA = @COD_LOJA_NOVA
FROM
	[BI].[dbo].[BI_VENDA_COMPRADOR] AS A
WHERE 1 = 1
	AND A.COD_LOJA = @COD_LOJA_ANTIGA
	
UPDATE A
SET
	A.COD_LOJA = @COD_LOJA_NOVA
FROM
	[BI].[dbo].[BI_VENDA_CUPOM] AS A
WHERE 1 = 1
	AND A.COD_LOJA = @COD_LOJA_ANTIGA	
		
UPDATE A
SET
	A.COD_LOJA = @COD_LOJA_NOVA
FROM
	[BI].[dbo].[BI_VENDA_CUPOM_DELIVERY] AS A
WHERE 1 = 1
	AND A.COD_LOJA = @COD_LOJA_ANTIGA	
		
UPDATE A
SET
	A.COD_LOJA = @COD_LOJA_NOVA
FROM
	[BI].[dbo].[BI_VENDA_CUPOM_HORA] AS A
WHERE 1 = 1
	AND A.COD_LOJA = @COD_LOJA_ANTIGA	
		
UPDATE A
SET
	A.COD_LOJA = @COD_LOJA_NOVA
FROM
	[BI].[dbo].[BI_VENDA_GRUPO] AS A
WHERE 1 = 1
	AND A.COD_LOJA = @COD_LOJA_ANTIGA	
		
UPDATE A
SET
	A.COD_LOJA = @COD_LOJA_NOVA
FROM
	[BI].[dbo].[BI_VENDA_META] AS A
WHERE 1 = 1
	AND A.COD_LOJA = @COD_LOJA_ANTIGA	
		
UPDATE A
SET
	A.COD_LOJA = @COD_LOJA_NOVA
FROM
	[BI].[dbo].[BI_VENDA_META_COMPRADOR] AS A
WHERE 1 = 1
	AND A.COD_LOJA = @COD_LOJA_ANTIGA	
		
UPDATE A
SET
	A.COD_LOJA = @COD_LOJA_NOVA
FROM
	[BI].[dbo].[BI_VENDA_META_GRUPO] AS A
WHERE 1 = 1
	AND A.COD_LOJA = @COD_LOJA_ANTIGA	
		
UPDATE A
SET
	A.COD_LOJA = @COD_LOJA_NOVA
FROM
	[BI].[dbo].[BI_VENDA_PDV_HORA] AS A
WHERE 1 = 1
	AND A.COD_LOJA = @COD_LOJA_ANTIGA	
		
UPDATE A
SET
	A.COD_LOJA = @COD_LOJA_NOVA
FROM
	[BI].[dbo].[BI_VENDA_PRODUTO] AS A
WHERE 1 = 1
	AND A.COD_LOJA = @COD_LOJA_ANTIGA	
		
UPDATE A
SET
	A.COD_LOJA = @COD_LOJA_NOVA
FROM
	[BI].[dbo].[BI_VENDA_PRODUTO_BKP] AS A
WHERE 1 = 1
	AND A.COD_LOJA = @COD_LOJA_ANTIGA	
		
UPDATE A
SET
	A.COD_LOJA = @COD_LOJA_NOVA
FROM
	[BI].[dbo].[BI_VENDA_PRODUTO_MES] AS A
WHERE 1 = 1
	AND A.COD_LOJA = @COD_LOJA_ANTIGA	
			
UPDATE A
SET
	A.COD_LOJA = @COD_LOJA_NOVA
FROM
	[BI].[dbo].[CADASTRO_ALTERAR_MIX_COMPRAS] AS A
WHERE 1 = 1
	AND A.COD_LOJA = @COD_LOJA_ANTIGA	
		
UPDATE A
SET
	A.COD_LOJA = @COD_LOJA_NOVA
FROM
	[BI].[dbo].[CADASTRO_ALTERAR_MIX_LOJA] AS A
WHERE 1 = 1
	AND A.COD_LOJA = @COD_LOJA_ANTIGA			
UPDATE A
SET
	A.COD_LOJA = @COD_LOJA_NOVA
FROM
	[BI].[dbo].[COMPRA_GRUPO_COMPRADORES] AS A
WHERE 1 = 1
	AND A.COD_LOJA = @COD_LOJA_ANTIGA	
		
UPDATE A
SET
	A.COD_LOJA = @COD_LOJA_NOVA
FROM
	[BI].[dbo].[COMPRA_METADADO_COMPRADOR] AS A
WHERE 1 = 1
	AND A.COD_LOJA = @COD_LOJA_ANTIGA	
			
UPDATE A
SET
	A.COD_LOJA = @COD_LOJA_NOVA
FROM
	[BI].[dbo].[COMPRA_PRODUTO_COMPRADOR] AS A
WHERE 1 = 1
	AND A.COD_LOJA = @COD_LOJA_ANTIGA	
		
UPDATE A
SET
	A.COD_LOJA = @COD_LOJA_NOVA
FROM
	[BI].[dbo].[COMPRAS_AGENDA_ESTOQUE_LOJA] AS A
WHERE 1 = 1
	AND A.COD_LOJA = @COD_LOJA_ANTIGA	
			
UPDATE A
SET
	A.COD_LOJA = @COD_LOJA_NOVA
FROM
	[BI].[dbo].[COMPRAS_AGENDA_PEDIDO_LOJA] AS A
WHERE 1 = 1
	AND A.COD_LOJA = @COD_LOJA_ANTIGA	
		
UPDATE A
SET
	A.COD_LOJA = @COD_LOJA_NOVA
FROM
	[BI].[dbo].[COMPRAS_AGENDA_PEDIDO_LOJA_ACOMPANHAMENTO] AS A
WHERE 1 = 1
	AND A.COD_LOJA = @COD_LOJA_ANTIGA	
			
UPDATE A
SET
	A.COD_LOJA = @COD_LOJA_NOVA
FROM
	[BI].[dbo].[COMPRAS_AGENDA_PEDIDO_LOJA_LIBERADOS] AS A
WHERE 1 = 1
	AND A.COD_LOJA = @COD_LOJA_ANTIGA	
		
UPDATE A
SET
	A.COD_LOJA = @COD_LOJA_NOVA
FROM
	[BI].[dbo].[COMPRAS_DNV_CALCULADORA] AS A
WHERE 1 = 1
	AND A.COD_LOJA = @COD_LOJA_ANTIGA	
			
UPDATE A
SET
	A.COD_LOJA = @COD_LOJA_NOVA
FROM
	[BI].[dbo].[COMPRAS_ESTATISTICA_PRODUTO] AS A
WHERE 1 = 1
	AND A.COD_LOJA = @COD_LOJA_ANTIGA	
		
UPDATE A
SET
	A.COD_LOJA = @COD_LOJA_NOVA
FROM
	[BI].[dbo].[COMPRAS_FORNECEDORES_BLOQUEADOS_LOJA] AS A
WHERE 1 = 1
	AND A.COD_LOJA = @COD_LOJA_ANTIGA	
			
UPDATE A
SET
	A.COD_LOJA = @COD_LOJA_NOVA
FROM
	[BI].[dbo].[COMPRAS_FORNECEDORES_LOJA] AS A
WHERE 1 = 1
	AND A.COD_LOJA = @COD_LOJA_ANTIGA	
		
UPDATE A
SET
	A.COD_LOJA = @COD_LOJA_NOVA
FROM
	[BI].[dbo].[COMPRAS_ITENS_LIBERADOS_LOJA] AS A
WHERE 1 = 1
	AND A.COD_LOJA = @COD_LOJA_ANTIGA	
			
UPDATE A
SET
	A.COD_LOJA = @COD_LOJA_NOVA
FROM
	[BI].[dbo].[COMPRAS_ORDEM_PRODUCAO] AS A
WHERE 1 = 1
	AND A.COD_LOJA = @COD_LOJA_ANTIGA	
		
UPDATE A
SET
	A.COD_LOJA = @COD_LOJA_NOVA
FROM
	[BI].[dbo].[COMPRAS_PEDIDOS] AS A
WHERE 1 = 1
	AND A.COD_LOJA = @COD_LOJA_ANTIGA	

UPDATE A
SET
	A.COD_LOJA = @COD_LOJA_NOVA
FROM
	[BI].[dbo].[COMPRAS_PEDIDOS_LOJA] AS A
WHERE 1 = 1
	AND A.COD_LOJA = @COD_LOJA_ANTIGA	
	
UPDATE A
SET
	A.COD_LOJA = @COD_LOJA_NOVA
FROM
	[BI].[dbo].[COMPRAS_PEDIDOS] AS A
WHERE 1 = 1
	AND A.COD_LOJA = @COD_LOJA_ANTIGA	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	