SET NOCOUNT ON

DECLARE @COD_LOJA AS INT;
DECLARE @COD_PRODUTO AS INT;
DECLARE @DATA AS DATE;

DECLARE nome_cursor CURSOR FOR
	SELECT top 100000
		[COD_LOJA]
		,[COD_PRODUTO]
		,[DATA]
	FROM
		[BI].[dbo].[BI_ESTOQUE_PRODUTO_DIA]
	WHERE 1=1
		AND VLR_VENDA IS NULL
		AND CONVERT(DATE,DATA) >= '20130101'
		AND CONVERT(DATE,DATA) < '20150101'
		AND FLG_ATUALIZADO IS NULL
	order by
		[DATA]
		,[COD_LOJA]
		,[COD_PRODUTO]
		
OPEN nome_cursor
FETCH NEXT FROM nome_cursor
INTO @COD_LOJA, @COD_PRODUTO, @DATA

WHILE @@FETCH_STATUS = 0
BEGIN
	-- -------------------------------------------------------------------------------------
	-- -------------------------------------------------------------------------------------
	IF EXISTS (SELECT TOP 1 * FROM [BI].[DBO].[BI_PRECO_VENDA] AS TPV WHERE TPV.TIPO = 0 AND TPV.COD_LOJA = @COD_LOJA  AND TPV.COD_PRODUTO = @COD_PRODUTO AND CONVERT(DATE,TPV.DTA_INI) <= CONVERT(DATE,@DATA) AND CONVERT(DATE,TPV.DTA_FIM) >= CONVERT(DATE,@DATA))
	BEGIN
		DECLARE @TAB_PRECO_MARCHE AS TABLE
		(
			COD_LOJA INT
			,COD_PRODUTO INT
			,VLR_VENDA_MARCHE NUMERIC(18,2)
			PRIMARY KEY (COD_LOJA, COD_PRODUTO)
		)
		DELETE FROM @TAB_PRECO_MARCHE
		
		INSERT INTO @TAB_PRECO_MARCHE
		SELECT
			PV.COD_LOJA
			,PV.COD_PRODUTO
			,AVG(PV.VALOR) AS VLR_VENDA_MARCHE
		FROM
			[BI].[DBO].[BI_PRECO_VENDA] AS PV
		WHERE 1 = 1
				AND CONVERT(DATE,PV.DTA_INI) = (SELECT MAX(TPV.DTA_INI) FROM [BI].[DBO].[BI_PRECO_VENDA] AS TPV WHERE TPV.TIPO = 0 AND TPV.COD_LOJA = @COD_LOJA  AND TPV.COD_PRODUTO = @COD_PRODUTO AND CONVERT(DATE,TPV.DTA_INI) <= CONVERT(DATE,@DATA) AND CONVERT(DATE,TPV.DTA_FIM) >= CONVERT(DATE,@DATA))
				AND CONVERT(DATE,PV.DTA_FIM) >= CONVERT(DATE,@DATA)
				AND PV.TIPO = 0
				AND PV.COD_LOJA = @COD_LOJA
				AND PV.COD_PRODUTO = @COD_PRODUTO
		GROUP BY
			PV.COD_LOJA
			,PV.COD_PRODUTO
		
		-- ------------------------
		-- UPDATE
		-- ------------------------
		UPDATE EPD
		SET
			EPD.VLR_VENDA = T.VLR_VENDA_MARCHE
		FROM
			[BI].[dbo].[BI_ESTOQUE_PRODUTO_DIA] AS EPD
			INNER JOIN @TAB_PRECO_MARCHE AS T
				ON 1=1
				AND EPD.COD_LOJA = T.COD_LOJA
				AND EPD.COD_PRODUTO = T.COD_PRODUTO
				AND CONVERT(DATE,EPD.DATA) = CONVERT(DATE,@DATA)
	END
	
	UPDATE [BI].[dbo].[BI_ESTOQUE_PRODUTO_DIA]
	SET
		FLG_ATUALIZADO = 1
	WHERE 1=1
		AND COD_LOJA = @COD_LOJA
		AND COD_PRODUTO = @COD_PRODUTO
		AND CONVERT(DATE,DATA) = CONVERT(DATE,@DATA)
		
	-- -------------------------------------------------------------------------------------
	-- -------------------------------------------------------------------------------------
    FETCH NEXT FROM nome_cursor 
    INTO @COD_LOJA, @COD_PRODUTO, @DATA
END 
CLOSE nome_cursor;
DEALLOCATE nome_cursor;


	