UPDATE P_BI
SET
	P_BI.FLG_CANCELADO_AX = 1
FROM
	BI.dbo.COMPRAS_PEDIDOS AS P_BI
	INNER JOIN SMA_AX50_SP1_DB_PROD.dbo.PURCHTABLE AS P_AX
		ON P_BI.COD_PEDIDO = P_AX.PURCHID
WHERE 1=1
	AND P_AX.PURCHSTATUS = 4
	AND ISNUMERIC(P_AX.PURCHID) = 1
	AND P_BI.FLG_CANCELADO_AX IS NULL



UPDATE P_BI
SET
	P_BI.FLG_CANCELADO_ZEUS = 1
FROM
	BI.dbo.COMPRAS_PEDIDOS AS P_BI
	INNER JOIN [192.168.0.6].ZEUS_RTG.DBO.TAB_PEDIDO_CANCELADO AS P_ZEUS
		ON P_BI.COD_PEDIDO = P_ZEUS.NUM_PEDIDO
WHERE 1=1
	AND CONVERT(DATE,P_BI.DATA) >= CONVERT(DATE,GETDATE()-180)
	AND P_BI.FLG_CANCELADO_ZEUS IS NULL