SELECT 
	S.ANO_454
	,S.MES_454
	,S.SEMANA_454
	,S.DATA
	,CP.NO_DEPARTAMENTO
	,CP.NO_SECAO
	,CP.NO_GRUPO
	,CP.COD_PRODUTO
	,CP.DESCRICAO
	,BI.dbo.fn_FormataVlr_Excel(SUM(VP.VALOR_TOTAL)) AS VLR_TOTAL
	,BI.dbo.fn_FormataVlr_Excel(SUM(VP.QTDE_PRODUTO)) AS QTD_TOTAL
FROM
	BI.dbo.BI_VENDA_PRODUTO AS VP
	INNER JOIN BI.dbo.BI_CAD_PRODUTO AS CP
		ON VP.COD_PRODUTO = CP.COD_PRODUTO
	LEFT JOIN BI.DBO.BI_CAD_SEMANA AS S
		ON VP.DATA = S.DATA
WHERE 1=1
	AND CONVERT(DATE,VP.DATA) BETWEEN CONVERT(DATE,'20151001') AND CONVERT(DATE,'20151031')
	AND COD_LOJA = 8
GROUP BY
	S.ANO_454
	,S.MES_454
	,S.SEMANA_454
	,S.DATA
	,CP.NO_DEPARTAMENTO
	,CP.NO_SECAO
	,CP.NO_GRUPO
	,CP.COD_PRODUTO
	,CP.DESCRICAO
