DECLARE @YEAR [INT] = 2015
DECLARE @LAST_YEAR [INT] = 2014
DECLARE @WEEK [INT] = 7

SELECT
	'ATUAL' AS PERIODO
	,VP.COD_LOJA
	,L.NO_LOJA
	,CP.PNP
	,CP.NO_DEPARTAMENTO
	,CP.NO_SECAO
	,CP.NO_GRUPO
	,CP.COD_PRODUTO
	,CP.DESCRICAO AS NO_PRODUTO
	,BI.dbo.fn_FormataVlr_Excel(SUM(VP.VALOR_TOTAL)) AS VLR_VENDA
	,BI.dbo.fn_FormataVlr_Excel(SUM(VP.QTDE_PRODUTO)) AS QTD_VENDA
FROM
	BI.DBO.BI_VENDA_PRODUTO AS VP
	INNER JOIN BI.DBO.BI_CAD_PRODUTO AS CP
		ON 1=1
		AND VP.COD_PRODUTO = CP.COD_PRODUTO
	INNER JOIN BI.dbo.BI_CAD_LOJA2 AS L
		ON 1=1
		AND VP.COD_LOJA = L.COD_LOJA
WHERE 1=1
	AND LEFT(dbo.ISO_WEEK(VP.DATA),4) = @YEAR
	AND BI.DBO.F_ISO_WEEK_OF_YEAR(VP.DATA) = @WEEK
	AND VP.COD_LOJA = 7
GROUP BY
	VP.COD_LOJA
	,L.NO_LOJA
	,CP.PNP
	,CP.NO_DEPARTAMENTO
	,CP.NO_SECAO
	,CP.NO_GRUPO
	,CP.COD_PRODUTO
	,CP.DESCRICAO

UNION ALL

SELECT
	'ANTERIOR'
	,VP.COD_LOJA
	,L.NO_LOJA
	,CP.PNP
	,CP.NO_DEPARTAMENTO
	,CP.NO_SECAO
	,CP.NO_GRUPO
	,CP.COD_PRODUTO
	,CP.DESCRICAO
	,BI.dbo.fn_FormataVlr_Excel(SUM(VP.VALOR_TOTAL)) AS VLR_VENDA
	,BI.dbo.fn_FormataVlr_Excel(SUM(VP.QTDE_PRODUTO)) AS QTD_VENDA
FROM
	BI.DBO.BI_VENDA_PRODUTO AS VP
	INNER JOIN BI.DBO.BI_CAD_PRODUTO AS CP
		ON 1=1
		AND VP.COD_PRODUTO = CP.COD_PRODUTO
	INNER JOIN BI.dbo.BI_CAD_LOJA2 AS L
		ON 1=1
		AND VP.COD_LOJA = L.COD_LOJA
WHERE 1=1
	AND LEFT(dbo.ISO_WEEK(VP.DATA),4) = @LAST_YEAR
	AND BI.DBO.F_ISO_WEEK_OF_YEAR(VP.DATA) = @WEEK
	AND VP.COD_LOJA = 7
GROUP BY
	VP.COD_LOJA
	,L.NO_LOJA
	,CP.PNP
	,CP.NO_DEPARTAMENTO
	,CP.NO_SECAO
	,CP.NO_GRUPO
	,CP.COD_PRODUTO
	,CP.DESCRICAO
ORDER BY
	VP.COD_LOJA
	,L.NO_LOJA
	,CP.PNP
	,CP.NO_DEPARTAMENTO
	,CP.NO_SECAO
	,CP.NO_GRUPO
	,CP.DESCRICAO
	,PERIODO
