select
	NO_DEPARTAMENTO
	,NO_SECAO
	,NO_GRUPO
	,VP.COD_PRODUTO
	,DESCRICAO
	,BI.DBO.fn_FormataVlr_Excel(SUM(VP.VALOR_TOTAL)) AS VALOR
	,BI.DBO.fn_FormataVlr_Excel(SUM(VP.QTDE_PRODUTO)) AS QTD
	,BI.DBO.fn_FormataVlr_Excel(SUM(VP.QTDE_DEMANDA)) AS DEMANDA
from
	BI.dbo.BI_VENDA_PRODUTO AS VP
	INNER JOIN BI.dbo.BI_CAD_PRODUTO AS CP
		ON 1=1
		AND VP.COD_PRODUTO = CP.COD_PRODUTO
WHERE 1= 1
	AND CP.COD_DEPARTAMENTO = 8
	AND VP.COD_LOJA = 7
	AND CP.COD_GRUPO IN (1,12,9,14,13)
	AND CONVERT(DATE,DATA) BETWEEN CONVERT(DATE,'20140801') AND CONVERT(DATE,'20140831')
GROUP BY
	NO_DEPARTAMENTO
	,NO_SECAO
	,NO_GRUPO
	,VP.COD_PRODUTO
	,DESCRICAO