SELECT
	COD_LOJA
	,CONVERT(DATE,DATA) AS DATA
	,BI.dbo.fn_FormataVlr_Excel(SUM(QTDE_CUPOM)) AS QTD_CUPOM
	,BI.dbo.fn_FormataVlr_Excel(SUM(VALOR_TOTAL)) AS VLR_TOTAL
	,BI.dbo.fn_FormataVlr_Excel(AVG(CUPOM_MEDIO)) AS AVG_TICKET
FROM
	BI.DBO.BI_VENDA_CUPOM AS VC
WHERE 1=1
	AND CONVERT(DATE,DATA) >= '2015-01-01'
GROUP BY
	COD_LOJA
	,CONVERT(DATE,DATA)	
ORDER BY
	COD_LOJA
	,CONVERT(DATE,DATA)	