--SELECT * FROM  BI.dbo.CADASTRO_CAD_METADADOS
--SELECT * FROM  BI.dbo.CADASTRO_CAD_PRODUTO_METADADOS WHERE COD_METADADO = 6

SELECT
	CP.COD_PRODUTO
	,CP.DESCRICAO
	,CP.CLASSIF_PRODUTO
	,M.NO_METADADO
	,PM.VLR_METADADO
	,bi.dbo.fn_FormataVlr_Excel(SUM(LP.VLR_TOTAL_1ANO)) AS VLR_TOTAL_1ANO
	,bi.dbo.fn_FormataVlr_Excel(SUM(LP.QTDE_PRODUTO_1ANO)) AS QTDE_PRODUTO_1ANO

FROM
	BI.DBO.BI_CAD_PRODUTO AS CP
	INNER JOIN BI.dbo.BI_LINHA_PRODUTOS AS LP
		ON 1=1
		AND CP.COD_PRODUTO = LP.COD_PRODUTO
	LEFT JOIN BI.dbo.CADASTRO_CAD_PRODUTO_METADADOS AS PM
		ON 1=1
		AND CP.COD_PRODUTO = PM.COD_PRODUTO
		AND PM.COD_METADADO = 6
	LEFT JOIN BI.dbo.CADASTRO_CAD_METADADOS AS M
		ON 1=1
		AND PM.COD_METADADO = M.COD_METADADO
WHERE 1=1
	AND CP.COD_PRODUTO IN (688888)
GROUP BY
	CP.COD_PRODUTO
	,CP.DESCRICAO
	,CP.CLASSIF_PRODUTO
	,M.NO_METADADO
	,PM.VLR_METADADO