SELECT
	MTD_MARCA
	,BI.dbo.fn_FormataVlr_Excel(SUM(VALOR)) AS VLR_TOTAL
FROM
(
SELECT
	VP.COD_LOJA
	,VP.COD_PRODUTO
	,CP.DESCRICAO	
	,isnull((SELECT VLR_METADADO FROM CADASTRO_CAD_PRODUTO_METADADOS TPM WHERE TPM.COD_PRODUTO = VP.COD_PRODUTO AND TPM.COD_METADADO = 6),'NAO POSSUI') AS MTD_MARCA
	,SUM(VP.VALOR_TOTAL) AS VALOR
FROM
	BI_VENDA_PRODUTO AS VP
	INNER JOIN BI_CAD_PRODUTO AS CP
		ON VP.COD_PRODUTO = CP.COD_PRODUTO
WHERE 1=1
	AND CONVERT(DATE,VP.DATA) BETWEEN CONVERT(DATE,'20150201') AND CONVERT(DATE,'20150228')
	AND COD_LOJA = 7
GROUP BY
	VP.COD_LOJA
	,VP.COD_PRODUTO
	,CP.DESCRICAO
) AS X
GROUP BY
	MTD_MARCA
ORDER BY
	SUM(VALOR) DESC
	
	
	
SELECT
	VP.COD_PRODUTO
	,CP.DESCRICAO	
	,isnull((SELECT VLR_METADADO FROM CADASTRO_CAD_PRODUTO_METADADOS TPM WHERE TPM.COD_PRODUTO = VP.COD_PRODUTO AND TPM.COD_METADADO = 6),'NAO POSSUI') AS MTD_MARCA
	,BI.dbo.fn_FormataVlr_Excel(SUM(VP.VALOR_TOTAL)) AS VALOR
FROM
	BI_VENDA_PRODUTO AS VP
	INNER JOIN BI_CAD_PRODUTO AS CP
		ON VP.COD_PRODUTO = CP.COD_PRODUTO
WHERE 1=1
	AND CONVERT(DATE,VP.DATA) BETWEEN CONVERT(DATE,'20150201') AND CONVERT(DATE,'20150228')
	AND COD_LOJA = 7
GROUP BY
	VP.COD_PRODUTO
	,CP.DESCRICAO
ORDER BY 
	SUM(VP.VALOR_TOTAL) DESC
	
	
