SELECT
	VP.COD_LOJA
	,VP.COD_PRODUTO
	,CP.DESCRICAO
	,BI.dbo.fn_FormataVlr_Excel(SUM(VP.VALOR_TOTAL)) AS VLR_TOTAL
	,BI.dbo.fn_FormataVlr_Excel(SUM(VP.QTDE_PRODUTO)) AS QTD_TOTAL
FROM
	BI_VENDA_PRODUTO AS VP
	INNER JOIN BI_CAD_PRODUTO AS CP
		ON VP.COD_PRODUTO = CP.COD_PRODUTO
WHERE 1=1
	AND CP.COD_DEPARTAMENTO = 2
	--AND CP.COD_SECAO = 38
	AND CONVERT(DATE,VP.DATA) BETWEEN CONVERT(DATE,'20140901') AND CONVERT(DATE,'20141231')
GROUP BY
	VP.COD_LOJA
	,VP.COD_PRODUTO
	,CP.DESCRICAO