SELECT
	L.NO_LOJA
	,S.SEMANA_454
	,BI.dbo.fn_FormataVlr_Excel(SUM(VC.VALOR_TOTAL)) AS VLR_TOTAL
	,BI.dbo.fn_FormataVlr_Excel(SUM(VC.QTDE_CUPOM)) AS QTD_TOTAL
FROM
	BI.DBO.BI_VENDA_CUPOM AS VC
	INNER JOIN BI.DBO.BI_CAD_SEMANA AS S
		ON VC.DATA = S.DATA	
	INNER JOIN BI.dbo.BI_CAD_LOJA2 AS L
		ON VC.COD_LOJA = L.COD_LOJA
WHERE 1=1
	AND CONVERT(DATE,VC.DATA) >= '2015-07-20'
	AND DATEPART(DW,VC.DATA) IN (2,3,4)
GROUP BY 
	L.NO_LOJA
	,S.SEMANA_454