SELECT
	VP.COD_LOJA
	,L.NO_LOJA
	,CP.PNP
	,CP.NO_DEPARTAMENTO
	,CP.NO_SECAO
	,VP.COD_PRODUTO
	,CP.DESCRICAO AS NO_PRODUTO
	,BI.dbo.fn_FormataVlr_Excel(SUM(VP.VALOR_TOTAL)) AS VLR_VENDA
	,BI.dbo.fn_FormataVlr_Excel(SUM(VP.QTDE_PRODUTO)) AS QTD_VENDA
FROM
	BI.DBO.BI_VENDA_PRODUTO AS VP
	INNER JOIN BI.DBO.BI_CAD_PRODUTO AS CP
		ON 1=1
		AND VP.COD_PRODUTO = CP.COD_PRODUTO
	INNER JOIN BI.dbo.BI_CAD_LOJA2 AS L
		ON 1=1
		AND VP.COD_LOJA = L.COD_LOJA
WHERE 1=1
	AND CONVERT(DATE,VP.DATA) BETWEEN CONVERT(DATE,'20150801') AND CONVERT(DATE,'20150831')
	AND VP.COD_LOJA IN (8)
GROUP BY
	VP.COD_LOJA
	,L.NO_LOJA
	,CP.PNP
	,CP.NO_DEPARTAMENTO
	,CP.NO_SECAO
	,VP.COD_PRODUTO
	,CP.DESCRICAO
ORDER BY
	VP.COD_LOJA
	,CP.PNP
	,CP.NO_DEPARTAMENTO
	,CP.NO_SECAO
	--,SUM(VP.VALOR_TOTAL) DESC