SELECT
	YEAR(VP.DATA) ANO
	,MONTH(VP.DATA) MES
	,VP.COD_PRODUTO
	,BI.dbo.fn_FormataVlr_Excel(SUM(VP.VALOR_TOTAL)) VLR_TOTAL
	,BI.dbo.fn_FormataVlr_Excel(SUM(VP.QTDE_PRODUTO)) QTD_TOTAL
FROM
	BI_VENDA_PRODUTO AS VP
WHERE 1=1
	AND CONVERT(DATE,VP.DATA) BETWEEN CONVERT(DATE,'20140901') AND CONVERT(DATE,'20150317')
	AND VP.COD_PRODUTO IN (SELECT COD_PRODUTO FROM CADASTRO_CAD_PRODUTO_METADADOS TPM WHERE TPM.COD_METADADO = 4 AND TPM.VLR_METADADO = 1)
GROUP BY
	YEAR(VP.DATA)
	,MONTH(VP.DATA)
	,VP.COD_PRODUTO
	
	
SELECT
	COD_LOJA
	,COD_PRODUTO
	,BI.dbo.fn_FormataVlr_Excel(QTD_ESTOQUE) QTD_ESTOQUE
	,BI.dbo.fn_FormataVlr_Excel(VLR_CUSTO_UN) VLR_CUSTO_UN
FROM
	BI_ESTOQUE_PRODUTO AS EP
WHERE 1=1
	AND COD_LOJA IN (28,5)
	AND QTD_ESTOQUE <> 0
	AND EP.COD_PRODUTO IN (SELECT COD_PRODUTO FROM CADASTRO_CAD_PRODUTO_METADADOS TPM WHERE TPM.COD_METADADO = 4 AND TPM.VLR_METADADO = 1)