SELECT
	CP.NO_DEPARTAMENTO
	,CP.NO_SECAO
	,CP.NO_GRUPO
	,CP.COD_PRODUTO
	,CP.DESCRICAO AS NO_PRODUTO
	,CP.FORA_LINHA
	,CP.COD_FORNECEDOR
	,CF.DES_FANTASIA
	,BI.dbo.fn_FormataVlr_Excel(MAX(PV.VLR_VENDA)) AS VLR_VENDA
	,BI.dbo.fn_FormataVlr_Excel(SUM(VP.VALOR_TOTAL)) AS VLR_TOTAL
	,BI.dbo.fn_FormataVlr_Excel(SUM(VP.QTDE_PRODUTO)) AS QTD_TOTAL
FROM
	BI_VENDA_PRODUTO AS VP
	INNER JOIN BI_CAD_PRODUTO AS CP
		ON 1=1
		AND VP.COD_PRODUTO = CP.COD_PRODUTO
	LEFT JOIN BI_CAD_FORNECEDOR AS CF
		ON 1=1
		AND CF.COD_FORNECEDOR = CP.COD_FORNECEDOR
	LEFT JOIN BI_LINHA_PRODUTOS AS PV
		ON 1=1
		AND VP.COD_PRODUTO = PV.COD_PRODUTO
		AND VP.COD_LOJA = PV.COD_LOJA
WHERE 1=1
	AND ((CP.COD_DEPARTAMENTO = 10 AND CP.COD_SECAO = 26 AND CP.COD_GRUPO = 11) OR (CP.COD_DEPARTAMENTO = 14 AND CP.COD_SECAO = 8 AND CP.COD_GRUPO = 4))
	AND CONVERT(DATE,VP.DATA) >= '20140101'
GROUP BY
	CP.NO_DEPARTAMENTO
	,CP.NO_SECAO
	,CP.NO_GRUPO
	,CP.COD_PRODUTO
	,CP.DESCRICAO
	,CP.FORA_LINHA
	,CP.COD_FORNECEDOR
	,CF.DES_FANTASIA