SELECT TOP 100
*
FROM
	NFE.dbo.TAB_RECEBIMENTO_NFE AS NFE_XML LEFT JOIN zeus_rtg.dbo.TAB_FORNECEDOR_NOTA AS FN ON (NFE_XML.num_danfe = FN.num_danfe)
		LEFT JOIN zeus_rtg.dbo.TAB_FORNECEDOR_PRODUTO AS FP WITH (NOLOCK)
			ON (FN.COD_FORNECEDOR = FP.COD_FORNECEDOR AND FN.NUM_NF_FORN = FP.NUM_NF_FORN AND FN.NUM_SERIE_NF = FP.NUM_SERIE_NF AND FN.COD_LOJA = FP.COD_LOJA)
WHERE 1 = 1
	AND CONVERT(DATE,NFE_XML.dta_gravacao) >= CONVERT(DATE,'20140108')
	AND CONVERT(DATE,NFE_XML.dta_gravacao) <= CONVERT(DATE,'20140326')
	AND NFE_XML.num_cnpj_emit = '61186888002137'
	AND NFE_XML.num_cnpj_dest in
(	
'11317530000699'
)	
	AND FN.num_danfe IS NULL