SELECT
	DATEPART(year,s.DTA_SAIDA) as ANO,
	DATEPART(month,s.DTA_SAIDA) as MES,
	s.COD_LOJA,
	p.COD_PRODUTO AS COD_PRODUTO,
	P.DES_PRODUTO,
	p.COD_SECAO AS COD_SECAO, 
	p.COD_GRUPO AS COD_GRUPO, 
	--p.FLG_NAO_PIS_COFINS AS PISCOFINS,
	--l.[COD_TRIBUTACAO],
	l.[VAL_MARGEM]/100 as MARGEM_REF,
	--(CASE WHEN tri.TIPO_TRIBUTACAO <=2 THEN tri.val_icms*(1-val_reducao_base_calculo/100)/100 ELSE 0 END) as VLR_ICMS_SAIDA,
	--tri.TIPO_TRIBUTACAO AS TIPOTRIB, 
	SUM(s.QTD_TOTAL_PRODUTO) AS QTD_SAIDA, 
	SUM(s.VAL_TOTAL_PRODUTO) AS VLR_VENDA_BRUTA, 
	/*
	SUM(s.QTD_TOTAL_PRODUTO * s.VAL_CUSTO_REP) AS VLR_CUSTO_REP, 
	--SUM(s.QTD_TOTAL_PRODUTO * s.VAL_CUSTO_MEDIO) AS VENDA_MEDIO, 
	SUM(s.QTD_TOTAL_PRODUTO * s.VAL_PMZ) AS VLR_VENDA_PMZ, 
	SUM(s.QTD_TOTAL_PRODUTO * s.VAL_CUSTO_SICMS) AS VLR_CMV, 
	SUM(s.VAL_DEB_ICMS) AS VLR_ICMS,
	--SUM(s.VAL_TOTAL_PRODUTO - s.VAL_DEB_ICMS) AS VLR_VENDA_SICMS 
	SUM(CASE WHEN p.FLG_NAO_PIS_COFINS = 'N' THEN s.VAL_TOTAL_PRODUTO *(prm.VAL_PIS/100+prm.VAL_COFINS/100) ELSE 0 END) AS VLR_PISCOFINS,
	SUM(CASE WHEN p.FLG_NAO_PIS_COFINS = 'N' THEN (s.VAL_TOTAL_PRODUTO -s.QTD_TOTAL_PRODUTO * s.VAL_CUSTO_SICMS)*(prm.VAL_PIS/100+prm.VAL_COFINS/100) ELSE 0 END) AS VLR_PISCOFINS_NET
	*/
	(Sum(s.VAL_TOTAL_PRODUTO)-SUM(s.QTD_TOTAL_PRODUTO * s.VAL_CUSTO_SICMS)-SUM(CASE WHEN p.FLG_NAO_PIS_COFINS = 'N' THEN s.VAL_TOTAL_PRODUTO *(prm.VAL_PIS/100+prm.VAL_COFINS/100) ELSE 0 END)-sum((CASE WHEN tri.TIPO_TRIBUTACAO <=2 THEN tri.val_icms*(1-val_reducao_base_calculo/100)/100 ELSE 0 END)*s.VAL_TOTAL_PRODUTO)) as LUCRO_BRUTO_POND,
	(Sum(s.VAL_TOTAL_PRODUTO)-SUM(s.QTD_TOTAL_PRODUTO * s.VAL_CUSTO_SICMS)-SUM(CASE WHEN p.FLG_NAO_PIS_COFINS = 'N' THEN s.VAL_TOTAL_PRODUTO *(prm.VAL_PIS/100+prm.VAL_COFINS/100) ELSE 0 END)-sum((CASE WHEN tri.TIPO_TRIBUTACAO <=2 THEN tri.val_icms*(1-val_reducao_base_calculo/100)/100 ELSE 0 END)*s.VAL_TOTAL_PRODUTO))/SUM(s.VAL_TOTAL_PRODUTO) AS MARGEM_REAL
	FROM 
	   [192.168.0.6].zeus_rtg.dbo.TAB_PRODUTO as p
	   INNER JOIN [192.168.0.6].zeus_rtg.dbo.TAB_PRODUTO_SAIDA as s with (NOLOCK) 
		ON(p.COD_PRODUTO = s.COD_PRODUTO) 
	   INNER JOIN [192.168.0.6].zeus_rtg.dbo.TAB_PRODUTO_LOJA as l with (NOLOCK) 
		ON(s.COD_LOJA = l.COD_LOJA) AND (s.COD_PRODUTO = l.COD_PRODUTO) 
	   INNER JOIN [192.168.0.6].zeus_rtg.dbo.TAB_PARAMETRO_LOJA as prm with (NOLOCK) 
		ON(l.COD_LOJA = prm.COD_LOJA) 
	   INNER JOIN [192.168.0.6].zeus_rtg.dbo.TAB_TRIBUTACAO as tri with (NOLOCK) 
		ON(l.COD_TRIBUTACAO = tri.COD_TRIBUTACAO) 
	WHERE 1=1
		AND p.FLG_GRADE_PRODUTO = 'N' 
		--AND s.COD_LOJA IN (1,7)
		AND s.QTD_TOTAL_PRODUTO <> 0.00 
		and p.COD_PRODUTO in (select distinct COD_PRODUTO from [192.168.0.6].zeus_rtg.dbo.tab_produto_fornecedor where COD_FORNECEDOR in (2585,14461))
		AND convert(date,s.DTA_SAIDA)  BETWEEN convert(date,'20110101') AND convert(date,'20130930')
	GROUP BY
	DATEPART(year,s.DTA_SAIDA),
	DATEPART(month,s.DTA_SAIDA),
	s.COD_LOJA,
	p.COD_PRODUTO,
	P.DES_PRODUTO,
	p.COD_SECAO, 
	p.COD_GRUPO,
	l.[VAL_MARGEM]/100