USE [BI]
GO

/****** Object:  Table [dbo].[BI_VENDA_PRODUTO]    Script Date: 08/15/2014 10:27:33 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[BI_VENDA_PRODUTO](
	[COD_LOJA] [int] NOT NULL,
	[DATA] [datetime] NOT NULL,
	[COD_PRODUTO] [int] NOT NULL,
	[TIPO_VENDA] [int] NOT NULL,
	[QTDE_PRODUTO] [numeric](18, 3) NULL,
	[VALOR_TOTAL] [numeric](18, 2) NULL,
	[VALOR_UNITARIO] [numeric](18, 2) NULL,
	[QTDE_DEMANDA] [numeric](18, 2) NULL,
	[COD_CLIENTE] [int] NULL,
 CONSTRAINT [PK_BI_VENDA] PRIMARY KEY CLUSTERED 
(
	[COD_LOJA] ASC,
	[DATA] ASC,
	[COD_PRODUTO] ASC,
	[TIPO_VENDA] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 80) ON [PRIMARY]
) ON [PRIMARY]

GO


