select
	DATEPART(DW,VP.DATA) AS DIA_SEMANA
	,CP.COD_PRODUTO
	,CP.DESCRICAO
	,BI.dbo.fn_FormataVlr_Excel(SUM(VALOR_TOTAL)) AS VLR_TOTAL
	,BI.dbo.fn_FormataVlr_Excel(SUM(QTDE_PRODUTO)) AS QTD_TOTAL
from 
	BI_VENDA_PRODUTO as VP
	INNER JOIN BI_CAD_PRODUTO AS CP
		ON 1=1
		AND VP.COD_PRODUTO = CP.COD_PRODUTO
WHERE 1=1
	AND VP.COD_PRODUTO IN (569293,553117)
	AND CONVERT(DATE,VP.DATA) >= '20140101'
GROUP BY
	DATEPART(DW,VP.DATA)
	,CP.COD_PRODUTO
	,CP.DESCRICAO
	
	
