SELECT
	CP.COD_PRODUTO
	,CP.DESCRICAO AS NO_PRODUTO
	,CP.CLASSIF_PRODUTO AS ABC_PROD
	,CP.PNP
	,CP.NO_DEPARTAMENTO
	,CP.NO_SECAO
	,CP.COD_FORNECEDOR
	,CF.DESCRICAO AS NO_FORNECEDOR
	,CF.ABC_FORN
	,BI.dbo.fn_FormataVlr_Excel(SUM(VP.VALOR_TOTAL)) AS VLR_TOTAL
	,BI.dbo.fn_FormataVlr_Excel(SUM(VP.QTDE_PRODUTO)) AS QTD_TOTAL		
FROM
	BI.dbo.BI_VENDA_PRODUTO AS VP
	INNER JOIN BI.dbo.BI_CAD_PRODUTO AS CP
		ON VP.COD_PRODUTO = CP.COD_PRODUTO
	INNER JOIN BI.dbo.BI_CAD_FORNECEDOR AS CF
		ON CP.COD_FORNECEDOR = CF.COD_FORNECEDOR
WHERE 1=1
	AND CONVERT(DATE,VP.DATA) >= CONVERT(date,GETDATE()-31)
	AND CP.PNP = 'NP'
GROUP BY
	CP.COD_PRODUTO
	,CP.DESCRICAO
	,CP.CLASSIF_PRODUTO
	,CP.PNP
	,CP.NO_DEPARTAMENTO
	,CP.NO_SECAO
	,CP.COD_FORNECEDOR
	,CF.DESCRICAO
	,CF.ABC_FORN