	-- ------------------------------------------------------------------------------------------------------------------------------------------------------------------
	--
	-- ------------------------------------------------------------------------------------------------------------------------------------------------------------------
	SELECT
		VI.[COD_LOJA]
		,VI.COD_RESTAURANTE
		,CR.NO_RESTAURANTE
		,S.ANO_454
		,S.SEMANA_454
		,DEPARA.COD_PRODUTO AS COD_PRODUTO		
		,(CASE
			WHEN DEPARA.COD_PRODUTO IS NULL THEN 'Food'
			WHEN CP.COD_PRODUTO IS NULL  THEN 'Erro DePara'
			WHEN CP.COD_DEPARTAMENTO = 1 AND CP.COD_SECAO = 13 AND CP.COD_GRUPO = 6 AND CP.COD_SUB_GRUPO = 1 THEN 'Food'
			WHEN CP.COD_DEPARTAMENTO = 2 AND CP.COD_SECAO = 7 AND CP.COD_GRUPO = 11 AND CP.COD_SUB_GRUPO = 1 THEN 'Drinks'
			WHEN CP.COD_DEPARTAMENTO = 2 AND CP.COD_SECAO = 7 AND CP.COD_GRUPO = 11 AND CP.COD_SUB_GRUPO = 2 THEN 'Drinks'
			WHEN CP.COD_DEPARTAMENTO = 2 AND CP.COD_SECAO = 27 AND CP.COD_GRUPO = 24 AND CP.COD_SUB_GRUPO = 1 THEN 'Drinks'
			WHEN CP.COD_DEPARTAMENTO = 2 AND CP.COD_SECAO = 27 AND CP.COD_GRUPO = 25 AND CP.COD_SUB_GRUPO = 1 THEN 'Drinks'
			WHEN CP.COD_DEPARTAMENTO = 2 AND CP.COD_SECAO = 27 AND CP.COD_GRUPO = 27 AND CP.COD_SUB_GRUPO = 1 THEN 'Drinks'
			WHEN CP.COD_DEPARTAMENTO = 2 AND CP.COD_SECAO = 27 AND CP.COD_GRUPO = 28 AND CP.COD_SUB_GRUPO = 1 THEN 'Drinks'
			WHEN CP.COD_DEPARTAMENTO = 2 AND CP.COD_SECAO = 27 AND CP.COD_GRUPO = 32 AND CP.COD_SUB_GRUPO = 1 THEN 'Drinks'
			WHEN CP.COD_DEPARTAMENTO = 3 AND CP.COD_SECAO = 61 AND CP.COD_GRUPO = 13 AND CP.COD_SUB_GRUPO = 11 THEN 'Food'
			WHEN CP.COD_DEPARTAMENTO = 5 AND CP.COD_SECAO = 23 AND CP.COD_GRUPO = 1 AND CP.COD_SUB_GRUPO = 1 THEN 'Food'
			WHEN CP.COD_DEPARTAMENTO = 6 AND CP.COD_SECAO = 32 AND CP.COD_GRUPO = 11 AND CP.COD_SUB_GRUPO = 1 THEN 'Food'
			WHEN CP.COD_DEPARTAMENTO = 6 AND CP.COD_SECAO = 50 AND CP.COD_GRUPO = 55 AND CP.COD_SUB_GRUPO = 1 THEN 'Food'
			WHEN CP.COD_DEPARTAMENTO = 7 AND CP.COD_SECAO = 1 AND CP.COD_GRUPO = 10 AND CP.COD_SUB_GRUPO = 100 THEN 'Others'
			WHEN CP.COD_DEPARTAMENTO = 7 AND CP.COD_SECAO = 6 AND CP.COD_GRUPO = 1 AND CP.COD_SUB_GRUPO = 1 THEN 'Others'
			WHEN CP.COD_DEPARTAMENTO = 8 AND CP.COD_SECAO = 17 AND CP.COD_GRUPO = 2 AND CP.COD_SUB_GRUPO = 1 THEN 'Food'
			WHEN CP.COD_DEPARTAMENTO = 8 AND CP.COD_SECAO = 17 AND CP.COD_GRUPO = 14 AND CP.COD_SUB_GRUPO = 1 THEN 'Food'
			WHEN CP.COD_DEPARTAMENTO = 9 AND CP.COD_SECAO = 91 AND CP.COD_GRUPO = 91 AND CP.COD_SUB_GRUPO = 92 THEN 'Drinks'
			WHEN CP.COD_DEPARTAMENTO = 9 AND CP.COD_SECAO = 91 AND CP.COD_GRUPO = 94 AND CP.COD_SUB_GRUPO = 91 THEN 'Drinks'
			WHEN CP.COD_DEPARTAMENTO = 9 AND CP.COD_SECAO = 92 AND CP.COD_GRUPO = 91 AND CP.COD_SUB_GRUPO = 91 THEN 'Drinks'
			WHEN CP.COD_DEPARTAMENTO = 9 AND CP.COD_SECAO = 95 AND CP.COD_GRUPO = 92 AND CP.COD_SUB_GRUPO = 91 THEN 'Drinks'
			WHEN CP.COD_DEPARTAMENTO = 9 AND CP.COD_SECAO = 95 AND CP.COD_GRUPO = 95 AND CP.COD_SUB_GRUPO = 91 THEN 'Drinks'
			WHEN CP.COD_DEPARTAMENTO = 9 AND CP.COD_SECAO = 97 AND CP.COD_GRUPO = 91 AND CP.COD_SUB_GRUPO = 91 THEN 'Drinks'
			WHEN CP.COD_DEPARTAMENTO = 9 AND CP.COD_SECAO = 97 AND CP.COD_GRUPO = 92 AND CP.COD_SUB_GRUPO = 91 THEN 'Drinks'
			WHEN CP.COD_DEPARTAMENTO = 12 AND CP.COD_SECAO = 74 AND CP.COD_GRUPO = 12 AND CP.COD_SUB_GRUPO = 11 THEN 'Others'
			WHEN CP.COD_DEPARTAMENTO = 13 AND CP.COD_SECAO = 52 AND CP.COD_GRUPO = 11 AND CP.COD_SUB_GRUPO = 11 THEN 'Others'
			WHEN CP.COD_DEPARTAMENTO = 14 AND CP.COD_SECAO = 39 AND CP.COD_GRUPO = 6 AND CP.COD_SUB_GRUPO = 1 THEN 'Food'
			WHEN CP.COD_DEPARTAMENTO = 16 AND CP.COD_SECAO = 25 AND CP.COD_GRUPO = 1 AND CP.COD_SUB_GRUPO = 1 THEN 'Food'
			WHEN CP.COD_DEPARTAMENTO = 16 AND CP.COD_SECAO = 29 AND CP.COD_GRUPO = 1 AND CP.COD_SUB_GRUPO = 1 THEN 'Food'
			WHEN CP.COD_DEPARTAMENTO = 16 AND CP.COD_SECAO = 30 AND CP.COD_GRUPO = 1 AND CP.COD_SUB_GRUPO = 1 THEN 'Food'
			WHEN CP.COD_DEPARTAMENTO = 16 AND CP.COD_SECAO = 30 AND CP.COD_GRUPO = 2 AND CP.COD_SUB_GRUPO = 1 THEN 'Food'
			WHEN CP.COD_DEPARTAMENTO = 16 AND CP.COD_SECAO = 31 AND CP.COD_GRUPO = 1 AND CP.COD_SUB_GRUPO = 1 THEN 'Food'
			WHEN CP.COD_DEPARTAMENTO = 16 AND CP.COD_SECAO = 31 AND CP.COD_GRUPO = 5 AND CP.COD_SUB_GRUPO = 1 THEN 'Food'
			WHEN CP.COD_DEPARTAMENTO = 16 AND CP.COD_SECAO = 35 AND CP.COD_GRUPO = 1 AND CP.COD_SUB_GRUPO = 4 THEN 'Drinks'
			WHEN CP.COD_DEPARTAMENTO = 16 AND CP.COD_SECAO = 35 AND CP.COD_GRUPO = 14 AND CP.COD_SUB_GRUPO = 1 THEN 'Food'
			WHEN CP.COD_DEPARTAMENTO = 16 AND CP.COD_SECAO = 35 AND CP.COD_GRUPO = 15 AND CP.COD_SUB_GRUPO = 1 THEN 'Food'
			WHEN CP.COD_DEPARTAMENTO = 16 AND CP.COD_SECAO = 35 AND CP.COD_GRUPO = 15 AND CP.COD_SUB_GRUPO = 2 THEN 'Food'
			WHEN CP.COD_DEPARTAMENTO = 16 AND CP.COD_SECAO = 43 AND CP.COD_GRUPO = 1 AND CP.COD_SUB_GRUPO = 1 THEN 'Food'
			WHEN CP.COD_DEPARTAMENTO = 16 AND CP.COD_SECAO = 56 AND CP.COD_GRUPO = 1 AND CP.COD_SUB_GRUPO = 1 THEN 'Food'
			WHEN CP.COD_DEPARTAMENTO = 16 AND CP.COD_SECAO = 56 AND CP.COD_GRUPO = 3 AND CP.COD_SUB_GRUPO = 1 THEN 'Food'
			WHEN CP.COD_DEPARTAMENTO = 16 AND CP.COD_SECAO = 56 AND CP.COD_GRUPO = 3 AND CP.COD_SUB_GRUPO = 2 THEN 'Food'
			WHEN CP.COD_DEPARTAMENTO = 16 AND CP.COD_SECAO = 58 AND CP.COD_GRUPO = 1 AND CP.COD_SUB_GRUPO = 1 THEN 'Drinks'
			WHEN CP.COD_DEPARTAMENTO = 16 AND CP.COD_SECAO = 58 AND CP.COD_GRUPO = 2 AND CP.COD_SUB_GRUPO = 1 THEN 'Drinks'
			WHEN CP.COD_DEPARTAMENTO = 16 AND CP.COD_SECAO = 58 AND CP.COD_GRUPO = 4 AND CP.COD_SUB_GRUPO = 1 THEN 'Drinks'
			WHEN CP.COD_DEPARTAMENTO = 16 AND CP.COD_SECAO = 58 AND CP.COD_GRUPO = 5 AND CP.COD_SUB_GRUPO = 1 THEN 'Drinks'
			WHEN CP.COD_DEPARTAMENTO = 16 AND CP.COD_SECAO = 59 AND CP.COD_GRUPO = 1 AND CP.COD_SUB_GRUPO = 1 THEN 'Drinks'
			WHEN CP.COD_DEPARTAMENTO = 16 AND CP.COD_SECAO = 59 AND CP.COD_GRUPO = 2 AND CP.COD_SUB_GRUPO = 3 THEN 'Drinks'
			WHEN CP.COD_DEPARTAMENTO = 20 AND CP.COD_SECAO = 12 AND CP.COD_GRUPO = 3 AND CP.COD_SUB_GRUPO = 32 THEN 'Others'
			WHEN CP.COD_DEPARTAMENTO = 20 AND CP.COD_SECAO = 12 AND CP.COD_GRUPO = 4 AND CP.COD_SUB_GRUPO = 33 THEN 'Food'
			WHEN CP.COD_DEPARTAMENTO = 20 AND CP.COD_SECAO = 14 AND CP.COD_GRUPO = 1 AND CP.COD_SUB_GRUPO = 10 THEN 'Others'
			WHEN CP.COD_DEPARTAMENTO = 20 AND CP.COD_SECAO = 15 AND CP.COD_GRUPO = 5 AND CP.COD_SUB_GRUPO = 10 THEN 'Others'
			WHEN CP.COD_DEPARTAMENTO = 20 AND CP.COD_SECAO = 24 AND CP.COD_GRUPO = 1 AND CP.COD_SUB_GRUPO = 10 THEN 'Others'	
			WHEN CP.COD_DEPARTAMENTO = 16 AND CP.COD_SECAO = 25 AND CP.COD_GRUPO = 3 AND CP.COD_SUB_GRUPO = 1 THEN 'Food'
			WHEN CP.COD_DEPARTAMENTO = 16 AND CP.COD_SECAO = 33 AND CP.COD_GRUPO = 1 AND CP.COD_SUB_GRUPO = 1 THEN 'Food'
			WHEN CP.COD_DEPARTAMENTO = 7 AND CP.COD_SECAO = 6 AND CP.COD_GRUPO = 3 AND CP.COD_SUB_GRUPO = 1 THEN 'Others'
			WHEN CP.COD_DEPARTAMENTO = 19 AND CP.COD_SECAO = 71 AND CP.COD_GRUPO = 73 AND CP.COD_SUB_GRUPO = 72 THEN 'Others'
			WHEN CP.COD_DEPARTAMENTO = 7 AND CP.COD_SECAO = 10 AND CP.COD_GRUPO = 1 AND CP.COD_SUB_GRUPO = 1 THEN 'Others'
			WHEN CP.COD_DEPARTAMENTO = 20 AND CP.COD_SECAO = 15 AND CP.COD_GRUPO = 1 AND CP.COD_SUB_GRUPO = 12 THEN 'Others'
			WHEN CP.COD_DEPARTAMENTO = 14 AND CP.COD_SECAO = 39 AND CP.COD_GRUPO = 3 AND CP.COD_SUB_GRUPO = 1 THEN 'Others'
			WHEN CP.COD_DEPARTAMENTO = 16 AND CP.COD_SECAO = 35 AND CP.COD_GRUPO = 18 AND CP.COD_SUB_GRUPO = 1 THEN 'Food'
			ELSE 'ERRO'
		END) AS Classif		
		,CP.COD_DEPARTAMENTO
		,CP.NO_DEPARTAMENTO
		,COD_SECAO
		,CP.NO_SECAO
		,COD_GRUPO
		,CP.NO_GRUPO
		,CP.COD_SUB_GRUPO
		,CP.NO_SUBGRUPO
		,CP.DESCRICAO		
		,sum(VI.VALOR_UNITARIO * VI.QUANTIDADE) as  VLR_UNITARIO_PROD
		,sum(VI.VALOR_DESCONTO) as VLR_DSCONTO_PROD
		,sum(VI.VALOR_TOTAL) as VLR_TOTAL_PRODUTO
		,sum(VI.VALOR_TOTAL)*0.968 as VLR_TOTAL_SEM_IMP
	FROM
		[DW].[dbo].[TAB_CHEFFSOLUTION_CUPOM_ITENS] AS VI
		LEFT JOIN BI.dbo.BI_CAD_RESTAURANTE AS CR
			ON 1=1
			AND VI.COD_LOJA = CR.COD_LOJA
			AND VI.COD_RESTAURANTE = CR.COD_RESTAURANTE
		
		LEFT JOIN [BI].[dbo].[CAD_DE_PARA_CHEFF] AS DEPARA
			ON 1=1
			AND VI.COD_PRODUTO_CHEFF = DEPARA.COD_PRODUTO_CHEFF
			AND VI.COD_RESTAURANTE = DEPARA.COD_RESTAURANTE
		LEFT JOIN BI.dbo.BI_CAD_SEMANA AS S
			ON VI.DATA = S.DATA
		LEFT JOIN BI.dbo.BI_CAD_PRODUTO AS CP
			ON DEPARA.COD_PRODUTO = CP.COD_PRODUTO
	WHERE 1=1
		AND CONVERT(DATE,VI.DATA) BETWEEN CONVERT(DATE,'2015-01-01') AND CONVERT(DATE,GETDATE()-1)
		AND VI.COD_LOJA IN (33)
		--and CP.COD_DEPARTAMENTO = 7
	GROUP BY
		VI.[COD_LOJA]
		,VI.COD_RESTAURANTE
		,CR.NO_RESTAURANTE
		,S.ANO_454
		,S.SEMANA_454
		,DEPARA.COD_PRODUTO
		,(CASE
			WHEN DEPARA.COD_PRODUTO IS NULL THEN 'Food'
			WHEN CP.COD_PRODUTO IS NULL  THEN 'Erro DePara'
			WHEN CP.COD_DEPARTAMENTO = 1 AND CP.COD_SECAO = 13 AND CP.COD_GRUPO = 6 AND CP.COD_SUB_GRUPO = 1 THEN 'Food'
			WHEN CP.COD_DEPARTAMENTO = 2 AND CP.COD_SECAO = 7 AND CP.COD_GRUPO = 11 AND CP.COD_SUB_GRUPO = 1 THEN 'Drinks'
			WHEN CP.COD_DEPARTAMENTO = 2 AND CP.COD_SECAO = 7 AND CP.COD_GRUPO = 11 AND CP.COD_SUB_GRUPO = 2 THEN 'Drinks'
			WHEN CP.COD_DEPARTAMENTO = 2 AND CP.COD_SECAO = 27 AND CP.COD_GRUPO = 24 AND CP.COD_SUB_GRUPO = 1 THEN 'Drinks'
			WHEN CP.COD_DEPARTAMENTO = 2 AND CP.COD_SECAO = 27 AND CP.COD_GRUPO = 25 AND CP.COD_SUB_GRUPO = 1 THEN 'Drinks'
			WHEN CP.COD_DEPARTAMENTO = 2 AND CP.COD_SECAO = 27 AND CP.COD_GRUPO = 27 AND CP.COD_SUB_GRUPO = 1 THEN 'Drinks'
			WHEN CP.COD_DEPARTAMENTO = 2 AND CP.COD_SECAO = 27 AND CP.COD_GRUPO = 28 AND CP.COD_SUB_GRUPO = 1 THEN 'Drinks'
			WHEN CP.COD_DEPARTAMENTO = 2 AND CP.COD_SECAO = 27 AND CP.COD_GRUPO = 32 AND CP.COD_SUB_GRUPO = 1 THEN 'Drinks'
			WHEN CP.COD_DEPARTAMENTO = 3 AND CP.COD_SECAO = 61 AND CP.COD_GRUPO = 13 AND CP.COD_SUB_GRUPO = 11 THEN 'Food'
			WHEN CP.COD_DEPARTAMENTO = 5 AND CP.COD_SECAO = 23 AND CP.COD_GRUPO = 1 AND CP.COD_SUB_GRUPO = 1 THEN 'Food'
			WHEN CP.COD_DEPARTAMENTO = 6 AND CP.COD_SECAO = 32 AND CP.COD_GRUPO = 11 AND CP.COD_SUB_GRUPO = 1 THEN 'Food'
			WHEN CP.COD_DEPARTAMENTO = 6 AND CP.COD_SECAO = 50 AND CP.COD_GRUPO = 55 AND CP.COD_SUB_GRUPO = 1 THEN 'Food'
			WHEN CP.COD_DEPARTAMENTO = 7 AND CP.COD_SECAO = 1 AND CP.COD_GRUPO = 10 AND CP.COD_SUB_GRUPO = 100 THEN 'Others'
			WHEN CP.COD_DEPARTAMENTO = 7 AND CP.COD_SECAO = 6 AND CP.COD_GRUPO = 1 AND CP.COD_SUB_GRUPO = 1 THEN 'Others'
			WHEN CP.COD_DEPARTAMENTO = 8 AND CP.COD_SECAO = 17 AND CP.COD_GRUPO = 2 AND CP.COD_SUB_GRUPO = 1 THEN 'Food'
			WHEN CP.COD_DEPARTAMENTO = 8 AND CP.COD_SECAO = 17 AND CP.COD_GRUPO = 14 AND CP.COD_SUB_GRUPO = 1 THEN 'Food'
			WHEN CP.COD_DEPARTAMENTO = 9 AND CP.COD_SECAO = 91 AND CP.COD_GRUPO = 91 AND CP.COD_SUB_GRUPO = 92 THEN 'Drinks'
			WHEN CP.COD_DEPARTAMENTO = 9 AND CP.COD_SECAO = 91 AND CP.COD_GRUPO = 94 AND CP.COD_SUB_GRUPO = 91 THEN 'Drinks'
			WHEN CP.COD_DEPARTAMENTO = 9 AND CP.COD_SECAO = 92 AND CP.COD_GRUPO = 91 AND CP.COD_SUB_GRUPO = 91 THEN 'Drinks'
			WHEN CP.COD_DEPARTAMENTO = 9 AND CP.COD_SECAO = 95 AND CP.COD_GRUPO = 92 AND CP.COD_SUB_GRUPO = 91 THEN 'Drinks'
			WHEN CP.COD_DEPARTAMENTO = 9 AND CP.COD_SECAO = 95 AND CP.COD_GRUPO = 95 AND CP.COD_SUB_GRUPO = 91 THEN 'Drinks'
			WHEN CP.COD_DEPARTAMENTO = 9 AND CP.COD_SECAO = 97 AND CP.COD_GRUPO = 91 AND CP.COD_SUB_GRUPO = 91 THEN 'Drinks'
			WHEN CP.COD_DEPARTAMENTO = 9 AND CP.COD_SECAO = 97 AND CP.COD_GRUPO = 92 AND CP.COD_SUB_GRUPO = 91 THEN 'Drinks'
			WHEN CP.COD_DEPARTAMENTO = 12 AND CP.COD_SECAO = 74 AND CP.COD_GRUPO = 12 AND CP.COD_SUB_GRUPO = 11 THEN 'Others'
			WHEN CP.COD_DEPARTAMENTO = 13 AND CP.COD_SECAO = 52 AND CP.COD_GRUPO = 11 AND CP.COD_SUB_GRUPO = 11 THEN 'Others'
			WHEN CP.COD_DEPARTAMENTO = 14 AND CP.COD_SECAO = 39 AND CP.COD_GRUPO = 6 AND CP.COD_SUB_GRUPO = 1 THEN 'Food'
			WHEN CP.COD_DEPARTAMENTO = 16 AND CP.COD_SECAO = 25 AND CP.COD_GRUPO = 1 AND CP.COD_SUB_GRUPO = 1 THEN 'Food'
			WHEN CP.COD_DEPARTAMENTO = 16 AND CP.COD_SECAO = 29 AND CP.COD_GRUPO = 1 AND CP.COD_SUB_GRUPO = 1 THEN 'Food'
			WHEN CP.COD_DEPARTAMENTO = 16 AND CP.COD_SECAO = 30 AND CP.COD_GRUPO = 1 AND CP.COD_SUB_GRUPO = 1 THEN 'Food'
			WHEN CP.COD_DEPARTAMENTO = 16 AND CP.COD_SECAO = 30 AND CP.COD_GRUPO = 2 AND CP.COD_SUB_GRUPO = 1 THEN 'Food'
			WHEN CP.COD_DEPARTAMENTO = 16 AND CP.COD_SECAO = 31 AND CP.COD_GRUPO = 1 AND CP.COD_SUB_GRUPO = 1 THEN 'Food'
			WHEN CP.COD_DEPARTAMENTO = 16 AND CP.COD_SECAO = 31 AND CP.COD_GRUPO = 5 AND CP.COD_SUB_GRUPO = 1 THEN 'Food'
			WHEN CP.COD_DEPARTAMENTO = 16 AND CP.COD_SECAO = 35 AND CP.COD_GRUPO = 1 AND CP.COD_SUB_GRUPO = 4 THEN 'Drinks'
			WHEN CP.COD_DEPARTAMENTO = 16 AND CP.COD_SECAO = 35 AND CP.COD_GRUPO = 14 AND CP.COD_SUB_GRUPO = 1 THEN 'Food'
			WHEN CP.COD_DEPARTAMENTO = 16 AND CP.COD_SECAO = 35 AND CP.COD_GRUPO = 15 AND CP.COD_SUB_GRUPO = 1 THEN 'Food'
			WHEN CP.COD_DEPARTAMENTO = 16 AND CP.COD_SECAO = 35 AND CP.COD_GRUPO = 15 AND CP.COD_SUB_GRUPO = 2 THEN 'Food'
			WHEN CP.COD_DEPARTAMENTO = 16 AND CP.COD_SECAO = 43 AND CP.COD_GRUPO = 1 AND CP.COD_SUB_GRUPO = 1 THEN 'Food'
			WHEN CP.COD_DEPARTAMENTO = 16 AND CP.COD_SECAO = 56 AND CP.COD_GRUPO = 1 AND CP.COD_SUB_GRUPO = 1 THEN 'Food'
			WHEN CP.COD_DEPARTAMENTO = 16 AND CP.COD_SECAO = 56 AND CP.COD_GRUPO = 3 AND CP.COD_SUB_GRUPO = 1 THEN 'Food'
			WHEN CP.COD_DEPARTAMENTO = 16 AND CP.COD_SECAO = 56 AND CP.COD_GRUPO = 3 AND CP.COD_SUB_GRUPO = 2 THEN 'Food'
			WHEN CP.COD_DEPARTAMENTO = 16 AND CP.COD_SECAO = 58 AND CP.COD_GRUPO = 1 AND CP.COD_SUB_GRUPO = 1 THEN 'Drinks'
			WHEN CP.COD_DEPARTAMENTO = 16 AND CP.COD_SECAO = 58 AND CP.COD_GRUPO = 2 AND CP.COD_SUB_GRUPO = 1 THEN 'Drinks'
			WHEN CP.COD_DEPARTAMENTO = 16 AND CP.COD_SECAO = 58 AND CP.COD_GRUPO = 4 AND CP.COD_SUB_GRUPO = 1 THEN 'Drinks'
			WHEN CP.COD_DEPARTAMENTO = 16 AND CP.COD_SECAO = 58 AND CP.COD_GRUPO = 5 AND CP.COD_SUB_GRUPO = 1 THEN 'Drinks'
			WHEN CP.COD_DEPARTAMENTO = 16 AND CP.COD_SECAO = 59 AND CP.COD_GRUPO = 1 AND CP.COD_SUB_GRUPO = 1 THEN 'Drinks'
			WHEN CP.COD_DEPARTAMENTO = 16 AND CP.COD_SECAO = 59 AND CP.COD_GRUPO = 2 AND CP.COD_SUB_GRUPO = 3 THEN 'Drinks'
			WHEN CP.COD_DEPARTAMENTO = 20 AND CP.COD_SECAO = 12 AND CP.COD_GRUPO = 3 AND CP.COD_SUB_GRUPO = 32 THEN 'Others'
			WHEN CP.COD_DEPARTAMENTO = 20 AND CP.COD_SECAO = 12 AND CP.COD_GRUPO = 4 AND CP.COD_SUB_GRUPO = 33 THEN 'Food'
			WHEN CP.COD_DEPARTAMENTO = 20 AND CP.COD_SECAO = 14 AND CP.COD_GRUPO = 1 AND CP.COD_SUB_GRUPO = 10 THEN 'Others'
			WHEN CP.COD_DEPARTAMENTO = 20 AND CP.COD_SECAO = 15 AND CP.COD_GRUPO = 5 AND CP.COD_SUB_GRUPO = 10 THEN 'Others'
			WHEN CP.COD_DEPARTAMENTO = 20 AND CP.COD_SECAO = 24 AND CP.COD_GRUPO = 1 AND CP.COD_SUB_GRUPO = 10 THEN 'Others'
			WHEN CP.COD_DEPARTAMENTO = 16 AND CP.COD_SECAO = 25 AND CP.COD_GRUPO = 3 AND CP.COD_SUB_GRUPO = 1 THEN 'Food'
			WHEN CP.COD_DEPARTAMENTO = 16 AND CP.COD_SECAO = 33 AND CP.COD_GRUPO = 1 AND CP.COD_SUB_GRUPO = 1 THEN 'Food'
			WHEN CP.COD_DEPARTAMENTO = 7 AND CP.COD_SECAO = 6 AND CP.COD_GRUPO = 3 AND CP.COD_SUB_GRUPO = 1 THEN 'Others'
			WHEN CP.COD_DEPARTAMENTO = 19 AND CP.COD_SECAO = 71 AND CP.COD_GRUPO = 73 AND CP.COD_SUB_GRUPO = 72 THEN 'Others'
			WHEN CP.COD_DEPARTAMENTO = 7 AND CP.COD_SECAO = 10 AND CP.COD_GRUPO = 1 AND CP.COD_SUB_GRUPO = 1 THEN 'Others'
			WHEN CP.COD_DEPARTAMENTO = 20 AND CP.COD_SECAO = 15 AND CP.COD_GRUPO = 1 AND CP.COD_SUB_GRUPO = 12 THEN 'Others'
			WHEN CP.COD_DEPARTAMENTO = 14 AND CP.COD_SECAO = 39 AND CP.COD_GRUPO = 3 AND CP.COD_SUB_GRUPO = 1 THEN 'Others'
			WHEN CP.COD_DEPARTAMENTO = 16 AND CP.COD_SECAO = 35 AND CP.COD_GRUPO = 18 AND CP.COD_SUB_GRUPO = 1 THEN 'Food'
			ELSE 'ERRO'
		END)
		,CP.COD_DEPARTAMENTO
		,CP.NO_DEPARTAMENTO
		,COD_SECAO
		,CP.NO_SECAO
		,COD_GRUPO
		,CP.NO_GRUPO
		,CP.COD_SUB_GRUPO
		,CP.NO_SUBGRUPO
		,CP.DESCRICAO
		
	-- ------------------------------------------------------------------------------------------------------------------------------------------------------------------
	--
	-- ------------------------------------------------------------------------------------------------------------------------------------------------------------------
	DECLARE @TAB_AJUSTE_ESTOQUE AS TABLE
	(
		COD_LOJA INT
		,DTA_AJUSTE DATE
		,COD_AJUSTE INT
		,DES_AJUSTE VARCHAR(50)
		,COD_PRODUTO INT
		,QTD_AJUSTE NUMERIC(18,2)
		,VAL_CUSTO_MED NUMERIC(18,2)
		,VAL_CUSTO_REP NUMERIC(18,2)
	)
	INSERT INTO @TAB_AJUSTE_ESTOQUE
		SELECT
			T.COD_LOJA
			,T.DTA_AJUSTE
			,T.COD_AJUSTE
			,TA.DES_AJUSTE
			,T.COD_PRODUTO
			,T.QTD_AJUSTE*-1
			,T.VAL_CUSTO_MED
			,T.VAL_CUSTO_REP
		FROM
			[192.168.0.6].ZEUS_RTG.DBO.TAB_AJUSTE_ESTOQUE AS T
			INNER JOIN [192.168.0.6].ZEUS_RTG.DBO.TAB_TIPO_AJUSTE AS TA
				ON 1=1
				AND T.COD_AJUSTE = TA.COD_AJUSTE		
		WHERE 1=1
			AND T.COD_LOJA = 33
			AND TA.COD_AJUSTE IN (250,251,252,253,254,255,256,257,258,259,260,261,262,263,264,292,293,270,271,273,274,275,276,277,278,279,280,282,284)
			AND CONVERT(DATE,DTA_AJUSTE) >= '2016-01-01'
	