INSERT INTO bi.dbo.CAD_DE_PARA_CHEFF
(
	COD_PRODUTO_CHEFF
	,COD_PRODUTO
	,COD_RESTAURANTE
)
	SELECT DISTINCT
		F.fartcod
		,CB.COD_PRODUTO
		,RIGHT(F.eproc_cnpj ,3)
		--,fartdes
		--,F.fartcar
	FROM
		[187.33.3.7,1433].[Eproc_1024].[dbo].[FO_FAART] AS F
		LEFT JOIN bi.dbo.CAD_DE_PARA_CHEFF AS DEPARA
			on 1=1
			AND F.fartcod = DEPARA.COD_PRODUTO_CHEFF
			AND DEPARA.[COD_RESTAURANTE]=RIGHT(F.eproc_cnpj ,3)
		LEFT JOIN AX2009_INTEGRACAO.dbo.TAB_CODIGO_BARRA AS CB
			ON 1=1
			AND RIGHT('0000000000000'+F.fartcar,13) = RIGHT('0000000000000'+CB.COD_EAN,13)
	WHERE 1=1
		AND DEPARA.COD_PRODUTO IS NULL
		AND ISNULL(F.fartcar,'') <> ''
		
--SELECT * FROM bi.dbo.CAD_DE_PARA_CHEFF WHERE COD_PRODUTO_CHEFF = 04216 AND COD_RESTAURANTE = 102