	DECLARE @DATA_INI AS DATE = GETDATE()-7
	DECLARE @DATA_FIM AS DATE = GETDATE()-1
	DECLARE @QTD_DIAS AS INT = DATEDIFF(D,@DATA_INI,@DATA_FIM) + 1


	SELECT * FROM	
	(	
		SELECT
			VP.COD_LOJA
			,VP.COD_PRODUTO
			,CP.DESCRICAO AS NO_PRODUTO
			,CP.NO_DEPARTAMENTO
			,CP.NO_SECAO
			,CP.NO_GRUPO
			,BI.dbo.fn_FormataVlr_Excel(LP.VLR_VENDA) AS PV
			,BI.dbo.fn_FormataVlr_Excel(LP.VLR_OFERTA) AS PO
			,BI.dbo.fn_FormataVlr_Excel(SUM(VP.VALOR_TOTAL)/nullif(SUM(VP.QTDE_PRODUTO),0)) AS PV_PD
			,BI.dbo.fn_FormataVlr_Excel(EP.QTD_ESTOQUE) AS QTD_ESTOQUE
			,BI.dbo.fn_FormataVlr_Excel(SUM(VP.VALOR_TOTAL)/@QTD_DIAS) AS AVG_VLR_PD		
			,BI.dbo.fn_FormataVlr_Excel(SUM(VP.QTDE_PRODUTO)/@QTD_DIAS) AS AVG_QTD_PD
			,BI.dbo.fn_FormataVlr_Excel((EP.QTD_ESTOQUE*(SUM(VP.VALOR_TOTAL)/nullif(SUM(VP.QTDE_PRODUTO),0)))/(SUM(VP.VALOR_TOTAL)/@QTD_DIAS)) AS DPD
			,LP.FORA_LINHA
		FROM
			BI.dbo.BI_LINHA_PRODUTOS AS LP
			INNER JOIN BI.dbo.BI_CAD_PRODUTO AS CP
				ON LP.COD_PRODUTO = CP.COD_PRODUTO
			LEFT JOIN BI.DBO.BI_VENDA_PRODUTO AS VP
				ON 1=1
				AND LP.COD_LOJA = VP.COD_LOJA
				AND LP.COD_PRODUTO = VP.COD_PRODUTO
			LEFT JOIN DW.dbo.ESTOQUE AS EP
				ON 1=1
				AND LP.COD_LOJA = EP.COD_LOJA
				AND LP.COD_PRODUTO = EP.COD_PRODUTO
				AND CONVERT(DATE,EP.DATA) = CONVERT(DATE,GETDATE())			
		WHERE 1=1
			AND CONVERT(DATE,VP.DATA) BETWEEN CONVERT(DATE,@DATA_INI) AND CONVERT(DATE,@DATA_FIM)
			AND VP.COD_LOJA = 29
			AND LP.VLR_OFERTA IS NOT NULL
		GROUP BY
			VP.COD_LOJA
			,VP.COD_PRODUTO
			,CP.DESCRICAO
			,CP.NO_DEPARTAMENTO
			,CP.NO_SECAO
			,CP.NO_GRUPO
			,LP.VLR_VENDA
			,LP.VLR_OFERTA
			,EP.QTD_ESTOQUE
			,LP.FORA_LINHA
	) AS TAB_DPD
	LEFT JOIN
	(
		SELECT
			CP.COD_PRODUTO
			,isnull((SELECT VLR_METADADO FROM CADASTRO_CAD_PRODUTO_METADADOS TPM WHERE TPM.COD_PRODUTO = CP.COD_PRODUTO AND TPM.COD_METADADO = 4),0) AS MTD_IMP_PROP
			,isnull((SELECT VLR_METADADO FROM CADASTRO_CAD_PRODUTO_METADADOS TPM WHERE TPM.COD_PRODUTO = CP.COD_PRODUTO AND TPM.COD_METADADO = 3),0) AS MTD_IMP		
		FROM
			BI_CAD_PRODUTO AS CP
		WHERE 1=1
	) AS TAB_METADADO
	ON TAB_DPD.COD_PRODUTO = TAB_METADADO.COD_PRODUTO		
		
	ORDER BY
		NO_DEPARTAMENTO
		,NO_SECAO
		,NO_GRUPO
		,AVG_VLR_PD DESC
		,FORA_LINHA
		
	/*
	SELECT
		COD_LOJA
		,COD_PRODUTO
		,QTD_ESTOQUE
	FROM
		DW.dbo.ESTOQUE
	WHERE 1=1
		AND COD_LOJA = 29
		AND CONVERT(DATE,DATA) = CONVERT(DATE,GETDATE())
	*/