SELECT
*
FROM
	BI.dbo.BI_LINHA_PRODUTOS AS LP
	INNER JOIN BI.dbo.BI_CAD_PRODUTO AS CP
		ON LP.COD_PRODUTO = CP.COD_PRODUTO
	LEFT JOIN BI.dbo.VW_ESTOQUE_ATUAL AS EP
		ON 1=1
		AND LP.COD_LOJA = EP.COD_LOJA
		AND LP.COD_PRODUTO = EP.COD_PRODUTO
WHERE 1=1
	AND LP.COD_LOJA = 29
	AND LP.COD_DEPARTAMENTO = 2
	AND LP.COD_SECAO = 27
	AND ISNULL(EP.QTD_ESTOQUE,0) = 0
	
	
	
SELECT 
	[cod_chef],[DESCRICAO],[ATIVO],[TIPO_PRODUTO]
	,[SITUACAO_TRIBUTARIA],[GRUPO_PRODUTO],[PRECO]
	,[UNIDADE],[ALIQUOTA],[RESTAURANTE],CC.COD_PRODUTO
	,EAN
FROM
	[BI].[dbo].[VW_PRODUTOS_CHEFFSOLUTION] AS PC
	LEFT JOIN dbo.CAD_DE_PARA_CHEFF AS CC
		ON 1=1
		AND CC.[COD_PRODUTO_CHEFF]*1=PC.cod_chef
		AND CC.[COD_RESTAURANTE]=PC.[RESTAURANTE]
WHERE 1=1
AND CC.COD_PRODUTO IS NULL
