DECLARE @TAB_EMB_COMPRA AS TABLE
(
	COD_LOJA INT
	,COD_PRODUTO INT
	,COD_FORNECEDOR INT
	,QTD_EMBALAGEM_COMPRA NUMERIC(18,2)
)

INSERT INTO @TAB_EMB_COMPRA
	SELECT
		COD_LOJA
		,COD_PRODUTO
		,COD_FORNECEDOR
		,QTD_EMBALAGEM_COMPRA
	FROM
		[192.168.0.6].ZEUS_RTG.DBO.TAB_PRODUTO_FORNECEDOR
	WHERE 1=1
		AND COD_LOJA = 29
		
SELECT
	LP.COD_LOJA
	,LP.COD_PRODUTO
	,CP.DESCRICAO AS NO_PRODUTO
	,CP.NO_DEPARTAMENTO
	,CP.NO_SECAO
	,CP.NO_GRUPO
	,BI.dbo.fn_FormataVlr_Excel(LP.VLR_VENDA) AS PV
	,BI.dbo.fn_FormataVlr_Excel(LP.VLR_OFERTA) AS PO
	,LP.FORA_LINHA
	,CP.COD_FORNECEDOR
	,CF.DESCRICAO AS NO_FORNECEDOR
	,BI.dbo.fn_FormataVlr_Excel(EMB.QTD_EMBALAGEM_COMPRA) AS QTD_EMBALAGEM_COMPRA
	,isnull((SELECT VLR_METADADO FROM CADASTRO_CAD_PRODUTO_METADADOS TPM WHERE TPM.COD_PRODUTO = CP.COD_PRODUTO AND TPM.COD_METADADO = 4),0) AS MTD_IMP_PROP
	,isnull((SELECT VLR_METADADO FROM CADASTRO_CAD_PRODUTO_METADADOS TPM WHERE TPM.COD_PRODUTO = CP.COD_PRODUTO AND TPM.COD_METADADO = 3),0) AS MTD_IMP		
FROM
	BI.dbo.BI_LINHA_PRODUTOS AS LP
	INNER JOIN BI.dbo.BI_CAD_PRODUTO AS CP
		ON LP.COD_PRODUTO = CP.COD_PRODUTO
	LEFT JOIN BI.dbo.COMPRAS_CAD_COMPRADOR AS CC
		ON CP.COD_USUARIO = CC.COD_USUARIO
	LEFT JOIN BI.dbo.BI_CAD_FORNECEDOR AS CF
		ON CP.COD_FORNECEDOR = CF.COD_FORNECEDOR
	LEFT JOIN @TAB_EMB_COMPRA AS EMB
		ON 1=1
		AND LP.COD_LOJA = EMB.COD_LOJA
		AND LP.COD_PRODUTO = EMB.COD_PRODUTO
		AND CP.COD_FORNECEDOR = EMB.COD_FORNECEDOR
WHERE 1=1
	AND LP.COD_LOJA = 29