DECLARE @TAB_VENDA_EAT AS TABLE
(
	COD_PRODUTO INT
)

INSERT INTO @TAB_VENDA_EAT
SELECT DISTINCT
	VP.COD_PRODUTO
	--,CP.DESCRICAO AS NO_PRODUTO
FROM
	BI.dbo.BI_VENDA_PRODUTO AS VP
	INNER JOIN BI.dbo.BI_CAD_PRODUTO AS CP
		ON VP.COD_PRODUTO = CP.COD_PRODUTO
	--INNER JOIN BI.dbo.BI_LINHA_PRODUTOS AS LP
	--	ON 1=1
	--	AND VP.COD_LOJA = LP.COD_LOJA
	--	AND VP.COD_PRODUTO = LP.COD_PRODUTO
WHERE 1=1
	AND CONVERT(DATE,DATA) BETWEEN CONVERT(DATE,GETDATE()-30) AND CONVERT(DATE,GETDATE()-1)
	AND CP.COD_DEPARTAMENTO = 2
	AND CP.COD_SECAO = 27
	AND VP.COD_LOJA = 29

EXCEPT

SELECT DISTINCT
	VP.COD_PRODUTO
	--,CP.DESCRICAO AS NO_PRODUTO
FROM
	BI.dbo.BI_VENDA_PRODUTO AS VP
	INNER JOIN BI.dbo.BI_CAD_PRODUTO AS CP
		ON VP.COD_PRODUTO = CP.COD_PRODUTO
	--INNER JOIN BI.dbo.BI_LINHA_PRODUTOS AS LP
	--	ON 1=1
	--	AND VP.COD_LOJA = LP.COD_LOJA
	--	AND VP.COD_PRODUTO = LP.COD_PRODUTO
WHERE 1=1
	AND CONVERT(DATE,DATA) BETWEEN CONVERT(DATE,GETDATE()-30) AND CONVERT(DATE,GETDATE()-1)
	AND CP.COD_DEPARTAMENTO = 2
	AND CP.COD_SECAO = 27
	AND VP.COD_LOJA = 33
	


SELECT
	VP.COD_PRODUTO
	,CP.DESCRICAO AS NO_PRODUTO
	,SUM(VALOR_TOTAL) AS VLR_TOTAL_U30D
	,SUM(QTDE_PRODUTO) AS QTD_TOTAL_U30D
FROM
	BI.dbo.BI_VENDA_PRODUTO AS VP
	INNER JOIN BI.dbo.BI_CAD_PRODUTO AS CP
		ON VP.COD_PRODUTO = CP.COD_PRODUTO
	INNER JOIN @TAB_VENDA_EAT AS T
		ON 1=1
		AND VP.COD_PRODUTO = T.COD_PRODUTO
WHERE 1=1
	AND CONVERT(DATE,DATA) BETWEEN CONVERT(DATE,GETDATE()-30) AND CONVERT(DATE,GETDATE()-1)
	AND VP.COD_LOJA = 29
GROUP BY
	VP.COD_PRODUTO
	,CP.DESCRICAO
ORDER BY
	SUM(QTDE_PRODUTO) DESC 