SELECT-- top 10
	L.NO_LOJA
	,S.MES_454 AS [MONTH]
	,S.SEMANA_454 AS WEEK
	,DATEPART(DW,VC.DATA) AS WEED_DAY
	,BI.dbo.fn_FormataVlr_Excel(sum(VC.VALOR_TOTAL)) AS CUPOM_SALES
	,BI.dbo.fn_FormataVlr_Excel(sum(VC.QTDE_CUPOM)) AS CUPOM_TICKETS
FROM
	BI.dbo.BI_VENDA_CUPOM AS VC
	INNER JOIN BI.dbo.BI_CAD_LOJA2 AS L
		ON VC.COD_LOJA = L.COD_LOJA
	INNER JOIN BI.dbo.BI_CAD_SEMANA AS S
		ON VC.DATA = S.DATA
WHERE 1=1
	AND VC.COD_LOJA IN (29,33)
	AND CONVERT(DATE,VC.DATA) BETWEEN CONVERT(DATE,'20150601') AND CONVERT(DATE,'20151129') 
GROUP BY
	L.NO_LOJA
	,S.MES_454
	,S.SEMANA_454
	,DATEPART(DW,VC.DATA)


SELECT-- top 10
	L.NO_LOJA
	,CD.PNP
	,(CASE
		WHEN VD.COD_DEPARTAMENTO IN (3,10,9) THEN 'GROCERY'
		WHEN VD.COD_DEPARTAMENTO IN (2) THEN 'WINE'
		WHEN VD.COD_DEPARTAMENTO IN (19) THEN 'HOUSEWARES/BOOKS'
		WHEN VD.COD_DEPARTAMENTO IN (12,13) THEN 'COSMETICS'
		WHEN VD.COD_DEPARTAMENTO IN (1) THEN 'SALUMI/FORMAGGI'
		WHEN VD.COD_DEPARTAMENTO IN (4) THEN 'FRUITS&VEGETABLES'
		WHEN VD.COD_DEPARTAMENTO IN (5) THEN 'MEAT'
		WHEN VD.COD_DEPARTAMENTO IN (6) THEN 'BAKERY'
		WHEN VD.COD_DEPARTAMENTO IN (21) THEN 'FISH'
		WHEN VD.COD_DEPARTAMENTO IN (8) THEN 'FRESH PASTA/ROTISSERIE'
		WHEN VD.COD_DEPARTAMENTO IN (16) THEN 'RESTAURANT'
		ELSE 'OTHERS'
	END) AS EAT_DEP
	,S.MES_454 AS [MONTH]
	,S.SEMANA_454 AS WEEK
	,DATEPART(DW,VD.DATA) AS WEED_DAY
	,BI.dbo.fn_FormataVlr_Excel(sum(VD.VLR_VENDA)) AS DEP_SALES
	,BI.dbo.fn_FormataVlr_Excel(sum(VD.QTD_CUPOM_DEP)) AS DEP_TICKETS
FROM
	BI.dbo.BI_VENDA_DEPARTAMENTO AS VD
	INNER JOIN BI.dbo.BI_CAD_LOJA2 AS L
		ON VD.COD_LOJA = L.COD_LOJA
	INNER JOIN (SELECT DISTINCT COD_DEPARTAMENTO, PNP FROM BI.dbo.BI_CAD_PRODUTO) AS CD
		ON VD.COD_DEPARTAMENTO = CD.COD_DEPARTAMENTO
	INNER JOIN BI.dbo.BI_CAD_SEMANA AS S
		ON VD.DATA = S.DATA
WHERE 1=1
	AND VD.COD_LOJA IN (29,33)
	AND CONVERT(DATE,VD.DATA) BETWEEN CONVERT(DATE,'20150601') AND CONVERT(DATE,'20151129') 
GROUP BY
	L.NO_LOJA
	,CD.PNP
	,(CASE
		WHEN VD.COD_DEPARTAMENTO IN (3,10,9) THEN 'GROCERY'
		WHEN VD.COD_DEPARTAMENTO IN (2) THEN 'WINE'
		WHEN VD.COD_DEPARTAMENTO IN (19) THEN 'HOUSEWARES/BOOKS'
		WHEN VD.COD_DEPARTAMENTO IN (12,13) THEN 'COSMETICS'
		WHEN VD.COD_DEPARTAMENTO IN (1) THEN 'SALUMI/FORMAGGI'
		WHEN VD.COD_DEPARTAMENTO IN (4) THEN 'FRUITS&VEGETABLES'
		WHEN VD.COD_DEPARTAMENTO IN (5) THEN 'MEAT'
		WHEN VD.COD_DEPARTAMENTO IN (6) THEN 'BAKERY'
		WHEN VD.COD_DEPARTAMENTO IN (21) THEN 'FISH'
		WHEN VD.COD_DEPARTAMENTO IN (8) THEN 'FRESH PASTA/ROTISSERIE'
		WHEN VD.COD_DEPARTAMENTO IN (16) THEN 'RESTAURANT'
		ELSE 'OTHERS'
	END)
	,S.MES_454
	,S.SEMANA_454
	,DATEPART(DW,VD.DATA)
	
	--SELECT DATEPART(DW,GETDATE())
	
select
	L.NO_LOJA
	,(CASE
		WHEN LP.COD_DEPARTAMENTO IN (3,10,9) THEN 'GROCERY'
		WHEN LP.COD_DEPARTAMENTO IN (2) THEN 'WINE'
		WHEN LP.COD_DEPARTAMENTO IN (19) THEN 'HOUSEWARES/BOOKS'
		WHEN LP.COD_DEPARTAMENTO IN (12,13) THEN 'COSMETICS'
		WHEN LP.COD_DEPARTAMENTO IN (1) THEN 'SALUMI/FORMAGGI'
		WHEN LP.COD_DEPARTAMENTO IN (4) THEN 'FRUITS&VEGETABLES'
		WHEN LP.COD_DEPARTAMENTO IN (5) THEN 'MEAT'
		WHEN LP.COD_DEPARTAMENTO IN (6) THEN 'BAKERY'
		WHEN LP.COD_DEPARTAMENTO IN (21) THEN 'FISH'
		WHEN LP.COD_DEPARTAMENTO IN (8) THEN 'FRESH PASTA/ROTISSERIE'
		WHEN LP.COD_DEPARTAMENTO IN (16) THEN 'RESTAURANT'
		ELSE 'OTHERS'
	END) AS EAT_DEP
	,COUNT(DISTINCT COD_PRODUTO) AS PROD_COUNT
from
	BI_LINHA_PRODUTOS as lp
	inner join BI.dbo.BI_CAD_LOJA2 as l
		on lp.COD_LOJA = l.COD_LOJA
where 1=1
	and LP.COD_LOJA in (29)
	AND lp.FORA_LINHA = 'N'
GROUP BY
	L.NO_LOJA
	,(CASE
		WHEN LP.COD_DEPARTAMENTO IN (3,10,9) THEN 'GROCERY'
		WHEN LP.COD_DEPARTAMENTO IN (2) THEN 'WINE'
		WHEN LP.COD_DEPARTAMENTO IN (19) THEN 'HOUSEWARES/BOOKS'
		WHEN LP.COD_DEPARTAMENTO IN (12,13) THEN 'COSMETICS'
		WHEN LP.COD_DEPARTAMENTO IN (1) THEN 'SALUMI/FORMAGGI'
		WHEN LP.COD_DEPARTAMENTO IN (4) THEN 'FRUITS&VEGETABLES'
		WHEN LP.COD_DEPARTAMENTO IN (5) THEN 'MEAT'
		WHEN LP.COD_DEPARTAMENTO IN (6) THEN 'BAKERY'
		WHEN LP.COD_DEPARTAMENTO IN (21) THEN 'FISH'
		WHEN LP.COD_DEPARTAMENTO IN (8) THEN 'FRESH PASTA/ROTISSERIE'
		WHEN LP.COD_DEPARTAMENTO IN (16) THEN 'RESTAURANT'
		ELSE 'OTHERS'
	END)