
	SELECT
		L.NO_LOJA
		,ISNULL(R.TIPO_RESTAURANTE,'') AS TIPO_RESTAURANTE
		--,R.NO_RESTAURANTE
		,CONVERT(DATE,C.DATA) AS DATA
		,DATEPART(DW,C.DATA) AS WD
		,(CASE
			WHEN DATEPART(DW,C.DATA) = 1 THEN 'Dom'
			WHEN DATEPART(DW,C.DATA) = 2 THEN 'Seg'
			WHEN DATEPART(DW,C.DATA) = 3 THEN 'Ter'
			WHEN DATEPART(DW,C.DATA) = 4 THEN 'Qua'
			WHEN DATEPART(DW,C.DATA) = 5 THEN 'Qui'
			WHEN DATEPART(DW,C.DATA) = 6 THEN 'Sex'
			WHEN DATEPART(DW,C.DATA) = 7 THEN 'Sab'
		END) as WD_NAME
		,BI.dbo.fn_FormataVlr_Excel(SUM(C.VALOR_TOTAL)) AS VLR_TOTAL
		,BI.dbo.fn_FormataVlr_Excel(SUM(C.QTDE_CUPOM)) AS QTD_TOTAL
	FROM
		BI.DBO.BI_VENDA_CUPOM AS C
		INNER JOIN BI.dbo.BI_CAD_LOJA2 AS L
			ON C.COD_LOJA = L.COD_LOJA
		LEFT JOIN BI.dbo.BI_CAD_RESTAURANTE AS R
			ON 1=1
			AND C.COD_LOJA = R.COD_LOJA
			AND C.TIPO = R.COD_RESTAURANTE
	WHERE 1=1
		AND C.COD_LOJA IN (29,33)
		AND CONVERT(DATE,DATA) >= '2015-05-19'
		--AND CONVERT(DATE,DATA) between CONVERT(date,getdate()-29) and CONVERT(date,getdate()-1)
		--AND CONVERT(DATE,DATA) between CONVERT(date,getdate()-8) and CONVERT(date,getdate()-1)
		AND CONVERT(DATE,DATA) <> '2015-06-01'
	GROUP BY
		L.NO_LOJA
		,ISNULL(R.TIPO_RESTAURANTE,'')
		--,R.NO_RESTAURANTE
		,CONVERT(DATE,C.DATA)
		,DATEPART(DW,C.DATA)
	ORDER BY
		CONVERT(DATE,C.DATA)
		,L.NO_LOJA
