SELECT --TOP 10
	CONVERT(DATE,AE.DTA_AJUSTE) AS DATA
	,CP.COD_PRODUTO
	,CP.DESCRICAO AS NO_PRODUTO
	,CP.NO_DEPARTAMENTO
	,CP.NO_SECAO
	,CP.NO_GRUPO
	,BI.dbo.fn_FormataVlr_Excel(AE.QTD_AJUSTE) AS QTD_AJUSTE
	,BI.dbo.fn_FormataVlr_Excel(AE.VAL_CUSTO_REP) AS CUSTO_REP
FROM
	[192.168.0.6].[Zeus_rtg].[dbo].[TAB_AJUSTE_ESTOQUE] AS AE
	INNER JOIN BI.dbo.BI_CAD_PRODUTO AS CP
		ON AE.COD_PRODUTO = CP.COD_PRODUTO	
where 1=1
	AND COD_AJUSTE = 261
	AND CONVERT(DATE,AE.DTA_AJUSTE) BETWEEN CONVERT(DATE,'20150901') AND CONVERT(DATE,'20150930')
	
	
	
	--select * from [192.168.0.6].[Zeus_rtg].[dbo].[TAB_tipo_ajuste]