
SELECT
	VP.COD_LOJA
	,CP.NO_DEPARTAMENTO
	,CP.NO_SECAO
	,CP.NO_GRUPO
	,VP.COD_PRODUTO
	,CP.DESCRICAO AS NO_PRODUTO
	,CC.NO_COMPRADOR
	,BI.dbo.fn_FormataVlr_Excel(SUM(VP.VALOR_TOTAL)) AS VLR_TOTAL
	,BI.dbo.fn_FormataVlr_Excel(SUM(VP.QTDE_PRODUTO)) AS QTD_TOTAL	
FROM
	BI.DBO.BI_VENDA_PRODUTO AS VP
	INNER JOIN BI.dbo.BI_CAD_PRODUTO AS CP
		ON VP.COD_PRODUTO = CP.COD_PRODUTO
	LEFT JOIN BI.DBO.COMPRAS_CAD_COMPRADOR AS CC
		ON CP.COD_USUARIO = CC.COD_USUARIO
WHERE 1=1
	AND VP.COD_PRODUTO = CP.COD_PRODUTO
	AND VP.COD_LOJA = 29
	AND CONVERT(DATE,VP.DATA) BETWEEN CONVERT(DATE,'2015-05-19') AND CONVERT(DATE,GETDATE()-1)
GROUP BY
	VP.COD_LOJA
	,CP.NO_DEPARTAMENTO
	,CP.NO_SECAO
	,CP.NO_GRUPO	
	,VP.COD_PRODUTO
	,CP.DESCRICAO
	,CC.NO_COMPRADOR
ORDER BY
	VP.COD_LOJA
	,CP.NO_DEPARTAMENTO
	,CP.NO_SECAO
	,CP.NO_GRUPO
	,SUM(VP.VALOR_TOTAL) DESC
	
	
SELECT top 100
	VP.COD_LOJA
	,CP.NO_DEPARTAMENTO
	,CP.NO_SECAO
	,CP.NO_GRUPO
	,VP.COD_PRODUTO
	,CP.DESCRICAO AS NO_PRODUTO
	,CC.NO_COMPRADOR
	,BI.dbo.fn_FormataVlr_Excel(SUM(VP.VALOR_TOTAL)) AS VLR_TOTAL
	,BI.dbo.fn_FormataVlr_Excel(SUM(VP.QTDE_PRODUTO)) AS QTD_TOTAL	
FROM
	BI.DBO.BI_VENDA_PRODUTO AS VP
	INNER JOIN BI.dbo.BI_CAD_PRODUTO AS CP
		ON VP.COD_PRODUTO = CP.COD_PRODUTO
	LEFT JOIN BI.DBO.COMPRAS_CAD_COMPRADOR AS CC
		ON CP.COD_USUARIO = CC.COD_USUARIO
WHERE 1=1
	AND VP.COD_PRODUTO = CP.COD_PRODUTO
	AND VP.COD_LOJA = 29
	AND CONVERT(DATE,VP.DATA) BETWEEN CONVERT(DATE,'2015-05-19') AND CONVERT(DATE,GETDATE()-1)
GROUP BY
	VP.COD_LOJA
	,CP.NO_DEPARTAMENTO
	,CP.NO_SECAO
	,CP.NO_GRUPO	
	,VP.COD_PRODUTO
	,CP.DESCRICAO
	,CC.NO_COMPRADOR
ORDER BY
	SUM(VP.VALOR_TOTAL) DESC