SELECT --TOP 10
	CONVERT(DATE,VP.DATA) AS DATA
	,VP.COD_PRODUTO
	,CP.DESCRICAO AS NO_PRODUTO
	,CP.NO_DEPARTAMENTO
	,CP.NO_SECAO
	,CP.NO_GRUPO
	,BI.dbo.fn_FormataVlr_Excel(VP.VALOR_TOTAL) AS VLR_TOTAL
	,BI.dbo.fn_FormataVlr_Excel(VP.QTDE_PRODUTO) AS QTD_TOTAL
FROM
	BI.dbo.BI_VENDA_PRODUTO AS VP
	INNER JOIN BI.dbo.BI_CAD_PRODUTO AS CP
		ON VP.COD_PRODUTO = CP.COD_PRODUTO
WHERE 1=1
	AND VP.COD_LOJA = 33
	AND VP.TIPO_VENDA = 111
	AND CONVERT(DATE,VP.DATA) BETWEEN CONVERT(DATE,'20150901') AND CONVERT(DATE,'20150930')
	
ORDER BY
	CP.DESCRICAO
	,CONVERT(DATE,VP.DATA)