SET NOCOUNT ON;
DECLARE @OFFER AS TABLE
(
	[COD_LOJA] INT
	,[COD_PRODUTO] INT
	,[DTA_INI] DATE
	,[DTA_FIM] DATE
	,VC_MARCHE NUMERIC(8,3)
	,DESCR_VC_MARCHE VARCHAR(50)
)

INSERT INTO @OFFER
	SELECT
		[COD_LOJA]
		,[COD_PRODUTO]
		,[DTA_INI]
		,[DTA_FIM]
		,[VALOR] AS VC_MARCHE
		,DESCRICAO AS DESCR_VCMARCHE
	FROM [BI].[DBO].[BI_PRECO_VENDA]
	WHERE 1=1
		AND INATIVO IS NULL
		AND TIPO=2
		AND DTA_INI<=CONVERT(DATE,GETDATE())
		AND DTA_FIM>=CONVERT(DATE,GETDATE());

SELECT
	PV.[COD_LOJA] as [Loja]
	,CP.[COD_PRODUTO] as [PLU]
	,CP.DESCRICAO as [Produto]
	,[VLR_VENDA] AS [Vlr Venda]
	,(CASE 
		WHEN [VLR_OFERTA] IS NOT NULL THEN [VLR_OFERTA]
		WHEN BPV.VC_MARCHE IS NOT NULL THEN BPV.VC_MARCHE
	END) AS [Vlr Oferta]
	,(CASE 
		WHEN [VLR_OFERTA] IS NOT NULL THEN PO.[DTA_INI]
		WHEN BPV.VC_MARCHE IS NOT NULL THEN BPV.[DTA_INI]
	END) AS [Promocao]
	,(CASE 
		WHEN [VLR_OFERTA] IS NOT NULL THEN PO.[DTA_INI]
		WHEN BPV.VC_MARCHE IS NOT NULL THEN BPV.[DTA_INI]
	END) AS [Data Inicio]
	,(CASE 
		WHEN [VLR_OFERTA] IS NOT NULL THEN PO.[DTA_FIM]
		WHEN BPV.VC_MARCHE IS NOT NULL THEN BPV.[DTA_FIM]
	END) AS [Data Fim]


	,isnull(PO.[DESCRICAO],'') AS [Promocao]
	,isnull (BPV.DESCR_VC_MARCHE,'') [Vc Marche]

	,isnull (CP.COD_PRODUTO_SIMILAR,'') [codSimilar]
	,AX_PROD.PROIBIDO_COMPRA [Proibe Compra]
FROM
	[BI].[DBO].[BI_CAD_PRODUTO] AS CP LEFT JOIN [BI].[DBO].[VW_PRECOS_VENDA_ATIVOS] AS PV ON (PV.COD_PRODUTO = CP.COD_PRODUTO)  
		LEFT JOIN BI.DBO.VW_PRECOS_OFERTA_ATIVOS AS PO ON (PV.COD_LOJA=PO.COD_LOJA AND PV.COD_PRODUTO=PO.COD_PRODUTO)
			LEFT JOIN @OFFER AS BPV ON (PV.COD_LOJA=BPV.COD_LOJA AND PV.COD_PRODUTO=BPV.COD_PRODUTO)
				LEFT JOIN AX2009_INTEGRACAO.DBO.VW_MARCHE_PRODUTO_SITUACAO AS AX_PROD ON (CP.COD_PRODUTO = AX_PROD.COD_PRODUTO AND PV.[COD_LOJA]=AX_PROD.COD_LOJA)
WHERE 1=1
	AND CP.COD_PRODUTO = 549110
	AND ([VLR_OFERTA] IS NOT NULL OR BPV.VC_MARCHE IS NOT NULL)
ORDER BY
	CP.[COD_PRODUTO]