DECLARE @YEAR AS INT = 2015
DECLARE @WEEK AS INT = 29


-- -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
--
-- -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
	DECLARE @DATA_PESQUISA AS DATE

	SELECT 
		@DATA_PESQUISA = MAX(EXT.DATA_PESQUISA)
	FROM
		[BI].[DBO].[BI_PRECO_PESQUISA] AS EXT
	WHERE 1 = 1
		AND LEFT(BI.dbo.ISO_WEEK(EXT.DATA_PESQUISA),4) = @YEAR
		AND BI.DBO.F_ISO_WEEK_OF_YEAR(EXT.DATA_PESQUISA) = @WEEK

	DECLARE @PROD_NIELSEN AS TABLE
	(
		COD_PRODUTO INT
		,SEMANA INT
	)

	INSERT INTO @PROD_NIELSEN
	SELECT DISTINCT
		EXT.COD_PRODUTO
		,BI.DBO.F_ISO_WEEK_OF_YEAR(EXT.DATA_PESQUISA)	
	FROM
		[BI].[DBO].[BI_PRECO_PESQUISA] AS EXT
	WHERE 1 = 1
		AND EXT.COD_PRODUTO IS NOT NULL
		AND EXT.VLR_VENDA_MARCHE_POND IS NULL
		AND LEFT(BI.dbo.ISO_WEEK(EXT.DATA_PESQUISA),4) = @YEAR
		AND BI.DBO.F_ISO_WEEK_OF_YEAR(EXT.DATA_PESQUISA) = @WEEK
		--AND EXT.COD_PRODUTO = 124690

	DECLARE @PROD_NIELSEN_MARCHE AS TABLE
	(
		COD_PRODUTO INT
		,PRECO_PONDERADO NUMERIC(8,2)
	)

	INSERT INTO @PROD_NIELSEN_MARCHE
	SELECT
		VP.COD_PRODUTO
		,SUM(VP.VALOR_TOTAL)/SUM(VP.QTDE_PRODUTO)
	FROM
		[BI].[DBO].[BI_VENDA_PRODUTO] AS VP
		INNER JOIN @PROD_NIELSEN AS PN
			ON 1 = 1
			AND VP.COD_PRODUTO = PN.COD_PRODUTO
			AND BI.DBO.F_ISO_WEEK_OF_YEAR(VP.DATA) = PN.SEMANA
	WHERE 1 = 1
		AND VP.COD_LOJA <> 7
	GROUP BY
		VP.COD_PRODUTO

	UPDATE EXT
	SET
		EXT.VLR_VENDA_MARCHE_POND = T.PRECO_PONDERADO
	FROM
		[BI].[DBO].[BI_PRECO_PESQUISA] AS EXT
		INNER JOIN @PROD_NIELSEN_MARCHE AS T
			ON 1=1
			AND EXT.COD_PRODUTO = T.COD_PRODUTO
			AND CONVERT(DATE,EXT.DATA_PESQUISA) = @DATA_PESQUISA
	WHERE 1 = 1
		AND EXT.VLR_VENDA_MARCHE_POND IS NULL

	--SELECT * FROM [BI].[DBO].[BI_PRECO_PESQUISA] WHERE CONVERT(DATE,DATA_PESQUISA) = '20140808'

-- -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
--
-- -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
	DECLARE @DATA_EXTRACAO AS DATE

	SELECT 
		@DATA_EXTRACAO = MAX(EXT.DATA_EXTRACAO)
	FROM
		[BI].[DBO].[BI_PRECOS_TERCEIROS] AS EXT
	WHERE 1 = 1
		AND LEFT(BI.dbo.ISO_WEEK(EXT.DATA_EXTRACAO),4) = @YEAR
		AND BI.DBO.F_ISO_WEEK_OF_YEAR(EXT.DATA_EXTRACAO) = @WEEK

	DECLARE @PROD_SITE AS TABLE
	(
		COD_PRODUTO INT
		,SEMANA INT
	)

	INSERT INTO @PROD_SITE
	SELECT DISTINCT
		EXT.COD_PRODUTO
		,BI.DBO.F_ISO_WEEK_OF_YEAR(EXT.DATA_EXTRACAO)	
	FROM
		[BI].[DBO].[BI_PRECOS_TERCEIROS] AS EXT
	WHERE 1 = 1
		AND EXT.COD_PRODUTO IS NOT NULL
		AND EXT.VLR_VENDA_MARCHE_POND IS NULL
		AND LEFT(BI.dbo.ISO_WEEK(EXT.DATA_EXTRACAO),4) = @YEAR
		AND BI.DBO.F_ISO_WEEK_OF_YEAR(EXT.DATA_EXTRACAO) = @WEEK
		--AND EXT.COD_PRODUTO = 124690

	DECLARE @PROD_SITE_MARCHE AS TABLE
	(
		COD_PRODUTO INT
		,PRECO_PONDERADO NUMERIC(8,2)
	)

	INSERT INTO @PROD_SITE_MARCHE
	SELECT
		VP.COD_PRODUTO
		,SUM(VP.VALOR_TOTAL)/SUM(VP.QTDE_PRODUTO)
	FROM
		[BI].[DBO].[BI_VENDA_PRODUTO] AS VP
		INNER JOIN @PROD_SITE AS PN
			ON 1 = 1
			AND VP.COD_PRODUTO = PN.COD_PRODUTO
			AND BI.DBO.F_ISO_WEEK_OF_YEAR(VP.DATA) = PN.SEMANA
	WHERE 1 = 1
		AND VP.COD_LOJA <> 7
	GROUP BY
		VP.COD_PRODUTO

	UPDATE EXT
	SET
		EXT.VLR_VENDA_MARCHE_POND = T.PRECO_PONDERADO
	FROM
		[BI].[DBO].[BI_PRECOS_TERCEIROS] AS EXT
		INNER JOIN @PROD_SITE_MARCHE AS T
			ON 1=1
			AND EXT.COD_PRODUTO = T.COD_PRODUTO
			AND CONVERT(DATE,EXT.DATA_EXTRACAO) = @DATA_EXTRACAO
	WHERE 1 = 1
		AND EXT.VLR_VENDA_MARCHE_POND IS NULL