-- -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
--
-- -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
UPDATE EXT
SET
	EXT.COD_PRODUTO = P.COD_PRODUTO_MARCHE
FROM
	[BI].[DBO].[BI_PRECOS_TERCEIROS] AS EXT INNER JOIN [BI].[DBO].[BI_CAD_PRODUTO_TERCEIROS] AS P ON (EXT.COD_PRODUTO_TERCEIRO = P.COD_PRODUTO_TERCEIRO)
WHERE 1 = 1
	AND EXT.COD_PRODUTO IS NULL
	AND P.COD_PRODUTO_MARCHE IS NOT NULL
	
-- -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
--
-- -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
DECLARE @TAB_PRECOS_TERCEIROS AS TABLE
(
	COD_PRODUTO INT
	,DATA_EXTRACAO DATE
	,VLR_VENDA_MARCHE NUMERIC(18,2)
)

INSERT INTO @TAB_PRECOS_TERCEIROS
SELECT
	EXT.COD_PRODUTO
	,EXT.DATA_EXTRACAO
	,AVG(PV.VALOR) AS VLR_VENDA_MARCHE
FROM
	[BI].[DBO].[BI_PRECOS_TERCEIROS] AS EXT
	INNER JOIN [BI].[DBO].[BI_PRECO_VENDA] AS PV
		ON 1=1
		AND EXT.COD_PRODUTO = PV.COD_PRODUTO
		--AND CONVERT(DATE,PV.DTA_INI) <= CONVERT(DATE,EXT.DATA_EXTRACAO)
		AND CONVERT(DATE,PV.DTA_INI) = (SELECT MAX(TPV.DTA_INI) FROM [BI].[DBO].[BI_PRECO_VENDA] AS TPV WHERE TPV.TIPO = 0 AND TPV.COD_LOJA <> 7 AND TPV.COD_PRODUTO = PV.COD_PRODUTO AND CONVERT(DATE,TPV.DTA_INI) <= CONVERT(DATE,EXT.DATA_EXTRACAO) AND CONVERT(DATE,TPV.DTA_FIM) >= CONVERT(DATE,EXT.DATA_EXTRACAO))
		AND CONVERT(DATE,PV.DTA_FIM) >= CONVERT(DATE,EXT.DATA_EXTRACAO)
		AND PV.TIPO = 0
		AND PV.COD_LOJA <> 7
WHERE 1 = 1
	AND EXT.COD_PRODUTO IS NOT NULL
	AND EXT.VLR_VENDA_MARCHE IS NULL
	--AND EXT.COD_PRODUTO = 521680
GROUP BY
	EXT.COD_PRODUTO
	,EXT.DATA_EXTRACAO

UPDATE EXT
SET
	EXT.VLR_VENDA_MARCHE = T.VLR_VENDA_MARCHE
FROM
	[BI_PRECOS_TERCEIROS] AS EXT
	INNER JOIN @TAB_PRECOS_TERCEIROS AS T
		ON 1=1
		AND EXT.COD_PRODUTO = T.COD_PRODUTO
		AND CONVERT(DATE,EXT.DATA_EXTRACAO) = CONVERT(DATE,T.DATA_EXTRACAO)


--SELECT * FROM [BI_PRECOS_TERCEIROS] WHERE COD_PRODUTO = 187800 ORDER BY DATA_EXTRACAO DESC

-- -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
--
-- -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
DECLARE @TAB_PRECOS_PESQUISA AS TABLE
(
	COD_PRODUTO INT
	,DATA_EXTRACAO DATE
	,VLR_VENDA_MARCHE NUMERIC(18,2)
)

INSERT INTO @TAB_PRECOS_PESQUISA
SELECT
	EXT.COD_PRODUTO
	,EXT.DATA_PESQUISA
	,AVG(PV.VALOR) AS VLR_VENDA_MARCHE
FROM
	[BI].[DBO].[BI_PRECO_PESQUISA] AS EXT
	INNER JOIN [BI].[DBO].[BI_PRECO_VENDA] AS PV
		ON 1=1
		AND EXT.COD_PRODUTO = PV.COD_PRODUTO
		--AND CONVERT(DATE,PV.DTA_INI) <= CONVERT(DATE,EXT.DATA_EXTRACAO)
		AND CONVERT(DATE,PV.DTA_INI) = (SELECT MAX(TPV.DTA_INI) FROM [BI].[DBO].[BI_PRECO_VENDA] AS TPV WHERE TPV.TIPO = 0 AND TPV.COD_LOJA <> 7 AND TPV.COD_PRODUTO = PV.COD_PRODUTO AND CONVERT(DATE,TPV.DTA_INI) <= CONVERT(DATE,EXT.DATA_PESQUISA) AND CONVERT(DATE,TPV.DTA_FIM) >= CONVERT(DATE,EXT.DATA_PESQUISA))
		AND CONVERT(DATE,PV.DTA_FIM) >= CONVERT(DATE,EXT.DATA_PESQUISA)
		AND PV.TIPO = 0
		AND PV.COD_LOJA <> 7
WHERE 1 = 1
	AND EXT.COD_PRODUTO IS NOT NULL
	AND EXT.VLR_VENDA_MARCHE IS NULL
	--AND EXT.COD_PRODUTO = 521680
GROUP BY
	EXT.COD_PRODUTO
	,EXT.DATA_PESQUISA

UPDATE EXT
SET
	EXT.VLR_VENDA_MARCHE = T.VLR_VENDA_MARCHE
FROM
	[BI].[DBO].[BI_PRECO_PESQUISA] AS EXT
	INNER JOIN @TAB_PRECOS_PESQUISA AS T
		ON 1=1
		AND EXT.COD_PRODUTO = T.COD_PRODUTO
		AND CONVERT(DATE,EXT.DATA_PESQUISA) = CONVERT(DATE,T.DATA_EXTRACAO)


--SELECT * FROM [BI_PRECO_PESQUISA] WHERE COD_PRODUTO IS NOT NULL AND COD_PRODUTO = 187800 ORDER BY DATA_PESQUISA DESC


--UPDATE [BI_PRECOS_TERCEIROS] SET VLR_VENDA_MARCHE = NULL
--UPDATE [BI_PRECO_PESQUISA] SET VLR_VENDA_MARCHE = NULL


/*

SELECT
	COD_PRODUTO_MARCHE AS COD_PRODUTO
	,EXT.[COD_TERCEIRO]
	,EXT.[COD_PRODUTO_TERCEIRO]
	,[VLR_PRODUTO] AS VLR_VENDA_3
	,[PROMOCAO] AS PROMO_3
	,EXT.[NO_PRODUTO_TERCEIRO]
	,[DATA_EXTRACAO]
	,P.[ANALIZADO]
	,'Site PA' AS TIPO_PESQUISA
FROM
	[BI].[DBO].[BI_PRECOS_TERCEIROS] AS EXT INNER JOIN [BI].[DBO].[BI_CAD_PRODUTO_TERCEIROS] AS P ON (EXT.COD_PRODUTO_TERCEIRO = P.COD_PRODUTO_TERCEIRO)
		INNER JOIN [BI].[DBO].BI_CAD_PRODUTO AS PM ON (PM.COD_PRODUTO = P.COD_PRODUTO_MARCHE)
		LEFT JOIN [BI].[DBO].COMPRAS_CAD_COMPRADOR AS CC ON (PM.COD_USUARIO = CC.COD_USUARIO)
		LEFT JOIN [BI].[DBO].BI_CAD_FORNECEDOR AS FORN ON (PM.COD_FORNECEDOR = FORN.COD_FORNECEDOR)
WHERE 1=1
	AND P.COD_PRODUTO_MARCHE IS NOT NULL
	AND CONVERT(DATE, [DATA_EXTRACAO]) > CONVERT(DATE,GETDATE()-60)

union all

SELECT 
	N.COD_PRODUTO AS COD_PRODUTO
	,null
	,null
	,AVG(N.VLR_PRECO_VENDA) AS VLR_VENDA_NIELSEN
	,AVG(N.VLR_PRECO_OFERTA) AS PROMO_NIELSEN
	,null
	,N.DATA_PESQUISA as [DATA_EXTRACAO]
	,null
	,'Nielsen' AS TIPO_PESQUISA
FROM
	[BI].[DBO].[BI_PRECO_PESQUISA] AS N
WHERE 1=1
	AND N.COD_PRODUTO IS NOT NULL
	--AND N.NO_USUARIO =  'NIELSEN'
	AND CONVERT(DATE, N.DATA_PESQUISA) > CONVERT(DATE,GETDATE()-60)
GROUP BY
	N.COD_PRODUTO
	,N.DATA_PESQUISA;
	
*/