DECLARE @TAB_CONCORRENTES AS TABLE
(
	COD_PRODUTO INT
	,VLR_VENDA_PA NUMERIC(12,2)
	,DATA_EXTRACAO DATE
)
INSERT INTO @TAB_CONCORRENTES
	SELECT
		COD_PRODUTO_MARCHE AS COD_PRODUTO
		,[VLR_PRODUTO] AS VLR_VENDA_PA    
		,(SELECT MAX(DATA_EXTRACAO)  FROM [BI].[DBO].[BI_PRECOS_TERCEIROS] AS T WHERE T.COD_PRODUTO_TERCEIRO=EXT.COD_PRODUTO_TERCEIRO) AS DATA_EXTRACAO    
	FROM
		[BI].[DBO].[BI_PRECOS_TERCEIROS] AS EXT
		INNER JOIN [BI].[DBO].[BI_CAD_PRODUTO_TERCEIROS] AS P    
			ON EXT.COD_PRODUTO_TERCEIRO = P.COD_PRODUTO_TERCEIRO
	WHERE 1=1
		AND P.COD_PRODUTO_MARCHE IS NOT NULL    
		AND EXT.DATA_EXTRACAO=(SELECT MAX(DATA_EXTRACAO)  FROM [BI].[DBO].[BI_PRECOS_TERCEIROS] AS T WHERE T.COD_PRODUTO_TERCEIRO=EXT.COD_PRODUTO_TERCEIRO) 

SELECT
	CP.NO_DEPARTAMENTO
	,CP.[NO_SECAO]
	,CP.NO_GRUPO
	,PL.[COD_LOJA]
	,PL.[COD_PRODUTO]
	,CP.[COD_PRODUTO_SIMILAR]
	,CP.[DESCRICAO]     
	,CP.[COD_FORNECEDOR] AS COD_FORN_PRIN
	,PF.[VAL_CUSTO_EMBALAGEM]
	,PF.[QTD_EMBALAGEM_COMPRA]
	, '' AS CUSTO
	,[IPI_VLR]
	,[IPI_PERC]
	,'' AS IPICALC
	,IP.[PIS] + IP.[COFINS] AS PIS_COFINS   
	,IP.[CST_ICMS_ENTRADA]
	,IP.[ALIQUOTA_ICMS_ENTRADA]
	,IP.[REDUCAO_ICMS_ENTRADA]
	,IP.[IVA]
	,IP.[PAUTA_GOV]
	,IP.[ALIQUOTA_ICMS_SAIDA]
	,IP.[REDUCAO_ICMS_SAIDA]    
	,CREDITA_PISCOFINS*1
	,PL.[VLR_MRGREF]
	,'' AS VLRVENDA
	,'' AS ICMSSAIDA
	,'' AS ICMSENTRADA
	,'' AS LB
	,'' AS MRGREAL
	,PVA.[VLR_VENDA]
	,'' AS PRECOOFERTA
	,'' AS PRECOVCMARCHE
	,'' AS LB_ATUAL
	,'' AS MRG_ATUAL      
	,PV_CC.VLR_VENDA_PA
	,PV_CC.DATA_EXTRACAO
FROM
	[BI].[DBO].[BI_LINHA_PRODUTOS] AS PL
	INNER JOIN [BI].[DBO].[BI_CAD_PRODUTO] AS CP    
		ON PL.COD_PRODUTO=CP.COD_PRODUTO
	LEFT JOIN [BI].[DBO].[BI_PRECO_IMPOSTOS] AS IP
		ON 1=1
		AND PL.COD_PRODUTO=IP.COD_PRODUTO    
		AND CP.COD_FORNECEDOR=IP.COD_FORNECEDOR
	LEFT JOIN [192.168.0.6].[ZEUS_RTG].[DBO].[TAB_PRODUTO_FORNECEDOR] AS PF
		ON 1=1
		AND PF.COD_FORNECEDOR=CP.COD_FORNECEDOR      
		AND PF.COD_LOJA=PL.COD_LOJA
		AND PF.COD_PRODUTO=PL.COD_PRODUTO
	LEFT JOIN [BI].[DBO].[VW_PRECOS_VENDA_ATIVOS] AS PVA
		ON 1=1
		AND PVA.COD_PRODUTO=PL.COD_PRODUTO     
		AND PVA.COD_LOJA=PL.COD_LOJA
	LEFT JOIN @TAB_CONCORRENTES AS PV_CC   
		ON PV_CC.COD_PRODUTO=PL.COD_PRODUTO 
WHERE 1=1      
	AND CP.COD_PRODUTO IN  (688888)--& GETDATATOSQL & _
	AND PL.COD_LOJA IN  (1,2,3)--& GETDATATOSQLOJA