DECLARE @DATAINI DATE = '20140728'--'20140706'
DECLARE @DATAFIM DATE = '20140803'	

DECLARE @YEAR AS INT = 2015
DECLARE @WEEK AS INT = 7

-- --------------------------------------------------------------------------------------------------------------------------
-- VENDA PERIODO
-- --------------------------------------------------------------------------------------------------------------------------
DECLARE @TAB_VENDA AS TABLE
(
	ANO INT
	,SEMANA INT
	,VLR_VENDA NUMERIC(18,2)
)

INSERT INTO @TAB_VENDA
SELECT
	LEFT(dbo.ISO_WEEK(VP.DATA),4) as [Ano]
	,BI.DBO.F_ISO_WEEK_OF_YEAR(VP.DATA) as [Semana]
	,SUM(VALOR_TOTAL) AS [Vlr venda]
FROM
	BI.dbo.BI_VENDA_PRODUTO AS VP INNER JOIN BI.DBO.BI_CAD_PRODUTO AS P
		ON VP.COD_PRODUTO = P.COD_PRODUTO
WHERE 1 = 1
	--AND CONVERT(DATE,VP.DATA) BETWEEN @DATAINI AND @DATAFIM
	AND LEFT(BI.dbo.ISO_WEEK(VP.DATA),4) = @YEAR
	AND BI.DBO.F_ISO_WEEK_OF_YEAR(VP.DATA) = @WEEK
	AND P.COD_DEPARTAMENTO NOT IN (2,14,12,15,16,17)
GROUP BY
	LEFT(dbo.ISO_WEEK(VP.DATA),4) 
	,BI.DBO.F_ISO_WEEK_OF_YEAR(VP.DATA)

-- --------------------------------------------------------------------------------------------------------------------------
-- AJUSTES LOJA - SELECT * FROM [192.168.0.6].[Zeus_rtg].[dbo].[TAB_TIPO_AJUSTE] WHERE COD_AJUSTE IN (51,120,121,122,123)
-- --------------------------------------------------------------------------------------------------------------------------
DECLARE @TAB_AJUSTE_LOJA AS TABLE
(
	ANO INT
	,SEMANA INT
	,QTD_QUEBRA NUMERIC(18,2)
	,VLR_CUSTO_REP NUMERIC(18,2)
)

INSERT INTO @TAB_AJUSTE_LOJA
SELECT 
	LEFT(dbo.ISO_WEEK(M.DTA_AJUSTE),4) as [Ano]
	,BI.DBO.F_ISO_WEEK_OF_YEAR(M.DTA_AJUSTE) as [Semana]
	,SUM(-1*[QTD_AJUSTE]) AS [Qtd Prod Quebra]
	,SUM(-1*[QTD_AJUSTE]*[VAL_CUSTO_REP]) AS [Vlr Custo Rep]
FROM 
	[192.168.0.6].ZEUS_RTG.DBO.[TAB_AJUSTE_ESTOQUE] AS M
	INNER JOIN BI.DBO.BI_CAD_PRODUTO AS P
		ON M.COD_PRODUTO = P.COD_PRODUTO
WHERE 1=1
	--AND CONVERT(DATE,[DTA_AJUSTE]) BETWEEN @DATAINI AND @DATAFIM
	AND LEFT(BI.dbo.ISO_WEEK(DTA_AJUSTE),4) = @YEAR
	AND BI.DBO.F_ISO_WEEK_OF_YEAR(DTA_AJUSTE) <= @WEEK
	AND M.COD_AJUSTE IN (51,120,121,122,123)
	AND P.COD_DEPARTAMENTO NOT IN (2,14,12,15,16,17)
GROUP BY 
	LEFT(dbo.ISO_WEEK(M.DTA_AJUSTE),4)
	,BI.DBO.F_ISO_WEEK_OF_YEAR(M.DTA_AJUSTE)

SELECT
	A.ANO
	,A.SEMANA
	,BI.dbo.fn_FormataVlr_Excel(A.VLR_CUSTO_REP / V.VLR_VENDA) AS PERC_AJUSTE_LOJA
FROM
	@TAB_AJUSTE_LOJA AS A
	INNER JOIN @TAB_VENDA AS V
		ON A.ANO = V.ANO
		AND A.SEMANA = V.SEMANA
ORDER BY
	A.ANO
	,A.SEMANA

-- --------------------------------------------------------------------------------------------------------------------------
-- AJUSTES MATRIZ - SELECT * FROM [192.168.0.6].[Zeus_rtg].[dbo].[TAB_TIPO_AJUSTE] WHERE COD_AJUSTE IN (1,2,155)
-- --------------------------------------------------------------------------------------------------------------------------
DECLARE @TAB_AJUSTE_MATRIZ AS TABLE
(
	ANO INT
	,SEMANA INT
	,QTD_AJUSTE NUMERIC(18,2)
)

INSERT INTO @TAB_AJUSTE_MATRIZ
SELECT 
	LEFT(dbo.ISO_WEEK(M.DTA_AJUSTE),4) as [Ano]
	,BI.DBO.F_ISO_WEEK_OF_YEAR(M.DTA_AJUSTE) as [Semana]
	,COUNT(M.COD_PRODUTO)
FROM 
	[192.168.0.6].ZEUS_RTG.DBO.[TAB_AJUSTE_ESTOQUE] AS M
	INNER JOIN BI.DBO.BI_CAD_PRODUTO AS P
		ON P.COD_PRODUTO = M.COD_PRODUTO
WHERE 1=1
	--AND CONVERT(DATE,[DTA_AJUSTE]) BETWEEN @DATAINI AND @DATAFIM
	AND LEFT(BI.dbo.ISO_WEEK(DTA_AJUSTE),4) = @YEAR
	AND BI.DBO.F_ISO_WEEK_OF_YEAR(DTA_AJUSTE) <= @WEEK
	AND M.COD_AJUSTE IN (1,2,155)	
	AND P.COD_DEPARTAMENTO NOT IN (2,14,12,15,16,17)
GROUP BY 
	LEFT(dbo.ISO_WEEK(M.DTA_AJUSTE),4)
	,BI.DBO.F_ISO_WEEK_OF_YEAR(M.DTA_AJUSTE)

SELECT
	A.ANO
	,A.SEMANA
	,dbo.fn_FormataVlr_Excel(QTD_AJUSTE) as AJUSTES_MATRIZ
FROM
	@TAB_AJUSTE_MATRIZ AS A
	INNER JOIN @TAB_VENDA AS V
		ON A.ANO = V.ANO
		AND A.SEMANA = V.SEMANA
ORDER BY
	A.ANO
	,A.SEMANA