DECLARE @DATAINI DATE = '20140728'--'20140706'
DECLARE @DATAFIM DATE = '20140803'	

DECLARE @YEAR AS INT = 2015
DECLARE @WEEK AS INT = 7

DECLARE @TAB_DANFES AS TABLE
(
	NUM_DANFE VARCHAR(50)
	,DATA DATE
)

INSERT INTO @TAB_DANFES
SELECT DISTINCT
	 DAMFE
	 ,MAX(DATA)
FROM  [192.168.0.6].[INTRANET].[DBO].[TAB_RECEB_MERCADORIA] AS rec 
WHERE 1 = 1
	--AND CONVERT(DATE,DATA) BETWEEN @DATAINI AND @DATAFIM
	AND LEFT(BI.dbo.ISO_WEEK(DATA),4) = @YEAR
	AND BI.DBO.F_ISO_WEEK_OF_YEAR(DATA) = @WEEK
GROUP BY
	DAMFE

DECLARE @TAB_RECEBIMENTO AS TABLE
(
	ANO INT
	,SEMANA INT
	,QTD_ERRO NUMERIC(18,2)
	,QTD_TOTAL NUMERIC(18,2)
)
INSERT INTO @TAB_RECEBIMENTO
SELECT
	LEFT(BI.dbo.ISO_WEEK(D.DATA),4) as [Ano]
	,BI.DBO.F_ISO_WEEK_OF_YEAR(D.DATA) as [Semana]
	,SUM(CASE WHEN MENSAGEM IS NOT NULL THEN 1 ELSE 0 END) 
	,COUNT(DET.NUM_DANFE)
FROM
	CtrlNfe.dbo.NFE_DET AS DET
	INNER JOIN @TAB_DANFES AS D
		ON DET.NUM_DANFE COLLATE SQL_Latin1_General_CP1_CI_AS = D.NUM_DANFE
WHERE 1 = 1
GROUP BY
	LEFT(BI.dbo.ISO_WEEK(D.DATA),4)
	,BI.DBO.F_ISO_WEEK_OF_YEAR(D.DATA)
	
SELECT
	ANO
	,SEMANA
	--,QTD_ERRO
	--,QTD_TOTAL
	,dbo.fn_FormataVlr_Excel(QTD_ERRO / QTD_TOTAL) AS PERC
FROM
	@TAB_RECEBIMENTO
ORDER BY
	ANO
	,SEMANA
	
	
	
	
