-- ------------------------------------------------------------------------------------------------------------------------------------------------------
-- DPD
-- ------------------------------------------------------------------------------------------------------------------------------------------------------
DECLARE @DATAINI DATE = '20140728'--'20140706'
DECLARE @DATAFIM DATE = '20140803'	

DECLARE @YEAR AS INT = 2015
DECLARE @WEEK AS INT = 7

DECLARE @TAB_DPD AS TABLE
(
	ANO INT
	,SEMANA INT	
	,COD_PRODUTO INT
	,QTD_ESTOQUE NUMERIC(18,2)
	,AVG_VLR_VENDA NUMERIC(18,2)
	,VLR_VENDA NUMERIC(18,2)
)

INSERT INTO @TAB_DPD
SELECT DISTINCT
	LEFT(BI.dbo.ISO_WEEK(MOV.DATA),4) as [Ano]
	,BI.DBO.F_ISO_WEEK_OF_YEAR(MOV.DATA) as [Semana]
	,LINHA.COD_PRODUTO
	,(ISNULL((CASE WHEN MOV.QTD_ESTOQUE < 0 THEN 0 ELSE MOV.QTD_ESTOQUE END),0)) AS QTD_ESTOQUE
	,(EST.AVG_QTD_VENDA*LINHA.VLR_VENDA)/7 AS AVG_VLR_VENDA
	,LINHA.VLR_VENDA
FROM 
	BI.DBO.BI_LINHA_PRODUTOS AS LINHA INNER JOIN BI.dbo.BI_CAD_PRODUTO AS CP ON (LINHA.COD_PRODUTO = CP.COD_PRODUTO)
		INNER JOIN BI.DBO.COMPRAS_ESTATISTICA_PRODUTO AS EST ON (LINHA.COD_LOJA = EST.COD_LOJA AND LINHA.COD_PRODUTO = EST.COD_PRODUTO)
		--INNER JOIN [192.168.0.6].ZEUS_RTG.DBO.TAB_PRODUTO_MOVIMENTO AS MOV ON (LINHA.COD_LOJA = MOV.COD_LOJA AND LINHA.COD_PRODUTO = MOV.COD_PRODUTO)
		INNER JOIN BI.dbo.BI_ESTOQUE_PRODUTO_DIA AS MOV ON (LINHA.COD_LOJA = MOV.COD_LOJA AND LINHA.COD_PRODUTO = MOV.COD_PRODUTO)
		
WHERE 1 = 1
	--AND CONVERT(DATE,MOV.DATA) BETWEEN @DATAINI AND @DATAFIM
	AND LEFT(BI.dbo.ISO_WEEK(MOV.DATA),4) = @YEAR
	AND BI.DBO.F_ISO_WEEK_OF_YEAR(MOV.DATA) = @WEEK
	AND LINHA.COD_LOJA NOT IN (4,10,19)
	AND CP.CLASSIF_PRODUTO IN ('A1','A2')
	AND CP.PESADO = 'N'

SELECT
	ANO
	,SEMANA
	,BI.dbo.fn_FormataVlr_Excel(SUM(QTD_ESTOQUE*VLR_VENDA)/SUM(AVG_VLR_VENDA)) AS DPD
FROM
	@TAB_DPD
GROUP BY
	ANO
	,SEMANA