/*

Sum(if(QTD_RECEBIDA>0,1,0))/Sum(if(QTD_PEDIDO>0,1,0))*100

SUM(CASE WHEN PED.[QTD_RECEBIDA] > 0 THEN 1 ELSE 0 END) / (CASE WHEN (PED.[QTD_PEDIDO]*PED.[QTD_EMBALAGEM]) > 0 THEN 1 ELSE 0 END)

*/

	DECLARE @YEAR AS INT = 2015
	DECLARE @WEEK AS INT = 7

	DECLARE @TAB_RECEBIMENTO AS TABLE
	(
		COD_FORNECEDOR INT
		,NUM_PEDIDO INT
		,COD_LOJA INT
		,DATA_RECEBIMENTO DATETIME
	)
	INSERT INTO @TAB_RECEBIMENTO
	SELECT DISTINCT
		FORNECEDOR_COD
		,PEDIDO_NUMERO
		,COD_LOJA
		,CONVERT(DATE,DATA)
	FROM
		[192.168.0.6].[INTRANET].[DBO].[TAB_RECEB_MERCADORIA]
	WHERE 1 = 1
		AND LEFT(dbo.ISO_WEEK(DATA),4) = @YEAR
		AND BI.DBO.F_ISO_WEEK_OF_YEAR(DATA) = @WEEK
		
	DECLARE @TAB_PEDIDO AS TABLE
	(
		ANO INT
		,SEMANA INT
		,QTD_RECEBIDA NUMERIC(18,2)
		,QTD_PEDIDO NUMERIC(18,2)
	)
	INSERT INTO @TAB_PEDIDO
	SELECT
		LEFT(dbo.ISO_WEEK(P.DTA_EMISSAO),4)
		,BI.DBO.F_ISO_WEEK_OF_YEAR(P.DTA_EMISSAO)
		,SUM(CASE WHEN PED.[QTD_RECEBIDA] > 0 THEN 1 ELSE 0 END) AS [QTD_RECEBIDA]
		,SUM(CASE WHEN (PED.[QTD_PEDIDO]*PED.[QTD_EMBALAGEM]) > 0 THEN 1 ELSE 0 END) AS [QTD_PEDIDO]
	FROM
		[192.168.0.6].[ZEUS_RTG].[DBO].[TAB_PEDIDO] AS P INNER JOIN [192.168.0.6].[ZEUS_RTG].[DBO].[TAB_PEDIDO_PRODUTO] AS PED ON (P.COD_PARCEIRO = PED.COD_PARCEIRO AND P.NUM_PEDIDO = PED.NUM_PEDIDO AND P.COD_LOJA = PED.COD_LOJA)	
			INNER JOIN @TAB_RECEBIMENTO AS REC ON (PED.COD_PARCEIRO = REC.COD_FORNECEDOR AND PED.NUM_PEDIDO = REC.NUM_PEDIDO AND PED.COD_LOJA = REC.COD_LOJA)
			--LEFT JOIN BI.DBO.BI_CAD_PRODUTO AS CP ON (PED.COD_PRODUTO = CP.COD_PRODUTO)
				--LEFT JOIN BI.DBO.BI_CAD_FORNECEDOR AS CF ON (PED.[COD_PARCEIRO] = CF.COD_FORNECEDOR)
	WHERE 1 = 1
		AND PED.[QTD_PEDIDO] > 0
		AND LEFT(BI.dbo.ISO_WEEK(P.DTA_EMISSAO),4) = @YEAR
		AND BI.DBO.F_ISO_WEEK_OF_YEAR(P.DTA_EMISSAO) = @WEEK
	GROUP BY
		LEFT(dbo.ISO_WEEK(P.DTA_EMISSAO),4)
		,BI.DBO.F_ISO_WEEK_OF_YEAR(P.DTA_EMISSAO)		
	
	SELECT
		ANO
		,SEMANA
		,1- (QTD_RECEBIDA / QTD_PEDIDO) AS PERC_RECEBIMENTO
	FROM
		@TAB_PEDIDO