SELECT DISTINCT
	[COD_LOJA]
	,'P1' AS PERIODO_META
	,dbo.F_ISO_WEEK_OF_YEAR([DATA]) AS NR_SEMANA
	,LEFT(dbo.ISO_WEEK(DATA),4) - 1 AS ANO
	,dbo.ISO_WEEK(DATA) AS NR_META
FROM
	[BI].[dbo].[BI_VENDA_META]
WHERE
	CONVERT(DATE,DATA) >= CONVERT(DATE,'20140101')
	AND CONVERT(DATE,DATA) <= CONVERT(DATE,'20141227')


UNION ALL

SELECT DISTINCT
	[COD_LOJA]
	,'P2' AS PERIODO_META
	,dbo.F_ISO_WEEK_OF_YEAR([DATA]) AS NR_SEMANA
	,LEFT(dbo.ISO_WEEK(DATA),4) AS ANO
	,dbo.ISO_WEEK(DATA) AS NR_META
FROM
	[BI].[dbo].[BI_VENDA_META]
WHERE
	CONVERT(DATE,DATA) >= CONVERT(DATE,'20140101')
	AND CONVERT(DATE,DATA) <= CONVERT(DATE,'20141227')

ORDER BY
	[COD_LOJA]
	,NR_SEMANA
	,PERIODO_META
