	SELECT --TOP 10
		CP.NO_DEPARTAMENTO
		--,CP.NO_SECAO
		,COUNT(DISTINCT CASE WHEN VCC.CPF_IDENTIFICACAO = 0 THEN VCC.CUPOM_HASH ELSE NULL END) AS CUPOM_NAO_IDENT	
		,COUNT(DISTINCT CASE WHEN VCC.CPF_IDENTIFICACAO <> 0 THEN VCC.CUPOM_HASH ELSE NULL END) AS CUPOM_IDENT
		,COUNT(DISTINCT VCC.CUPOM_HASH) AS CUPOM_TOTAL
	FROM
		BI.dbo.BI_VENDA_CUPOM_CAPA AS VCC
		INNER JOIN BI.dbo.BI_VENDA_CUPOM_PRODUTO AS VCP
			ON VCC.CUPOM_HASH = VCP.CUPOM_HASH
		INNER JOIN BI.dbo.BI_CAD_PRODUTO AS CP
			ON VCP.COD_PRODUTO = CP.COD_PRODUTO
		INNER JOIN BI.dbo.BI_CAD_SEMANA AS S
			ON VCC.DATA = S.DATA
	WHERE 1=1
		AND VCC.COD_LOJA in (1,3,2,6,9,13,17,18,20,22,23,24,30)
		--AND S.ANO = 2014
		AND S.DATA between convert(date,'2015-01-01') and convert(date,'2015-10-31')
	GROUP BY
		CP.NO_DEPARTAMENTO
		--,CP.NO_SECAO
	ORDER BY
		CP.NO_DEPARTAMENTO
		--,CP.NO_SECAO
	