
DECLARE @DATA DATE

DECLARE DATA_cursor CURSOR FOR 
	SELECT DISTINCT DATA FROM BI.dbo.BI_VENDA_PRODUTO WHERE QTDE_PRODUTO = 0 and CONVERT(DATE,DATA) >= '2013-01-01' ORDER BY DATA

OPEN DATA_cursor

FETCH NEXT FROM DATA_cursor 
INTO @DATA

WHILE @@FETCH_STATUS = 0
BEGIN
    EXEC BI.[dbo].[CARGA_BI_VENDA_PRODUTO]  @DATA,@DATA

    FETCH NEXT FROM DATA_cursor 
    INTO @DATA
END 
CLOSE DATA_cursor;
DEALLOCATE DATA_cursor;
