/*
IF OBJECT_ID('TEMPDB.DBO.#TAB_VENDA_CUPOM') IS NOT NULL DROP TABLE #TAB_VENDA_CUPOM
CREATE TABLE  #TAB_VENDA_CUPOM
(		
	COD_LOJA INT
	,DATA DATE
	,CUPOM INT
	,VLR_CUPOM NUMERIC(18,2)
	
)
CREATE CLUSTERED INDEX IX_TAB_VENDA_CUPOMON ON #TAB_VENDA_CUPOM (COD_LOJA, DATA, CUPOM)

INSERT INTO #TAB_VENDA_CUPOM
SELECT
	COD_LOJA
	,Data
	,CUPOM
	,sum(VALOR_TOTAL) as valor
FROM
	DW.dbo.BI_ANAL_MOVTO_CAIXA 
WHERE 1=1
	AND CONVERT(DATE,DATA) BETWEEN CONVERT(DATE,'2014-01-01') AND CONVERT(DATE,'2015-10-31')
	AND COD_LOJA IN (1,3,2,6,9,13,17,18,20,22,23,24,30,4,10,19) --SSS
	--AND COD_LOJA IN (21,25,27,31) --Novas
group by
	COD_LOJA
	,Data
	,CUPOM
*/

SELECT
	YEAR(CC.DATA) ANO
	,MONTH(CC.DATA) MES
	,BI.dbo.fn_FormataVlr_Excel(COUNT(CC.CUPOM)) CUPOM_TOTAL
	,BI.dbo.fn_FormataVlr_Excel(COUNT(CASE WHEN NOTA_FISCAL_PAULISTA IS NULL AND CONTA_CLIENTE IS NULL AND VOCE_MARCHE IS NULL THEN CC.CUPOM END))	AS CUPOM_NAO_IDENT
	,BI.dbo.fn_FormataVlr_Excel(SUM(CASE WHEN NOTA_FISCAL_PAULISTA IS NULL AND CONTA_CLIENTE IS NULL AND VOCE_MARCHE IS NULL THEN VC.VLR_CUPOM END)) AS VLR_CUPOM_NAO_IDENT
	
	,BI.dbo.fn_FormataVlr_Excel(COUNT(CASE WHEN (NOTA_FISCAL_PAULISTA IS NOT NULL OR CONTA_CLIENTE IS NOT NULL) AND VOCE_MARCHE IS NULL THEN CC.CUPOM END)) CUPOM_CPF
	,BI.dbo.fn_FormataVlr_Excel(SUM(CASE WHEN (NOTA_FISCAL_PAULISTA IS NOT NULL OR CONTA_CLIENTE IS NOT NULL) AND VOCE_MARCHE IS NULL THEN VC.VLR_CUPOM END)) VLR_CUPOM_CPF
	,BI.dbo.fn_FormataVlr_Excel(COUNT(DISTINCT CASE WHEN (NOTA_FISCAL_PAULISTA IS NOT NULL OR CONTA_CLIENTE IS NOT NULL) AND VOCE_MARCHE IS NULL THEN ISNULL(NOTA_FISCAL_PAULISTA,CONTA_CLIENTE) END)) QTD_CPF
	
	,BI.dbo.fn_FormataVlr_Excel(COUNT(CASE WHEN VOCE_MARCHE IS NOT NULL THEN CC.CUPOM END)) AS CUPOM_VCM
	,BI.dbo.fn_FormataVlr_Excel(SUM(CASE WHEN VOCE_MARCHE IS NOT NULL THEN VC.VLR_CUPOM END)) AS VLR_CUPOM_VCM
	,BI.dbo.fn_FormataVlr_Excel(COUNT(DISTINCT CASE WHEN VOCE_MARCHE IS NOT NULL THEN VOCE_MARCHE END)) AS QTD_VCM
FROM
	[DW].[dbo].[CUPOM_CLIENTES] as CC	
	INNER JOIN #TAB_VENDA_CUPOM AS VC
		ON 1=1
		AND CC.COD_LOJA = VC.COD_LOJA
		AND CC.CUPOM = VC.CUPOM
		AND CC.DATA = VC.DATA		
WHERE 1=1
	AND CONVERT(DATE,CC.DATA) BETWEEN CONVERT(DATE,'2014-01-01') AND CONVERT(DATE,'2015-10-31')
	--AND CC.COD_LOJA IN (1,3,2,6,9,13,17,18,20,22,23,24,30,4,10,19) --SSS
	AND CC.COD_LOJA IN (21,25,27,31) --Novas
GROUP BY
	YEAR(CC.DATA)
	,MONTH(CC.DATA)
ORDER BY
	YEAR(CC.DATA)
	,MONTH(CC.DATA)

/* SALES CHECK

SELECT
	COD_LOJA
	,sum(VALOR_TOTAL) as valor
FROM
	DW.dbo.BI_ANAL_MOVTO_CAIXA 
WHERE 1=1
	AND CONVERT(DATE,DATA) BETWEEN CONVERT(DATE,'2015-01-01') AND CONVERT(DATE,'2015-10-31')--CONVERT(DATE,'2014-12-31')
	AND COD_LOJA IN (1,3,2,6,9,13,17,18,20,22,23,24,30,4,10,19) --SSS
	--AND COD_LOJA IN (21,25,27,31) --Novas
group by
	COD_LOJA

*/

DECLARE @TAB_QTD_CLIENTES_ANO AS TABLE
(
	ANO INT
	,QTD_CLIENTES INT
)
INSERT INTO @TAB_QTD_CLIENTES_ANO
	SELECT
		YEAR(CC.DATA) ANO
		,COUNT(DISTINCT VOCE_MARCHE)		
	FROM
		[DW].[dbo].[CUPOM_CLIENTES] as CC	
		--INNER JOIN #TAB_VENDA_CUPOM AS VC
		--	ON 1=1
		--	AND CC.COD_LOJA = VC.COD_LOJA
		--	AND CC.CUPOM = VC.CUPOM
		--	AND CC.DATA = VC.DATA		
	WHERE 1=1
		AND CONVERT(DATE,CC.DATA) BETWEEN CONVERT(DATE,'2014-01-01') AND CONVERT(DATE,'2015-10-31')
		AND VOCE_MARCHE IS NOT NULL
		AND CC.COD_LOJA IN (1,3,2,6,9,13,17,18,20,22,23,24,30,4,10,19) --SSS
		--AND CC.COD_LOJA IN (21,25,27,31) --Novas
	GROUP BY
		YEAR(CC.DATA)
	

SELECT
	X.ANO
	,''''+X.VOCE_MARCHE
	,X.SEQ
	,(CASE
		WHEN X.SEQ <= ABC.QTD_CLIENTES * 0.2 THEN 'A'
		WHEN X.SEQ > ABC.QTD_CLIENTES * 0.2 and  X.SEQ < ABC.QTD_CLIENTES * 0.7 THEN 'B'
		WHEN X.SEQ >= ABC.QTD_CLIENTES * 0.7 THEN 'C'
	END) AS ABC_CLIENTE
	,BI.dbo.fn_FormataVlr_Excel(X.VLR_CUPOM_VCM) AS VLR_CUPOM_VCM
	,BI.dbo.fn_FormataVlr_Excel(X.QTD_CUPOM_VCM) AS QTD_CUPOM_VCM
FROM 
(
	SELECT
		YEAR(CC.DATA) ANO
		,VOCE_MARCHE		
		,SUM(VC.VLR_CUPOM) AS VLR_CUPOM_VCM
		,COUNT(CC.CUPOM) AS QTD_CUPOM_VCM
		,RANK() over (partition by YEAR(CC.DATA) ORDER BY SUM(VC.VLR_CUPOM) DESC) AS SEQ	
	FROM
		[DW].[dbo].[CUPOM_CLIENTES] as CC	
		INNER JOIN #TAB_VENDA_CUPOM AS VC
			ON 1=1
			AND CC.COD_LOJA = VC.COD_LOJA
			AND CC.CUPOM = VC.CUPOM
			AND CC.DATA = VC.DATA		
	WHERE 1=1
		AND CONVERT(DATE,CC.DATA) BETWEEN CONVERT(DATE,'2014-01-01') AND CONVERT(DATE,'2015-10-31')
		AND VOCE_MARCHE IS NOT NULL
		AND CC.COD_LOJA IN (1,3,2,6,9,13,17,18,20,22,23,24,30,4,10,19) --SSS
		--AND CC.COD_LOJA IN (21,25,27,31) --Novas
	GROUP BY
		YEAR(CC.DATA)
		,VOCE_MARCHE
) AS X

	INNER JOIN @TAB_QTD_CLIENTES_ANO AS ABC
	ON X.ANO = ABC.ANO



