SELECT --TOP 10
	YEAR(cp.data) as ano
	,month(cp.data) as mes
	,(CASE
		WHEN DATEPART(DW,CP.DATA) = 1 THEN 'DOM'
		WHEN DATEPART(DW,CP.DATA) = 2 THEN 'SEG'
		WHEN DATEPART(DW,CP.DATA) = 3 THEN 'TER'
		WHEN DATEPART(DW,CP.DATA) = 4 THEN 'QUA'
		WHEN DATEPART(DW,CP.DATA) = 5 THEN 'QUI'
		WHEN DATEPART(DW,CP.DATA) = 6 THEN 'SEX'
		WHEN DATEPART(DW,CP.DATA) = 7 THEN 'SAB'
	END) AS DIA_SEMANA
	--,NO_DEPARTAMENTO
	--,NO_SECAO
	--,NO_GRUPO
	,BI.dbo.fn_FormataVlr_Excel(SUM(CP.VLR_VENDA)) AS VLR_VENDA
	,BI.dbo.fn_FormataVlr_Excel(COUNT(DISTINCT CUPOM_HASH)) AS VLR_VENDA
FROM 
	BI.DBO.BI_VENDA_CUPOM_PRODUTO AS CP
	INNER JOIN BI_CAD_PRODUTO AS CAD
		ON 1=1
		AND CP.COD_PRODUTO = CAD.COD_PRODUTO
WHERE 1=1
	AND CP.COD_LOJA = 7
	AND CONVERT(DATE,CP.DATA) BETWEEN CONVERT(DATE,'20130901') AND CONVERT(DATE,'20140111')
GROUP BY
	YEAR(cp.data)
	,month(cp.data)
	,(CASE
		WHEN DATEPART(DW,CP.DATA) = 1 THEN 'DOM'
		WHEN DATEPART(DW,CP.DATA) = 2 THEN 'SEG'
		WHEN DATEPART(DW,CP.DATA) = 3 THEN 'TER'
		WHEN DATEPART(DW,CP.DATA) = 4 THEN 'QUA'
		WHEN DATEPART(DW,CP.DATA) = 5 THEN 'QUI'
		WHEN DATEPART(DW,CP.DATA) = 6 THEN 'SEX'
		WHEN DATEPART(DW,CP.DATA) = 7 THEN 'SAB'
	END)
	--,NO_DEPARTAMENTO
	--,NO_SECAO
	--,NO_GRUPO
	