DECLARE @DATA_INI AS DATE = '20140101'
DECLARE @DATA_FIM AS DATE = '20141231'

-- -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
-- 
-- -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
DECLARE @TAB_VENDA_IP AS TABLE
(
	NO_DEPARTAMENTO VARCHAR(50)
	--,NO_SECAO VARCHAR(50)
	,VLR_VENDA NUMERIC(18,2)
)

INSERT INTO @TAB_VENDA_IP
SELECT
	CP.NO_DEPARTAMENTO
	--,CP.NO_SECAO
	,SUM(VALOR_TOTAL) AS VLR_VENDA
FROM
	BI.DBO.BI_VENDA_PRODUTO AS VP
	INNER JOIN BI.dbo.BI_CAD_PRODUTO AS CP
		ON 1=1
		AND VP.COD_PRODUTO = CP.COD_PRODUTO
WHERE 1=1
	AND VP.DATA BETWEEN CONVERT(DATE,@DATA_INI) AND CONVERT(DATE,@DATA_FIM)
	AND VP.COD_PRODUTO IN (SELECT DISTINCT COD_PRODUTO FROM CADASTRO_CAD_PRODUTO_METADADOS WHERE COD_METADADO = 4 AND VLR_METADADO = 1)
	AND CP.DESCRICAO NOT LIKE '%DALFOUR%'
GROUP BY
	CP.NO_DEPARTAMENTO
	--,CP.NO_SECAO


DECLARE @TAB_VENDA_LOJA AS TABLE
(
	NO_DEPARTAMENTO VARCHAR(50)
	--,NO_SECAO VARCHAR(50)
	,VLR_VENDA NUMERIC(18,2)
)

INSERT INTO @TAB_VENDA_LOJA
SELECT
	CP.NO_DEPARTAMENTO
	--,CP.NO_SECAO
	,SUM(VALOR_TOTAL) AS VLR_VENDA
FROM
	BI.DBO.BI_VENDA_PRODUTO AS VP
	INNER JOIN BI.dbo.BI_CAD_PRODUTO AS CP
		ON 1=1
		AND VP.COD_PRODUTO = CP.COD_PRODUTO
WHERE 1=1
	AND VP.DATA BETWEEN CONVERT(DATE,@DATA_INI) AND CONVERT(DATE,@DATA_FIM)
	AND CP.DESCRICAO NOT LIKE '%DALFOUR%'
GROUP BY
	CP.NO_DEPARTAMENTO
	--,CP.NO_SECAO
	
SELECT
	VIP.NO_DEPARTAMENTO
	--,VIP.NO_SECAO
	,BI.dbo.fn_FormataVlr_Excel(VIP.VLR_VENDA) AS VENDA_IP
	,BI.dbo.fn_FormataVlr_Excel(VL.VLR_VENDA) AS VENDA_LOJA
	,BI.dbo.fn_FormataVlr_Excel(VIP.VLR_VENDA/VL.VLR_VENDA) AS PERC
FROM
	@TAB_VENDA_IP AS VIP
	INNER JOIN @TAB_VENDA_LOJA AS VL
		ON 1=1
		AND VIP.NO_DEPARTAMENTO = VL.NO_DEPARTAMENTO
		--AND VIP.NO_SECAO = VL.NO_SECAO
		
-- -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
-- 
-- -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
SELECT
	CP.NO_DEPARTAMENTO
	,CP.NO_SECAO
	,CP.NO_GRUPO
	,CP.COD_PRODUTO
	,CP.DESCRICAO AS NO_PRODUTO
	,BI.dbo.fn_FormataVlr_Excel(SUM(VALOR_TOTAL)) AS VLR_VENDA
FROM
	BI.DBO.BI_VENDA_PRODUTO AS VP
	INNER JOIN BI.dbo.BI_CAD_PRODUTO AS CP
		ON 1=1
		AND VP.COD_PRODUTO = CP.COD_PRODUTO
WHERE 1=1
	AND VP.DATA BETWEEN CONVERT(DATE,@DATA_INI) AND CONVERT(DATE,@DATA_FIM)
	AND CP.DESCRICAO NOT LIKE '%DALFOUR%'
	AND VP.COD_PRODUTO IN (SELECT DISTINCT COD_PRODUTO FROM CADASTRO_CAD_PRODUTO_METADADOS WHERE COD_METADADO = 4 AND VLR_METADADO = 1)
GROUP BY
	CP.NO_DEPARTAMENTO
	,CP.NO_SECAO
	,CP.NO_GRUPO
	,CP.COD_PRODUTO
	,CP.DESCRICAO
	
-- -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
-- 
-- -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
SELECT
	CP.NO_DEPARTAMENTO
	,CP.NO_SECAO
	,CP.NO_GRUPO
	,CP.COD_PRODUTO
	,CP.DESCRICAO AS NO_PRODUTO
	,YEAR(VP.DATA) AS ANO
	,MONTH(VP.DATA) AS MES
	,BI.dbo.fn_FormataVlr_Excel(SUM(VALOR_TOTAL)) AS VLR_VENDA
FROM
	BI.DBO.BI_VENDA_PRODUTO AS VP
	INNER JOIN BI.dbo.BI_CAD_PRODUTO AS CP
		ON 1=1
		AND VP.COD_PRODUTO = CP.COD_PRODUTO
WHERE 1=1
	AND VP.DATA BETWEEN CONVERT(DATE,@DATA_INI) AND CONVERT(DATE,@DATA_FIM)
	AND CP.DESCRICAO NOT LIKE '%DALFOUR%'
	AND VP.COD_PRODUTO IN (SELECT DISTINCT COD_PRODUTO FROM CADASTRO_CAD_PRODUTO_METADADOS WHERE COD_METADADO = 4 AND VLR_METADADO = 1)
GROUP BY
	CP.NO_DEPARTAMENTO
	,CP.NO_SECAO
	,CP.NO_GRUPO
	,CP.COD_PRODUTO
	,CP.DESCRICAO
	,YEAR(VP.DATA)
	,MONTH(VP.DATA)

-- -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
-- 
-- -----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
DECLARE @TAB_CUSTO_PRODUTO AS TABLE
(
	COD_PRODUTO INT
	,COD_FORNECEDOR INT
	,COD_LOJA INT
	,VLR_CUSTO NUMERIC(18,2)
)

INSERT INTO @TAB_CUSTO_PRODUTO
	SELECT
		COD_PRODUTO
		,COD_FORNECEDOR
		,COD_LOJA
		,[VAL_CUSTO_EMBALAGEM]/[QTD_EMBALAGEM_COMPRA]
	FROM
		[192.168.0.6].[Zeus_rtg].[dbo].[TAB_PRODUTO_FORNECEDOR]	
	WHERE [QTD_EMBALAGEM_COMPRA] <> 0	
		
SELECT
	CP.NO_DEPARTAMENTO
	,CP.NO_SECAO
	,CP.NO_GRUPO
	,CP.COD_PRODUTO
	,CP.DESCRICAO AS NO_PRODUTO
	,BI.dbo.fn_FormataVlr_Excel(SUM(QTD_ESTOQUE*C.VLR_CUSTO)) AS EST_CUSTO
FROM
	BI.dbo.BI_CAD_PRODUTO AS CP
	INNER JOIN BI_ESTOQUE_PRODUTO AS EP
		ON 1=1
		AND EP.COD_PRODUTO = CP.COD_PRODUTO
	INNER JOIN @TAB_CUSTO_PRODUTO AS C
		ON 1=1
		AND CP.COD_PRODUTO = C.COD_PRODUTO
		AND CP.COD_FORNECEDOR = C.COD_FORNECEDOR
		AND EP.COD_LOJA = C.COD_LOJA
WHERE 1=1
	--AND VP.DATA BETWEEN CONVERT(DATE,@DATA_INI) AND CONVERT(DATE,@DATA_FIM)
	AND CP.COD_PRODUTO IN (SELECT DISTINCT COD_PRODUTO FROM CADASTRO_CAD_PRODUTO_METADADOS WHERE COD_METADADO = 4 AND VLR_METADADO = 1)
	and EP.COD_LOJA not in (5,28)
	AND CP.DESCRICAO NOT LIKE '%DALFOUR%'
GROUP BY
	CP.NO_DEPARTAMENTO
	,CP.NO_SECAO
	,CP.NO_GRUPO
	,CP.COD_PRODUTO
	,CP.DESCRICAO


SELECT
	CP.NO_DEPARTAMENTO
	,CP.NO_SECAO
	,CP.NO_GRUPO
	,CP.COD_PRODUTO
	,CP.DESCRICAO AS NO_PRODUTO
	,BI.dbo.fn_FormataVlr_Excel(SUM(QTD_ESTOQUE*C.VLR_CUSTO)) AS EST_CUSTO
FROM
	BI.dbo.BI_CAD_PRODUTO AS CP
	INNER JOIN BI_ESTOQUE_PRODUTO AS EP
		ON 1=1
		AND EP.COD_PRODUTO = CP.COD_PRODUTO
	INNER JOIN @TAB_CUSTO_PRODUTO AS C
		ON 1=1
		AND CP.COD_PRODUTO = C.COD_PRODUTO
		AND CP.COD_FORNECEDOR = C.COD_FORNECEDOR
		AND EP.COD_LOJA = C.COD_LOJA
WHERE 1=1
	--AND VP.DATA BETWEEN CONVERT(DATE,@DATA_INI) AND CONVERT(DATE,@DATA_FIM)
	AND CP.COD_PRODUTO IN (SELECT DISTINCT COD_PRODUTO FROM CADASTRO_CAD_PRODUTO_METADADOS WHERE COD_METADADO = 4 AND VLR_METADADO = 1)
	and EP.COD_LOJA = 28
GROUP BY
	CP.NO_DEPARTAMENTO
	,CP.NO_SECAO
	,CP.NO_GRUPO
	,CP.COD_PRODUTO
	,CP.DESCRICAO
