	SET NOCOUNT ON;
	DECLARE @TAB_QUEBRA AS TABLE
	(
		[COD_LOJA] INT
		,[DATA] DATE
		,[COD_DEPARTAMENTO] INT
		,[COD_AJUSTE] INT
		,[QTD_QUEBRA] NUMERIC(18,2)
		,[VLR_QUEBRA] NUMERIC(18,2)
	)
	
	INSERT INTO @TAB_QUEBRA
	SELECT
		[COD_LOJA]
		,[DATA]
		,[COD_DEPARTAMENTO]
		,[COD_AJUSTE]
		,SUM([QTD_QUEBRA]) AS A
		,SUM([VLR_QUEBRA]) AS B
	FROM
		[BI].[DBO].[BI_QUEBRA_DEPARTAMENTO] AS QD
	WHERE 1=1
		AND CONVERT(DATE,QD.DATA) between CONVERT(DATE,GETDATE()-1) AND CONVERT(DATE,GETDATE()-1)
		--and QD.COD_LOJA in ()
		and COD_AJUSTE in (51)
	GROUP BY
		[COD_LOJA]
		,[DATA]
		,COD_DEPARTAMENTO
		,[COD_AJUSTE]
			
	SELECT
		(CASE WHEN VP.[COD_LOJA] IS NULL THEN QD.[COD_LOJA] ELSE VP.[COD_LOJA] END) AS [Loja]
		,ISNULL(SUM(QD.VLR_QUEBRA),0)*-1 AS [Vlr Quebra]
		,ISNULL(SUM(QD.QTD_QUEBRA),0)*-1 AS [Qtd Quebra]
		,ISNULL(SUM(VP.VLR_VENDA),0) AS [Vlr Venda]
		,ISNULL(SUM (QD.VLR_QUEBRA)/SUM(VP.VLR_VENDA),0)*-1 as [% Quebra]
	FROM
		BI.DBO.BI_VENDA_DEPARTAMENTO AS VP
		LEFT JOIN @TAB_QUEBRA AS QD
			ON 1=1
			AND VP.COD_LOJA = QD.COD_LOJA
			AND VP.DATA = QD.DATA
			AND VP.COD_DEPARTAMENTO = QD.COD_DEPARTAMENTO
	WHERE 1=1
		AND CONVERT(DATE,VP.DATA) between CONVERT(DATE,GETDATE()-1) AND CONVERT(DATE,GETDATE()-1)
	GROUP BY
		(CASE WHEN VP.[COD_LOJA] IS NULL THEN QD.[COD_LOJA] ELSE VP.[COD_LOJA] END)
	ORDER BY
		[Loja]