SELECT
	GC.COD_DEPARTAMENTO
	,T.NO_DEPARTAMENTO
	,GC.COD_SECAO
	,T.NO_SECAO
	,GC.COD_GRUPO
	,T.NO_GRUPO
	,GC.COD_USUARIO
	,CC.NO_COMPRADOR
FROM
	[BI].[dbo].[COMPRA_GRUPO_COMPRADORES] AS GC
	INNER JOIN
	(
	select distinct COD_DEPARTAMENTO, NO_DEPARTAMENTO, COD_SECAO, NO_SECAO, COD_GRUPO, NO_GRUPO from BI.dbo.BI_CAD_PRODUTO
	) AS T
		ON 1=1
		AND GC.COD_DEPARTAMENTO = T.COD_DEPARTAMENTO
		AND GC.COD_SECAO = T.COD_SECAO
		AND GC.COD_GRUPO = T.COD_GRUPO
	LEFT JOIN BI.dbo.COMPRAS_CAD_COMPRADOR AS CC
		ON GC.COD_USUARIO = CC.COD_USUARIO
ORDER BY
	T.NO_DEPARTAMENTO
	,T.NO_SECAO
	,T.NO_GRUPO
		
		

SELECT
	GC.COD_DEPARTAMENTO
	,T.NO_DEPARTAMENTO
	,GC.COD_SECAO
	,T.NO_SECAO
	,GC.COD_GRUPO
	,T.NO_GRUPO
	,GC.COD_FORNECEDOR
	,CF.DESCRICAO AS NO_FORNECEDOR
	,GC.COD_USUARIO
	,CC.NO_COMPRADOR
FROM
	[BI].[dbo].[COMPRA_FORNECEDOR_COMPRADOR] AS GC
	INNER JOIN
	(
	select distinct COD_DEPARTAMENTO, NO_DEPARTAMENTO, COD_SECAO, NO_SECAO, COD_GRUPO, NO_GRUPO from BI.dbo.BI_CAD_PRODUTO
	) AS T
		ON 1=1
		AND GC.COD_DEPARTAMENTO = T.COD_DEPARTAMENTO
		AND GC.COD_SECAO = T.COD_SECAO
		AND GC.COD_GRUPO = T.COD_GRUPO
	LEFT JOIN BI.dbo.COMPRAS_CAD_COMPRADOR AS CC
		ON GC.COD_USUARIO = CC.COD_USUARIO
	LEFT JOIN BI.dbo.BI_CAD_FORNECEDOR AS CF
		ON GC.COD_FORNECEDOR = CF.COD_FORNECEDOR
ORDER BY
	T.NO_DEPARTAMENTO
	,T.NO_SECAO
	,T.NO_GRUPO		
		
		
		
SELECT
	GC.COD_DEPARTAMENTO
	,T.NO_DEPARTAMENTO
	,GC.COD_SECAO
	,T.NO_SECAO
	,GC.COD_GRUPO
	,T.NO_GRUPO
	,GC.COD_METADADO
	,CM.NO_METADADO
	,GC.VLR_METADADO
	,GC.COD_USUARIO
	,CC.NO_COMPRADOR
FROM
	[BI].[dbo].[COMPRA_METADADO_COMPRADOR] AS GC
	INNER JOIN
	(
	select distinct COD_DEPARTAMENTO, NO_DEPARTAMENTO, COD_SECAO, NO_SECAO, COD_GRUPO, NO_GRUPO from BI.dbo.BI_CAD_PRODUTO
	) AS T
		ON 1=1
		AND GC.COD_DEPARTAMENTO = T.COD_DEPARTAMENTO
		AND GC.COD_SECAO = T.COD_SECAO
		AND GC.COD_GRUPO = T.COD_GRUPO
	LEFT JOIN BI.dbo.COMPRAS_CAD_COMPRADOR AS CC
		ON GC.COD_USUARIO = CC.COD_USUARIO
	LEFT JOIN BI.dbo.CADASTRO_CAD_METADADOS AS CM
		ON GC.COD_METADADO = CM.COD_METADADO
ORDER BY
	T.NO_DEPARTAMENTO
	,T.NO_SECAO
	,T.NO_GRUPO