select 
	NO_DEPARTAMENTO
	,COUNT(LP.COD_PRODUTO) PRODUTO_LOJA
	,COUNT(DISTINCT LP.COD_PRODUTO) PRODUTO_DISTINTOS
from
	BI.dbo.BI_LINHA_PRODUTOS AS LP
	INNER JOIN BI.dbo.BI_CAD_PRODUTO AS CP
		ON LP.COD_PRODUTO = CP.COD_PRODUTO
	LEFT JOIN BI.dbo.VW_ESTOQUE_ATUAL AS E
		ON 1=1
		AND LP.COD_LOJA = E.COD_LOJA
		AND LP.COD_PRODUTO = E.COD_PRODUTO
where 1=1
	AND LP.CLASSIF_PRODUTO_LOJA = 'Z' AND LP.FORA_LINHA = 'N' 
	AND LP.COD_DEPARTAMENTO NOT IN (15,99,20,7,18)
	AND LP.COD_SECAO NOT IN (16,39,85,21,9) --NATAL/OUTROS/SUCOSePOUPAS
	AND LP.COD_LOJA NOT IN (7,8,29,33)
	AND ISNULL(E.QTD_ESTOQUE,0) = 0
GROUP BY
	NO_DEPARTAMENTO
	
	
select 
	LP.COD_PRODUTO
	,CP.DESCRICAO
	,CP.NO_DEPARTAMENTO
	,CP.NO_SECAO
	,CP.NO_GRUPO
	,sum(case when LP.CLASSIF_PRODUTO_LOJA = 'C' then 1 else 0 end) AS QTD_LOJAS_C
	,sum(case when LP.CLASSIF_PRODUTO_LOJA = 'Z' then 1 else 0 end) AS QTD_LOJAS_Z
	,sum(case when LP.CLASSIF_PRODUTO_LOJA = 'B' then 1 else 0 end) AS QTD_LOJAS_B
	,sum(case when LP.CLASSIF_PRODUTO_LOJA IN ('A1','A2','A3') then 1 else 0 end) AS QTD_LOJAS_A
	,SUM(CASE WHEN LP.FORA_LINHA = 'N' THEN 1 ELSE 0 END) QTD_LOJA_LINHA
--SELECT *
from
	BI.dbo.BI_LINHA_PRODUTOS AS LP
	INNER JOIN BI.dbo.BI_CAD_PRODUTO AS CP
		ON LP.COD_PRODUTO = CP.COD_PRODUTO
where 1=1
	AND LP.COD_LOJA NOT IN (7,8,29,33)
	--AND LP.COD_PRODUTO = 55949
	AND LP.FORA_LINHA = 'N' 
GROUP BY
	LP.COD_PRODUTO
	,CP.DESCRICAO
	,CP.NO_DEPARTAMENTO
	,CP.NO_SECAO
	,CP.NO_GRUPO
HAVING
	sum(case when LP.CLASSIF_PRODUTO_LOJA = 'B' then 1 else 0 end) = 0
	AND sum(case when LP.CLASSIF_PRODUTO_LOJA IN ('A1','A2','A3') then 1 else 0 end) = 0
	AND SUM(CASE WHEN LP.FORA_LINHA = 'N' THEN 1 ELSE 0 END) > 0
