DECLARE @TAB_PROD_VENDA AS TABLE
(
	COD_LOJA INT
	,COD_PRODUTO INT
)

INSERT INTO @TAB_PROD_VENDA
SELECT DISTINCT
	VP.COD_LOJA
	,VP.COD_PRODUTO
FROM
	BI.dbo.BI_VENDA_PRODUTO AS VP
	INNER JOIN BI.dbo.BI_LINHA_PRODUTOS AS LP
		ON 1=1
		AND VP.COD_LOJA = LP.COD_LOJA
		AND VP.COD_PRODUTO = LP.COD_PRODUTO
WHERE 1=1
	AND LP.CLASSIF_PRODUTO_LOJA = 'C'
	AND CONVERT(DATE,DATA) <= CONVERT(DATE,GETDATE()-180)
	
select 
	LP.COD_PRODUTO
	,CP.DESCRICAO
	,CP.NO_DEPARTAMENTO
	,CP.NO_SECAO
	,CP.NO_GRUPO
	,(CASE WHEN TPV.COD_PRODUTO IS NOT NULL THEN 1 ELSE 0 END) AS VENDA_U180D
	,sum(case when LP.CLASSIF_PRODUTO_LOJA = 'C' then 1 else 0 end) AS QTD_LOJAS_C
	,sum(case when LP.CLASSIF_PRODUTO_LOJA = 'Z' then 1 else 0 end) AS QTD_LOJAS_Z
	,sum(case when LP.CLASSIF_PRODUTO_LOJA = 'B' then 1 else 0 end) AS QTD_LOJAS_B
	,sum(case when LP.CLASSIF_PRODUTO_LOJA IN ('A1','A2','A3') then 1 else 0 end) AS QTD_LOJAS_A
	,SUM(CASE WHEN LP.FORA_LINHA = 'N' THEN 1 ELSE 0 END) QTD_LOJA_LINHA
	
--SELECT *
from
	BI.dbo.BI_LINHA_PRODUTOS AS LP
	INNER JOIN BI.dbo.BI_CAD_PRODUTO AS CP
		ON LP.COD_PRODUTO = CP.COD_PRODUTO
	LEFT JOIN @TAB_PROD_VENDA AS TPV
		ON 1=1
		AND TPV.COD_LOJA = LP.COD_LOJA
		AND TPV.COD_PRODUTO = LP.COD_PRODUTO
where 1=1
	AND LP.COD_LOJA NOT IN (7,8,29,33)
	AND LP.FORA_LINHA = 'N'
GROUP BY
	LP.COD_PRODUTO
	,CP.DESCRICAO
	,CP.NO_DEPARTAMENTO
	,CP.NO_SECAO
	,CP.NO_GRUPO
	,(CASE WHEN TPV.COD_PRODUTO IS NOT NULL THEN 1 ELSE 0 END)
HAVING
	sum(case when LP.CLASSIF_PRODUTO_LOJA = 'B' then 1 else 0 end) = 0
	AND sum(case when LP.CLASSIF_PRODUTO_LOJA IN ('A1','A2','A3') then 1 else 0 end) = 0
	AND SUM(CASE WHEN LP.FORA_LINHA = 'N' THEN 1 ELSE 0 END) > 0
