SELECT
	CONVERT(DATE,EPD.DATA) AS DATA
	,EPD.COD_PRODUTO
	,VP.VALOR_TOTAL
	,VP.QTDE_PRODUTO
	,EPD.QTD_ESTOQUE
FROM
	BI_ESTOQUE_PRODUTO_DIA AS EPD
	LEFT JOIN BI_VENDA_PRODUTO as VP
		ON 1=1
		AND VP.COD_LOJA = EPD.COD_LOJA
		AND VP.COD_PRODUTO = EPD.COD_PRODUTO
		AND VP.DATA = EPD.DATA
WHERE 1=1
	AND EPD.COD_PRODUTO = 346528
	AND EPD.COD_LOJA = 1
	AND CONVERT(DATE,EPD.DATA) >= CONVERT(DATE,'20140101')
ORDER BY 
	CONVERT(DATE,EPD.DATA)
	
SELECT * FROM COMPRAS_ESTATISTICA_PRODUTO WHERE COD_PRODUTO = 346528 AND  COD_LOJA = 1