	set nocount on;
	DECLARE @DATA AS DATE = CONVERT(DATE,GETDATE())
	DECLARE @AGENDA AS TABLE
	(
		COD_USUARIO INT
		,NO_COMPRADOR VARCHAR(50)
		,FREQ INT
		,LT INT
		,DPD INT
		,DATA_PEDIDO VARCHAR(50)
		,DIA VARCHAR(50)
		,COD_FORNECEDOR INT
		,NO_FORN VARCHAR(50)
		,OBS VARCHAR(1000)
		,DATA_BASE DATE
	)

	INSERT INTO @AGENDA
	SELECT
		C.COD_USUARIO 
		,c.NO_COMPRADOR as Comprador
		,[VLR_FREQ] as Freq
		,[VLR_LEAD_TIME] as LT
		,[VLR_DPD] as DPD
		,CONVERT(DATE,@DATA) as [Data Pedido]
		,'' as [Dia]
		,a.[COD_FORNECEDOR] as [Cod Forn]
		,DESCRICAO as Fornecedor		  
		,OBSERVACAO as Obs
		,convert(DATE,[DATA_BASE]) as [Data Base]
	FROM
		[BI].[dbo].[COMPRAS_AGENDA_PEDIDO_MATRIZ] as a inner join  [BI].[dbo].BI_CAD_FORNECEDOR as f on (f.COD_FORNECEDOR = a.COD_FORNECEDOR)
			left join [BI].dbo.COMPRAS_CAD_COMPRADOR as c on (c.COD_USUARIO = a.COD_COMPRADOR)
	where 1=1
		and DATEDIFF(d,DATA_BASE,@DATA) % VLR_FREQ = 0


	DECLARE @PEDIDOS_7D AS TABLE
	(
		COD_USUARIO INT
		,COD_FORNECEDOR INT
		,QTD_LOJAS INT
	)

	INSERT INTO @PEDIDOS_7D
	SELECT
		COD_USUARIO
		,COD_PARCEIRO AS COD_FORNECEDOR
		,COUNT(DISTINCT COD_LOJA)
	FROM
		[192.168.0.6].ZEUS_RTG.DBO.TAB_PEDIDO
	WHERE 1 = 1
		AND CONVERT(DATE,DTA_EMISSAO) = CONVERT(DATE,@DATA)
	GROUP BY
		COD_USUARIO
		,COD_PARCEIRO
			
	SELECT 	
		A.NO_COMPRADOR as [Comprador]
		,A.FREQ as [Freq]
		,A.LT as [LT]
		,ISNULL(A.DPD,'') as [DPD]
		,A.DATA_PEDIDO as [Data Pedido]
		,A.DIA as [Dia]
		,A.COD_FORNECEDOR as [Cod Forn]
		,A.NO_FORN as [Fornecedor]
		,ISNULL(A.OBS,'') as [Obs]
		,A.DATA_BASE as [Data Base]
		,ISNULL(P.QTD_LOJAS,0) as [Qtd Lojas]
	FROM
		@AGENDA AS A LEFT JOIN @PEDIDOS_7D AS P ON (A.COD_FORNECEDOR = P.COD_FORNECEDOR AND A.COD_USUARIO = P.COD_USUARIO)
	WHERE 1 = 1
