DECLARE @RUP_SEM_PED AS TABLE
(
	COD_LOJA INT
	,NO_DEPARTAMENTO VARCHAR(50)
	,NO_SECAO VARCHAR(50)
	,NO_GRUPO VARCHAR(50)
	,COD_PRODUTO INT
	,DESCRICAO VARCHAR(50)
	,CLASSIF_PRODUTO VARCHAR(50)
	,COD_USUARIO INT
	,NO_COMPRADOR VARCHAR(50)
	,COD_FORNECEDOR INT
	,NO_FORN VARCHAR(50)
)

INSERT INTO @RUP_SEM_PED
SELECT
	EP.COD_LOJA
	,CP.NO_DEPARTAMENTO
	,CP.NO_SECAO
	,CP.NO_GRUPO
	,EP.COD_PRODUTO
	,CP.DESCRICAO
	,CP.CLASSIF_PRODUTO
	,CP.COD_USUARIO
	,COMP.NO_COMPRADOR
	,CP.COD_FORNECEDOR
	,CF.DESCRICAO AS NO_FORN
FROM
	BI_CAD_PRODUTO AS CP INNER JOIN BI_ESTOQUE_PRODUTO AS EP ON (CP.COD_PRODUTO = EP.COD_PRODUTO)
		LEFT JOIN COMPRAS_CAD_COMPRADOR AS COMP ON (CP.COD_USUARIO = COMP.COD_USUARIO)
		LEFT JOIN BI_CAD_FORNECEDOR AS CF ON (CP.COD_FORNECEDOR= CF.COD_FORNECEDOR)
WHERE 1 = 1
	AND EP.QTD_ESTOQUE = 0
	AND CP.FORA_LINHA = 'N'
	AND CP.CLASSIF_PRODUTO IN ('A1','A2','A3','B','C')

DECLARE @PEDIDOS_7D AS TABLE
(
	COD_LOJA INT
	,COD_PRODUTO INT
)

INSERT INTO @PEDIDOS_7D
SELECT DISTINCT
	P.COD_LOJA
	,CONVERT(DOUBLE PRECISION,PP.COD_PRODUTO) AS COD_PRODUTO
FROM
	[192.168.0.6].ZEUS_RTG.DBO.TAB_PEDIDO AS P INNER JOIN  [192.168.0.6].ZEUS_RTG.DBO.TAB_PEDIDO_PRODUTO AS PP ON (P.COD_LOJA = PP.COD_LOJA AND P.COD_PARCEIRO = PP.COD_PARCEIRO AND P.NUM_PEDIDO = PP.NUM_PEDIDO)
WHERE 1 = 1
	AND CONVERT(DATE,P.DTA_EMISSAO) >= CONVERT(DATE,GETDATE()-7)
	
DELETE RP
FROM
	@RUP_SEM_PED AS RP INNER JOIN @PEDIDOS_7D AS P ON (RP.COD_LOJA = P.COD_LOJA AND RP.COD_PRODUTO = P.COD_PRODUTO)


SELECT * FROM @RUP_SEM_PED