DECLARE @TAB_LOJA AS TABLE
(
	ANO INT
	,MES INT
	,COD_LOJA INT
	,TOTAL_VLR_LOJA NUMERIC(10,2)
	,TOTAL_QTDE_LOJA NUMERIC(10,2)
)

INSERT INTO @TAB_LOJA
SELECT
	YEAR(VP.DATA) AS ANO
	,MONTH(VP.DATA) AS MES
	,VP.COD_LOJA
	,SUM(VALOR_TOTAL) AS TOTAL_VLR_LOJA
	,SUM(QTDE_PRODUTO) AS TOTAL_QTDE_LOJA
FROM
	BI.DBO.BI_CAD_PRODUTO AS CP INNER JOIN BI.DBO.BI_VENDA_PRODUTO AS VP ON (CP.COD_PRODUTO = VÁP.COD_PRODUTO)
WHERE 1 = 1
	AND CONVERT(DATE,VP.DATA) BETWEEN CONVERT(DATE,'20130101') AND CONVERT(DATE,'20140228')
GROUP BY
	YEAR(VP.DATA)
	,MONTH(VP.DATA)
	,VP.COD_LOJA


DECLARE @TAB_DEP AS TABLE
(
	ANO INT
	,MES INT
	,COD_LOJA INT
	,COD_DEPARTAMENTO INT
	,NO_DEPARTAMENTO VARCHAR(30)
	,TOTAL_VLR_DEP NUMERIC(10,2)
	,TOTAL_QTDE_DEP NUMERIC(10,2)
)

INSERT INTO @TAB_DEP
SELECT
	YEAR(VP.DATA) AS ANO
	,MONTH(VP.DATA) AS MES
	,VP.COD_LOJA
	,CP.COD_DEPARTAMENTO
	,CP.NO_DEPARTAMENTO
	,SUM(VALOR_TOTAL) AS TOTAL_VLR_DEP
	,SUM(QTDE_PRODUTO) AS TOTAL_QTDE_DEP
FROM
	BI.DBO.BI_CAD_PRODUTO AS CP INNER JOIN BI.DBO.BI_VENDA_PRODUTO AS VP ON (CP.COD_PRODUTO = VP.COD_PRODUTO)
WHERE 1 = 1
	AND CONVERT(DATE,VP.DATA) BETWEEN CONVERT(DATE,'20130101') AND CONVERT(DATE,'20140228')
	AND CP.COD_DEPARTAMENTO = 5
GROUP BY
	YEAR(VP.DATA)
	,MONTH(VP.DATA)
	,VP.COD_LOJA
	,CP.COD_DEPARTAMENTO
	,CP.NO_DEPARTAMENTO
	
SELECT
	L.ANO
	,L.MES
	,L.COD_LOJA
	,D.COD_DEPARTAMENTO
	,D.NO_DEPARTAMENTO
	,dbo.fn_FormataVlr_Excel(L.TOTAL_VLR_LOJA) AS TOTAL_VLR_LOJA
	,dbo.fn_FormataVlr_Excel(D.TOTAL_VLR_DEP) AS TOTAL_VLR_DEP
	,dbo.fn_FormataVlr_Excel(L.TOTAL_QTDE_LOJA) AS TOTAL_QTDE_LOJA
	,dbo.fn_FormataVlr_Excel(D.TOTAL_QTDE_DEP) AS TOTAL_QTDE_DEP
FROM
	@TAB_LOJA AS L LEFT JOIN @TAB_DEP AS D ON (L.ANO = D.ANO AND L.MES = D.MES AND L.COD_LOJA = D.COD_LOJA)
ORDER BY
	L.COD_LOJA
	,L.ANO
	,L.MES