SELECT
	LINHA.[COD_LOJA]
	,LINHA.[COD_PRODUTO]
	,LINHA.[COD_SECAO]
	,LINHA.[COD_GRUPO]
	,LINHA.[FORA_LINHA]
	,LINHA.[ENVIA_PDV]
	,LINHA.[CLASSIF_PRODUTO_LOJA]
	,LINHA.[QTDE_PRODUTO_1ANO]
	,LINHA.[VALOR_TOTAL_1ANO]
	,MOV.[QTD_ESTOQUE]
FROM
	[BI].[dbo].[BI_LINHA_PRODUTOS] AS LINHA LEFT JOIN [BI].[dbo].[BI_TESTE_MOVIMENTO_PRODUTOS] AS MOV ON (LINHA.COD_PRODUTO = MOV.COD_PRODUTO AND LINHA.COD_LOJA = MOV.COD_LOJA)
WHERE 1 = 1
AND LINHA.FORA_LINHA = 'S'
--AND LINHA.QTDE_PRODUTO_1ANO > 0;



select * from [192.168.0.6].zeus_rtg.dbo.tab_secao where cod_secao not in (6,10,37,40,41,15,35,19,99,9,16,20)

SELECT
	LINHA.[COD_LOJA]
	,LINHA.[COD_PRODUTO]
	,PROD.DESCRICAO
	,LINHA.[COD_SECAO]
	,LINHA.[COD_GRUPO]
	,LINHA.[FORA_LINHA]
	,LINHA.[ENVIA_PDV]
	,LINHA.[CLASSIF_PRODUTO_LOJA]
	,LINHA.[QTDE_PRODUTO_1ANO]
	,LINHA.[VALOR_TOTAL_1ANO]
FROM
	BI_LINHA_PRODUTOS AS LINHA left join BI_CAD_PRODUTO AS PROD ON (LINHA.COD_PRODUTO = PROD.COD_PRODUTO)
WHERE 1=1
	AND LINHA.COD_PRODUTO IN
	(
		SELECT  DISTINCT
		[COD_PRODUTO]
		FROM AX2009_INTEGRACAO.dbo.TAB_REFERENCIA_FORNECEDOR
		WHERE 1=1
		AND COD_FORNECEDOR = 61
		AND COD_PRODUTO IN (SELECT COD_PRODUTO FROM BI_CAD_PRODUTO WHERE COD_SECAO = 39)
	)
	AND LINHA.FORA_LINHA = 'S'


FORNECEDORES:
SELECT [COD_FORNECEDOR]
      ,[DESCRICAO] AS NO_FORNECEDOR
  FROM [BI].[dbo].[BI_CAD_FORNECEDOR]
  where COD_FORNECEDOR = 101662
;


 SELECT  [COD_FORNECEDOR]
		  ,[COD_PRODUTO]
		  ,[COD_LOJA]
		  ,[QTD_EMBALAGEM_COMPRA]
		  ,[VAL_CUSTO_EMBALAGEM]
		  ,[VAL_DESCONTO_PER_1]
		  --,[QTD_EST_ATUAL]
		  ,[ipv]
		  ,[val_venda]
  FROM [BI].[dbo].[PRODUTO_FORNECEDOR_LINHA]
  WHERE 1=1
  AND COD_LOJA  IN (1,2,3,6,7,9,12,13,17,18,20,10,4,19)
  AND COD_FORNECEDOR = 61
  AND COD_PRODUTO IN (SELECT COD_PRODUTO FROM BI_CAD_PRODUTO WHERE COD_SECAO = 39)
  

  
   SELECT  DISTINCT
		  [COD_PRODUTO]
  FROM [BI].[dbo].[PRODUTO_FORNECEDOR_LINHA]
  WHERE 1=1
    AND COD_FORNECEDOR = 101662
  AND COD_PRODUTO IN (SELECT COD_PRODUTO FROM BI_CAD_PRODUTO WHERE COD_SECAO = 39)