UPDATE RIT
SET
	RIT.MARCHE_SHELFLIFE = CP.DIAS_VALIDADE	
FROM
	[BI].[dbo].[BI_CAD_PRODUTO] AS CP
	INNER JOIN SMA_AX50_SP1_DB_PROD.dbo.RBOINVENTTABLE AS RIT
		ON 1=1
		AND CP.COD_PRODUTO = CONVERT(INT,RIT.ITEMID)
WHERE 1=1
	AND CP.COD_DEPARTAMENTO = 4
	AND CP.COD_SECAO IN (44,45,46,48)