SELECT
	CP.COD_FORNECEDOR
	,CF.DES_FANTASIA
	,CP.COD_PRODUTO
	,CP.DESCRICAO
	,C.VLR_EMB_COMPRA AS VLR_CUSTO
	,BI.dbo.fn_FormataVlr_Excel(CP.VLR_MRGREF_MIN) AS VLR_MRGREF_MIN
	,BI.dbo.fn_FormataVlr_Excel(CP.VLR_MRGREF_MAX) AS VLR_MRGREF_MAX
	,(SELECT BI.dbo.fn_FormataVlr_Excel(SUM(VALOR_TOTAL)) FROM BI_VENDA_PRODUTO AS TVP WHERE CP.COD_PRODUTO = TVP.COD_PRODUTO AND CONVERT(DATE,TVP.DATA) BETWEEN CONVERT(DATE,'20130101') AND CONVERT(DATE,'20131231')) AS VLR_VENDA_2013
	,(SELECT BI.dbo.fn_FormataVlr_Excel(SUM(QTDE_PRODUTO)) FROM BI_VENDA_PRODUTO AS TVP WHERE CP.COD_PRODUTO = TVP.COD_PRODUTO AND CONVERT(DATE,TVP.DATA) BETWEEN CONVERT(DATE,'20130101') AND CONVERT(DATE,'20131231')) AS QTD_VENDA_2013
	,BI.dbo.fn_FormataVlr_Excel(SUM(VP.VALOR_TOTAL)) AS VLR_VENDA_2014
	,BI.dbo.fn_FormataVlr_Excel(SUM(VP.QTDE_PRODUTO)) AS QTD_VENDA_2014	
FROM
	BI.DBO.BI_CAD_PRODUTO AS CP
	INNER JOIN BI.DBO.BI_VENDA_PRODUTO AS VP
		ON 1=1
		AND CP.COD_PRODUTO = VP.COD_PRODUTO
	INNER JOIN VW_CUSTOS_ATIVOS AS C
		ON 1=1
		AND CP.COD_PRODUTO = C.COD_PRODUTO
		AND CP.COD_FORNECEDOR = C.COD_FORNECEDOR
	INNER JOIN BI.DBO.BI_CAD_FORNECEDOR AS CF
		ON 1=1
		AND CP.COD_FORNECEDOR = CF.COD_FORNECEDOR
	
WHERE 1 = 1
	AND CONVERT(DATE,VP.DATA) >= CONVERT(DATE,'20140101')
	AND CP.COD_DEPARTAMENTO = 3
	AND CP.COD_SECAO = 62
	AND CP.COD_GRUPO = 11
GROUP BY
	CP.COD_FORNECEDOR
	,CF.DES_FANTASIA
	,CP.COD_PRODUTO
	,CP.DESCRICAO
	,C.VLR_EMB_COMPRA
	,CP.VLR_MRGREF_MIN
	,CP.VLR_MRGREF_MAX