select
	8 AS COD_LOJA
	,ALTEC.DATA
	,isnull(PROD.PLU,999999) AS COD_PRODUTO
	,2 AS TIPO_VENDA 
	,SUM(QTDE) AS QTDE_PRODUTO
	,SUM(TOTAL) AS VALOR_TOTAL
	,0 AS VALOR_UNITARIO
	,COUNT(QTDE) AS QTDE_DEMANDA
	,0 AS COD_CLIENTE
from
	[192.168.0.6].Alltec.dbo.ITENS_CUPONS as ALTEC left outer join [192.168.0.6].Alltec.dbo.PRODUTO as PROD	on (PROD.CODPRODUTO = ALTEC.PRODUTO	AND PROD.COD_LOJA = ALTEC.COD_lOJA)
WHERE 1 = 1
	and ALTEC.DATA between convert(date,'20140101') and convert(date,'20140131')
GROUP BY
	ALTEC.DATA
	,PROD.PLU
	


select
	8 AS [COD_LOJA] 
	,DATA AS [DATA] 
	,COUNT(NUMERO_CUPOM) AS [QTDE_CUPOM]
	,SUM(VALOR_ITENS) AS [VALOR_TOTAL]
	,AVG(VALOR_ITENS) AS [CUPOM_MEDIO]
	,2 AS TIPO
from
	[192.168.0.6].Alltec.dbo.CUPONS_FISCAIS
WHERE 1 = 1
	AND DATA >= @DT_INICIO
	AND DATA <= @DT_TErmino
GROUP BY
	DATA 





select
	COD_LOJA
	,TIPO_VENDA
	,SUM(VALOR_TOTAL)
from
	BI_VENDA_PRODUTO
where 1 = 1
	and TIPO_VENDA = 2
	and DATA between convert(date,'20140101') and convert(date,'20140131') 
GROUP BY
	COD_LOJA
	,TIPO_VENDA

UNION ALL

select
	COD_LOJA
	,TIPO
	,SUM(VALOR_TOTAL)
from
	BI_VENDA_CUPOM
where 1 = 1
	and TIPO = 2
	and DATA between convert(date,'20140101') and convert(date,'20140131') 
GROUP BY
	COD_LOJA
	,TIPO
	

select
	COD_LOJA
	,TIPO_VENDA
	--,VP.COD_PRODUTO
	,CP.NO_DEPARTAMENTO
	--,CP.NO_SECAO
	--,CP.NO_GRUPO
	--,CP.NO_SUBGRUPO
	,SUM(VALOR_TOTAL) AS VENDA
from
	BI_VENDA_PRODUTO AS VP LEFT JOIN BI_CAD_PRODUTO AS CP ON (VP.COD_PRODUTO = CP.COD_PRODUTO)
where 1 = 1
	and TIPO_VENDA = 2
	and DATA between convert(date,'20140101') and convert(date,'20140131') 
GROUP BY
	COD_LOJA
	,TIPO_VENDA
	--,VP.COD_PRODUTO
	,CP.NO_DEPARTAMENTO
	--,CP.NO_SECAO
	--,CP.NO_GRUPO
	--,CP.NO_SUBGRUPO
	
	
SELECT
	COD_LOJA
	,COD_DEPARTAMENTO
	,COD_SECAO
	,COD_GRUPO
	,SUM(VLR_VENDA) AS VENDA
FROM [BI].[dbo].[BI_VENDA_GRUPO]
where 1 = 1
	and DATA between convert(date,'20140101') and convert(date,'20140131')
	AND COD_LOJA = 8
GROUP BY
	COD_LOJA
	,COD_DEPARTAMENTO
	,COD_SECAO
	,COD_GRUPO
	

SELECT
	COD_LOJA
	,COD_DEPARTAMENTO
	,COD_SECAO
	,COD_GRUPO
	,SUM(VLR_META) AS VLR_META
FROM [BI].[dbo].[BI_VENDA_META_GRUPO]
where 1 = 1
	and DATA between convert(date,'20140101') and convert(date,'20140131')
	AND COD_LOJA = 8
	AND VLR_META > 0
GROUP BY
	COD_LOJA
	,COD_DEPARTAMENTO
	,COD_SECAO
	,COD_GRUPO