	DECLARE @DATA_INI AS DATE = GETDATE()-5
-- ------------------------------------------------------------------------------------------------
-- IMPORTADO - INSERT
-- ------------------------------------------------------------------------------------------------DECLARE @DATA_INI AS DATE = GETDATE()-1
	INSERT INTO BI.DBO.CADASTRO_CAD_PRODUTO_METADADOS
	(
		COD_PRODUTO
		,COD_METADADO
		,VLR_METADADO
	)
	SELECT DISTINCT
		CPN.ITEMID
		,3 AS COD_METADADO
		,CPN.MDT_IMP
	FROM 
		BI.DBO.CADASTRO_CAD_PRODUTO_NOVO AS CPN
			LEFT JOIN BI.DBO.CADASTRO_CAD_PRODUTO_METADADOS AS PM
			ON 1 = 1
			AND CPN.ITEMID = PM.COD_PRODUTO
			AND PM.COD_METADADO = 3
	WHERE 1 = 1
		AND CONVERT(DATE,CPN.DTA_GRAVACAO) >= CONVERT(DATE,@DATA_INI)
		AND CPN.MDT_IMP IS NOT NULL
		AND PM.VLR_METADADO IS NULL
		AND CPN.ITEMID IS NOT NULL
		AND ISNUMERIC(CPN.MDT_IMP) = 1
		AND CPN.PRODUTO_NOVO = 1
	
-- ------------------------------------------------------------------------------------------------
-- MARCA - INSERT
-- ------------------------------------------------------------------------------------------------DECLARE @DATA_INI AS DATE = GETDATE()-1
	INSERT INTO BI.DBO.CADASTRO_CAD_PRODUTO_METADADOS
	(
		COD_PRODUTO
		,COD_METADADO
		,VLR_METADADO
	)
	SELECT DISTINCT
		CPN.ITEMID
		,6 AS COD_METADADO
		,CPN.MDT_NO_MARCA
	FROM 
		BI.DBO.CADASTRO_CAD_PRODUTO_NOVO AS CPN
			LEFT JOIN BI.DBO.CADASTRO_CAD_PRODUTO_METADADOS AS PM
			ON 1 = 1
			AND CPN.ITEMID = PM.COD_PRODUTO
			AND PM.COD_METADADO = 6
	WHERE 1 = 1
		AND CONVERT(DATE,CPN.DTA_GRAVACAO) >= CONVERT(DATE,@DATA_INI)
		AND CPN.MDT_NO_MARCA IS  NOT NULL
		AND PM.VLR_METADADO IS NULL
		AND CPN.ITEMID IS NOT NULL
		AND ISNUMERIC(CPN.MDT_NO_MARCA) = 0
		AND CPN.PRODUTO_NOVO = 1
		
-- ------------------------------------------------------------------------------------------------
-- UNIDADE MEDIDA - INSERT
-- ------------------------------------------------------------------------------------------------DECLARE @DATA_INI AS DATE = GETDATE()-180
	INSERT INTO BI.DBO.CADASTRO_CAD_PRODUTO_METADADOS
	(
		COD_PRODUTO
		,COD_METADADO
		,VLR_METADADO
	)
	SELECT DISTINCT
		CPN.ITEMID
		,20 AS COD_METADADO
		,CPN.MDT_UNI_MEDIDA
	FROM 
		BI.DBO.CADASTRO_CAD_PRODUTO_NOVO AS CPN
			LEFT JOIN BI.DBO.CADASTRO_CAD_PRODUTO_METADADOS AS PM
			ON 1 = 1
			AND CPN.ITEMID = PM.COD_PRODUTO
			AND PM.COD_METADADO = 20
	WHERE 1 = 1
		AND CONVERT(DATE,CPN.DTA_GRAVACAO) >= CONVERT(DATE,@DATA_INI)
		AND CPN.MDT_UNI_MEDIDA IS  NOT NULL
		AND PM.VLR_METADADO IS NULL
		AND CPN.ITEMID IS NOT NULL
		AND ISNUMERIC(CPN.MDT_UNI_MEDIDA) = 0
		AND CPN.PRODUTO_NOVO = 1

-- ------------------------------------------------------------------------------------------------
-- QTD UNIDADE MEDIDA - INSERT
-- ------------------------------------------------------------------------------------------------DECLARE @DATA_INI AS DATE = GETDATE()-100
	INSERT INTO BI.DBO.CADASTRO_CAD_PRODUTO_METADADOS
	(
		COD_PRODUTO
		,COD_METADADO
		,VLR_METADADO
	)
	SELECT DISTINCT
		CPN.ITEMID
		,21 AS COD_METADADO
		,CPN.MDT_QTD_UNI_MEDIDA
	FROM 
		BI.DBO.CADASTRO_CAD_PRODUTO_NOVO AS CPN
			LEFT JOIN BI.DBO.CADASTRO_CAD_PRODUTO_METADADOS AS PM
			ON 1 = 1
			AND CPN.ITEMID = PM.COD_PRODUTO
			AND PM.COD_METADADO = 21
	WHERE 1 = 1
		AND CONVERT(DATE,CPN.DTA_GRAVACAO) >= CONVERT(DATE,@DATA_INI)
		AND CPN.MDT_QTD_UNI_MEDIDA IS  NOT NULL
		AND PM.VLR_METADADO IS NULL
		AND CPN.ITEMID IS NOT NULL
		AND ISNUMERIC(CPN.MDT_QTD_UNI_MEDIDA) = 1
		AND CPN.PRODUTO_NOVO = 1

-- ------------------------------------------------------------------------------------------------
-- PAIS DE ORIGEM - INSERT
-- ------------------------------------------------------------------------------------------------DECLARE @DATA_INI AS DATE = GETDATE()-1
	INSERT INTO BI.DBO.CADASTRO_CAD_PRODUTO_METADADOS
	(
		COD_PRODUTO
		,COD_METADADO
		,VLR_METADADO
	)
	SELECT DISTINCT
		CPN.ITEMID
		,8 AS COD_METADADO
		,CPN.MDT_NO_PAIS_ORG
	FROM 
		BI.DBO.CADASTRO_CAD_PRODUTO_NOVO AS CPN
			LEFT JOIN BI.DBO.CADASTRO_CAD_PRODUTO_METADADOS AS PM
			ON 1 = 1
			AND CPN.ITEMID = PM.COD_PRODUTO
			AND PM.COD_METADADO = 8
	WHERE 1 = 1
		AND CONVERT(DATE,CPN.DTA_GRAVACAO) >= CONVERT(DATE,@DATA_INI)
		AND CPN.MDT_NO_PAIS_ORG IS  NOT NULL
		AND PM.VLR_METADADO IS NULL
		AND CPN.ITEMID IS NOT NULL
		AND ISNUMERIC(CPN.MDT_NO_PAIS_ORG) = 0
		AND CPN.PRODUTO_NOVO = 1

-- ------------------------------------------------------------------------------------------------
-- IMPORTACAO PROPRIA - INSERT
-- ------------------------------------------------------------------------------------------------DECLARE @DATA_INI AS DATE = GETDATE()-1
	INSERT INTO BI.DBO.CADASTRO_CAD_PRODUTO_METADADOS
	(
		COD_PRODUTO
		,COD_METADADO
		,VLR_METADADO
	)
	SELECT DISTINCT
		CPN.ITEMID
		,4 AS COD_METADADO
		,CPN.MTD_IP
	FROM 
		BI.DBO.CADASTRO_CAD_PRODUTO_NOVO AS CPN
			LEFT JOIN BI.DBO.CADASTRO_CAD_PRODUTO_METADADOS AS PM
			ON 1 = 1
			AND CPN.ITEMID = PM.COD_PRODUTO
			AND PM.COD_METADADO = 4
	WHERE 1 = 1
		AND CONVERT(DATE,CPN.DTA_GRAVACAO) >= CONVERT(DATE,@DATA_INI)
		AND CPN.MTD_IP IS  NOT NULL
		AND PM.VLR_METADADO IS NULL
		AND CPN.ITEMID IS NOT NULL
		AND ISNUMERIC(CPN.MTD_IP) = 1
		AND CPN.PRODUTO_NOVO = 1
		
-- ------------------------------------------------------------------------------------------------
-- MARCA PROPRIA - INSERT
-- ------------------------------------------------------------------------------------------------DECLARE @DATA_INI AS DATE = GETDATE()-1
	INSERT INTO BI.DBO.CADASTRO_CAD_PRODUTO_METADADOS
	(
		COD_PRODUTO
		,COD_METADADO
		,VLR_METADADO
	)
	SELECT DISTINCT
		CPN.ITEMID
		,1 AS COD_METADADO
		,CPN.MTD_MP
	FROM 
		BI.DBO.CADASTRO_CAD_PRODUTO_NOVO AS CPN
			LEFT JOIN BI.DBO.CADASTRO_CAD_PRODUTO_METADADOS AS PM
			ON 1 = 1
			AND CPN.ITEMID = PM.COD_PRODUTO
			AND PM.COD_METADADO = 1
	WHERE 1 = 1
		AND CONVERT(DATE,CPN.DTA_GRAVACAO) >= CONVERT(DATE,@DATA_INI)
		AND CPN.MTD_MP IS  NOT NULL
		AND PM.VLR_METADADO IS NULL
		AND CPN.ITEMID IS NOT NULL
		AND ISNUMERIC(CPN.MTD_MP) = 1
		AND CPN.PRODUTO_NOVO = 1
		
-- ------------------------------------------------------------------------------------------------
-- MARCA PROPRIA - UPDATE
-- ------------------------------------------------------------------------------------------------DECLARE @DATA_INI AS DATE = GETDATE()-1
/*
	UPDATE PM
	SET
		PM.VLR_METADADO = CPN.MTD_MP
	FROM 
		BI.DBO.CADASTRO_CAD_PRODUTO_NOVO AS CPN
			LEFT JOIN BI.DBO.CADASTRO_CAD_PRODUTO_METADADOS AS PM
			ON 1 = 1
			AND CPN.ITEMID = PM.COD_PRODUTO
			AND PM.COD_METADADO = 1
	WHERE 1 = 1
		AND CONVERT(DATE,CPN.DTA_GRAVACAO) >= CONVERT(DATE,@DATA_INI)
		AND CPN.MTD_MP IS NOT NULL
		AND CPN.MTD_MP <> PM.VLR_METADADO
		AND PM.VLR_METADADO IS NOT NULL
		AND CPN.ITEMID IS NOT NULL
		AND ISNUMERIC(CPN.MTD_MP) = 1
		AND CPN.PRODUTO_NOVO = 1
*/