SELECT
	CAD_PRODUTO.[COD_PRODUTO]
	,CAD_PRODUTO.[COD_SECAO]
	,CAD_PRODUTO.[COD_GRUPO]
	,CAD_PRODUTO.[COD_SUB_GRUPO]
	,CAD_PRODUTO.[NO_GRUPO]
	,CAD_PRODUTO.NO_PRODUTO
	,CAD_PRODUTO.[PESADO]
	,CAD_PRODUTO.[FLG_MARCA_PROPRIA]
	,CAD_PRODUTO.FORA_LINHA
	,CAD_PRODUTO.COD_FORNECEDOR_PRINCIPAL
	,FORN_PRODUTO.[COD_FORNECEDOR]
	,FORN_PRODUTO.[QTD_EMBALAGEM_COMPRA]
	,FORN_PRODUTO.[VAL_CUSTO_EMBALAGEM]
	,FORN_PRODUTO.[VAL_DESCONTO_PER_1]
	,FORN_PRODUTO.[QTD_EST_ATUAL]
	,FORN_PRODUTO.[ipv]
	,FORN_PRODUTO.[val_venda]
	,TAB_IMPOSTO_1.ICMS_ALIQ_ENTRADA
	,TAB_IMPOSTO_2.ICMS_ALIQ
	,TAB_IMPOSTO_2.PIS_COFINS
FROM
(
	SELECT
		[COD_PRODUTO]
		,[COD_SECAO]
		,[COD_GRUPO]
		,[COD_SUB_GRUPO]
		--,[NO_SECAO]
		,[NO_GRUPO]
		,[DESCRICAO] AS NO_PRODUTO
		,[PESADO]
		,[FLG_MARCA_PROPRIA]
		,FORA_LINHA
		,COD_FORNECEDOR AS COD_FORNECEDOR_PRINCIPAL
	FROM [BI].[dbo].[BI_CAD_PRODUTO]
	WHERE 1=1
) AS CAD_PRODUTO

LEFT JOIN

(
	SELECT 
		[COD_FORNECEDOR]
		,[COD_PRODUTO]
		,[COD_LOJA]
		,[QTD_EMBALAGEM_COMPRA]
		,[VAL_CUSTO_EMBALAGEM]
		,[VAL_DESCONTO_PER_1]
		,[QTD_EST_ATUAL]
		,[ipv]
		,[val_venda]
	FROM [BI].[dbo].[PRODUTO_FORNECEDOR_LINHA]
	WHERE 1=1
		AND COD_LOJA  IN (1,2,3,6,7,9,12,13,17,18,20)
		AND COD_FORNECEDOR NOT IN (14322,14357,14775,16386,14721,2355,14321)
) AS FORN_PRODUTO ON (FORN_PRODUTO.[COD_PRODUTO] = CAD_PRODUTO.[COD_PRODUTO])

LEFT JOIN 

(
	SELECT
		COD_PRODUTO
		,SUM([VAL_TABELA_LIQ]*i.ICMS_ALIQ)/SUM(CASE WHEN [VAL_TABELA_LIQ] = 0 THEN 1 ELSE [VAL_TABELA_LIQ] END ) AS ICMS_ALIQ_ENTRADA

	FROM
		[192.168.0.6].[Zeus_Rtg].[dbo].[vw_MARCHE_ENTRADAS_GERAIS] AS nf INNER JOIN [BI].[dbo].[ICMS_ALIQ] AS i ON nf.[COD_TRIBUTACAO] = i.ICMS_COD
	where 1=1
		and ano = 2012
		AND BONIFICACAO = 'N'
	GROUP BY  COD_PRODUTO
) as TAB_IMPOSTO_1  ON (TAB_IMPOSTO_1.[COD_PRODUTO] = CAD_PRODUTO.[COD_PRODUTO])

LEFT JOIN

(
	SELECT
		[COD_PRODUTO]
		,max(ICMS_ALIQ) as ICMS_ALIQ
		,max([PIS_COFINS]) as [PIS_COFINS]
	FROM
		[192.168.0.6].[Zeus_Rtg].[dbo].[AX_TABELA_IMPOSTOS] as p LEFT JOIN [BI].[dbo].[ICMS_ALIQ] AS i ON P.[COD_TRIBUTACAO] = i.ICMS_COD
	group by [COD_PRODUTO]
) as TAB_IMPOSTO_2  ON (TAB_IMPOSTO_2.[COD_PRODUTO] = CAD_PRODUTO.[COD_PRODUTO])


WHERE 1 = 1
	AND FORN_PRODUTO.COD_FORNECEDOR = 17797