	--TRUNCATE TABLE BI.DBO.BI_VENDA_CUPOM_PRODUTO
	DECLARE @DT_INICIO AS DATE = '20140821'
	DECLARE @DT_TERMINO AS DATE = '20140824'
	
	INSERT INTO BI.DBO.BI_VENDA_CUPOM_PRODUTO
	(
		[DATA]
		,[HORA]
		,[COD_LOJA]
		,[CAIXA]
		,[CUPOM]
		,[COD_PRODUTO]
		,[COD_OPERADOR]
		,[VLR_VENDA]
		,[QTDE_VENDA]
		,[VLR_DESCONTO]
	)
	SELECT
		MC.DATA
		,MC.HORA
		,MC.COD_LOJA
		,MC.CAIXA
		,MC.CUPOM
		,T.COD_PRODUTO
		,MC.OPERADOR
		,SUM(T.VALOR) AS VLR_VENDA
		,SUM(T.QTDE) AS QTDE_VENDA
		,SUM(MC.VALOR_DESCONTO)
	FROM
		[DW].[DBO].[BI_ANAL_MOVTO_CAIXA] AS MC
		INNER JOIN [DW].[DBO].[BI_ANAL_TICKET] AS T
			ON 1=1
			AND MC.COD_LOJA = T.COD_LOJA
			AND MC.CAIXA = T.CAIXA
			AND MC.CUPOM = T.CUPOM
	WHERE 1 = 1
		AND T.COD_PRODUTO IS NOT NULL
		AND CONVERT(DATE,MC.DATA) BETWEEN CONVERT(DATE,@DT_INICIO) AND CONVERT(DATE,@DT_TERMINO)
	GROUP BY
		MC.DATA
		,MC.HORA
		,MC.COD_LOJA
		,MC.CAIXA
		,MC.CUPOM
		,T.COD_PRODUTO
		,MC.OPERADOR
		
		

