INSERT INTO BI_ESTOQUE_PRODUTO_DIA
(
	[COD_LOJA]
	,[COD_PRODUTO]
	,[DATA]
	,[QTD_ESTOQUE]
)
SELECT
	[COD_LOJA]
	,[COD_PRODUTO]
	,CONVERT(DATE,DTA_MOVIMENTO)
	,[QTD_ESTOQUE]	
FROM [192.168.0.6].ZEUS_RTG.DBO.TAB_PRODUTO_MOVIMENTO AS M WHERE CONVERT(DATE,DTA_MOVIMENTO) = '20140901'