	DECLARE @DTA_INI AS DATE = '20140101'
	DECLARE @DTA_FIM AS DATE = '20141001'
		
	INSERT INTO [BI].[dbo].[BI_MARGEM_PRODUTO_MES]
	(
		[COD_LOJA]
		,[ANO]
		,[MES]
		,[COD_PRODUTO]
		,[LUCRO_BRUTO]
		,[VLR_VENDA]
		,[VLR_AJUSTE]	
		,[VLR_MRG]
	)
	SELECT
		(CASE WHEN VPM.COD_LOJA = 4 THEN 23 WHEN VPM.COD_LOJA = 10 THEN 22 WHEN VPM.COD_LOJA = 19 THEN 24 ELSE VPM.COD_LOJA END) AS COD_LOJA
		,YEAR(VPM.DATA) AS ANO
		,MONTH(VPM.DATA) AS MES
		,VPM.COD_PRODUTO	
		,(SUM(VPM.VLR_VENDA_BRUTA) - SUM(VPM.VLR_CMV) - SUM(VPM.VLR_PISCOFINS) - SUM(VPM.VLR_ICMS_SAIDA*VPM.VLR_VENDA_BRUTA)) AS LB
		,SUM(VPM.VLR_VENDA_BRUTA) AS VLR_VENDA
		,ISNULL((SELECT A.AJUSTE_NET FROM [BI].[dbo].[BI_MARGEM_PRODUTO_AJUSTE] AS A WHERE A.COD_LOJA = (CASE WHEN VPM.COD_LOJA = 4 THEN 23 WHEN VPM.COD_LOJA = 10 THEN 22 WHEN VPM.COD_LOJA = 19 THEN 24 ELSE VPM.COD_LOJA END) AND YEAR(VPM.DATA) = A.ANO AND MONTH(VPM.DATA) = A.MES AND VPM.COD_PRODUTO = A.COD_PRODUTO),0) as VLR_AJUSTE
		,(SUM(VPM.VLR_VENDA_BRUTA) - SUM(VPM.VLR_CMV) - SUM(VPM.VLR_PISCOFINS) - SUM(VPM.VLR_ICMS_SAIDA*VPM.VLR_VENDA_BRUTA) + ISNULL((SELECT A.AJUSTE_NET FROM [BI].[dbo].[BI_MARGEM_PRODUTO_AJUSTE] AS A WHERE A.COD_LOJA = (CASE WHEN VPM.COD_LOJA = 4 THEN 23 WHEN VPM.COD_LOJA = 10 THEN 22 WHEN VPM.COD_LOJA = 19 THEN 24 ELSE VPM.COD_LOJA END) AND YEAR(VPM.DATA) = A.ANO AND MONTH(VPM.DATA) = A.MES AND VPM.COD_PRODUTO = A.COD_PRODUTO),0)) / (CASE WHEN SUM(VLR_VENDA_BRUTA) = 0 THEN 9999999 ELSE SUM(VLR_VENDA_BRUTA) END) AS VLR_MRG
	FROM
		[BI].[dbo].[BI_VENDA_PRODUTO_CMV] AS VPM	
	WHERE 1=1
		AND CONVERT(DATE,VPM.DATA) >= CONVERT(DATE,@DTA_INI)
		AND CONVERT(DATE,VPM.DATA) < CONVERT(DATE,@DTA_FIM)
	GROUP BY
		(CASE WHEN VPM.COD_LOJA = 4 THEN 23 WHEN VPM.COD_LOJA = 10 THEN 22 WHEN VPM.COD_LOJA = 19 THEN 24 ELSE VPM.COD_LOJA END)
		,YEAR(VPM.DATA)
		,MONTH(VPM.DATA)
		,VPM.COD_PRODUTO
	ORDER BY
		(CASE WHEN VPM.COD_LOJA = 4 THEN 23 WHEN VPM.COD_LOJA = 10 THEN 22 WHEN VPM.COD_LOJA = 19 THEN 24 ELSE VPM.COD_LOJA END)
		,YEAR(VPM.DATA)
		,MONTH(VPM.DATA)
		,VPM.COD_PRODUTO
		