SELECT
	PROD.*
	,RBO.*
	,ISNULL(CAST(RBO.DIVISIONGROUP AS INT),10) AS COD_SECAO
	,ISNULL(RIGHT(RBO.ITEMDEPARTMENT,(LEN(RBO.ITEMDEPARTMENT) - (CHARINDEX(RBO.DIVISIONGROUP,RBO.ITEMDEPARTMENT) + LEN(RBO.DIVISIONGROUP)-1))),3) AS COD_GRUPO
	,(CASE
		WHEN RBO.RETAILGROUP <> '' THEN
		 CAST(LEFT(RBO.RETAILGROUP,   (LEN(RBO.RETAILGROUP) - (LEN(RIGHT(RBO.ITEMDEPARTMENT,(LEN(RBO.ITEMDEPARTMENT) - (CHARINDEX(RBO.DIVISIONGROUP,RBO.ITEMDEPARTMENT) + LEN(RBO.DIVISIONGROUP)-1)))) + LEN(CONVERT(INT,RBO.DIVISIONGROUP))))   ) AS INT)
		ELSE 1
	  END) AS COD_SUB_GRUPO	
FROM
SMA_AX50_SP1_DB_PROD.dbo.INVENTTABLE AS PROD INNER JOIN	SMA_AX50_SP1_DB_PROD.dbo.RBOINVENTTABLE AS RBO ON (RBO.DATAAREAID = PROD.DATAAREAID AND RBO.ITEMID = PROD.ITEMID)
	LEFT JOIN AX2009_INTEGRACAO.DBO.TAB_CODIGO_BARRA_PRINCIPAL AS CODBARRA ON (CODBARRA.itemid = RBO.ITEMID)
WHERE 1 =1 
	AND PROD.DATAAREAID = 'VCM'
	AND CODBARRA.COD_EAN is null
	and PROD.ITEMNAME not like '%PLU BAIXO VAGO%'
	AND ISNULL(CAST(RBO.DIVISIONGROUP AS INT),10)  <> 6
	and PROD.ITEMNAME not like '%REV.%'
	and PROD.ITEMNAME not like '%REVISTA%'
	AND PROD.CREATEDDATETIME >= '20140101'
	AND ISNULL(CAST(RBO.DIVISIONGROUP AS INT),10) <> 0