	DECLARE @DT_INICIO AS DATE = CONVERT(DATE,'20130101')
	DECLARE @DT_TERMINO AS DATE = CONVERT(DATE,'20130201')
	
	SELECT
		CUPOM.COD_LOJA
		,CUPOM.VALOR_TOTAL AS VLR_CUPOM
		,PRODUTO.VALOR_TOTAL AS VLR_PROD
		,GRUPO.VALOR_TOTAL AS VLR_GRUPO
		,CUPOM.VALOR_TOTAL - PRODUTO.VALOR_TOTAL AS DIFF_CUPOM_PROD
		,CUPOM.VALOR_TOTAL - GRUPO.VALOR_TOTAL AS DIFF_CUPOM_GRUPO
		,PRODUTO.VALOR_TOTAL - GRUPO.VALOR_TOTAL AS DIFF_PROD_GRUPO		
	FROM
	(
		-- -------------------------------------------
		-- BI_VENDA_CUPOM
		-- -------------------------------------------
		SELECT
			COD_LOJA
			,SUM(VALOR_TOTAL) AS VALOR_TOTAL
		FROM
			BI_VENDA_CUPOM
		WHERE 1 = 1
			AND CONVERT(DATE,DATA) >= CONVERT(DATE,@DT_INICIO)
			AND CONVERT(DATE,DATA) < CONVERT(DATE,@DT_TERMINO)
		GROUP BY
			COD_LOJA
	) AS CUPOM
	INNER JOIN
	(
		-- -------------------------------------------
		-- BI_VENDA_PRODUTO
		-- -------------------------------------------
		SELECT
			COD_LOJA
			,SUM(VALOR_TOTAL) AS VALOR_TOTAL
		FROM
			BI_VENDA_PRODUTO
		WHERE 1 = 1
			AND CONVERT(DATE,DATA) >= CONVERT(DATE,@DT_INICIO)
			AND CONVERT(DATE,DATA) < CONVERT(DATE,@DT_TERMINO)
		GROUP BY
			COD_LOJA
	) AS PRODUTO
	ON (CUPOM.COD_LOJA = PRODUTO.COD_LOJA)
	
	INNER JOIN
	(
		-- -------------------------------------------
		-- BI_VENDA_PRODUTO
		-- -------------------------------------------
		SELECT
			COD_LOJA
			,SUM(VLR_VENDA) AS VALOR_TOTAL
		FROM
			[BI].[DBO].[BI_VENDA_GRUPO]
		WHERE 1 = 1
			AND CONVERT(DATE,DATA) >= CONVERT(DATE,@DT_INICIO)
			AND CONVERT(DATE,DATA) < CONVERT(DATE,@DT_TERMINO)
		GROUP BY
			COD_LOJA
	) AS GRUPO
	ON (CUPOM.COD_LOJA = GRUPO.COD_LOJA)
	ORDER BY CUPOM.COD_LOJA	
