SELECT *
FROM 
	[192.168.0.6].ZEUS_RTG.DBO.TAB_PRODUTO AS P
		INNER JOIN [192.168.0.6].ZEUS_RTG.DBO.TAB_PRODUTO_SAIDA AS S WITH (NOLOCK) 	ON(P.COD_PRODUTO = S.COD_PRODUTO) 
		INNER JOIN [192.168.0.6].ZEUS_RTG.DBO.TAB_PRODUTO_LOJA AS L WITH (NOLOCK) ON(S.COD_LOJA = L.COD_LOJA) AND (S.COD_PRODUTO = L.COD_PRODUTO) 
		INNER JOIN [192.168.0.6].ZEUS_RTG.DBO.TAB_PARAMETRO_LOJA AS PRM WITH (NOLOCK) ON(L.COD_LOJA = PRM.COD_LOJA) 
		INNER JOIN [192.168.0.6].ZEUS_RTG.DBO.TAB_TRIBUTACAO AS TRI WITH (NOLOCK) ON(L.COD_TRIBUTACAO = TRI.COD_TRIBUTACAO)
		--INNER JOIN BI.DBO.BI_LINHA_PRODUTOS AS LP ON (P.COD_PRODUTO = LP.COD_PRODUTO AND L.COD_LOJA = LP.COD_LOJA)
WHERE 1=1
	--AND P.FLG_GRADE_PRODUTO = 'N' 
	AND P.COD_PRODUTO = 119122
	--AND S.COD_LOJA IN (1,7)
	--AND S.QTD_TOTAL_PRODUTO <> 0.00 
	AND CONVERT(DATE,S.DTA_SAIDA) BETWEEN CONVERT(DATE,'20140101') AND CONVERT(DATE,'20140201')
	


SELECT DISTINCT
	NO_DEPARTAMENTO
	,NO_SECAO
	,NO_GRUPO
	,NO_SUBGRUPO
FROM
	BI_CAD_PRODUTO AS CP
WHERE 1 = 1
	AND CP.COD_SECAO IN (41,20,19,10,6)
ORDER BY
	NO_DEPARTAMENTO
	,NO_SECAO
	,NO_GRUPO
	,NO_SUBGRUPO