DECLARE @DATAINI DATE = '20140407'--'20140706'
DECLARE @DATAFIM DATE = '20140713'	

select
	LEFT(BI.dbo.ISO_WEEK(RM.DATA),4) as [Ano]
	,BI.DBO.F_ISO_WEEK_OF_YEAR(RM.DATA) as [Semana]
	,CONT.OCORRENCIA
	,SUM(CASE WHEN CONT.OCORRENCIA <> 1 THEN 1 ELSE 0 END) AS ERRO
	,COUNT(CONT.COD_PRODUTO) AS TOTAL
from
	[192.168.0.6].Intranet.DBO.TAB_RECEB_MERCADORIA AS RM
	INNER JOIN [192.168.0.6].Intranet.DBO.TAB_RECEB_MERCADORIA_CONTAGEM AS CONT
		ON RM.ID = CONT.ID
WHERE 1 = 1
	AND CONVERT(DATE,RM.DATA) BETWEEN @DATAINI AND @DATAFIM
	AND OCORRENCIA NOT IN (2,3,12,17)
GROUP BY
	LEFT(BI.dbo.ISO_WEEK(RM.DATA),4)
	,BI.DBO.F_ISO_WEEK_OF_YEAR(RM.DATA)
	,CONT.OCORRENCIA


DECLARE @TAB_RECEBIMENTO AS TABLE
(
	ANO INT
	,SEMANA INT
	,QTD_ERRO NUMERIC(18,2)
	,QTD_TOTAL NUMERIC(18,2)
)

INSERT INTO @TAB_RECEBIMENTO
select
	LEFT(BI.dbo.ISO_WEEK(RM.DATA),4) as [Ano]
	,BI.DBO.F_ISO_WEEK_OF_YEAR(RM.DATA) as [Semana]
	,SUM(CASE WHEN CONT.OCORRENCIA <> 1 THEN 1 ELSE 0 END) AS ERRO
	,COUNT(CONT.COD_PRODUTO) AS TOTAL
from
	[192.168.0.6].Intranet.DBO.TAB_RECEB_MERCADORIA AS RM
	INNER JOIN [192.168.0.6].Intranet.DBO.TAB_RECEB_MERCADORIA_CONTAGEM AS CONT
		ON RM.ID = CONT.ID
WHERE 1 = 1
	AND CONVERT(DATE,RM.DATA) BETWEEN @DATAINI AND @DATAFIM
	AND OCORRENCIA NOT IN (2,3,12,17)
GROUP BY
	LEFT(BI.dbo.ISO_WEEK(RM.DATA),4)
	,BI.DBO.F_ISO_WEEK_OF_YEAR(RM.DATA)
	
SELECT
	ANO
	,SEMANA
	,QTD_ERRO
	,QTD_TOTAL
	,QTD_ERRO / QTD_TOTAL AS PERC
FROM
	@TAB_RECEBIMENTO
ORDER BY
	ANO
	,SEMANA
	
	
/*
SELECT TOP 100 * FROM
	[192.168.0.6].Intranet.DBO.TAB_RECEB_MERCADORIA AS RM
	INNER JOIN [192.168.0.6].Intranet.DBO.TAB_RECEB_MERCADORIA_CONTAGEM AS CONT
	ON RM.ID = CONT.ID

SELECT * FROM [192.168.0.6].Intranet.DBO.TAB_RECEB_MERCADORIA_OCORRENCIAS
*/