select
	COD_LOJA
	,CP.COD_PRODUTO
	,CP.DESCRICAO
	,CP.COD_FORNECEDOR	
	,CF.DESCRICAO
	,EP.QTD_ESTOQUE	
from
	BI_CAD_PRODUTO as CP INNER JOIN BI_ESTOQUE_PRODUTO AS EP ON (CP.COD_PRODUTO = EP.COD_PRODUTO)
		INNER JOIN BI_CAD_FORNECEDOR AS CF ON (CP.COD_FORNECEDOR = CF.COD_FORNECEDOR)
WHERE 1 = 1
	AND CP.COD_SECAO = 8
	AND EP.QTD_ESTOQUE <> 0