SELECT
	MOV.COD_LOJA
	,MOV.COD_PRODUTO
	,PROD.DES_PRODUTO
	,MOV.QTD_ESTOQUE	
FROM
	ZEUS_RTG.DBO.TAB_PRODUTO_MOVIMENTO AS MOV INNER JOIN ZEUS_RTG.DBO.TAB_PRODUTO AS PROD ON (MOV.COD_PRODUTO = PROD.COD_PRODUTO)
WHERE 1 = 1
	AND CONVERT(DATE,MOV.DTA_MOVIMENTO) >= CONVERT(DATE,GETDATE()-1)
	AND CONVERT(DATE,MOV.DTA_MOVIMENTO) < CONVERT(DATE,GETDATE())
	AND MOV.QTD_ESTOQUE < 0
ORDER BY
	MOV.COD_LOJA
	,MOV.QTD_ESTOQUE