DECLARE @COD_PROD AS INT

DECLARE FORA_LINHA_CURSOR CURSOR FOR 

SELECT COD_PRODUTO FROM BI.DBO.BI_CAD_PRODUTO

OPEN FORA_LINHA_CURSOR

FETCH NEXT FROM FORA_LINHA_CURSOR 
INTO @COD_PROD

WHILE @@FETCH_STATUS = 0
BEGIN
    IF EXISTS (SELECT 1 FROM BI.DBO.BI_LINHA_PRODUTOS WHERE FORA_LINHA = 'N' AND COD_PRODUTO = @COD_PROD)
    BEGIN
		UPDATE BI.DBO.BI_CAD_PRODUTO SET FORA_LINHA = 'N' WHERE COD_PRODUTO = @COD_PROD
    END
    ELSE
    BEGIN
		UPDATE BI.DBO.BI_CAD_PRODUTO SET FORA_LINHA = 'S' WHERE COD_PRODUTO = @COD_PROD
    END

    FETCH NEXT FROM FORA_LINHA_CURSOR 
    INTO @COD_PROD
END 
CLOSE FORA_LINHA_CURSOR;
DEALLOCATE FORA_LINHA_CURSOR;