TRUNCATE TABLE [BI].[dbo].[CADASTRO_CAD_PRODUTO_SIMILAR]

INSERT INTO [BI].[dbo].[CADASTRO_CAD_PRODUTO_SIMILAR]
select
	ps.[COD_PRODUTO_SIMILAR],
	ps.[DES_PRODUTO_SIMILAR],
	(CASE WHEN us.[COD_USUARIO] IS NULL THEN 999 ELSE us.[COD_USUARIO] END),
	ps.[DTA_CADASTRO]
from
	[192.168.0.6].Zeus_Rtg.dbo.TAB_PRODUTO_SIMILAR as ps LEFT join [192.168.0.6].[Zeus_rtg].[dbo].[TAB_USUARIO] as us on (ps.USUARIO = us.DES_USUARIO)
WHERE 1 = 1

SELECT * FROM [BI].[dbo].[CADASTRO_CAD_PRODUTO_SIMILAR]



/*
GO

UPDATE A
SET
	A.[COD_PRODUTO_SIMILAR] = B.[COD_PRODUTO_SIMILAR]
FROM [BI].[dbo].[CADASTRO_CAD_PRODUTO_SIMILAR] A INNER JOIN [192.168.0.6].Zeus_Rtg.dbo.TAB_PRODUTO_SIMILAR as B ON (A.[NO_PRODUTO_SIMILAR] = B.[DES_PRODUTO_SIMILAR])
*/