SELECT --TOP 100
	CP.COD_FORNECEDOR
	,CF.DES_FANTASIA
	,CP.NO_DEPARTAMENTO
	,CP.NO_SECAO
	,CP.NO_GRUPO
	,CP.NO_SUBGRUPO
	,CP.COD_PRODUTO
	,CP.DESCRICAO
	,(CASE
		WHEN LP.VLR_VCMARCHE IS NOT NULL THEN LP.VLR_VCMARCHE
		WHEN LP.VLR_OFERTA IS NOT NULL THEN LP.VLR_OFERTA
		WHEN LP.VLR_VENDA IS NOT NULL THEN LP.VLR_VENDA	
	END) AS PV
	,(SELECT 1 FROM BI.DBO.CADASTRO_CAD_PRODUTO_METADADOS AS PM WHERE PM.COD_PRODUTO = CP.COD_PRODUTO AND PM.COD_METADADO = 3 AND PM.VLR_METADADO = '1') AS IMPORTADO
	,(SELECT 1 FROM BI.DBO.CADASTRO_CAD_PRODUTO_METADADOS AS PM WHERE PM.COD_PRODUTO = CP.COD_PRODUTO AND PM.COD_METADADO = 4 AND PM.VLR_METADADO = '1') AS IMP_PRORIA
	,(SELECT 1 FROM AX2009_INTEGRACAO.DBO.TAB_CODIGO_BARRA_PRINCIPAL AS CB WHERE CB.COD_PRODUTO = CP.COD_PRODUTO AND CONVERT(DOUBLE PRECISION,CB.COD_EAN) >= 8000000000000 AND CONVERT(DOUBLE PRECISION,CB.COD_EAN) < 8400000000000) AS ITALIANO
	,LP.VLR_TOTAL_1ANO
	,LP.QTDE_PRODUTO_1ANO
FROM
	BI.DBO.BI_CAD_PRODUTO AS CP INNER JOIN BI.DBO.BI_LINHA_PRODUTOS AS LP ON (CP.COD_PRODUTO = LP.COD_PRODUTO)
		LEFT JOIN BI.DBO.BI_CAD_FORNECEDOR AS CF ON (CP.COD_FORNECEDOR = CF.COD_FORNECEDOR)
WHERE 1 = 1
	AND LP.COD_LOJA = 7
	AND LP.FORA_LINHA = 'N'
ORDER BY
	CP.NO_DEPARTAMENTO
	,CP.NO_SECAO
	,CP.NO_GRUPO
	,CP.NO_SUBGRUPO
	,CP.COD_PRODUTO