select * from BI_CAD_GRUPO


SELECT DISTINCT
	LP.COD_PRODUTO
	,CP.DESCRICAO
	,CG.NO_DEPARTAMENTO
	,CG.NO_SECAO
FROM
	BI_LINHA_PRODUTOS LP LEFT JOIN BI_CAD_GRUPO CG ON LP.COD_SECAO = CG.COD_SECAO AND LP.COD_GRUPO = CG.COD_GRUPO
		LEFT JOIN BI_CAD_PRODUTO AS CP ON (LP.COD_PRODUTO = CP.COD_PRODUTO)
WHERE 1 = 1
	AND COD_LOJA NOT IN (7)
	AND LP.FORA_LINHA = 'N' 
	AND (CG.COD_DEPARTAMENTO = 6 AND LP.COD_SECAO IN (32,18))
	OR (CG.COD_DEPARTAMENTO = 1)
	
ORDER BY
	NO_DEPARTAMENTO,NO_SECAO,CP.DESCRICAO
	
	

SELECT DISTINCT
	LP.COD_PRODUTO
	,CP.DESCRICAO
	,CG.NO_DEPARTAMENTO
	,CG.NO_SECAO
FROM
	BI_LINHA_PRODUTOS LP LEFT JOIN BI_CAD_GRUPO CG ON LP.COD_SECAO = CG.COD_SECAO AND LP.COD_GRUPO = CG.COD_GRUPO
		LEFT JOIN BI_CAD_PRODUTO AS CP ON (LP.COD_PRODUTO = CP.COD_PRODUTO)
WHERE 1 = 1
	AND COD_LOJA IN (7)
	AND LP.FORA_LINHA = 'N' 
	AND (CG.COD_DEPARTAMENTO = 6 AND LP.COD_SECAO IN (32,18))
	--OR (CG.COD_DEPARTAMENTO = 1)
ORDER BY
	NO_DEPARTAMENTO,NO_SECAO,CP.DESCRICAO
	
