DECLARE @COD_LOJA AS INT = 7

SELECT
	CP.NO_DEPARTAMENTO
	,CP.NO_SECAO
	,CP.NO_GRUPO
	,LP.COD_PRODUTO
	,CP.DESCRICAO
	,LP.VLR_VENDA
	,LP.VLR_OFERTA
	,LP.VLR_VCMARCHE
FROM
	BI_LINHA_PRODUTOS AS LP
	INNER JOIN BI_CAD_PRODUTO AS CP
		ON LP.COD_PRODUTO = CP.COD_PRODUTO
WHERE 1=1
	AND LP.COD_LOJA = @COD_LOJA
	AND LP.FORA_LINHA = 'N'
	AND LP.COD_PRODUTO NOT IN
	(
	SELECT DISTINCT
		COD_PRODUTO
	FROM
		BI_LINHA_PRODUTOS AS LP
	WHERE 1=1
		AND COD_LOJA NOT IN (@COD_LOJA,26)
		AND FORA_LINHA = 'N'
	)