SELECT --TOP 50
	CN.COD_CLIENTE
	,CN.NUM_NF_CLI
	,CN.NUM_SERIE_NF
	,CN.COD_FISCAL
	,CN.COD_LOJA
	,CN.VAL_TOTAL_NF
	,CN.DTA_EMISSAO
	,CN.DES_NATUREZA
	--,CN.EXPORTADO
	,CN.FLG_CANCELADO
	,CLI.DES_CLIENTE
	,CLI.FLG_EMPRESA
	,CLI.NUM_CGC
	,CLI.NUM_INSC_EST
	,CLI.DES_ENDERECO
	,CLI.DES_BAIRRO
	,CLI.NUM_CEP
	,CLI.DES_SIGLA
FROM
	TAB_CLIENTE_NOTA AS CN WITH (NOLOCK)-- INNER JOIN TAB_CLIENTE_PRODUTO AS CP WITH (NOLOCK)
		--ON (CN.COD_CLIENTE = CP.COD_CLIENTE AND CFN.NUM_NF_CLI = CP.NUM_NF_CLI AND CN.NUM_SERIE_NF = CP.NUM_SERIE_NF)
	LEFT JOIN TAB_CLIENTE AS CLI ON (CN.COD_CLIENTE = CLI.COD_CLIENTE)
WHERE 1 = 1
AND CONVERT(DATE,CN.DTA_EMISSAO) >= CONVERT(DATE,'20131101')
AND CONVERT(DATE,CN.DTA_EMISSAO) < CONVERT(DATE,'20140101')
--AND FN.COD_FORNECEDOR = 14721
--AND FN.NUM_NF_CLI = 14926
AND CN.COD_FISCAL IN (206,194)