	DECLARE @DANFE AS VARCHAR(50) = '35140560313905000143550010006895441803000199'

	SELECT DISTINCT
		DET.[Cod_fornecedor] AS [Cod Forn]
		,CF.DES_FANTASIA as [Forn] 
		,DET.[COD_LOJA] as [Loja]
		,DET.[NUM_DANFE] as [Danfe]
		,IDE.dEmi AS [Data Emissao]
		,COBR.dVEnc AS [Data Venc]
		,DET.[DTA_GRAVACAO] as [Data Gravacao]
		,COUNT(DET.cProd) AS [Item]
		,SUM(CASE WHEN DET.MENSAGEM IS NOT NULL THEN 1 ELSE 0 END) AS [Item Erro]
	FROM
		[CTRLNFE].[DBO].[NFE_DET] AS DET
			LEFT JOIN [CtrlNfe].[dbo].[NFE_IDE] AS IDE ON (DET.num_danfe = IDE.num_danfe)
			LEFT JOIN [CtrlNfe].[dbo].[NFE_COBR] AS COBR ON (DET.num_danfe = COBR.num_danfe)
			LEFT JOIN BI.DBO.BI_CAD_FORNECEDOR AS CF ON (DET.Cod_fornecedor = CF.Cod_fornecedor)
	WHERE 1 = 1
		--AND CONVERT(DATE,DET.DTA_GRAVACAO) BETWEEN CONVERT(DATE,@DATA_INI) AND CONVERT(DATE,@DATA_FIM)
		AND DET.NUM_DANFE = @DANFE
	GROUP BY
		DET.[Cod_fornecedor]
		,CF.DES_FANTASIA
		,DET.[COD_LOJA]
		,DET.[NUM_DANFE]
		,IDE.dEmi
		,COBR.dVEnc
		,DET.[DTA_GRAVACAO]
	ORDER BY
		DET.[COD_FORNECEDOR]
		,DET.[COD_LOJA]
		,DET.[NUM_DANFE]
		,DET.[DTA_GRAVACAO]
	
	SELECT
		DET.COD_PRODUTO AS [Plu]
		,DET.xProd AS [Prod Danfe]
		,CP.DESCRICAO AS [Prod BI]
		,DET.MENSAGEM
		,DET.*
	FROM
		[CTRLNFE].[DBO].[NFE_DET] AS DET INNER JOIN [CTRLNFE].[DBO].[NFE_STATUS] AS STA ON (DET.NUM_DANFE = STA.NUM_DANFE)
			LEFT JOIN BI.DBO.BI_CAD_PRODUTO AS CP ON (DET.COD_PRODUTO = CP.COD_PRODUTO)
	WHERE 1 = 1
		--AND MENSAGEM IS NOT NULL
		--AND CONVERT(DATE,DET.DTA_GRAVACAO) BETWEEN CONVERT(DATE,@DATA_INI) AND CONVERT(DATE,@DATA_FIM)
		AND DET.NUM_DANFE = @DANFE 
	ORDER BY 
		DET.DTA_GRAVACAO
		
	
