SELECT
	CP.COD_DEPARTAMENTO
	,CP.NO_DEPARTAMENTO
	,CP.COD_SECAO
	,CP.NO_SECAO
	,CP.COD_GRUPO
	,CP.NO_GRUPO
	,CP.COD_PRODUTO
	,CP.DESCRICAO AS NO_PROD
	,CB.COD_EAN
	,CP.FORA_LINHA
	,dbo.fn_FormataVlr_Excel(MAX(LP.VLR_VENDA)) AS VLR_VENDA
	,dbo.fn_FormataVlr_Excel(MAX(LP.VLR_TOTAL_1ANO)) AS VLR_TOTAL_1ANO
	,dbo.fn_FormataVlr_Excel(MAX(LP.QTDE_PRODUTO_1ANO)) AS QTDE_PRODUTO_1ANO
FROM
	BI.DBO.BI_CAD_PRODUTO AS CP INNER JOIN AX2009_INTEGRACAO.DBO.TAB_CODIGO_BARRA AS CB ON (CP.COD_PRODUTO = CB.COD_PRODUTO)
		INNER JOIN BI.DBO.BI_LINHA_PRODUTOS AS LP ON (CP.COD_PRODUTO = LP.COD_PRODUTO)
WHERE 1 = 1
	AND CONVERT(DOUBLE PRECISION,CB.COD_EAN) >= 8000000000000
	AND CONVERT(DOUBLE PRECISION,CB.COD_EAN) < 8400000000000
	AND CP.COD_DEPARTAMENTO = 2
	AND CP.COD_SECAO = 27
	AND CP.COD_GRUPO NOT IN (24)
	AND LP.COD_LOJA NOT IN (7)
GROUP BY
	CP.COD_DEPARTAMENTO
	,CP.NO_DEPARTAMENTO
	,CP.COD_SECAO
	,CP.NO_SECAO
	,CP.COD_GRUPO
	,CP.NO_GRUPO
	,CP.COD_PRODUTO
	,CP.DESCRICAO
	,CB.COD_EAN
	,CP.FORA_LINHA