SELECT
	CP.COD_PRODUTO
	,CP.DESCRICAO AS NO_PROD
	,CP.COD_DEPARTAMENTO
	,CP.COD_SECAO
	,CP.COD_GRUPO
	,CB.COD_EAN
	,CP.FORA_LINHA
	,CP.COD_FORNECEDOR
	,CF.DESCRICAO AS NO_FORN
	,MAX(LP.VLR_VENDA) AS VLR_VENDA
	,MAX(PL.VAL_CUSTO_TABELA) AS VLR_CUSTO_TABELA
FROM
	BI.DBO.BI_CAD_PRODUTO AS CP INNER JOIN AX2009_INTEGRACAO.DBO.TAB_CODIGO_BARRA AS CB ON (CP.COD_PRODUTO = CB.COD_PRODUTO)
		LEFT JOIN BI.DBO.BI_LINHA_PRODUTOS AS LP ON (CP.COD_PRODUTO = LP.COD_PRODUTO)
		LEFT JOIN BI.DBO.BI_CAD_FORNECEDOR AS CF ON (CP.COD_FORNECEDOR = CF.COD_FORNECEDOR)
		LEFT JOIN [192.168.0.6].ZEUS_RTG.DBO.TAB_PRODUTO_LOJA AS PL ON (CP.COD_PRODUTO = PL.COD_PRODUTO)
WHERE 1 = 1
	AND CONVERT(DOUBLE PRECISION,CB.COD_EAN) >= 8000000000000
	AND CONVERT(DOUBLE PRECISION,CB.COD_EAN) < 8400000000000
GROUP BY
	CP.COD_PRODUTO
	,CP.DESCRICAO
	,CP.COD_DEPARTAMENTO
	,CP.COD_SECAO
	,CP.COD_GRUPO
	,CB.COD_EAN
	,CP.FORA_LINHA
	,CP.COD_FORNECEDOR
	,CF.DESCRICAO