SELECT
	VP.COD_PRODUTO
	,CP.DESCRICAO
	,dbo.fn_FormataVlr_Excel(SUM(VP.QTDE_PRODUTO)) as QTDE_VENDA
FROM
	[BI].[dbo].[BI_VENDA_PRODUTO] AS VP	LEFT JOIN [BI].[dbo].[PRODUTO_FORNECEDOR_LINHA] as PF ON (VP.COD_PRODUTO = PF.COD_PRODUTO)
		LEFT JOIN [BI].[dbo].[BI_CAD_PRODUTO] AS CP ON (VP.COD_PRODUTO = CP.COD_PRODUTO)
WHERE 1=1
	AND CONVERT(DATE,VP.DATA) >= CONVERT(DATE,'20130101')
	AND CONVERT(DATE,VP.DATA) < CONVERT(DATE,'20131101')
	AND PF.COD_FORNECEDOR = 13984
	--AND VP.COD_PRODUTO IN ()
GROUP BY
	VP.COD_PRODUTO
	,CP.DESCRICAO