SELECT
	--MONTH(VP.DATA) AS MES
	VP.COD_PRODUTO
	,CP.DESCRICAO
	,dbo.fn_FormataVlr_Excel(SUM(VP.QTDE_PRODUTO)) AS QTD_VENDA
	,dbo.fn_FormataVlr_Excel(SUM(VP.VALOR_TOTAL)) AS VALOR_VENDA
FROM
	[BI].[dbo].[BI_VENDA_PRODUTO] AS VP	LEFT JOIN [BI].[dbo].[BI_CAD_PRODUTO] as CP ON (VP.COD_PRODUTO = CP.COD_PRODUTO)
WHERE 1=1
	AND CONVERT(DATE,VP.DATA) >= CONVERT(DATE,'20130101')
	AND CONVERT(DATE,VP.DATA) < CONVERT(DATE,'20131101')
	AND CP.COD_SECAO = 27
	--AND PF.COD_FORNECEDOR = 13984
	--AND VP.COD_PRODUTO IN ()
GROUP BY
	--MONTH(VP.DATA)
	VP.COD_PRODUTO
	,CP.DESCRICAO
ORDER BY
	SUM(VP.VALOR_TOTAL) DESC