SELECT
	COMP.NO_COMPRADOR
	,PL.FORA_LINHA
	,EP.[COD_LOJA]
	,EP.[COD_PRODUTO]	
	,CP.DESCRICAO as NO_PRODUTO
	,dbo.fn_FormataVlr_Excel(SUM(EP.[QTD_ESTOQUE])) AS QTD_ESTOQUE
	,dbo.fn_FormataVlr_Excel(SUM(PF.VLR_EMB_COMPRA/nullif(PF.QTD_EMB_COMPRA,0))) AS CUSTO
	,dbo.fn_FormataVlr_Excel(SUM(EP.[QTD_ESTOQUE]*(PF.VLR_EMB_COMPRA/nullif(PF.QTD_EMB_COMPRA,0)))) AS ESTOQUE_CUSTO
FROM
	[BI].[DBO].[BI_ESTOQUE_PRODUTO] AS EP
		INNER JOIN BI.DBO.BI_CAD_PRODUTO AS CP
			ON 1 = 1
			AND EP.COD_PRODUTO = CP.COD_PRODUTO
		INNER JOIN [BI].[DBO].BI_LINHA_PRODUTOS AS PL
			ON 1 = 1
			AND EP.COD_PRODUTO = PL.COD_PRODUTO
			AND EP.COD_LOJA = PL.COD_LOJA
		INNER JOIN BI.dbo.COMPRAS_CAD_COMPRADOR AS COMP
			ON CP.COD_USUARIO = COMP.COD_USUARIO
		INNER JOIN VW_CUSTOS_ATIVOS AS PF
			ON 1 = 1
			AND EP.COD_PRODUTO = PF.COD_PRODUTO
			AND CP.COD_FORNECEDOR = PF.COD_FORNECEDOR				
WHERE 1=1
	AND EP.QTD_ESTOQUE>0
	AND CP.COD_USUARIO <> 8113
	AND CP.PESADO = 'N'
	AND CP.COD_DEPARTAMENTO NOT IN (7,99,20,15) --EXCLUSAO DEP OUTROS
	AND EP.COD_LOJA IN (1,2,3,4,6,7,9,10,12,13,17,18,19,20,21,30)
GROUP BY
	COMP.NO_COMPRADOR
	,PL.FORA_LINHA
	,EP.[COD_LOJA]
	,EP.[COD_PRODUTO]	
	,CP.DESCRICAO

/*
SELECT distinct 
	f.DESCRICAO as Fornecedor
	,f.[COD_FORNECEDOR] as Cod
	,f.ABC_FORN as ABC
	,pf.DES_REFERENCIA AS [Ref] 
	,c.VLR_EMB_COMPRA as [Vlr Emb]
	,UNID.MARCHEQTDEMBALAGEM as [Qtd Emb]
	,UNID.MARCHEMULTIPLO as [Multiplo]
	,c.VLR_EMB_COMPRA/nullif(c.QTD_EMB_COMPRA,0) as [Vlr Uni]
FROM 
	[AX2009_INTEGRACAO].[dbo].[TAB_PRODUTO_FORNECEDOR] as pf
	inner join [BI].[dbo].[COMPRAS_AGENDA_PEDIDO_MATRIZ] as a
		on a.COD_FORNECEDOR = pf.cod_fornecedor
	inner join [BI].[dbo].[BI_CAD_FORNECEDOR] as f
		on f.COD_FORNECEDOR = pf.cod_fornecedor
	left join BI.DBO.VW_CUSTOS_ATIVOS  as c
		on 1 = 1
		and c.COD_FORNECEDOR = pf.COD_FORNECEDOR
		and c.COD_PRODUTO = pf.COD_PRODUTO
	left join AX2009_INTEGRACAO.DBO.TAB_PRODUTO_REFERENCIA AS UNID 
		on 1 = 1
		and c.COD_FORNECEDOR = UNID.COD_FORNECEDOR
		and c.COD_PRODUTO = UNID.COD_PRODUTO
where 1=1
	and pf.COD_PRODUTO = 1001575


order by ABC, Fornecedor
	
*/


/*

SELECT
*
FROM
	[192.168.0.6].ZEUS_RTG.DBO.TAB_PRODUTO_MOVIMENTO AS PM
WHERE 1 = 1
	AND CONVERT(DATE,DTA_MOVIMENTO) = CONVERT(DATE,'20140623')
	AND COD_LOJA = 6
	AND COD_PRODUTO = 397346


*/


/*
SELECT
	DBO.FN_FORMATAVLR_EXCEL(SUM(EP.[QTD_ESTOQUE])) AS QTD_ESTOQUE
	,dbo.fn_FormataVlr_Excel(SUM(EP.[QTD_ESTOQUE]*PF.VAL_CUSTO_EMBALAGEM)) AS ESTOQUE_CUSTO
FROM
	[BI].[DBO].[BI_ESTOQUE_PRODUTO] AS EP
		INNER JOIN BI.DBO.BI_CAD_PRODUTO AS CP
			ON 1 = 1
			AND EP.COD_PRODUTO = CP.COD_PRODUTO
		INNER JOIN [BI].[DBO].BI_LINHA_PRODUTOS AS PL
			ON 1 = 1
			AND EP.COD_PRODUTO = PL.COD_PRODUTO
			AND EP.COD_LOJA = PL.COD_LOJA
		INNER JOIN [192.168.0.6].ZEUS_RTG.DBO.TAB_PRODUTO_FORNECEDOR AS PF
			ON 1 = 1
			AND EP.COD_LOJA = PF.COD_LOJA
			AND EP.COD_PRODUTO = PF.COD_PRODUTO
			AND CP.COD_FORNECEDOR = PF.COD_FORNECEDOR		
WHERE 1=1
	AND EP.QTD_ESTOQUE>0
	AND CP.COD_USUARIO <> 8113
	AND CP.COD_DEPARTAMENTO NOT IN (7,99,20,15) --EXCLUSAO DEP OUTROS
	AND EP.COD_LOJA IN (1,2,3,4,6,7,9,10,12,13,17,18,19,20,21,30)
*/



/*
SELECT
	EP.COD_LOJA
	,EP.COD_PRODUTO
	,COUNT(EP.COD_PRODUTO) AS QTD
FROM
	[BI].[DBO].[BI_ESTOQUE_PRODUTO] AS EP
		INNER JOIN BI.DBO.BI_CAD_PRODUTO AS CP
			ON 1 = 1
			AND EP.COD_PRODUTO = CP.COD_PRODUTO
		INNER JOIN [BI].[DBO].BI_LINHA_PRODUTOS AS PL
			ON 1 = 1
			AND EP.COD_PRODUTO = PL.COD_PRODUTO
			AND EP.COD_LOJA = PL.COD_LOJA
		INNER JOIN [192.168.0.6].ZEUS_RTG.DBO.TAB_PRODUTO_FORNECEDOR AS PF
			ON 1 = 1
			AND EP.COD_LOJA = PF.COD_LOJA
			AND EP.COD_PRODUTO = PF.COD_PRODUTO
			AND CP.COD_FORNECEDOR = PF.COD_FORNECEDOR		
WHERE 1=1
	AND EP.QTD_ESTOQUE>0
	AND CP.COD_USUARIO <> 8113
	AND CP.COD_DEPARTAMENTO NOT IN (7,99,20,15) --EXCLUSAO DEP OUTROS
	AND EP.COD_LOJA IN (1,2,3,4,6,7,9,10,12,13,17,18,19,20,21,30)
GROUP BY
	EP.COD_LOJA
	,EP.COD_PRODUTO
HAVING 
	COUNT(EP.COD_PRODUTO) > 1
*/	
	
	

--SELECT DISTINCT COD_DEPARTAMENTO, NO_DEPARTAMENTO FROM BI.DBO.BI_CAD_PRODUTO



/*
SELECT
	*
FROM
	[BI].[DBO].[BI_ESTOQUE_PRODUTO] AS EP
		INNER JOIN BI.DBO.BI_CAD_PRODUTO AS CP
			ON 1 = 1
			AND EP.COD_PRODUTO = CP.COD_PRODUTO
		INNER JOIN [BI].[DBO].BI_LINHA_PRODUTOS AS PL
			ON 1 = 1
			AND EP.COD_PRODUTO = PL.COD_PRODUTO
			AND EP.COD_LOJA = PL.COD_LOJA
		INNER JOIN [192.168.0.6].ZEUS_RTG.DBO.TAB_PRODUTO_FORNECEDOR AS PF
			ON 1 = 1
			AND EP.COD_LOJA = PF.COD_LOJA
			AND EP.COD_PRODUTO = PF.COD_PRODUTO
			AND CP.COD_FORNECEDOR = PF.COD_FORNECEDOR		
WHERE 1=1
	AND EP.QTD_ESTOQUE>0
	AND EP.COD_PRODUTO = 144179
	AND CP.COD_USUARIO <> 8113
	AND CP.COD_DEPARTAMENTO NOT IN (7,99,20,15) --EXCLUSAO DEP OUTROS
	AND EP.COD_LOJA IN (1,2,3,4,6,7,9,10,12,13,17,18,19,20,21,30)
*/


/*

select 
	NO_COMPRADOR
	,dbo.fn_FormataVlr_Excel(SUM(CASE WHEN FORA_LINHA = 'S' THEN ESTOQUE_CUSTO ELSE 0 END)/SUM(ESTOQUE_CUSTO)) AS CUSTO_FL_S
	,dbo.fn_FormataVlr_Excel(SUM(CASE WHEN FORA_LINHA = 'N' THEN ESTOQUE_CUSTO ELSE 0 END)/SUM(ESTOQUE_CUSTO)) AS CUSTO_FL_N
from
(
SELECT
	COMP.NO_COMPRADOR
	,PL.FORA_LINHA
	--,EP.[COD_LOJA]
	--,EP.[COD_PRODUTO]	
	--,CP.DESCRICAO as NO_PRODUTO
	,(SUM(EP.[QTD_ESTOQUE])) AS QTD_ESTOQUE
	,(SUM(PF.VLR_EMB_COMPRA/nullif(PF.QTD_EMB_COMPRA,0))) AS CUSTO
	,(SUM(EP.[QTD_ESTOQUE]*(PF.VLR_EMB_COMPRA/nullif(PF.QTD_EMB_COMPRA,0)))) AS ESTOQUE_CUSTO
FROM
	[BI].[DBO].[BI_ESTOQUE_PRODUTO] AS EP
		INNER JOIN BI.DBO.BI_CAD_PRODUTO AS CP
			ON 1 = 1
			AND EP.COD_PRODUTO = CP.COD_PRODUTO
		INNER JOIN [BI].[DBO].BI_LINHA_PRODUTOS AS PL
			ON 1 = 1
			AND EP.COD_PRODUTO = PL.COD_PRODUTO
			AND EP.COD_LOJA = PL.COD_LOJA
		INNER JOIN BI.dbo.COMPRAS_CAD_COMPRADOR AS COMP
			ON CP.COD_USUARIO = COMP.COD_USUARIO
		INNER JOIN VW_CUSTOS_ATIVOS AS PF
			ON 1 = 1
			AND EP.COD_PRODUTO = PF.COD_PRODUTO
			AND CP.COD_FORNECEDOR = PF.COD_FORNECEDOR				
WHERE 1=1
	AND EP.QTD_ESTOQUE>0
	AND CP.COD_USUARIO <> 8113
	AND CP.PESADO = 'N'
	AND CP.COD_DEPARTAMENTO NOT IN (7,99,20,15) --EXCLUSAO DEP OUTROS
	AND EP.COD_LOJA IN (1,2,3,4,6,7,9,10,12,13,17,18,19,20,21,30)
GROUP BY
	COMP.NO_COMPRADOR
	,PL.FORA_LINHA
	--,EP.[COD_LOJA]
	--,EP.[COD_PRODUTO]	
	--,CP.DESCRICAO
) as X
GROUP BY
	NO_COMPRADOR
	
	
*/
