select --TOP 10
	CP.COD_FORNECEDOR
	,CF.DES_FANTASIA
	,CP.COD_PRODUTO
	,CP.DESCRICAO
	,dbo.fn_FormataVlr_Excel(SUM(VALOR_TOTAL)) VLR_VENDA
from 
	BI_VENDA_PRODUTO AS VP INNER JOIN BI_CAD_PRODUTO AS CP ON (VP.COD_PRODUTO = CP.COD_PRODUTO)
		LEFT JOIN BI_CAD_FORNECEDOR AS CF ON (CP.COD_FORNECEDOR = CF.COD_FORNECEDOR)
WHERE 1 = 1
	--AND CP.COD_FORNECEDOR = 15866
	AND CP.COD_DEPARTAMENTO <> 6
	AND CP.COD_FORNECEDOR IS NULL
	AND CONVERT(DATE,DATA) BETWEEN CONVERT(DATE,'20140401') AND CONVERT(DATE,'20140430')
GROUP BY
	CP.COD_FORNECEDOR
	,CF.DES_FANTASIA
	,CP.COD_PRODUTO
	,CP.DESCRICAO
ORDER BY
	SUM(VALOR_TOTAL) DESC