DECLARE @TAB_ENTRADAS AS TABLE
(
	COD_LOJA INT
	,COD_PRODUTO INT
	,DATA_ULT_ENTRADA DATE
)

INSERT INTO @TAB_ENTRADAS
SELECT
	[COD_LOJA]
	,[COD_PRODUTO]
	,MAX([DTA_ENTRADA]) AS DATA_ULT_ENTRADA
FROM
	[192.168.0.6].[Zeus_rtg].[dbo].[vw_MARCHE_ENTRADAS]
WHERE 1 = 1
	AND COD_LOJA = 7
GROUP BY
	[COD_LOJA]
	,[COD_PRODUTO]


DELETE E
FROM
	BI_ESTOQUE_PRODUTO AS EP
	LEFT JOIN @TAB_ENTRADAS AS E
		ON 1 = 1
		AND EP.COD_LOJA = E.COD_LOJA
		AND EP.COD_PRODUTO = E.COD_PRODUTO
WHERE 1 = 1
	AND E.COD_PRODUTO IS NULL


SELECT
	EP.COD_LOJA
	,CP.NO_DEPARTAMENTO
	,CP.NO_SECAO
	,CP.DESCRICAO
	,EP.COD_PRODUTO
	,LINHA.FORA_LINHA
	,E.DATA_ULT_ENTRADA
	,MAX(CONVERT(DATE,VP.DATA)) AS DATA_ULT_VENDA
	,MAX(CONVERT(DATE,PED.DATA)) AS DATA_ULT_PEDIDO
FROM
	BI_ESTOQUE_PRODUTO AS EP
	INNER JOIN BI_CAD_PRODUTO AS CP
		ON 1 = 1
		AND EP.COD_PRODUTO = CP.COD_PRODUTO
	INNER JOIN BI.DBO.BI_LINHA_PRODUTOS AS LINHA	
		ON 1 = 1
		AND EP.COD_LOJA = LINHA.COD_LOJA
		AND EP.COD_PRODUTO = LINHA.COD_PRODUTO	
	LEFT JOIN BI_VENDA_PRODUTO AS VP
		ON 1 = 1
		AND EP.COD_LOJA = VP.COD_LOJA
		AND EP.COD_PRODUTO = VP.COD_PRODUTO	
	LEFT JOIN COMPRAS_PEDIDOS AS PED
		ON 1 = 1
		AND EP.COD_LOJA = PED.COD_LOJA
		AND EP.COD_PRODUTO = PED.COD_PRODUTO	
	LEFT JOIN @TAB_ENTRADAS AS E
		ON 1 = 1
		AND EP.COD_LOJA = E.COD_LOJA
		AND EP.COD_PRODUTO = E.COD_PRODUTO
WHERE 1 = 1
	AND EP.COD_LOJA = 7
	AND EP.QTD_ESTOQUE = 0
	AND LINHA.FORA_LINHA = 'N'
GROUP BY
	EP.COD_LOJA
	,CP.NO_DEPARTAMENTO
	,CP.NO_SECAO
	,CP.DESCRICAO
	,EP.COD_PRODUTO
	,LINHA.FORA_LINHA
	,E.DATA_ULT_ENTRADA
ORDER BY
	CP.NO_DEPARTAMENTO
	,CP.NO_SECAO
	,CP.DESCRICAO


