DECLARE @DATA_INI AS DATE = '20150101'

DECLARE @TAB_VENDA AS TABLE
(
	COD_PRODUTO INT
)

INSERT INTO @TAB_VENDA
SELECT DISTINCT
	COD_PRODUTO
FROM
	[BI].[dbo].[BI_VENDA_PRODUTO]
WHERE 1=1
	AND CONVERT(DATE,DATA) < CONVERT(DATE,@DATA_INI)


DECLARE @TAB_DATA_MIN AS TABLE
(
	ITEMID INT
	,DATA_MIN DATETIME
)

INSERT INTO @TAB_DATA_MIN
SELECT
	ITEMID
	,MIN(DTA_GRAVACAO) AS DATA_MIN	
FROM
	[BI].[dbo].[CADASTRO_CAD_PRODUTO_NOVO]
GROUP BY
	ITEMID

--/*
UPDATE CN
SET
	CN.PRODUTO_NOVO = 1
--*/
--SELECT *
FROM 
	[BI].[dbo].[CADASTRO_CAD_PRODUTO_NOVO] AS CN
	INNER JOIN @TAB_DATA_MIN AS D
		ON 1=1
		AND CN.ITEMID = D.ITEMID
		AND CN.DTA_GRAVACAO = D.DATA_MIN
	LEFT JOIN @TAB_VENDA AS V
		ON 1=1
		AND CN.ITEMID = V.COD_PRODUTO
WHERE 1=1
	AND CONVERT(DATE,CN.DTA_GRAVACAO) >= CONVERT(DATE,@DATA_INI)
	AND V.COD_PRODUTO IS NULL