--SELECT * FROM BI_PRECO_COMPRA WHERE COD_PRODUTO = 1008791
DECLARE @TAB_CUSTO_BI AS TABLE
(
	COD_PRODUTO INT
	,COD_FORNECEDOR INT
	,VLR_EMB_COMPRA NUMERIC(10,2)
	,QTD_EMB_COMPRA NUMERIC(10,2)
	,DTA_GRAVACAO DATE
)

INSERT INTO @TAB_CUSTO_BI
	SELECT
		COD_PRODUTO
		,COD_FORNECEDOR
		,VLR_EMB_COMPRA
		,QTD_EMB_COMPRA
		,DTA_GRAVACAO
	FROM VW_CUSTOS_ATIVOS

DECLARE @TAB_CUSTO_ZEUS AS TABLE
(
	COD_PRODUTO INT
	,COD_FORNECEDOR INT
	,VLR_EMB_COMPRA NUMERIC(10,2)
	,QTD_EMB_COMPRA NUMERIC(10,2)
)

INSERT INTO @TAB_CUSTO_ZEUS
	SELECT DISTINCT
		COD_PRODUTO
		,COD_FORNECEDOR
		,VAL_CUSTO_EMBALAGEM
		,QTD_EMBALAGEM_COMPRA
	FROM [192.168.0.6].ZEUS_RTG.DBO.TAB_PRODUTO_FORNECEDOR

DELETE BI
FROM
	@TAB_CUSTO_BI AS BI INNER JOIN @TAB_CUSTO_ZEUS AS ZEUS ON (BI.COD_FORNECEDOR = ZEUS.COD_FORNECEDOR AND BI.COD_PRODUTO = ZEUS.COD_PRODUTO)
WHERE 1 = 1
	AND BI.VLR_EMB_COMPRA = ZEUS.VLR_EMB_COMPRA
	OR BI.VLR_EMB_COMPRA IS NULL

UPDATE ZEUS
SET
	ZEUS.VAL_CUSTO_EMBALAGEM = BI.VLR_EMB_COMPRA
	,ZEUS.QTD_EMBALAGEM_COMPRA = BI.QTD_EMB_COMPRA
FROM
	@TAB_CUSTO_BI AS BI INNER JOIN [192.168.0.6].ZEUS_RTG.DBO.TAB_PRODUTO_FORNECEDOR AS ZEUS ON (BI.COD_FORNECEDOR = ZEUS.COD_FORNECEDOR AND BI.COD_PRODUTO = ZEUS.COD_PRODUTO)

/*
SELECT
	BI.COD_FORNECEDOR
	,BI.COD_PRODUTO
	,BI.DTA_GRAVACAO
	,BI.VLR_EMB_COMPRA AS VLR_EMB_COMPRA_BI
	,BI.QTD_EMB_COMPRA AS QTD_EMB_COMPRA_BI
	,ZEUS.VLR_EMB_COMPRA AS VLR_EMB_COMPRA_ZEUS
	,ZEUS.QTD_EMB_COMPRA AS QTD_EMB_COMPRA_ZEUS
FROM
	@TAB_CUSTO_BI AS BI INNER JOIN @TAB_CUSTO_ZEUS AS ZEUS ON (BI.COD_FORNECEDOR = ZEUS.COD_FORNECEDOR AND BI.COD_PRODUTO = ZEUS.COD_PRODUTO)
WHERE 1 = 1
	AND BI.VLR_EMB_COMPRA <> ZEUS.VLR_EMB_COMPRA
	AND CONVERT(DATE,BI.DTA_GRAVACAO) <= CONVERT(DATE,GETDATE()-10)
*/
	

