SELECT
	VP.COD_LOJA
	,L.NO_LOJA
	,CONVERT(DATE,VP.DATA) AS DATA
	,CP.NO_DEPARTAMENTO
	,CP.NO_SECAO
	,CP.NO_GRUPO
	,VP.COD_PRODUTO
	,CP.DESCRICAO AS NO_PRODUTO
	,BI.dbo.fn_FormataVlr_Excel(VP.VALOR_TOTAL) AS VENDA_TOTAL
	,BI.dbo.fn_FormataVlr_Excel(VP.QTDE_PRODUTO) AS QTD_TOTAL
	,CP.COD_FORNECEDOR
	,CF.DESCRICAO AS NO_FORNECEDOR
FROM
	BI.DBO.BI_VENDA_PRODUTO AS VP
	INNER JOIN BI.dbo.BI_CAD_PRODUTO AS CP
		ON VP.COD_PRODUTO = CP.COD_PRODUTO
	INNER JOIN BI.dbo.BI_CAD_LOJA2 AS L
		ON VP.COD_LOJA = L.COD_LOJA
	LEFT JOIN BI.dbo.BI_CAD_FORNECEDOR AS CF
		ON CP.COD_FORNECEDOR = CF.COD_FORNECEDOR
WHERE 1=1
	AND VP.COD_LOJA = 29
	AND CONVERT(DATE,VP.DATA) = CONVERT(DATE,GETDATE()-1)
ORDER BY
	CP.NO_DEPARTAMENTO
	,CP.NO_SECAO
	,CP.NO_GRUPO
	,VP.VALOR_TOTAL DESC