	
	
SELECT
	VP.COD_PRODUTO
	,CP.DESCRICAO
	,CP.NO_DEPARTAMENTO
	,CP.NO_SECAO
	,CP.NO_GRUPO
	,CP.NO_SUBGRUPO
	,CP.COD_FORNECEDOR
	,CF.DES_FANTASIA
	,dbo.fn_FormataVlr_Excel(SUM(VP.QTDE_PRODUTO)) AS QTDE
	,dbo.fn_FormataVlr_Excel(SUM(VP.VALOR_TOTAL)) AS VALOR
FROM
	BI_VENDA_PRODUTO AS VP LEFT JOIN BI_CAD_PRODUTO AS CP ON (VP.COD_PRODUTO = CP.COD_PRODUTO)
		LEFT JOIN BI_CAD_FORNECEDOR AS CF ON (CP.COD_FORNECEDOR = CF.COD_FORNECEDOR)
WHERE 1 = 1
	AND COD_DEPARTAMENTO = 9
	AND COD_SECAO = 95
	AND VP.COD_LOJA <> 7
	AND CONVERT(DATE,VP.DATA) >= CONVERT(DATE,'20130101')
	AND CONVERT(DATE,VP.DATA) < CONVERT(DATE,'20140101')
GROUP BY
		VP.COD_PRODUTO
	,CP.DESCRICAO
	,CP.NO_DEPARTAMENTO
	,CP.NO_SECAO
	,CP.NO_GRUPO
	,CP.NO_SUBGRUPO
	,CP.COD_FORNECEDOR
	,CF.DES_FANTASIA