 SELECT  DISTINCT
PROD.itemid	
  ,     right(PROD.itemid,8) as COD_PRODUTO -- COD_PRODUTO = COD_PRODUTO
  ,   CODBARRA.COD_EAN as COD_BARRA_PRINCIPAL -- COD_BARRA_PRINCIPAL = COD_BARRA_PRINCIPAL
  ,   NULL as COD_ASSOCIADO -- COD_ASSOCIADO = COD_ASSOCIADO
  ,   PROD.TaxFiscalClassificationId as COD_NBM -- COD_NBM = COD_NBM
  
  ,   LEFT(PROD.NameAlias,25) as DES_REDUZIDA -- DES_REDUZIDA = DES_REDUZIDA
  ,   LEFT(PROD.ItemName,50) as DES_PRODUTO -- DES_PRODUTO = DES_PRODUTO
  ,   COMPRA.UNITID as DES_UNIDADE_COMPRA -- DES_UNIDADE_COMPRA = DES_UNIDADE_COMPRA
  ,   VENDA.UNITID as DES_UNIDADE_VENDA -- DES_UNIDADE_VENDA = DES_UNIDADE_VENDA
  ,   0 as TIPO_IPI -- TIPO_IPI = TIPO_IPI
  ,   0 as VAL_IPI -- VAL_IPI = VAL_IPI
/*
	ALTERACAO VICTOR 22/01/2014 [Remoção da tabela DE_PARA_HIERARQUIA_PROD]
  ,   ISNULL(HIERA.ZEUS_COD_SECAO,10) as COD_SECAO -- COD_SECAO = COD_SECAO
  ,   ISNULL(HIERA.ZEUS_COD_GRUPO ,3) as COD_GRUPO -- COD_GRUPO = COD_GRUPO
  ,   ISNULL(HIERA.ZEUS_COD_SUBGRUPO,1) as COD_SUB_GRUPO -- COD_SUB_GRUPO = COD_SUB_GRUPO
*/
--, COD_SECAO = (select ISNULL(HIERA.ZEUS_COD_SECAO,10)  from DE_PARA_HIERARQUIA_PROD as HIERA with (NOLOCK) where HIERA.AX_SECAO_CODIGO = RBO.DIVISIONGROUP)
--, COD_GRUPO = (
--			select ISNULL(HIERA.ZEUS_COD_GRUPO,10) as COD_GRUPO 
--			from DE_PARA_HIERARQUIA_PROD as HIERA with (NOLOCK) 
--			where 1 = 1
--			AND HIERA.AX_SECAO_CODIGO     = RBO.DIVISIONGROUP  
--			AND HIERA.AX_GRUPO_CODIGO     = RBO.ITEMDEPARTMENT 
--			)
--, COD_SUB_GRUPO = (
--			select ISNULL(HIERA.ZEUS_COD_GRUPO,10) as COD_GRUPO 
--			from DE_PARA_HIERARQUIA_PROD as HIERA with (NOLOCK) 
--			where 1 = 1
--			AND HIERA.AX_SECAO_CODIGO     = RBO.DIVISIONGROUP  
--			AND HIERA.AX_GRUPO_CODIGO     = RBO.ITEMDEPARTMENT 
--			AND HIERA.AX_SUBGRUPO_CODIGO  = RBO.RETAILGROUP 
--			) 

	--ALTERAÇÃO INICIA AQUI
  ,   ISNULL(CAST(RBO.DIVISIONGROUP AS INT),10) AS COD_SECAO
  ,   ISNULL(RIGHT(RBO.ITEMDEPARTMENT,(LEN(RBO.ITEMDEPARTMENT) - (CHARINDEX(RBO.DIVISIONGROUP,RBO.ITEMDEPARTMENT) + LEN(RBO.DIVISIONGROUP)-1))),3) AS COD_GRUPO
  ,RBO.RETAILGROUP
  ,   (CASE
		WHEN RBO.RETAILGROUP <> '' THEN
		 CAST(LEFT(RBO.RETAILGROUP,   (LEN(RBO.RETAILGROUP) - (LEN(RIGHT(RBO.ITEMDEPARTMENT,(LEN(RBO.ITEMDEPARTMENT) - (CHARINDEX(RBO.DIVISIONGROUP,RBO.ITEMDEPARTMENT) + LEN(RBO.DIVISIONGROUP)-1)))) + LEN(CONVERT(INT,RBO.DIVISIONGROUP))))   ) AS INT)
		ELSE 1
	  END) AS COD_SUB_GRUPO	
	--ALTERAÇÃO TERMINA AQUI
  ,   NULL as COD_CLASSIF -- COD_CLASSIF = COD_CLASSIF
  ,   NULL as COD_PRODUTO_SIMILAR -- COD_PRODUTO_SIMILAR = COD_PRODUTO_SIMILAR
  ,   case when RBO.scaleItem = 1 then 'S' else 'N' end as IPV -- IPV = IPV
  ,   0 as VAL_BONUS -- VAL_BONUS = VAL_BONUS
  ,   0 as DIAS_VALIDADE -- DIAS_VALIDADE = DIAS_VALIDADE
  ,   0 as STATUS -- STATUS = STATUS
  ,   0 as TIPO_PRODUTO -- TIPO_PRODUTO = TIPO_PRODUTO
  ,   case when RBO.blockedOnPOS = 1 then 'S' else 'N' end     as FORA_LINHA -- FORA_LINHA = FORA_LINHA
  ,   'N' as DECOMPOE_VENDA -- DECOMPOE_VENDA = DECOMPOE_VENDA
  ,   'N' as PERECIVEL -- PERECIVEL = PERECIVEL
  ,   0 as QTD_LIMITE_GONDOLA -- QTD_LIMITE_GONDOLA = QTD_LIMITE_GONDOLA
  ,  NULL   as DES_OBSERVACAO -- DES_OBSERVACAO = DES_OBSERVACAO
  ,  NULL   as IMAGEM_PRODUTO -- IMAGEM_PRODUTO = IMAGEM_PRODUTO
  ,   ' ' as USUARIO -- USUARIO = USUARIO
  ,   convert(varchar, PROD.CREATEDDATETIME, 101) as DTA_ALTERACAO -- DTA_ALTERACAO = DTA_ALTERACAO
  ,   convert(varchar, RBO.DATETOACTIVATEITEM, 101) as DTA_CADASTRO -- DTA_CADASTRO = DTA_CADASTRO
  ,   NULL as DES_EMBALAGEM -- DES_EMBALAGEM = DES_EMBALAGEM
  ,   0 as QTD_DIVISOR_PRECO -- QTD_DIVISOR_PRECO = QTD_DIVISOR_PRECO
  ,   'N' as FLG_ICMS_ANTECIPADO -- FLG_ICMS_ANTECIPADO = FLG_ICMS_ANTECIPADO
  ,   1 as VAL_PESO -- VAL_PESO = VAL_PESO
  ,   NULL as COD_INFO_RECEITA -- COD_INFO_RECEITA = COD_INFO_RECEITA
  ,   NULL as COD_INFO_NUTRICIONAL -- COD_INFO_NUTRICIONAL = COD_INFO_NUTRICIONAL
  ,   'N' as FLG_CRM -- FLG_CRM = FLG_CRM
  ,   'N' as FLG_FLUTUANTE -- FLG_FLUTUANTE = FLG_FLUTUANTE
  ,   NULL as COD_GRADE -- COD_GRADE = COD_GRADE
  ,   'N' as FLG_GRADE_PRODUTO -- FLG_GRADE_PRODUTO = FLG_GRADE_PRODUTO
  ,   NULL as COD_GRADE_ASSOC -- COD_GRADE_ASSOC = COD_GRADE_ASSOC
  ,   NULL as COD_MODELO_GRADE -- COD_MODELO_GRADE = COD_MODELO_GRADE
  ,   0 as TIPO_BONUS -- TIPO_BONUS = TIPO_BONUS
  ,   1 as ETQ_DIVISOR_PRECO -- ETQ_DIVISOR_PRECO = ETQ_DIVISOR_PRECO
  ,   NULL as TEXTO_DIVISOR_PRECO -- TEXTO_DIVISOR_PRECO = TEXTO_DIVISOR_PRECO
  ,   0 as COD_SETOR -- COD_SETOR = COD_SETOR
  ,   NULL as COD_SIT_TRIB_SAIDA -- COD_SIT_TRIB_SAIDA = COD_SIT_TRIB_SAIDA
  ,   NULL as COD_TIPI -- COD_TIPI = COD_TIPI
  ,   0 as per_fator_site -- per_fator_site = per_fator_site
  ,   'N' as flg_restaurante -- flg_restaurante = flg_restaurante
  ,   0 as PER_QUEBRA -- PER_QUEBRA = PER_QUEBRA
  --,   DESC_SECAO = (SELECT TOP 1 THP.AX_SECAO_DESCRICAO FROM [AX2009_INTEGRACAO].dbo.TAB_HIERARQUIA_PRODUTO THP WHERE CAST(THP.AX_SECAO_CODIGO AS int) = HIERA.AX_SECAO_CODIGO)
FROM         SMA_AX50_SP1_DB_PROD.dbo.INVENTTABLEMODULE AS VENDA WITH (NOLOCK) INNER JOIN
                      SMA_AX50_SP1_DB_PROD.dbo.INVENTTABLEMODULE AS COMPRA WITH (NOLOCK) ON VENDA.ITEMID = COMPRA.ITEMID INNER JOIN
                      TAB_CODIGO_BARRA_PRINCIPAL AS CODBARRA WITH (NOLOCK) INNER JOIN
                      SMA_AX50_SP1_DB_PROD.dbo.RBOINVENTTABLE AS RBO WITH (NOLOCK) ON CODBARRA.itemid = RBO.ITEMID INNER JOIN
                      SMA_AX50_SP1_DB_PROD.dbo.INVENTTABLE AS PROD WITH (NOLOCK) ON RBO.DATAAREAID = PROD.DATAAREAID AND RBO.ITEMID = PROD.ITEMID ON 
                      VENDA.ITEMID = PROD.ITEMID 
                      /*
						ALTERACAO VICTOR 22/01/2014 [Remoção da tabela DE_PARA_HIERARQUIA_PROD]
						LEFT OUTER JOIN DE_PARA_HIERARQUIA_PROD AS HIERA WITH (NOLOCK) ON RBO.DIVISIONGROUP = HIERA.AX_SECAO_CODIGO AND RBO.ITEMDEPARTMENT = HIERA.AX_GRUPO_CODIGO AND RBO.RETAILGROUP = HIERA.AX_SUBGRUPO_CODIGO
					*/
WHERE     (1 = 1) AND (COMPRA.MODULETYPE = 1) AND (COMPRA.DATAAREAID = 'BAR') AND (VENDA.MODULETYPE = 2) AND (VENDA.DATAAREAID = 'BAR') AND 
                      (PROD.DATAAREAID = 'VCM')

and PROD.itemid = 399005
