SELECT	
	FR.[DATA] AS DATA	
	--,FR.[COD_LOJA]
	,SUM(ISNULL(FR.CREDITO_REAL,ISNULL(FR.CREDITO_META,0)) + ISNULL(FR.[DEBITO_META],0) + ISNULL(FR.[DINHEIRO_META],0) + ISNULL(FR.VOUCHER_REAL,ISNULL(FR.VOUCHER_META,0)) + ISNULL(FR.[CONTA_CLIENTE_META],0) + ISNULL(FR.[DEVOLUCOES_META],0)) AS VLR_RECEBER
FROM
	[BI].[dbo].[FIN_FLUXO_RECEBIVEL] as FR
WHERE 1=1
	AND CONVERT(DATE,FR.DATA) BETWEEN CONVERT(DATE,'2016-01-01') AND CONVERT(DATE,'2016-12-31')
GROUP BY
	FR.[DATA]

SELECT 
	CONVERT(DATE,[DUEDATE]) AS DATA
	--,AX.COD_LOJA	
	,SUM(AX.[VALOR]) as VALOR_PAGAR

FROM
	[AX2009_INTEGRACAO].[dbo].[TAB_CONTAS_A_PAGAR_GERAL] AS AX
WHERE 1=1
	AND CONVERT(DATE,[DUEDATE]) between CONVERT(DATE,'2015-01-01') AND CONVERT(DATE,GETDATE()+360)
GROUP BY
	AX.[DUEDATE]
;