	SELECT
		DISTINCT NO_DESPESA
	FROM
		BI.DBO.[FIN_FLUXO_DESPESA]


	UPDATE FR
	SET
		FR.DESPESA_FOLHA_PRINC = FD.VLR_DESPESA
	FROM
		BI.DBO.FIN_FLUXO_RECEBIVEL AS FR
		INNER JOIN BI.DBO.[FIN_FLUXO_DESPESA] AS FD
			ON 1=1
			AND FR.COD_LOJA = FD.COD_LOJA
			AND FR.DATA = FD.DATA
	WHERE 1=1
		AND FD.NO_DESPESA = 'Folha Principal'		

	UPDATE FR
	SET
		FR.DESPESA_FOLHA_ANTEC = FD.VLR_DESPESA
	FROM
		BI.DBO.FIN_FLUXO_RECEBIVEL AS FR
		INNER JOIN BI.DBO.[FIN_FLUXO_DESPESA] AS FD
			ON 1=1
			AND FR.COD_LOJA = FD.COD_LOJA
			AND FR.DATA = FD.DATA
	WHERE 1=1
		AND FD.NO_DESPESA = 'Folha Antecipacao'	

	UPDATE FR
	SET
		FR.DESPESA_ALUGUEL = FD.VLR_DESPESA
	FROM
		BI.DBO.FIN_FLUXO_RECEBIVEL AS FR
		INNER JOIN BI.DBO.[FIN_FLUXO_DESPESA] AS FD
			ON 1=1
			AND FR.COD_LOJA = FD.COD_LOJA
			AND FR.DATA = FD.DATA
	WHERE 1=1
		AND FD.NO_DESPESA = 'Aluguel'	
	
	UPDATE FR
	SET
		FR.DESPESA_PIS_COFIN = FD.VLR_DESPESA
	FROM
		BI.DBO.FIN_FLUXO_RECEBIVEL AS FR
		INNER JOIN BI.DBO.[FIN_FLUXO_DESPESA] AS FD
			ON 1=1
			AND FR.COD_LOJA = FD.COD_LOJA
			AND FR.DATA = FD.DATA
	WHERE 1=1
		AND FD.NO_DESPESA = 'PIS/COFINS'
	
	UPDATE FR
	SET
		FR.DESPESA_ENERGIA = FD.VLR_DESPESA
	FROM
		BI.DBO.FIN_FLUXO_RECEBIVEL AS FR
		INNER JOIN BI.DBO.[FIN_FLUXO_DESPESA] AS FD
			ON 1=1
			AND FR.COD_LOJA = FD.COD_LOJA
			AND FR.DATA = FD.DATA
	WHERE 1=1
		AND FD.NO_DESPESA = 'Energia Eletrica'
	
	UPDATE FR
	SET
		FR.DESPESA_ICMS = FD.VLR_DESPESA
	FROM
		BI.DBO.FIN_FLUXO_RECEBIVEL AS FR
		INNER JOIN BI.DBO.[FIN_FLUXO_DESPESA] AS FD
			ON 1=1
			AND FR.COD_LOJA = FD.COD_LOJA
			AND FR.DATA = FD.DATA
	WHERE 1=1
		AND FD.NO_DESPESA = 'ICMS'

	UPDATE FR
	SET
		FR.DESPESA_JUROS = FD.VLR_DESPESA
	FROM
		BI.DBO.FIN_FLUXO_RECEBIVEL AS FR
		INNER JOIN BI.DBO.[FIN_FLUXO_DESPESA] AS FD
			ON 1=1
			AND FR.COD_LOJA = FD.COD_LOJA
			AND FR.DATA = FD.DATA
	WHERE 1=1
		AND FD.NO_DESPESA = 'JUROS'