	-- ---------------------------------------------------------------------------------------------------------------------
	-- 
	-- ---------------------------------------------------------------------------------------------------------------------
	SELECT
		CLI.DES_CLIENTE AS NO_CLIENTE
		,CLI.NUM_CGC
		,CB.COD_PRODUTO AS COD_PRODUTO
		--,CP.DESCRICAO AS NO_PRODUTO		
		,(CASE WHEN CP.DESCRICAO IS NULL THEN PROMO.des_promocao ELSE CP.DESCRICAO COLLATE SQL_Latin1_General_CP1_CI_AS END)	
		,(SELECT MIN(VLR_VENDA) FROM BI.dbo.BI_LINHA_PRODUTOS AS LP WHERE LP.COD_PRODUTO = CB.COD_PRODUTO) AS PRECO_VENDA 
		,PROMO.valorfixo AS VLR_FIXO
		,PROMO.PERCENTUAL AS VLR_PERC
		--,PROD_PROMO.codproduto AS EAN
		,PROMO.des_promocao AS NO_PROMO				
		,CONVERT(DATE,PROMO.datainicio) AS DTA_INI
		,CONVERT(DATE,PROMO.datatermino) AS DTA_FIM
	FROM
		[ZEUSRETAIL].[DBO].[TAB_CLIENTE] AS CLI		
		INNER JOIN [ZEUSRETAIL].[DBO].[TAB_CLIENTE_CATEGORIA] AS CLI_CAT
		   ON CLI_CAT.COD_CLIENTE = CLI.COD_CLIENTE	
		INNER JOIN [ZEUSRETAIL].[DBO].[TAB_PROMOCAO_CAT_CLIENTE] AS CAT_CLI_PROMO
			ON CLI_CAT.categoria_cliente = CAT_CLI_PROMO.categoria_cliente
		LEFT JOIN [ZEUSRETAIL].[DBO].[TAB_NOVAPROMOCAO] AS PROMO 
			ON CAT_CLI_PROMO.CODPROMOCAO = PROMO.CODPROMOCAO
		LEFT JOIN [ZEUSRETAIL].[DBO].[TAB_PROMOCAO_PRODUTO] AS PROD_PROMO 
		   ON CAT_CLI_PROMO.CODPROMOCAO = PROD_PROMO.CODPROMOCAO
		LEFT JOIN AX2009_INTEGRACAO.dbo.TAB_CODIGO_BARRA AS CB
			ON CONVERT(DOUBLE PRECISION,PROD_PROMO.codproduto) = CONVERT(DOUBLE PRECISION,CB.COD_EAN)
		LEFT JOIN BI.dbo.BI_CAD_PRODUTO AS CP
			ON CB.COD_PRODUTO = CP.COD_PRODUTO
	WHERE 1=1
		AND CLI.NUM_CGC = '43050849886'--'32313960854'
		AND CONVERT(DATE,PROMO.datatermino) >= CONVERT(DATE,GETDATE())
