DECLARE @TAB_VENDA AS TABLE
(
	COD_LOJA INT
	,COD_PRODUTO INT
	,VLR_TOTAL NUMERIC(18,2)
	,QTD_TOTAL NUMERIC(18,2)
)

INSERT INTO @TAB_VENDA
	SELECT
		COD_LOJA
		,COD_PRODUTO
		,SUM(VALOR_TOTAL) AS VLR_TOTAL
		,SUM(QTDE_PRODUTO) AS QTD_TOTAL
	FROM
		BI_VENDA_PRODUTO AS VP
	WHERE 1=1
		AND CONVERT(DATE,VP.DATA) BETWEEN CONVERT(DATE,'20140901') AND CONVERT(DATE,'20141130')
	GROUP BY
		COD_LOJA
		,COD_PRODUTO

SELECT
	EP.COD_LOJA
	,EP.COD_PRODUTO
	,CP.DESCRICAO
	,EP.QTD_ESTOQUE
	,EP.VLR_CUSTO_UN
	,BI.DBO.fn_FormataVlr_Excel(V.VLR_TOTAL) AS VLR_TOTAL
	,BI.DBO.fn_FormataVlr_Excel(V.QTD_TOTAL) AS QTD_TOTAL
FROM
	BI_ESTOQUE_PRODUTO_DIA AS EP
	INNER JOIN BI_CAD_PRODUTO AS CP
		ON EP.COD_PRODUTO = CP.COD_PRODUTO
	INNER JOIN @TAB_VENDA AS V
		ON 1=1
		AND EP.COD_LOJA = V.COD_LOJA
		AND EP.COD_PRODUTO = V.COD_PRODUTO
WHERE 1=1
	AND CONVERT(DATE,DATA) = CONVERT(DATE,GETDATE()-1)
ORDER BY
	EP.COD_LOJA
	,V.VLR_TOTAL DESC