	set nocount on;
	DECLARE @COD_FORNECEDOR AS INT = `3`
	DECLARE @DT_INI AS DATE = `1`
	DECLARE @DT_FIM AS DATE = `2`
	
	DECLARE @TAB_RECEBIMENTO AS TABLE
	(
		COD_FORNECEDOR INT
		,NUM_PEDIDO INT
		,COD_LOJA INT
		,DATA_RECEBIMENTO DATETIME
	)
	INSERT INTO @TAB_RECEBIMENTO
	SELECT DISTINCT
		FORNECEDOR_COD
		,PEDIDO_NUMERO
		,COD_LOJA
		,CONVERT(DATE,DATA)
	FROM
		[192.168.0.6].[INTRANET].[DBO].[TAB_RECEB_MERCADORIA]
	WHERE 1 = 1
		AND CONVERT(DATE,DATA) BETWEEN CONVERT(DATE,@DT_INI) AND CONVERT(DATE,@DT_FIM)
		AND FORNECEDOR_COD = @COD_FORNECEDOR
		

	SELECT
		PED.[COD_LOJA] AS [Cod Loja]
		,PED.[COD_PARCEIRO] AS [Cod Forn]
		,CF.DESCRICAO AS [Forn]
		,SUM(CASE WHEN PED.[QTD_RECEBIDA] > 0 THEN 1 ELSE 0 END) AS [Qtd Recebida]
		,SUM(CASE WHEN CONVERT(DATE,P.DTA_ENTREGA) = CONVERT(DATE,REC.DATA_RECEBIMENTO) THEN 1 ELSE 0 END) AS [Qtd Data Ok]
		,SUM(CASE WHEN (PED.[QTD_PEDIDO]*PED.[QTD_EMBALAGEM]) > 0 THEN 1 ELSE 0 END) AS [Qtd Pedida]
	FROM
		[192.168.0.6].[ZEUS_RTG].[DBO].[TAB_PEDIDO] AS P INNER JOIN [192.168.0.6].[ZEUS_RTG].[DBO].[TAB_PEDIDO_PRODUTO] AS PED ON (P.COD_PARCEIRO = PED.COD_PARCEIRO AND P.NUM_PEDIDO = PED.NUM_PEDIDO AND P.COD_LOJA = PED.COD_LOJA)	
			INNER JOIN @TAB_RECEBIMENTO AS REC ON (PED.COD_PARCEIRO = REC.COD_FORNECEDOR AND PED.NUM_PEDIDO = REC.NUM_PEDIDO AND PED.COD_LOJA = REC.COD_LOJA)
			--LEFT JOIN BI.DBO.BI_CAD_PRODUTO AS CP ON (PED.COD_PRODUTO = CP.COD_PRODUTO)
				LEFT JOIN BI.DBO.BI_CAD_FORNECEDOR AS CF ON (PED.[COD_PARCEIRO] = CF.COD_FORNECEDOR)
	WHERE 1 = 1
		AND PED.[QTD_PEDIDO] > 0
		AND CONVERT(DATE,P.DTA_EMISSAO) BETWEEN CONVERT(DATE,@DT_INI) AND CONVERT(DATE,@DT_FIM)
		AND PED.[COD_PARCEIRO] = @COD_FORNECEDOR
	GROUP BY
		PED.[COD_LOJA]
		,PED.[COD_PARCEIRO]
		,CF.DESCRICAO
		
		
		
		select * from [192.168.0.6].[ZEUS_RTG].[DBO].[TAB_PEDIDO] AS P 
		WHERE 1 = 1
		AND CONVERT(DATE,P.DTA_EMISSAO) BETWEEN CONVERT(DATE,'20140101') AND CONVERT(DATE,'20140401')