	DECLARE @COD_LOJA AS INT
	DECLARE @COD_PRODUTO AS INT
	DECLARE @DATA AS DATE

	DECLARE @COD_PEDIDO AS INT
	DECLARE @COD_FORNECEDOR AS INT
	DECLARE @COD_USUARIO_PED AS INT
	DECLARE @DATA_PED AS DATETIME

	DECLARE cursor_objects CURSOR FOR
		SELECT
			COD_LOJA
			,COD_PRODUTO
			,DTA_RECORD
		FROM
			[Alpha].[dbo].[RUPTURA_LOJA]
		WHERE
			INATIVO IS NULL

	OPEN cursor_objects


	FETCH NEXT FROM cursor_objects INTO @COD_LOJA, @COD_PRODUTO, @DATA


	WHILE @@FETCH_STATUS = 0
	BEGIN
		-- ----------------------------------------------------------------------------------------------------------
	    
		IF EXISTS (
					SELECT 1
					FROM
						[192.168.0.6].ZEUS_RTG.DBO.TAB_PEDIDO AS P INNER JOIN [192.168.0.6].ZEUS_RTG.DBO.TAB_PEDIDO_PRODUTO AS PP
						ON (P.NUM_PEDIDO = PP.NUM_PEDIDO AND P.COD_LOJA = PP.COD_LOJA AND P.COD_PARCEIRO = PP.COD_PARCEIRO)
					WHERE 1 = 1
						AND P.COD_LOJA = @COD_LOJA
						AND PP.COD_PRODUTO = @COD_PRODUTO
						--AND CONVERT(DATE,P.DTA_EMISSAO) >= CONVERT(DATE,@DATA)
						AND CONVERT(DATE,P.DTA_EMISSAO) >= CONVERT(DATE,DATEADD(D,-7,@DATA))
						AND CONVERT(DATE,P.DTA_ENTREGA) >= CONVERT(DATE,@DATA)
				)
		BEGIN
			SELECT TOP 1
				@COD_PEDIDO = P.NUM_PEDIDO
				,@COD_FORNECEDOR = P.COD_PARCEIRO
				,@COD_USUARIO_PED = P.COD_USUARIO
				,@DATA_PED = P.DTA_EMISSAO
			FROM
				[192.168.0.6].ZEUS_RTG.DBO.TAB_PEDIDO AS P INNER JOIN [192.168.0.6].ZEUS_RTG.DBO.TAB_PEDIDO_PRODUTO AS PP
				ON (P.NUM_PEDIDO = PP.NUM_PEDIDO AND P.COD_LOJA = PP.COD_LOJA AND P.COD_PARCEIRO = PP.COD_PARCEIRO)
			WHERE 1 = 1
				AND P.COD_LOJA = @COD_LOJA
				AND PP.COD_PRODUTO = @COD_PRODUTO
				AND CONVERT(DATE,P.DTA_EMISSAO) >= CONVERT(DATE,DATEADD(D,-7,@DATA))
				AND CONVERT(DATE,P.DTA_ENTREGA) >= CONVERT(DATE,@DATA)
			
			
			UPDATE RL
			SET
				RL.COD_USUARIO_PED = @COD_USUARIO_PED
				,RL.COD_FORNECEDOR = @COD_FORNECEDOR
				,RL.COD_PEDIDO = @COD_PEDIDO
				,RL.DTA_PEDIDO = @DATA_PED
				,RL.INATIVO = 1
			FROM
				[Alpha].[dbo].[RUPTURA_LOJA] AS RL
			WHERE 1 = 1
				AND COD_LOJA = @COD_LOJA
				AND COD_PRODUTO = @COD_PRODUTO
				AND INATIVO IS NULL
			
			/*
			PRINT @COD_PRODUTO
			PRINT @COD_LOJA
			PRINT @COD_USUARIO_PED
			PRINT @COD_FORNECEDOR
			PRINT @COD_PEDIDO
			PRINT @DATA_PED
			*/
		END
		-- ----------------------------------------------------------------------------------------------------------
		FETCH NEXT FROM cursor_objects INTO @COD_LOJA, @COD_PRODUTO, @DATA
	END

	CLOSE cursor_objects

	DEALLOCATE cursor_objects 