select * FROM [Alpha].[dbo].[RUPTURA_LOJA]


CREATE TRIGGER [dbo].[TRIGGER_ATUALIZA_PROJ_FUNC]
ON [FUNCIONARIOS] AFTER INSERT
AS
BEGIN
	DECLARE @DTDEMISSAO DATETIME
	DECLARE @IDFUNC INT
	
	SELECT @IDFUNC = (SELECT TOP 1 IDFUNCIONARIO FROM INSERTED)
	SELECT @DTDEMISSAO = (SELECT TOP 1 DtAdmissao FROM INSERTED)
	
	UPDATE FUNC_PROJ SET DtAlocFim = @DTDEMISSAO WHERE IDFUNCIONARIO = @IDFUNC
END

SELECT * FROM FUNC_PROJ

UPDATE [FUNCIONARIOS] SET DtAdmissao = GETDATE() WHERE IDFUNCIONARIO = 1