USE [BI]
GO

/****** Object:  StoredProcedure [dbo].[QW_23_VENDA]    Script Date: 10/14/2016 19:30:33 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

-- =============================================
-- Author:		<Author,,Name>
-- Create date: <Create Date,,>
-- Description:	<Description,,>
-- =============================================
ALTER PROCEDURE [dbo].[QW_23_VENDA]
AS
BEGIN
	SET NOCOUNT ON;
	
	DECLARE @DATA_INI AS DATE = '2016-08-01'
	DECLARE @DATA_FIM AS DATE = GETDATE()-1
	-- ------------------------------------------------------------------------------------------------------------------------------------------------------------------
	--
	-- ------------------------------------------------------------------------------------------------------------------------------------------------------------------
	SELECT
		VI.[COD_LOJA]
		,VI.COD_RESTAURANTE
		--,CR.NO_RESTAURANTE
		,CONVERT(DATE,VI.DATA) AS DATA
		,ISNULL(DEPARA.COD_PRODUTO,1) AS COD_PRODUTO			
		,sum(VI.VALOR_UNITARIO) as  VLR_UNITARIO_PROD
		,sum(VI.QUANTIDADE*ISNULL(VI.Quantidade_Dividida,1)) as QTD_VENDA
		,sum(VI.VALOR_DESCONTO) as VLR_DSCONTO_PROD
		,sum(VI.VALOR_TOTAL) as VLR_TOTAL_PRODUTO
		,sum(isnull(VI.ValorTotalSemImposto,VI.VALOR_TOTAL*0.968)) as VLR_TOTAL_SEM_IMP
	FROM
		[DW].[dbo].[TAB_CHEFFSOLUTION_CUPOM_ITENS] AS VI
		LEFT JOIN BI.dbo.BI_CAD_RESTAURANTE AS CR
			ON 1=1
			AND VI.COD_LOJA = CR.COD_LOJA
			AND VI.COD_RESTAURANTE = CR.COD_RESTAURANTE
		
		LEFT JOIN [BI].[dbo].[CAD_DE_PARA_CHEFF] AS DEPARA
			ON 1=1
			AND VI.COD_PRODUTO_CHEFF = DEPARA.COD_PRODUTO_CHEFF
			AND VI.COD_RESTAURANTE = DEPARA.COD_RESTAURANTE
		LEFT JOIN BI.dbo.BI_CAD_PRODUTO AS CP
			ON DEPARA.COD_PRODUTO = CP.COD_PRODUTO
	WHERE 1=1
		AND CONVERT(DATE,VI.DATA) BETWEEN CONVERT(DATE,@DATA_INI) AND CONVERT(DATE,@DATA_FIM)
		AND VI.COD_LOJA IN (33)
		AND VI.COD_RESTAURANTE NOT IN (111)
		--AND VI.COD_RESTAURANTE IN (SELECT DISTINCT COD_RESTAURANTE FROM BI.dbo.BI_CAD_RESTAURANTE WHERE TIPO_RESTAURANTE = 'FTS')	
		--and CP.COD_DEPARTAMENTO = 7
	GROUP BY
		VI.[COD_LOJA]
		,VI.COD_RESTAURANTE
		--,CR.NO_RESTAURANTE
		,CONVERT(DATE,VI.DATA)
		,DEPARA.COD_PRODUTO
	
	UNION ALL
		
	SELECT
		T.COD_LOJA
		,99 AS COD_RESTAURANTE
		,CONVERT(DATE,T.DTA_AJUSTE) AS DATA
		,T.COD_PRODUTO
		,MAX(T.VAL_CUSTO_REP)
		,0
		,0
		,SUM((T.QTD_AJUSTE)*T.VAL_CUSTO_REP) AS VLR_TOTAL_PRODUTO
		,SUM((T.QTD_AJUSTE)*T.VAL_CUSTO_REP) AS VLR_TOTAL_SEM_IMP				
	FROM
		[192.168.0.6].ZEUS_RTG.DBO.TAB_AJUSTE_ESTOQUE AS T
		INNER JOIN [192.168.0.6].ZEUS_RTG.DBO.TAB_TIPO_AJUSTE AS TA
			ON 1=1
			AND T.COD_AJUSTE = TA.COD_AJUSTE	
	WHERE 1=1
		AND T.COD_LOJA = 33
		AND T.COD_AJUSTE IN (494)
		AND CONVERT(DATE,T.DTA_AJUSTE) BETWEEN CONVERT(DATE,@DATA_INI) AND CONVERT(DATE,@DATA_FIM)
	GROUP BY
		T.COD_LOJA
		,CONVERT(DATE,T.DTA_AJUSTE)
		,T.COD_PRODUTO	
	
	UNION ALL
	
	SELECT
		T.COD_LOJA
		,98 AS COD_RESTAURANTE
		,CONVERT(DATE,T.DTA_AJUSTE) AS DATA
		,T.COD_PRODUTO
		,MAX(T.VAL_CUSTO_REP)
		,0
		,0
		,SUM((T.QTD_AJUSTE)*T.VAL_CUSTO_REP)*-1 AS VLR_TOTAL_PRODUTO
		,SUM((T.QTD_AJUSTE)*T.VAL_CUSTO_REP)*-1 AS VLR_TOTAL_SEM_IMP				
	FROM
		[192.168.0.6].ZEUS_RTG.DBO.TAB_AJUSTE_ESTOQUE AS T
		INNER JOIN [192.168.0.6].ZEUS_RTG.DBO.TAB_TIPO_AJUSTE AS TA
			ON 1=1
			AND T.COD_AJUSTE = TA.COD_AJUSTE	
	WHERE 1=1
		AND T.COD_LOJA = 33
		AND T.COD_AJUSTE IN (494)
		AND CONVERT(DATE,T.DTA_AJUSTE) BETWEEN CONVERT(DATE,@DATA_INI) AND CONVERT(DATE,@DATA_FIM)
	GROUP BY
		T.COD_LOJA
		,CONVERT(DATE,T.DTA_AJUSTE)
		,T.COD_PRODUTO	
	
	/* PASTA */
	UNION ALL
	
	SELECT	
		VI.[COD_LOJA]
		,VI.COD_RESTAURANTE
		--,CR.NO_RESTAURANTE
		,CONVERT(DATE,VI.DATA) AS DATA
		,ISNULL(DEPARA.COD_PRODUTO,1) AS COD_PRODUTO			
		,sum(VI.VALOR_UNITARIO) as  VLR_UNITARIO_PROD
		,sum(VI.QUANTIDADE*ISNULL(VI.Quantidade_Dividida,1)) as QTD_VENDA
		,sum(VI.VALOR_DESCONTO) as VLR_DSCONTO_PROD
		,sum(VI.VALOR_TOTAL) as VLR_TOTAL_PRODUTO --*0.787
		,sum(isnull(VI.ValorTotalSemImposto,VI.VALOR_TOTAL*0.968)) as VLR_TOTAL_SEM_IMP --*0.787
	FROM
		[DW].[dbo].[TAB_CHEFFSOLUTION_CUPOM_ITENS] AS VI
		LEFT JOIN BI.dbo.BI_CAD_RESTAURANTE AS CR
			ON 1=1
			AND VI.COD_LOJA = CR.COD_LOJA
			AND VI.COD_RESTAURANTE = CR.COD_RESTAURANTE
		
		LEFT JOIN [BI].[dbo].[CAD_DE_PARA_CHEFF] AS DEPARA
			ON 1=1
			AND VI.COD_PRODUTO_CHEFF = DEPARA.COD_PRODUTO_CHEFF
			AND VI.COD_RESTAURANTE = DEPARA.COD_RESTAURANTE
		LEFT JOIN BI.dbo.BI_CAD_PRODUTO AS CP
			ON DEPARA.COD_PRODUTO = CP.COD_PRODUTO
	WHERE 1=1
		AND CONVERT(DATE,VI.DATA) BETWEEN CONVERT(DATE,@DATA_INI) AND CONVERT(DATE,@DATA_FIM)
		AND VI.COD_LOJA IN (33)
		AND VI.COD_RESTAURANTE IN (111)
		AND DEPARA.COD_PRODUTO NOT IN (SELECT TPM.COD_PRODUTO FROM CADASTRO_CAD_PRODUTO_METADADOS TPM WHERE TPM.COD_METADADO = 48 AND TPM.VLR_METADADO = 1)
		
	GROUP BY
		VI.[COD_LOJA]
		,VI.COD_RESTAURANTE
		,CONVERT(DATE,VI.DATA)
		,DEPARA.COD_PRODUTO
	
	/* ROSSO */
	UNION ALL
	
	SELECT	
		VI.[COD_LOJA]
		,96 AS COD_RESTAURANTE
		--,CR.NO_RESTAURANTE
		,CONVERT(DATE,VI.DATA) AS DATA
		,1--DEPARA.COD_PRODUTO AS COD_PRODUTO			
		,sum(VI.VALOR_UNITARIO * VI.QUANTIDADE) as  VLR_UNITARIO_PROD
		,sum(VI.QUANTIDADE*ISNULL(VI.Quantidade_Dividida,1)) as QTD_VENDA
		,sum(VI.VALOR_DESCONTO) as VLR_DSCONTO_PROD
		,sum(VI.VALOR_TOTAL) as VLR_TOTAL_PRODUTO --*0.213
		,sum(isnull(VI.ValorTotalSemImposto,VI.VALOR_TOTAL*0.968)) as VLR_TOTAL_SEM_IMP --*0.213
	FROM
		[DW].[dbo].[TAB_CHEFFSOLUTION_CUPOM_ITENS] AS VI
		LEFT JOIN BI.dbo.BI_CAD_RESTAURANTE AS CR
			ON 1=1
			AND VI.COD_LOJA = CR.COD_LOJA
			AND VI.COD_RESTAURANTE = CR.COD_RESTAURANTE
		
		LEFT JOIN [BI].[dbo].[CAD_DE_PARA_CHEFF] AS DEPARA
			ON 1=1
			AND VI.COD_PRODUTO_CHEFF = DEPARA.COD_PRODUTO_CHEFF
			AND VI.COD_RESTAURANTE = DEPARA.COD_RESTAURANTE
		LEFT JOIN BI.dbo.BI_CAD_PRODUTO AS CP
			ON DEPARA.COD_PRODUTO = CP.COD_PRODUTO
	WHERE 1=1
		AND CONVERT(DATE,VI.DATA) BETWEEN CONVERT(DATE,@DATA_INI) AND CONVERT(DATE,@DATA_FIM)
		AND VI.COD_LOJA IN (33)
		AND VI.COD_RESTAURANTE IN (111)
		AND DEPARA.COD_PRODUTO IN (SELECT TPM.COD_PRODUTO FROM CADASTRO_CAD_PRODUTO_METADADOS TPM WHERE TPM.COD_METADADO = 48 AND TPM.VLR_METADADO = 1)
	GROUP BY
		VI.[COD_LOJA]
		,CONVERT(DATE,VI.DATA)
		--,DEPARA.COD_PRODUTO
	
END

GO


