DECLARE @TEMP_TAB_PEDIDO AS TABLE
(
	[COD_LOJA] [INT],
	[DTA_EMISSAO] [DATE],
	[COD_PARCEIRO] [INT],
	[COD_PEDIDO] [INT],
	[COD_PRODUTO] [INT],
	[QTD_PEDIDO] [INT],
	[TOTAL_ITENS] [INT]
);

INSERT INTO @TEMP_TAB_PEDIDO 
SELECT --TOP 100
	PED.COD_LOJA
	,PED.DTA_EMISSAO
	,PED.COD_PARCEIRO
	,PED.NUM_PEDIDO
	,PED_PROD.COD_PRODUTO
	,PED_PROD.QTD_PEDIDO
	,(SELECT COUNT(COD_PRODUTO) FROM ZEUS_RTG.DBO.TAB_PEDIDO_PRODUTO AS TPP WHERE TPP.NUM_PEDIDO = PED_PROD.NUM_PEDIDO AND TPP.COD_LOJA = PED_PROD.COD_LOJA AND TPP.COD_PARCEIRO = PED_PROD.COD_PARCEIRO)
FROM
	ZEUS_RTG.DBO.TAB_PEDIDO AS PED INNER JOIN ZEUS_RTG.DBO.TAB_PEDIDO_PRODUTO AS PED_PROD ON (PED.NUM_PEDIDO = PED_PROD.NUM_PEDIDO AND PED.COD_LOJA = PED_PROD.COD_LOJA AND PED.COD_PARCEIRO = PED_PROD.COD_PARCEIRO)
WHERE 1 = 1
	AND CONVERT(DATE,PED.DTA_EMISSAO) >= CONVERT(DATE,'20130801')

	
DECLARE @TEMP_TAB_PEDIDO_RECEBIMENTO AS TABLE
(
	[COD_LOJA] [INT],
	[DTA_EMISSAO] [DATE],
	[COD_PARCEIRO] [INT],
	[COD_PEDIDO] [INT],
	[COD_PRODUTO] [INT],
	[QTD_PEDIDO] [INT],
	[TOTAL_ITENS] [INT]
);

INSERT INTO @TEMP_TAB_PEDIDO_RECEBIMENTO
SELECT --TOP 100
	REC_MERC.COD_LOJA
	,REC_MERC.DATA
	,REC_MERC.FORNECEDOR_COD
	,REC_MERC.PEDIDO_NUMERO
	,REC_CONT.COD_PRODUTO
	,REC_CONT.QTD_ORIGINAL
	,(SELECT COUNT(COD_PRODUTO) FROM [INTRANET].[DBO].[TAB_RECEB_MERCADORIA] AS TREC_MERC INNER JOIN [INTRANET].[DBO].[TAB_RECEB_MERCADORIA_CONTAGEM] AS TREC_CONT ON (TREC_MERC.ID = TREC_CONT.ID) WHERE TREC_MERC.COD_LOJA = REC_MERC.COD_LOJA AND TREC_MERC.FORNECEDOR_COD = REC_MERC.FORNECEDOR_COD AND TREC_MERC.PEDIDO_NUMERO = REC_MERC.PEDIDO_NUMERO)
	--,(SELECT COUNT(PEDIDO_NUMERO) FROM [INTRANET].[DBO].[TAB_RECEB_MERCADORIA_CONTAGEM] AS TRMC WHERE TRMC.ID = REC_MERC.ID)
FROM [INTRANET].[DBO].[TAB_RECEB_MERCADORIA] AS REC_MERC INNER JOIN [INTRANET].[DBO].[TAB_RECEB_MERCADORIA_CONTAGEM] AS REC_CONT ON (REC_MERC.ID = REC_CONT.ID)
WHERE 1 = 1
	AND CONVERT(DATE,REC_MERC.DATA) >= CONVERT(DATE,'20130801')


SELECT
	PED.[COD_LOJA]
	,PED.[DTA_EMISSAO]
	,PED.[COD_PARCEIRO]
	,PED.[COD_PEDIDO]
	,PED.[COD_PRODUTO]
	,PED.[QTD_PEDIDO] AS QTD_PED
	,PED.[TOTAL_ITENS] AS TOTAL_ITENS_PED
	,isnull(REC.[QTD_PEDIDO],0) AS QTD_REC
	,isnull(REC.[TOTAL_ITENS],0) AS TOTAL_ITENS_REC
FROM
	@TEMP_TAB_PEDIDO AS PED LEFT JOIN @TEMP_TAB_PEDIDO_RECEBIMENTO AS REC ON (PED.COD_LOJA = REC.COD_LOJA AND PED.COD_PARCEIRO = REC.COD_PARCEIRO AND PED.COD_PRODUTO = REC.COD_PRODUTO AND PED.COD_PEDIDO = REC.COD_PEDIDO)
ORDER BY
	PED.[COD_LOJA],
	PED.[COD_PEDIDO],
	PED.[COD_PRODUTO];

--SELECT TOP 10 * FROM [INTRANET].[DBO].[TAB_RECEB_MERCADORIA] AS REC_MERC INNER JOIN [INTRANET].[DBO].[TAB_RECEB_MERCADORIA_CONTAGEM] AS REC_CONT ON (REC_MERC.ID = REC_CONT.ID)


