DECLARE @TAB_CARGOS AS TABLE
(
	CARGO_ID INT
	,CARGO_NOME VARCHAR(20)
);

INSERT INTO @TAB_CARGOS VALUES (1,'CARGO_A');
INSERT INTO @TAB_CARGOS VALUES (2,'CARGO_B');
INSERT INTO @TAB_CARGOS VALUES (3,'CARGO_C');
INSERT INTO @TAB_CARGOS VALUES (4,'CARGO_D');
INSERT INTO @TAB_CARGOS VALUES (5,'CARGO_E');

DECLARE @TAB_FUNCIONARIOS AS TABLE
(
	FUNC_ID INT
	,FUNC_NOME VARCHAR(20)
	,CARGO_ID INT
);

INSERT INTO @TAB_FUNCIONARIOS VALUES (1,'FUNCIONARIO_A',5);
INSERT INTO @TAB_FUNCIONARIOS VALUES (2,'FUNCIONARIO_B',4);
INSERT INTO @TAB_FUNCIONARIOS VALUES (3,'FUNCIONARIO_C',3);
INSERT INTO @TAB_FUNCIONARIOS VALUES (4,'FUNCIONARIO_D',2);
INSERT INTO @TAB_FUNCIONARIOS VALUES (5,'FUNCIONARIO_E',1);
INSERT INTO @TAB_FUNCIONARIOS VALUES (6,'FUNCIONARIO_F',5);
INSERT INTO @TAB_FUNCIONARIOS VALUES (7,'FUNCIONARIO_G',4);
INSERT INTO @TAB_FUNCIONARIOS VALUES (8,'FUNCIONARIO_H',3);
INSERT INTO @TAB_FUNCIONARIOS VALUES (9,'FUNCIONARIO_I',2);
INSERT INTO @TAB_FUNCIONARIOS VALUES (10,'FUNCIONARIO_J',1);
INSERT INTO @TAB_FUNCIONARIOS VALUES (11,'FUNCIONARIO_K',5);
INSERT INTO @TAB_FUNCIONARIOS VALUES (12,'FUNCIONARIO_L',4);
INSERT INTO @TAB_FUNCIONARIOS VALUES (13,'FUNCIONARIO_M',3);
INSERT INTO @TAB_FUNCIONARIOS VALUES (14,'FUNCIONARIO_N',2);
INSERT INTO @TAB_FUNCIONARIOS VALUES (15,'FUNCIONARIO_O',1);
INSERT INTO @TAB_FUNCIONARIOS VALUES (16,'FUNCIONARIO_P',1);
INSERT INTO @TAB_FUNCIONARIOS VALUES (17,'FUNCIONARIO_Q',1);
INSERT INTO @TAB_FUNCIONARIOS VALUES (18,'FUNCIONARIO_R',2);
INSERT INTO @TAB_FUNCIONARIOS VALUES (19,'FUNCIONARIO_S',2);
INSERT INTO @TAB_FUNCIONARIOS VALUES (20,'FUNCIONARIO_T',1);


SET NOCOUNT ON;

DECLARE @MESSAGE VARCHAR(80), @CARGO_ID INT, @CARGO_NOME VARCHAR(20),@FUNC_ID INT, @FUNC_NOME VARCHAR(20), @CONTADOR AS INT = 0;

PRINT '-------- RELATÓRIO --------';

-- --------------------------------------------------------------------------------------------------------
DECLARE CARGO_CURSOR CURSOR FOR 
	SELECT
		CARGO_ID,
		CARGO_NOME
	FROM
		@TAB_CARGOS
OPEN CARGO_CURSOR

FETCH NEXT FROM CARGO_CURSOR INTO @CARGO_ID, @CARGO_NOME
-- --------------------------------------------------------------------------------------------------------

WHILE @@FETCH_STATUS = 0
BEGIN
    PRINT ' '
    SELECT @MESSAGE = '----- CARGOS DO DEPARTAMENTO: ' + @CARGO_NOME

    PRINT @MESSAGE
    SET @CONTADOR = 0

	-- --------------------------------------------------------------------------------------------------------
    DECLARE FUNC_CURSOR CURSOR FOR 
		SELECT
			FUNC_ID,
			FUNC_NOME
		FROM
			@TAB_FUNCIONARIOS
		WHERE CARGO_ID = @CARGO_ID 
	OPEN FUNC_CURSOR
    
	FETCH NEXT FROM FUNC_CURSOR INTO @FUNC_ID, @FUNC_NOME
	-- --------------------------------------------------------------------------------------------------------
	
    IF @@FETCH_STATUS <> 0 
        PRINT '         <<NONE>>'     

    WHILE @@FETCH_STATUS = 0
    BEGIN

        SELECT @MESSAGE = '         ' + @FUNC_NOME
        PRINT @MESSAGE
        
        SET @CONTADOR = @CONTADOR + 1
        FETCH NEXT FROM FUNC_CURSOR INTO @FUNC_ID, @FUNC_NOME
    END
		PRINT ''
        PRINT 'TOTAL DE FUNCIONÁRIOS COM O CARGO ' + CAST(@CARGO_NOME AS VARCHAR(10)) + ': ' + CAST(@CONTADOR AS CHAR)    
		
    CLOSE FUNC_CURSOR
    DEALLOCATE FUNC_CURSOR

    FETCH NEXT FROM CARGO_CURSOR INTO @CARGO_ID, @CARGO_NOME
END 
CLOSE CARGO_CURSOR;
DEALLOCATE CARGO_CURSOR;