DECLARE @TAB_DEPARTAMENTOS AS TABLE
(
	DEPARTAMENTO_ID INT
	,DEPARTAMENTO_NOME VARCHAR(20)
);

INSERT INTO @TAB_DEPARTAMENTOS VALUES (1,'TI');
INSERT INTO @TAB_DEPARTAMENTOS VALUES (2,'RH');
INSERT INTO @TAB_DEPARTAMENTOS VALUES (3,'FINANCEIRO');

DECLARE @TAB_CARGOS AS TABLE
(
	CARGO_ID INT
	,CARGO_NOME VARCHAR(20)
	,DEPARTAMENTO_ID INT
);

INSERT INTO @TAB_CARGOS VALUES (1,'GERENTE',1);
INSERT INTO @TAB_CARGOS VALUES (2,'FUNCIONARIO',1);
INSERT INTO @TAB_CARGOS VALUES (3,'GERENTE',2);
INSERT INTO @TAB_CARGOS VALUES (4,'FUNCIONARIO',2);
INSERT INTO @TAB_CARGOS VALUES (5,'GERENTE',3);

DECLARE @TAB_FUNCIONARIOS AS TABLE
(
	FUNC_ID INT
	,FUNC_NOME VARCHAR(20)
	,CARGO_ID INT
);

INSERT INTO @TAB_FUNCIONARIOS VALUES (1,'FUNCIONARIO_A',5);
INSERT INTO @TAB_FUNCIONARIOS VALUES (2,'FUNCIONARIO_B',4);
INSERT INTO @TAB_FUNCIONARIOS VALUES (3,'FUNCIONARIO_C',3);
INSERT INTO @TAB_FUNCIONARIOS VALUES (4,'FUNCIONARIO_D',2);
INSERT INTO @TAB_FUNCIONARIOS VALUES (5,'FUNCIONARIO_E',1);


SET NOCOUNT ON;

DECLARE @DEPARTAMENTO_ID INT, @DEPARTAMENTO_NOME VARCHAR(50), @MESSAGE VARCHAR(80), @CARGO_ID INT, @CARGO_NOME VARCHAR(20),@FUNC_ID INT, @FUNC_NOME VARCHAR(20);

PRINT '-------- RELATÓRIO --------';

-- --------------------------------------------------------------------------------------------------------
DECLARE DEPARTAMENTOS_CURSOR CURSOR FOR 
	SELECT
		DEPARTAMENTO_ID,
		DEPARTAMENTO_NOME
	FROM
		@TAB_DEPARTAMENTOS;
OPEN DEPARTAMENTOS_CURSOR

FETCH NEXT FROM DEPARTAMENTOS_CURSOR INTO @DEPARTAMENTO_ID, @DEPARTAMENTO_NOME
-- --------------------------------------------------------------------------------------------------------

WHILE @@FETCH_STATUS = 0
BEGIN
    PRINT ' '
    SELECT @MESSAGE = '----- CARGOS DO DEPARTAMENTO: ' + @DEPARTAMENTO_NOME

    PRINT @MESSAGE

	-- --------------------------------------------------------------------------------------------------------
    DECLARE CARGO_CURSOR CURSOR FOR 
		SELECT
			CARGO_ID,
			CARGO_NOME
		FROM
			@TAB_CARGOS
		WHERE DEPARTAMENTO_ID = @DEPARTAMENTO_ID 
    OPEN CARGO_CURSOR
    
    FETCH NEXT FROM CARGO_CURSOR INTO @CARGO_ID, @CARGO_NOME
	-- --------------------------------------------------------------------------------------------------------
	
    IF @@FETCH_STATUS <> 0 
        PRINT '         <<NONE>>'     

    WHILE @@FETCH_STATUS = 0
    BEGIN

        SELECT @MESSAGE = '         ' + @CARGO_NOME
        PRINT @MESSAGE
        
        
        
        
        
			-- --------------------------------------------------------------------------------------------------------
			DECLARE FUNC_CURSOR CURSOR FOR 
				SELECT
					FUNC_ID,
					FUNC_NOME
				FROM
					@TAB_FUNCIONARIOS
				WHERE CARGO_ID = @CARGO_ID 
			OPEN FUNC_CURSOR
		    
			FETCH NEXT FROM FUNC_CURSOR INTO @FUNC_ID, @FUNC_NOME
			-- --------------------------------------------------------------------------------------------------------
			
			IF @@FETCH_STATUS <> 0 
				PRINT '         <<NONE>>'     

			WHILE @@FETCH_STATUS = 0
			BEGIN

				SELECT @MESSAGE = '						' + @FUNC_NOME
				PRINT @MESSAGE
				
				FETCH NEXT FROM FUNC_CURSOR INTO @FUNC_ID, @FUNC_NOME
			END
               
			CLOSE FUNC_CURSOR
			DEALLOCATE FUNC_CURSOR       
        
        FETCH NEXT FROM CARGO_CURSOR INTO @CARGO_ID, @CARGO_NOME
        END

    CLOSE CARGO_CURSOR
    DEALLOCATE CARGO_CURSOR

    FETCH NEXT FROM DEPARTAMENTOS_CURSOR 
    INTO @DEPARTAMENTO_ID, @DEPARTAMENTO_NOME
END 
CLOSE DEPARTAMENTOS_CURSOR;
DEALLOCATE DEPARTAMENTOS_CURSOR;