/*
DECLARE @TEMP_TAB_RECEBIDOS AS TABLE
(
	[COD_LOJA] [INT],
	[COD_PRODUTO] [INT]
);

INSERT INTO @TEMP_TAB_RECEBIDOS
SELECT DISTINCT
	REC_MERC.COD_LOJA,
	REC_CONT.COD_PRODUTO
FROM
	[192.168.0.6].[INTRANET].[DBO].[TAB_RECEB_MERCADORIA] AS REC_MERC INNER JOIN [192.168.0.6].[INTRANET].[DBO].[TAB_RECEB_MERCADORIA_CONTAGEM] AS REC_CONT ON (REC_MERC.ID = REC_CONT.ID);

select top 10 * from [192.168.0.6].[Zeus_rtg].dbo.vw_MARCHE_ENTRADAS
*/

--select * from @TEMP_TAB_RECEBIDOS where COD_PRODUTO = 00991798

DECLARE @TEMP_TAB_PROD_FORA AS TABLE
(
	[COD_LOJA] [INT],
	[COD_PRODUTO] [INT]
);

INSERT INTO @TEMP_TAB_PROD_FORA
SELECT DISTINCT
	SB.COD_LOJA
	,SB.[CODIGO]
FROM
	[192.168.0.13].[BI].[dbo].[VW_BI_SUPERBASE] AS SB LEFT JOIN vw_MARCHE_ENTRADAS AS E ON (E.COD_LOJA = SB.COD_LOJA AND E.COD_PRODUTO = SB.CODIGO)
where 1=1
	AND [PROIBIDO_COMPRA] = 'N'
	AND [FORA_MIX] = 'N'
	AND [FORA_LINHA] = 'N'
	AND SB.COD_SECAO IN (24,26,23,50,31,7,22,21,42,29,33,30,27)
	AND TIPO_PRODUTO <> 'SAZONAL'
	AND IPV = 'N'
	AND E.COD_PRODUTO IS NULL 


SELECT
	CONVERT(DATE,GETDATE()-1) AS DTA_MOVIMENTO
	,YEAR(GETDATE()) AS ANO
	,PF.COD_LOJA
	,PF.COD_PRODUTO
	,P.COD_SECAO
	,P.COD_GRUPO
	,E.CLASSIF_PRODUTO_LOJA
	,0 AS QTD_ESTOQUE
	,1 AS RUPTURA
	,0 AS NEGATIVO
FROM
	@TEMP_TAB_PROD_FORA PF LEFT JOIN [192.168.0.13].BI.DBO.BI_CAD_PRODUTO AS P ON (P.COD_PRODUTO = PF.COD_PRODUTO)
		LEFT JOIN [192.168.0.13].BI.DBO.COMPRAS_ESTATISTICA_PRODUTO AS E ON (E.COD_PRODUTO = PF.COD_PRODUTO AND E.COD_LOJA = PF.COD_LOJA);