SELECT
	'2014' AS ANO
	,L.NO_LOJA
	,CD.NO_DEPARTAMENTO
	,BI.dbo.fn_FormataVlr_Excel(SUM(VLR_VENDA)) AS VLR_TOTAL
FROM
	BI_VENDA_DEPARTAMENTO AS VD
	INNER JOIN (SELECT DISTINCT COD_DEPARTAMENTO, NO_DEPARTAMENTO FROM BI_CAD_PRODUTO) AS CD
		ON VD.COD_DEPARTAMENTO = CD.COD_DEPARTAMENTO
	INNER JOIN BI.dbo.BI_CAD_LOJA2 AS L
		ON VD.COD_LOJA = L.COD_LOJA
WHERE 1=1
	AND CONVERT(DATE,DATA) BETWEEN CONVERT(DATE,'2014-01-01') AND CONVERT(DATE,'2014-10-31')
	AND L.NO_REGIONAL = 'Fernanda'
GROUP BY
	L.NO_LOJA
	,CD.NO_DEPARTAMENTO
	
UNION ALL

SELECT
	'2015' AS ANO
	,L.NO_LOJA
	,CD.NO_DEPARTAMENTO
	,BI.dbo.fn_FormataVlr_Excel(SUM(VLR_VENDA)) AS VLR_TOTAL
FROM
	BI_VENDA_DEPARTAMENTO AS VD
	INNER JOIN (SELECT DISTINCT COD_DEPARTAMENTO, NO_DEPARTAMENTO FROM BI_CAD_PRODUTO) AS CD
		ON VD.COD_DEPARTAMENTO = CD.COD_DEPARTAMENTO
	INNER JOIN BI.dbo.BI_CAD_LOJA2 AS L
		ON VD.COD_LOJA = L.COD_LOJA
WHERE 1=1
	AND CONVERT(DATE,DATA) BETWEEN CONVERT(DATE,'2014-01-01') AND CONVERT(DATE,'2014-10-31')
	AND L.NO_REGIONAL = 'Fernanda'
GROUP BY
	L.NO_LOJA
	,CD.NO_DEPARTAMENTO
	


SELECT
	'2014' AS ANO
	,L.NO_LOJA
	,CD.NO_DEPARTAMENTO
	,BI.dbo.fn_FormataVlr_Excel(SUM(VLR_VENDA)) AS VLR_TOTAL
FROM
	BI_VENDA_DEPARTAMENTO AS VD
	INNER JOIN (SELECT DISTINCT COD_DEPARTAMENTO, NO_DEPARTAMENTO FROM BI_CAD_PRODUTO) AS CD
		ON VD.COD_DEPARTAMENTO = CD.COD_DEPARTAMENTO
	INNER JOIN BI.dbo.BI_CAD_LOJA2 AS L
		ON VD.COD_LOJA = L.COD_LOJA
WHERE 1=1
	AND CONVERT(DATE,DATA) BETWEEN CONVERT(DATE,'2014-08-01') AND CONVERT(DATE,'2014-10-31')
	AND L.NO_REGIONAL = 'Fernanda'
GROUP BY
	L.NO_LOJA
	,CD.NO_DEPARTAMENTO
	
UNION ALL

SELECT
	'2015' AS ANO
	,L.NO_LOJA
	,CD.NO_DEPARTAMENTO
	,BI.dbo.fn_FormataVlr_Excel(SUM(VLR_VENDA)) AS VLR_TOTAL
FROM
	BI_VENDA_DEPARTAMENTO AS VD
	INNER JOIN (SELECT DISTINCT COD_DEPARTAMENTO, NO_DEPARTAMENTO FROM BI_CAD_PRODUTO) AS CD
		ON VD.COD_DEPARTAMENTO = CD.COD_DEPARTAMENTO
	INNER JOIN BI.dbo.BI_CAD_LOJA2 AS L
		ON VD.COD_LOJA = L.COD_LOJA
WHERE 1=1
	AND CONVERT(DATE,DATA) BETWEEN CONVERT(DATE,'2015-08-01') AND CONVERT(DATE,'2015-10-31')
	AND L.NO_REGIONAL = 'Fernanda'
GROUP BY
	L.NO_LOJA
	,CD.NO_DEPARTAMENTO