SELECT
	P.COD_PARCEIRO as [Cod Forn]
	,f.[DES_FORNECEDOR] as Fornecedor
	,CP.NO_DEPARTAMENTO
	,CP.NO_SECAO	
	,CP.COD_PRODUTO
	,CP.DESCRICAO AS PRODUTO
	,SUM(PP.VAL_TABELA*PP.QTD_RECEBIDA) AS [Vlr Recebido]		
	--,SUM(PP.VAL_TABELA*PP.QTD_PEDIDO) as [Vlr Pedido]	
FROM
	[ZEUS_RTG].DBO.[TAB_PEDIDO] AS P
	INNER JOIN [Zeus_rtg].[dbo].[TAB_FORNECEDOR] AS F
		ON (f.cod_fornecedor = p.cod_parceiro)
	INNER JOIN [ZEUS_RTG].DBO.[TAB_PEDIDO_PRODUTO] AS PP
		ON 1=1
		and P.NUM_PEDIDO = PP.NUM_PEDIDO
		AND P.COD_LOJA = PP.COD_LOJA
		AND P.COD_PARCEIRO = PP.COD_PARCEIRO
	LEFT JOIN [192.168.0.13].BI.dbo.BI_CAD_PRODUTO AS CP
		ON PP.COD_PRODUTO = CP.COD_PRODUTO
WHERE 1 = 1
	AND CONVERT(DATE,DTA_EMISSAO) between CONVERT(DATE,'20150110') AND CONVERT(DATE,'20151111')
	AND P.COD_LOJA IN (29,33)
	--AND P.COD_LOJA IN (1)
GROUP BY 
	P.COD_PARCEIRO
	,f.[DES_FORNECEDOR]
	,CP.NO_DEPARTAMENTO
	,CP.NO_SECAO
	,CP.COD_PRODUTO
	,CP.DESCRICAO
ORDER BY 7 DESC


SELECT
	P.COD_PARCEIRO as [Cod Forn]
	,f.[DES_FORNECEDOR] as Fornecedor	
	,CP.NO_DEPARTAMENTO
	,CP.NO_SECAO
	,YEAR(P.DTA_EMISSAO) AS ANO
	,MONTH(P.DTA_EMISSAO) AS MES
	,SUM(PP.VAL_TABELA*PP.QTD_RECEBIDA) AS [Vlr Recebido]		
	,SUM(PP.VAL_TABELA*PP.QTD_PEDIDO) as [Vlr Pedido]	
FROM
	[ZEUS_RTG].DBO.[TAB_PEDIDO] AS P
	INNER JOIN [Zeus_rtg].[dbo].[TAB_FORNECEDOR] AS F
		ON (f.cod_fornecedor = p.cod_parceiro)
	INNER JOIN [ZEUS_RTG].DBO.[TAB_PEDIDO_PRODUTO] AS PP
		ON 1=1
		and P.NUM_PEDIDO = PP.NUM_PEDIDO
		AND P.COD_LOJA = PP.COD_LOJA
		AND P.COD_PARCEIRO = PP.COD_PARCEIRO
	LEFT JOIN [192.168.0.13].BI.dbo.BI_CAD_PRODUTO AS CP
		ON PP.COD_PRODUTO = CP.COD_PRODUTO
WHERE 1 = 1
	AND CONVERT(DATE,DTA_EMISSAO) between CONVERT(DATE,'20150101') AND CONVERT(DATE,'20151031')
	AND P.COD_LOJA IN (29,33)
	--AND P.COD_LOJA IN (1)
GROUP BY 
	P.COD_PARCEIRO
	,f.[DES_FORNECEDOR]
	,CP.NO_DEPARTAMENTO
	,CP.NO_SECAO
	,YEAR(P.DTA_EMISSAO)
	,MONTH(P.DTA_EMISSAO)
ORDER BY
	P.COD_PARCEIRO
	,f.[DES_FORNECEDOR]
	,CP.NO_DEPARTAMENTO
	,CP.NO_SECAO
	,YEAR(P.DTA_EMISSAO)
	,MONTH(P.DTA_EMISSAO)
