SELECT
	E.COD_LOJA
	,L.NO_LOJA
	,(CASE WHEN E.COD_LOJA IN (5,28) THEN 'ORB' ELSE L.CLUSTER END) CLUSTER
	,E.COD_PRODUTO
	,CP.DESCRICAO AS NO_PRODUTO
	,CP.NO_DEPARTAMENTO
	,CP.NO_SECAO
	,CP.NO_GRUPO
	,EP.CLASSIF_PRODUTO_LOJA
	,LP.FORA_LINHA
	,BI.DBO.FN_FORMATAVLR_EXCEL(C.VLR_EMB_COMPRA/C.QTD_EMB_COMPRA) AS VLR_CUSTO_UN
	,BI.DBO.FN_FORMATAVLR_EXCEL(LP.VLR_VENDA) AS VLR_VENDA
	,BI.DBO.FN_FORMATAVLR_EXCEL(LP.VLR_OFERTA) AS VLR_OFERTA
	,BI.DBO.FN_FORMATAVLR_EXCEL(LP.VLR_VCMARCHE) AS VLR_VCMARCHE
	,BI.DBO.FN_FORMATAVLR_EXCEL(isnull(EP.AVG_QTD_U180D_PD,0)) as AVG_QTD_U180D_PD
	,BI.DBO.FN_FORMATAVLR_EXCEL(isnull(EP.AVG_QTD_U90D_PD,0)) as AVG_QTD_U90D_PD
	,BI.DBO.FN_FORMATAVLR_EXCEL(isnull(EP.AVG_QTD_U30D_PD,0)) as AVG_QTD_U30D_PD
	,BI.DBO.FN_FORMATAVLR_EXCEL(isnull(E.QTD_ESTOQUE,0)) as QTD_ESTOQUE
FROM
	BI.dbo.VW_ESTOQUE_ATUAL AS E
	INNER JOIN BI.dbo.BI_CAD_PRODUTO AS CP
		ON E.COD_PRODUTO = CP.COD_PRODUTO	
	LEFT JOIN BI.dbo.COMPRAS_ESTATISTICA_PRODUTO AS EP
		ON 1=1
		AND E.COD_PRODUTO = EP.COD_PRODUTO
		AND E.COD_LOJA = EP.COD_LOJA		
	LEFT JOIN BI.DBO.BI_LINHA_PRODUTOS AS LP
		ON 1=1
		AND E.COD_PRODUTO = LP.COD_PRODUTO
		AND E.COD_LOJA = LP.COD_LOJA
	LEFT JOIN [BI].[dbo].[BI_CAD_LOJA2] AS L
		ON E.COD_LOJA = L.COD_LOJA
	LEFT JOIN BI.dbo.VW_CUSTOS_ATIVOS2 AS C
		ON E.COD_PRODUTO = C.COD_PRODUTO
		AND CP.COD_FORNECEDOR = C.COD_FORNECEDOR
WHERE 1=1
	AND CP.COD_PRODUTO IN (SELECT COD_PRODUTO FROM CADASTRO_CAD_PRODUTO_METADADOS TPM WHERE TPM.COD_METADADO = 4 and TPM.VLR_METADADO = 1)
	--AND LP.COD_LOJA not in (5)
	--AND LP.FORA_LINHA = 'N'
ORDER BY
	E.COD_LOJA
	,L.NO_LOJA
	,(CASE WHEN E.COD_LOJA IN (5,28) THEN 'ORB' ELSE L.CLUSTER END)
	,CP.NO_DEPARTAMENTO
	,CP.NO_SECAO
	,CP.NO_GRUPO
	,CP.DESCRICAO