SELECT
	CP.COD_FORNECEDOR as [Cod Forn]
	,Cf.DESCRICAO as Fornecedor
	,CP.NO_DEPARTAMENTO
	,CP.NO_SECAO	
	,CP.COD_PRODUTO
	,CP.DESCRICAO AS PRODUTO
	,BI.DBO.FN_FORMATAVLR_EXCEL(SUM(VP.VALOR_TOTAL)) AS [Vlr Venda]		
	--,SUM(PP.VAL_TABELA*PP.QTD_PEDIDO) as [Vlr Pedido]	
FROM
	BI.DBO.BI_VENDA_PRODUTO AS VP	
	LEFT JOIN BI.dbo.BI_CAD_PRODUTO AS CP
		ON VP.COD_PRODUTO = CP.COD_PRODUTO
	LEFT JOIN BI.DBO.BI_CAD_FORNECEDOR AS CF
		ON CP.COD_FORNECEDOR = CF.COD_FORNECEDOR
WHERE 1 = 1
	AND CONVERT(DATE,DATA) between CONVERT(DATE,'20150110') AND CONVERT(DATE,'20151111')
	--AND VP.COD_LOJA IN (29,33)
	
	--AND P.COD_LOJA IN (1)
GROUP BY 
	CP.COD_FORNECEDOR
	,Cf.DESCRICAO 
	,CP.NO_DEPARTAMENTO
	,CP.NO_SECAO	
	,CP.COD_PRODUTO
	,CP.DESCRICAO
