DECLARE @TAB_AX AS TABLE
(
	COD_FORNECEDOR INT
	,COD_PRODUTO INT 
	,DES_REFERENCIA VARCHAR(50)
	,DES_REFERENCIA_TRATADA VARCHAR(50)
	,MULTIPLO NUMERIC(5,2)
	,QTD_EMBALAGEM INT
	,UNIDADE_COMPRA VARCHAR(10)
);

INSERT INTO @TAB_AX
SELECT
	COD_PRODUTO
	,R.COD_FORNECEDOR
	,DES_REFERENCIA
	,DES_REFERENCIA_TRATADA
	,MARCHEMULTIPLO
	,MARCHEQTDEMBALAGEM
	,MARCHEUNITID
FROM
	[AX2009_INTEGRACAO].dbo.TAB_PRODUTO_REFERENCIA as r
		inner join [BI].dbo.BI_CAD_FORNECEDOR as f on (r.COD_FORNECEDOR = f.COD_FORNECEDOR)
where 1 = 1
	--ANd f.ABC_FORN in ('A1','A2','A3')
	--AND COD_PRODUTO = 497879
	
/*
DECLARE @TAB_ZEUS AS TABLE
(
	COD_FORNECEDOR INT
	,COD_PRODUTO INT 
	,DES_REFERENCIA VARCHAR(50)
	,MULTIPLO NUMERIC(5,2)
	,QTD_EMBALAGEM INT
	,UNIDADE_COMPRA VARCHAR(10)
);

INSERT INTO @TAB_ZEUS
SELECT DISTINCT --TOP 100
	COD_PRODUTO
	,R.COD_FORNECEDOR
	,DES_REFERENCIA
	,QTD_MINIMA_COMPRA
	,QTD_EMBALAGEM_COMPRA
	,DES_UNIDADE_COMPRA
FROM
	[192.168.0.6].[ZEUS_RTG].dbo.TAB_PRODUTO_FORNECEDOR AS R
		inner join [BI].dbo.BI_CAD_FORNECEDOR as f on (r.COD_FORNECEDOR = f.COD_FORNECEDOR)
where 1 = 1
	--ANd f.ABC_FORN in ('A1','A2','A3')
	AND COD_PRODUTO = 497879
	

SELECT --TOP 500
	AX.COD_FORNECEDOR
	,AX.COD_PRODUTO
	,AX.DES_REFERENCIA AS DES_REFERENCIA_AX
	,AX.DES_REFERENCIA_TRATADA AS DES_REFERENCIA_TRATADA_AX
	,ZEUS.DES_REFERENCIA AS DES_REFERENCIA_ZEUS
	,AX.MULTIPLO AS MULTIPLO_AX
	,ZEUS.MULTIPLO AS MULTIPLO_ZEUS
	,AX.QTD_EMBALAGEM AS QTD_EMBALAGEM_AX
	,ZEUS.QTD_EMBALAGEM AS QTD_EMBALAGEM_ZEUS
	,AX.UNIDADE_COMPRA AS UNIDADE_COMPRA_AX
	,ZEUS.UNIDADE_COMPRA AS UNIDADE_COMPRA_ZEUS
	,(CASE WHEN AX.DES_REFERENCIA <> ZEUS.DES_REFERENCIA THEN 1 ELSE 0 END) AS DIVERGENCIA_REFERENCIA
	,(CASE WHEN AX.MULTIPLO <> ZEUS.MULTIPLO THEN 1 ELSE 0 END) AS DIVERGENCIA_MULTIPLO
	,(CASE WHEN AX.UNIDADE_COMPRA <> ZEUS.UNIDADE_COMPRA THEN 1 ELSE 0 END) AS DIVERGENCIA_UNIDADE_COMPRA
FROM
	@TAB_AX AS AX LEFT JOIN @TAB_ZEUS AS ZEUS ON (AX.COD_FORNECEDOR = ZEUS.COD_FORNECEDOR AND AX.COD_PRODUTO = ZEUS.COD_PRODUTO)
WHERE 1 = 1
	--AND ZEUS.COD_FORNECEDOR IS NULL
	--AND AX.MULTIPLO <> 0
	--AND AX.QTD_EMBALAGEM <> 0
	AND (AX.DES_REFERENCIA <> ZEUS.DES_REFERENCIA)
	AND (AX.DES_REFERENCIA_TRATADA <> ZEUS.DES_REFERENCIA)
ORDER BY 
	AX.COD_FORNECEDOR
	,AX.COD_PRODUTO

*/


/*
-- --------------

SELECT
	COD_PRODUTO
	,COD_FORNECEDOR
	,DES_REFERENCIA
	,1 AS MARCHEMULTIPLO
	--,1 as MARCHEQTDEMBALAGEM
	--,MARCHEUNITID
FROM
	[AX2009_INTEGRACAO].dbo.TAB_PRODUTO_REFERENCIA
where 1 = 1
	AND MARCHEMULTIPLO = 0
	--AND MARCHEQTDEMBALAGEM = 0
*/


select * from @TAB_AX


select --top 100 
	R.COD_PRODUTO
	,R.COD_FORNECEDOR
	,R.DES_REFERENCIA_TRATADA
	,R.MARCHEMULTIPLO
	,R.MARCHEQTDEMBALAGEM
	,R.MARCHEUNITID
	,P.PESADO
	,(CASE WHEN P.PESADO = 'S' THEN 'KG' ELSE 'CX' END) AS NOVA_EMBALAGEM
FROM
	[AX2009_INTEGRACAO].dbo.TAB_PRODUTO_REFERENCIA as r
		inner join [BI].dbo.BI_CAD_PRODUTO as p on (r.COD_PRODUTO = P.COD_PRODUTO)
WHERE 1 = 1
	AND R.MARCHEQTDEMBALAGEM = 1